### ISSUE TITLE
Bdii2CSAgent: remove outdated info?

### ISSUE THREAD

**Issue by sposs** [DIRACGrid/DIRAC#1034]
The ILCDIRAC CS is full of CEs that are outdated (removed from the system, not supporting the VO any more, etc.). It would be nice if the CE2CSAgent could see those as "outdated" and send a notification that they should be removed eventually.

**Comment by chaen** [comment]
is this still valid ? wasn't the agent recently replaced ?

**Comment by atsareg** [comment]
This is still a valid request even for the new Bdii2CSAgent that replaces the CE2CSAgent. @VladimirRomanovsky : is it possible that you look at it ?

**Comment by fstagni** [comment]
@andresailer want to comment? You were the last touching this.

**Comment by andresailer** [comment]
Certainly our problem of outdated information in the CS has not shrunk.
Maybe one could write a script to run these checks occasionally? Given there is the potential of manual content for the CEs with things that are not part of the BDII, or things that are picked up from different agent instances (GLUE2 vs GLUE1 checks). And therefore the agent would produce a lot of false positives if it were to remind one of "outdated" information.

**Comment by chaen** [comment]
Was that implemented in the end ?

**Comment by andresailer** [comment]
Not as far as I know

**Comment by fstagni** [comment]
@atsareg this is the issues we discussed in today's BiLD meeting.
