### ISSUE TITLE
SiteDirector per country/GRID

### ISSUE THREAD

**Issue by sposs** [DIRACGrid/DIRAC#1035]
It can be useful to be able to define easily a SiteDirector that addresses only one particular country. Or grid.

**Comment by chaen** [comment]
I believe we have that, don't we ? @VladimirRomanovsky @fstagni @aldbr

**Comment by aldbr** [comment]
From what I've seen so far, the configuration allows to define multiple SiteDirectors and then they can be bound to specific Sites and CEs. So yes, we have this feature.
