### ISSUE TITLE
Bug in removeFile (ReplicaManager)

### ISSUE THREAD

**Issue by phicharp** [DIRACGrid/DIRAC#1091]
When removing a file that is present in the FC, but absent on the SE, removeFile returns the removal as failed, and doesn't remove the entry in the FC. One must then make a removeCatalogFile, while it would be simpler to do it directly in removeFile.

**Comment by fstagni** [comment]
Is this still valid? (2014...)

**Comment by sposs** [comment]
As far as I'm concerned, ALDIRAC was dropped at the time I left the company as too hard to maintain and use. So if not already done, please ignore the comment I make 3 years ago.

**Comment by chaen** [comment]
This is fixed now in the sense that the storage plugins consider a success removing a non existing file. Since @sposs asked to be ignored, I close this issue ;-)
