### ISSUE TITLE
New option requested in dirac-dms-user-lfns

### ISSUE THREAD

**Issue by phicharp** [DIRACGrid/DIRAC#1098]
Users would be able to select files more recent than a certain time, while currently only files older than a certain time can be obtained.
Adding a switch like "--Recent" could do the trick

**Comment by chaen** [comment]
Can be closed as well I thing, @atsareg to confirm

**Comment by atsareg** [comment]
Any selection can be done with DFC with dirac-dms-find-lfns or equivalent COMDIRAC/dfind commands.
