### ISSUE TITLE
Replica upload and registration with 2 catalogs

### ISSUE THREAD

**Issue by sposs** [DIRACGrid/DIRAC#1099]
In v6r6 it seems there is a "bug" when uploading a file (dirac-dms-add-file or add-files, does not matter). 
The file gets put on the SE but if the file has a guid that is used by another, then the LFC fails, the registration stops, and the file is not removed from the SE. We end up with a file that has a replica on a SE and no replica info in the FC (LFC and/or DFC). I think the handling of the LFC error should be better done (in particular the other file with the same GUID should be given in the returned message) and the file should be removed from the SE to avoid having orphans.

**Comment by chaen** [comment]
This is fixed already, please close
