### ISSUE TITLE
JobGroup selection in accounting pages

### ISSUE THREAD

**Issue by phicharp** [DIRACGrid/DIRAC#1103]
As requested already many times, could the jobGroup menu in the selection box of accounting plots be in reverse order? Most likely interesting productions are most recent ones...

**Comment by chaen** [comment]
@zmathe  I just checked, it is not the case, could you please add a sort statement.

**Comment by phicharp** [comment]
There is a problem with these pulldown manus, in that they make the selection after each character is typed and it makes it impossible almost to select a production because one needs to type in the first 3 zeros!!! Can the selection be made after a longer time (like 0.5 seconds or so)? and/or match any string in the item (not only startswith())?

**Comment by zmathe** [comment]
The widget has to be replaced. This will solve the problem.

**Comment by chaen** [comment]
This is now the case
