### ISSUE TITLE
get TransformationSummaryWeb

### ISSUE THREAD

**Issue by sposs** [DIRACGrid/DIRAC#1104]
In v6r6 and using the DBOD MySQL service, the query takes very often more than 220 seconds to complete, therefore timing out on the web side. I have something like 1500 productions in the system. Is it possible to optimize the code or do I need to find a dedicated mysql server for the TS?

**Comment by chaen** [comment]
Can this be closed now ?

**Comment by fstagni** [comment]
No, we can't yet close this one.

**Comment by fstagni** [comment]
Not valid anymore.
