### ISSUE TITLE
Transformation System - ValidateOutputDataAgent and Cleaning

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#1106]
The script "dirac-production-verify-outputdata" uses code from the ValidateOutputData agent, and it does not consider the standard dirac "-d", "-dd", etc flags.

TransformationCleaningAgent :
- the agent prints an error if the catalog directory is not present, it should be a warning
- the list of SEs is taken by the CS, directly in the agent section. It should be instead taken from the 'Resources' section.
- the list of directories to be cleaned is taken by many locations, and sometimes they overlap, and it does not check if a super-directory is already in the list.

**Comment by fstagni** [comment]
@marcelovilaca this is just another script of the "same" field of consistency checks. I assign it to you, just for not forgetting about it. No rush (this is a ~30months old task...)

**Comment by fstagni** [comment]
@marcelovilaca can you please post an update on this task?

**Comment by marcelovilaca** [comment]
Wow, didn't remember this... Will start to look at it now..

**Comment by chaen** [comment]
What's the status of this ? It is also a bit related to all the directory operations we discussed lately...

**Comment by fstagni** [comment]
Duplicate task.
