### ISSUE TITLE
Consistency check / validation for CS entries

### ISSUE THREAD

**Issue by roiser** [DIRACGrid/DIRAC#1123]
Hi,

following up on an issue we just discovered today, i.e. an entry happens to have ended up in a wrong section of the CS where it didn't have any influence on the operations of Dirac. Although it was believed that it did ....

Can we have a check of the Configration System such that we know which entries are being used by Dirac and which not? E.g. I could imagine some "counter" which tells us how often a given entry has been read in the last given amount of time. Then we could also easily identify entries in the CS which can be safely removed and therefore ease operations. 

Cheers

Stefan

**Comment by chaen** [comment]
The fact that we do not clean the CS is just a "bad management" issue, we are just messy :-) 
However, I support the idea of having in the config template also the Operations/etc values. As far as I know, this still does not exist. If we agree, maybe we can close this ticket, and create a new one with more explicit requirements ?

**Comment by atsareg** [comment]
What you suggest is defining the CS schema formally and introduce tools to check the actual contents of the CS against the schema. A la what can be done with XML documents. This is a large development, do we really need that ? Glue has a formally defined schema which does not prevent occasional mess in the contents, for example.

**Comment by chaen** [comment]
no, what I mean is that we can define "default" for Services and Agents, but we have no way to define default for Operations, and that is missing

**Comment by chaen** [comment]
I think this can be closed:
* we will probably never have the counter
* we now have the standard `dirac.cfg`
* all options are in the code (or migrating to)

**Comment by fstagni** [comment]
Agree.
