### ISSUE TITLE
CE2CS agent to report new platforms

### ISSUE THREAD

**Issue by atsareg** [DIRACGrid/DIRAC#1163]
The grid computing elements descriptions in the BDII contain among others architecture and OS parameters. Those are describing the CE computing platform. This platform must be mapped to the LHCb architecture tags to establish the compatibility. The CE2CS agent should check platforms for all the CEs, determine new platforms not yet present in any DIRAC platform compatibility list and add information about the newly discovered platforms to its mail report.

**Comment by fstagni** [comment]
Closing, I guess...
