### ISSUE TITLE
Getting all the Ports used by services on a given host

### ISSUE THREAD

**Issue by sposs** [DIRACGrid/DIRAC#1174]
I want to install a second instance of the Transformation service, but I don't know what port to use. I'd like the SystemAdministrator to given me all the used ports on the current host.

**Comment by chaen** [comment]
@Sbalbp @fstagni does that work now ?

**Comment by fstagni** [comment]
I don't think it is available yet, but it's a good idea. I assign it to Sergio, for answer now and for possible implementation later.

**Comment by Sbalbp** [comment]
No, it does not as of now

**Comment by fstagni** [comment]
Certified.
