### ISSUE TITLE
Sum rules in the web production monitoring

### ISSUE THREAD

**Issue by phicharp** [DIRACGrid/DIRAC#126]
Even when selecting all job status in the Production Monitoring, the sum of all statuses is not equal to the number of submitted jobs. This is weird as it is then quite difficult to figure out where the missing ones are.

Clearly the statuses have to be grouped in order to avoid too many columns. Proposal:

Waiting = received, checking, staging, waiting, rescheduled
Running = Matched, Running
Done = Done 
Completed = Completed
Stalled = Stalled
Failed = Failed
Deleted (new) = Deleted, Killed

**Comment by chaen** [comment]
Is it still valid ?
