### ISSUE TITLE
Comments in JDL

### ISSUE THREAD

**Issue by graciani** [DIRACGrid/DIRAC#1287]
a JDL with a comment seems to crash the execution of the JobWrapper, leaving the Job in "Matched" "SubmittedToCE".
A very simple JDL:

[
    Executable = "$DIRACROOT/scripts/dirac-proxy-info";
    # test

    JobName = "GenericJob";
    OutputSandbox =
        {
            "std.err",
            "std.out"
        };
    StdError = "std.err";
    StdOutput = "std.out";
    MaxCPUTime = "10";
]

Produces the following error:

== EXCEPTION ==
:EOL while scanning string literal (, line 1)
  File "/var/torque/tmpdir/843267.lpnhe-gs9091.in2p3.fr/CREAM743268327/job/Wrapper/Wrapper_501201", line 145, in
    jobArgs = eval( """{'Job': {'OwnerGroup': 'cta_user',
'Executable': '$DIRACROOT/scripts/dirac-proxy-info', '# test\n\n
JobName': 'GenericJob', 'DIRACSetup': 'CTA', 'StdError': 'std.err',
'SoftwareDistModule': 'CTADIRAC.Core.Utilities.SoftwareInstallation',
'Priority': '1', 'VirtualOrganization': 'vo.cta.in2p3.fr',
'SystemConfig': 'Linux_x86_64_glibc-2.5', 'CPUTime': '86400', 'JobID':
'501201', 'OwnerDN':
'/DC=es/DC=irisgrid/O=ecm-ub/CN=Ricardo.Graciani', 'OutputSandbox':
['std.err', 'std.out'], 'JobRequirements': '[             OwnerDN =
/DC=es/DC=irisgrid/O=ecm-ub/CN=Ricardo.Graciani;
VirtualOrganization = vo.cta.in2p3.fr;            Setup = CTA;
   CPUTime = 10;            OwnerGroup = cta_user;
UserPriority = 1;        ]', 'OwnerName': 'graciani', 'MaxCPUTime':
'10', 'Owner': 'graciani', 'StdOutput': 'std.out'}, 'Optimizer':
{'OptimizerChain': 'JobPath,JobSanity,JobScheduling,TaskQueue',
'JobID': 501201L}, 'CE': {'Requirements': 'other.OwnerGroup ==
cta_user && other.OwnerDN ==
/DC=es/DC=irisgrid/O=ecm-ub/CN=Ricardo.Graciani', 'CPUScalingFactor':
'8.4', 'TotalCPUs': '1', 'LogLevel': 'INFO', 'LHCbPlatform':
'Linux_x86_64_glibc-2.5', 'GridCEQueue':
'lpnhe-cream.in2p3.fr:8443/cream-pbs-vo.cta.in2p3.fr', 'DIRACVersion':
'CTA-HEAD', 'CPUNormalizationFactor': '8.4', 'WorkingDirectory':
'/var/torque/tmpdir/843267.lpnhe-gs9091.in2p3.fr/CREAM743268327',
'MaxRunningJobs': '1', 'ReleaseVersion': 'CTA-HEAD', 'CPUTime':
'725760', 'OwnerDN':
'/DC=es/DC=irisgrid/O=ecm-ub/CN=Ricardo.Graciani', 'MaxWaitingJobs':
'1', 'FileCatalog': 'LcgFileCatalog', 'CEQueue':
'cream-pbs-vo.cta.in2p3.fr', 'PilotReference':
'https://wms03.pic.es:9000/aUlOyVOoDm7yR9y76Xucdg', 'Site':
'LCG.GRIF.fr', 'OwnerGroup': 'cta_user', 'LocalAccountString':
'ctaibdntjqba001', 'MaxCPUTime': '725760', 'GridCE':
'lpnhe-cream.in2p3.fr', 'MaxTotalJobs': '10', 'GridMiddleware':
'gLite', 'Architecture': 'Linux_x86_64_glibc-2.5'}}""" )
===============

== EXCEPTION ==
:'NoneType' object has no attribute 'commit'
  File "/var/torque/tmpdir/843267.lpnhe-gs9091.in2p3.fr/CREAM743268327/job/Wrapper/Wrapper_501201",
line 151, in
    gJobReport.commit()
===============
2013-02-26 10:23:28 UTC WorkloadManagement/JobAgent ERROR: Fail in payload execution
2013-02-26 10:23:28 UTC WorkloadManagement/JobAgent  INFO: Exit status: 254
2013-02-26 10:23:28 UTC WorkloadManagement/JobAgent  INFO: Job 501201 submitted as

**Comment by chaen** [comment]
Still valid ?

**Comment by atsareg** [comment]
We use JobManifest internally now. Even if the JDL form of the JobManifest serialization is still used
( in the database for example ), the JDLs are created from the JobManifest without comments.
