### ISSUE TITLE
RSS Script to insert and test a new policy configuration

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#1301]
Due to the difficulties in setting up the RSS configuration, especially for what regards the policies configuration, we need a script that will guide the administrator in modifying the CS, limiting the available choices.

Within this same script, we also need a possibility to test, on some selected resource, the policies that are applied, before committing the changes in the CS. This can be done running all the policies machinery, from PDP on.

**Comment by chaen** [comment]
@fstagni can this be closed after Aresh changes ? (maybe you want to reassign the tasks as well ? )

**Comment by fstagni** [comment]
It's waiting to be released. I flagged and assigned to myself for certification test.
