### ISSUE TITLE
Improvements for file catalog CLI

### ISSUE THREAD

**Issue by sposs** [DIRACGrid/DIRAC#1360]
Would be useful that file meta data has some indication about the searchable ones (like a star)

Would be useful that the "meta tags" command works for the file level meta data (the getCompatibleMetadata method)

**Comment by chaen** [comment]
I believe all this is in place already, @atsareg can confirm (or not) and close (or not)

**Comment by atsareg** [comment]
The first part is available in the DFC CLI. It should be also made available in the COMDIRAC/dmeta command if nto already.
