### ISSUE TITLE
Awful stuff in InstallTools

### ISSUE THREAD

**Issue by sposs** [DIRACGrid/DIRAC#1408]
Trying to install a subclassed Agent (ILCInputDataAgent, based in InputDataAgent), but I could not install it because it did not have the string 'AgentModule' in there. Adding it in the documentation solved the problem... I fear this will cause some problems in the future...

**Comment by fstagni** [comment]
Is this still valid?

**Comment by chaen** [comment]
I guess it should be closed. Without the discussion it is difficult to know what was said, but I assume that the idea was that when installing, just look and trust what is in ConfigTemplate.cfg instead of trying to instantiate or load the actual module

**Comment by fstagni** [comment]
I agree with @chaen
