### ISSUE TITLE
[v7r0] Legacy code in WMS

### ISSUE THREAD

**Issue by ubeda** [DIRACGrid/DIRAC#1488]
I found the following methods on the different WMS Databases unused ( at least for what DIRAC and LHCbDIRAC concerns ). To be deleted ?

---------------------
**JobDB**
* getJobInfo
* countJobs
* selectJobWithStatus
* setJobParameter_old
* setJobParameters_old
* removeJobOptParameter
* removeJobFromDB
* setSandboxReady
* getUserSummaryWeb ( called at WMSAdministrator, but that service method is never called )

---------------------
**JobLoggingDB**
* getWMSTimeStamps ( called on the test testJobLoggingDB )

---------------------
**PilotAgentsDB**
* getExePilotsForJob
* getPilotsForJob
* getPilotCurrentJob
* getPilotOwner

---------------------
**SandboxMetadataDB**
* accessedSandboxByLocation
* setLocation

---------------------
**TaskQueueDB**
* findOrphanJobs
* getPrivatePilots
* propagateTQSharesIfChanged
* modifyJobsPriorities

**Comment by fstagni** [comment]
Cleanup in https://github.com/DIRACGrid/DIRAC/pull/2230
