### ISSUE TITLE
Overwrite RSS resource status

### ISSUE THREAD

**Issue by phicharp** [DIRACGrid/DIRAC#1495]
One may need in special components to overwrite the RSS  status. For example the ProductionCleaningAgent needs to delete replicas that are at SEs that are permanently protected against removal (e.g. ARCHIVE). For this it is proposed that a local CS can be used that would take precedence over the RSS, for example:

Systems
{
   Resources
   {
       CERN-ARCHIVE
       {
           RemoveAccess = Active
       }

It would avoid having to manually change the permissions, and also restrict them to specific components...

**Comment by fstagni** [comment]
I think this has been solved, after mutual agreement between me and Chris, by https://github.com/DIRACGrid/DIRAC/pull/2222
