### ISSUE TITLE
Installing services from extensions

### ISSUE THREAD

**Issue by sposs** [DIRACGrid/DIRAC#1502]
Now, to install a service, the client needs to have the /DIRAC/Extension defined. But that's not systematically defined in the CS (shared installations like Lyon for example), so one needs to add it by hand both in the Server etc/dirac.cfg and in the client's etc/dirac.cfg. As the extension is always installed (because that's where the extension's service is installed), why is it necessary to have /DIRAC/Extension installed?

**Comment by atsareg** [comment]
The client needs to add Configuration data for the new service. This is done by the client in order to keep track of the author of the new CS changes. So, I would say that this is normal that the client of the service administrator is installed and configured with the necessary extensions.

**Comment by zmathe** [comment]
#2977 fix the problem
