### ISSUE TITLE
getShifterProxy needs to be VO aware

### ISSUE THREAD

**Issue by sposs** [DIRACGrid/DIRAC#1505]
It's not possible to get the right proxy as the Operations helper is not using the VO setting. I can imagine that this is tricky to implement as the code that calls this function is not necessarily aware of the VO. Nonetheless, it's a serious issue when running multi-vo installations with VO specific shifters.

**Comment by atsareg** [comment]
Agents needing shifter proxies ( we should progressively get rid of those ) must have a mandatory VO option and run one agent per VO in the multi-VO installations.

**Comment by chaen** [comment]
why do you want to get rid of those ? I don't see how you could, providing that the DFC (for write operations) needs a proxy, and not a server certificate

**Comment by chaen** [comment]
The operation helpers are now using the VO parameter, aren't they ?

**Comment by atsareg** [comment]
getShifterProxy() utility is indeed not VO aware. And we still use Shifter logic in some places ( Transformation, FTS ). The FTS logic will be fixed to be "user-oriented". I would suggest that the Transformation system is fixed to have explicit Production Manager identity in the Operations. Then we can get rid of generic Shifters altogether.

**Comment by chaen** [comment]
@andresailer is this still the case ? How about your new implementation of the TS ?

**Comment by andresailer** [comment]
Well for the original problem, I don't think there is a generic solution to this problem, as many times the VO is deduced from the shifterProxy that is present..., which is why the AuthorDN/AuthorGroup is now used to either get a proxy or for delegation for the agents in the TransformationSystem.

But this issue can be closed, I think.
