### ISSUE TITLE
Create an RSS digest mail

### ISSUE THREAD

**Issue by roiser** [DIRACGrid/DIRAC#1525]
Hi,

currently we are receiving RSS mails for every single action taken by the system. In case e.g. of banning all SEs on a site this can lead to quite a number of mails. I would like to suggest to have RSS create one summary mail, e.g.

Subject: RSS actions taken for Site <Site>

e.g. for banning SEs
                    Read                   Write                       .......
<SE1>         Active->Inactive  Active->Inactive

and below all details that are currently being sent in the mails.

cheers
Stefan

**Comment by vipersec** [comment]
@fstagni @roiser 
Pull request created here 8a26ab7114ff4de809ceb2e79e7d88b82853c4fd

**Comment by fstagni** [comment]
I realized that in the emails it is missing an indication of the setup (e.g. "LHCb-Production" or "LHCb-Certification"): without, there's no mean to distinguish if an email is for a resource monitored in one setup or another.

**Comment by vipersec** [comment]
@fstagni I created a pull request https://github.com/DIRACGrid/DIRAC/pull/2919

**Comment by fstagni** [comment]
Certified and verified.
