### ISSUE TITLE
uniqueElements

### ISSUE THREAD

**Issue by ubeda** [DIRACGrid/DIRAC#1558]
Sometimes we do not need to keep the ordered of the elements in the list, we just need them to be unique. There are cases where we use uniqueElements and we could be using set()  -or list( set() ) if a list is needed- which is **much** faster than the uniqueElements implementation.

To be identified which cases do not require ordered unique elements.

**Comment by chaen** [comment]
There is an ordered set implementation btw. It is an external module. In case we do not want to change it everywhere in the code, we could change the implementation of the DIRAC uniqueElements (this ordered set is quite simple, it just uses a map and a double linked list )

**Comment by fstagni** [comment]
I guess you mean https://pypi.python.org/pypi/ordered-set

We should verify if this is really faster then uniqueElements, and if it, change to it.

**Comment by vipersec** [comment]
I created a pull request here: https://github.com/DIRACGrid/DIRAC/pull/2853
