### ISSUE TITLE
BUG: duplicated items on InstallTools.getSoftwareComponents

### ISSUE THREAD

**Issue by ubeda** [DIRACGrid/DIRAC#1591]
Calling the method:

```
InstallTools.getSoftwareComponents( [ 'LHCb' ] )[ 'Value' ][ 'Services' ][ 'ResourceStatus' ]

['ResourceManagement', 'Publisher', 'ResourceStatus', 'ResourceManagement', 'Publisher']
```

Returns a list which allows duplicated items ( as they are on DIRAC and LHCbDIRAC ). It can be easily fixed using a set instead of a list, but I do not know if the method is returning duplicates on purpose or by mistake.

What do you think @graciani ?

**Comment by fstagni** [comment]
Invalid as of today.
