### ISSUE TITLE
Problem checking permissions in FC

### ISSUE THREAD

**Issue by phicharp** [DIRACGrid/DIRAC#1604]
When checking permissions for a list of files in the FC (in fact checking whether the directory has write permission), the check is not properly done. In addition if the permission is not correct for a single file in a list, the whole list is rejected… 
This requires fixing the RM and the catalog client. The latter is the most delicate (LFC and DFC) but is less urgent than the RM.
In the RM: files with bad permission should just be added to ['Failed'] and not return S_ERROR()
In the FC: if the file exists, its permission is checked as it should be that of the directory. For multiple files, better get a list of directories first rather than check many times the same directory as now...

**Comment by chaen** [comment]
I believe this is fixed (VOMSPolicy + other fixes). @phicharp can you confirm ?

**Comment by phicharp** [comment]
AFAIR it is fixed indeed!... but so long agooooooo!
