### ISSUE TITLE
Automatic allocation of Port for new service install

### ISSUE THREAD

**Issue by sposs** [DIRACGrid/DIRAC#171]
To limit the struggle for administrators, could it be possible that when a service is installed using the CLI, in the case the Port is not defined, the SystemAdmin allocates a port automatically? It would need to assume things like a port range (normally setup as one block). I was thinking that the first 2 services to install (the Sysadmin and the CS) could have the extreme ports (9200 and 9300 for example). That would help as any new service would fall in between. Moreover, the sysadmin should know about installed services and used ports, so it could in principle do that.

Thanks!

**Comment by chaen** [comment]
I guess this can be closed. Especially with all the mesos/kubernetes setup
