### ISSUE TITLE
DB monitoring

### ISSUE THREAD

**Issue by ubeda** [DIRACGrid/DIRAC#1721]
Discussed privately with @acasajus 

it would be great to monitor the databases as we do with the services ( number of queries, connections, etc... )

Ping Luca, as he can probably enlighten us on which metrics would be interesting to collect. @ltomassetti

**Comment by chaen** [comment]
Since (and for good reasons :-) ), MySQL will not be distributed with DIRAC anymore, I don't think its monitoring should be part of it.

**Comment by fstagni** [comment]
I tend to agree with you. If there won't be other comments in the coming days, we may close this task.
