### ISSUE TITLE
DIRAC.GetFile with wildcard

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#1793]
(from Alexander Richards)

Exposed in the API is the 'getFile' method of API.Dirac. This it seams does work for a list of files but not for a wildcard. I note also that you have a method 'getFilesFromDirectory' in DataManagementSystem/Client/ReplicaManager.py.. This it seems is capable of accepting a wildcard. Would it be possible to have this exposed in the API or the getFile method to include wildcards?

**Comment by chaen** [comment]
Can be closed I believe, Andrei implemented it
