### ISSUE TITLE
Efficiency plots limited to 100%

### ISSUE THREAD

**Issue by phicharp** [DIRACGrid/DIRAC#1863]
The CPU efficiency plot is limited to 100%. Although this may appear reasonable, it doesn't allow us to monitor user jobs that eventually use more than 100% of CPU because they are multithreaded.
For multi-core jobs, it would be worth foreseeing an accounting of the number of cores available otherwise the efficiency will also be larger than 100% (wall-clock time should be multiplied by the number of cores).

**Comment by fstagni** [comment]
v7r1p17.
