### ISSUE TITLE
Review the JobDB structure and usage

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#1898]
The JobDB structure should be checked for:
- move to InnoDB
- for performance: SLOW queries identification
  in similar fashion to what has been done for TransformationDB.

Still to be decided to which release targeting the changes.

This task should be used to contain the notes of the evaluation.

**Comment by chaen** [comment]
wasn't this done ?

**Comment by fstagni** [comment]
No, this has not been finished.

**Comment by fstagni** [comment]
Indeed, re-checking this now, in 2014 already we moved to InnoDB and we added FOREIGN keys.

**Comment by chaen** [comment]
So it can be closed, correct ?

**Comment by atsareg** [comment]
yes, can be closed
