### ISSUE TITLE
Lock in the RequestExecutingAgent

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#1901]
Hi,

We would like to get more feedback on this.
 From observations so far, seems that the agent becomes stuck when new requests arrive, after some period of idleness.

A quick reminder:The RequestExecutingAgent is using ProcessPool utility to create slave workers (subprocesses running RequestTask) desingnated to execute requests read from ReqDB. Each worker is processing a separate request from a queue (shared between the ProcessPool and all workers). The documentation on the ProcessPool is here:
https://github.com/DIRACGrid/DIRACDocs/blob/master/source/DeveloperGuide/Utilities/ProcessPool/index.rst

When the agent is stuck, attaching a debugger or strace to the agent itself just teaches us that it is stuck somewhere in the dark corner of the python interpreter. On the other hand, attaching to the worker process is very instructive:

(gdb) bt
#0  0x0000003124a0d930 in sem_wait () from /lib64/libpthread.so.0
#1  0x00007fdfcf264d3a in locking_thread_callback (mode=<value optimized out>, type=<value optimized out>, file=<value optimized out>, line=<value optimized out>)
    at /tmp/dirac/ExtDIRACiWm71c/Externals/pyGSI/src/ssl/thread_safe.c:117 <--------- THIS SEEMS FISHY!!!
#2  0x00007fdfd2d3c89f in SSL_get_ex_data_X509_STORE_CTX_idx () from /opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/libssl.so.1.0.0
#3  0x00007fdfd2d3a965 in SSL_CTX_new () from /opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/libssl.so.1.0.0
#4  0x00007fdfcf2630bc in ssl_Context_New (i_method=<value optimized out>) at /tmp/dirac/ExtDIRACiWm71c/Externals/pyGSI/src/ssl/context.c:1641
[...]
#101 0x00000000004cfd5a in t_bootstrap (boot_raw=<value optimized out>) at ./Modules/threadmodule.c:428
#102 0x0000003124a079d1 in start_thread () from /lib64/libpthread.so.0
#103 0x00000031242e8b6d in clone () from /lib64/libc.so.6

There seems to be a deadlock in pyGSI. However the code is very nicely written, and Adri obviously knew what he was doing when writing it. Moreover pyGSI is used everywhere in DIRAC, so as such it is not responsible. The problem kicks in only when we use together multiprocessing and multithreading.

Looking at the internals of pyGSI, the semaphore is locked and release by a function which is given as callback to openSSL. The semaphore is actually only one element of an array (a global static C variable), but for simplification, we can consider it as a single mutex. 

We have an explanation on how this deadlock can happen, and why only in the RequestExecutingAgent. The principle of how a child can be stuck is as follow:

lock mutex
fork a process
in child:
 _   lock mutex (hangs forever)
in parent:
 _ do something
 _ free mutex
  
The child is stuck because when forking, it copies the whole parent process, including the locked mutex. And we can find a very similar pattern here:

* The agent initializes the lock
* The agent locks the mutex for whatever communication purpose (because in the SSLTransport layer of DISET)
* The processPool in the agent creates a worker process by forking, so copies everything, including the semaphore
* If the worker process tries to acquire the lock, it will hang forever.

This explains why we observe the lock :
- only in the RequestExecutingAgent: because it is one of the only component of DIRAC using the ProcessPool
- only after a lack of activity: the ProcessPool kills the useless worker, and when there are new Requests spawns new processes, and here is the risk of copy of the locked mutex

We can prove the principle with mock examples.

Could you please give some feedback about the scenario? Especially from experts of the internals of pyGSI?

Cheers,
Chris and Daniela

**Comment by andresailer** [comment]
I guess there is no solution to the RequestExecutingAgent getting stuck in any of the newer versions (v6r13, v6r14), right?
As I encountered this issue three times in the last week, I would now write an agent that checks the age of the "current" log file and force a restart of the RequestExecutingAgent when this file is getting too old.

**Comment by chaen** [comment]
Extra protections have been added,and one can decrease the likelyhood, but I don't think that there is any ultimate solution

**Comment by fstagni** [comment]
Given the discussion here, I close this task. It can be re-opened at any time.

**Comment by chaen** [comment]
yep, I have the feeling that this documentation will never be written anyway. It's okay, I still have the piece of paper on my desk if anyone wants to come and read it :-)
