### ISSUE TITLE
[DIRAC] [v6rx] LFN normalization issue

### ISSUE THREAD

**Issue by sposs** [DIRACGrid/DIRAC#1951]
In the putAndRegister (ReplicaManager, dunno about DataManager), if the input LFN looks like /something/somethingelse//path/file (has //), the fc.exists() check part will always fail because the returned dict has a normalized LFN, where all // were replaced by /. So res['Value']['Sucessful'] will never contain the input LFN. I think the first thing to do in those methods is to sanitize the input LFN (using maybe a decorator)...

**Comment by chaen** [comment]
in v6r15. Please close
