### ISSUE TITLE
[DIRAC][v6r10] Issue with File catalogs when file system and SE directory have the same structure

### ISSUE THREAD

**Issue by sposs** [DIRACGrid/DIRAC#2021]
I know the title does look strange but it's complicated to explain in one line. 

One ILCDIRAC user reported a problem that is very annoying. The situation is as follows: He has a file system that uses the same directory conventions/names as the storage element he uses, i.e his user directory in his file system is /grid/ilc/user/u/user, and the SE path is also /grid/ilc/user/u/user. Now, for some reason, and I think the LCG bindings are behind it, if the upload fails, the local copy of the file is deleted (as if the local file was the remote). So the input is deleted!! We are still doing tests with that user as having a SE that has the same directory structure as the file system isn't very common and I cannot test this myself.

Will keep posting updates on this, possibly closing the issue at the end.

**Comment by chaen** [comment]
I believe it can be closed
