### ISSUE TITLE
PilotOutput for jobs running on the ARC-CE

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#2064]
Hi,

[Transfered from the mailing list]

I have a Dirac install (v6r11p3 with v6r11p1 for Pilot, p3 didn't work). When running jobs on ARC-CEs (which seems to work in principle) I cannot retrieve the pilot output:
When I go from PilotMonitor -> PilotOutput I get the error message: "Error: ComputingElementFactory  could not instantiate ARCComputing Element()".

Apologies if this has been fixed since then.

Regards,
Daniela

**Comment by fstagni** [comment]
This is fixed in DIRAC v6r14
