### ISSUE TITLE
Cannot download sandbox via (old) webinterface when TrustedHost only

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRAC#2077]
As discussed via e-mail (with Adri, Andrei, Zoltan, Joel).
One cannot download sandboxes via the (old) webinterfaces when the Host has only the TrustedHost property. Adding other properties is not possible for security reasons.

The webserver is running dirac version v6r10p23

**Comment by andresailer** [comment]
Any news on this?

**Comment by chaen** [comment]
Is this still needed ?

**Comment by andresailer** [comment]
In principle we (and probably others) are still running the old webinterface.

**Comment by zmathe** [comment]
It is time to use the new interface.

**Comment by zmathe** [comment]
If I remember correctly: the solution is to add the required property to the host ( I can not remember which one) or use the new interface.

**Comment by andresailer** [comment]
We will move to the new system very soon. It would have been nice if this had been fixed a year ago though...

**Comment by fstagni** [comment]
The old web interface is unsupported. Sorry but I need to close this one.
