### ISSUE TITLE
Cannot transfer large set of information in DISET

### ISSUE THREAD

**Issue by phicharp** [DIRACGrid/DIRAC#2089]
We are suffering from not being able to transfer large amounts of data with DISET due to timeouts. Sometimes BK request returns 100,000's of files and in this case we always get a timeout. It is not possible to predict how large a dataset is going to be, therefore there is nothing that can be done at the user level. 
It would be important that DISET is able to handle safely large amounts of data. Streaming is also an option (as AMGA was doing very efficiently). We checked the problem is not with the DB side but with the transfer to the client...

**Comment by fstagni** [comment]
This is a rather old task. Is it still valid? May I ask if something has been done to address it?

**Comment by zmathe** [comment]
This is still valid. This is another improvement which can be added to the framework. We "solved" this problem by retrieving in bunches instead of all. We need kind of streaming in DIRAC.

**Comment by chaen** [comment]
Since we hope to get ride of DISET one day, can we consider this a "won't fix" ?
