### ISSUE TITLE
dirac-install-XXX: flag to disable CS update

### ISSUE THREAD

**Issue by atsareg** [DIRACGrid/DIRAC#209]
For development service or agent installation it will be useful to install components in a standard way but without updating the Configuration Service ( the default behavior ). A special flag disabling the CS update should be added.

**Comment by fstagni** [comment]
Resurrecting after 4 years... is this still a valid feature request? If this is the case, I think it can be assigned to Sergio.

**Comment by fstagni** [comment]
Bump

**Comment by fstagni** [comment]
No updates, closing.
