### ISSUE TITLE
Web portal installation: bug during the dirac.cfg creation 

### ISSUE THREAD

**Issue by zmathe** [DIRACGrid/DIRAC#2099]
We have discovered when DIRAC installed first time as an LHCb extension then the dirac.cfg is not correct. In the file missing the Extensions=LHCb, LHCbWeb 
We have to add by hand this line to the dirac.cfg: Extensions = LHCb, LHCbWeb
The configuration file contains:
ExtraModules = WebAppDIRAC,LHCb,LHCbWeb
Project = LHCb

We have added the Extensions=LHCb,LHCbWeb, in order to check that the line will added to the dirac.cfg when the Extensions is present in the install.cfg file. After that we were not able to install the portal.

**Comment by fstagni** [comment]
Zoltan, does this problem still holds?

**Comment by zmathe** [comment]
I do not know. I have not installed the web portal since a while.

**Comment by fstagni** [comment]
Any news on this? Otherwise it should be closed.

**Comment by zmathe** [comment]
I do not think it is fixed... We do not see this problem, because we have not installed WebApp since a while. It is not a high priority but we have to fix.
