### ISSUE TITLE
File Catalog Client cannot handle spaces in file/directory names

### ISSUE THREAD

**Issue by twhyntie** [DIRACGrid/DIRAC#2105]
Hello,

I'm using the File Catalog client via:

```
dirac-dms-filecatalog-cli
DFC:>
```

I uploaded some files via the Python API and, due to a bug in my script, one of the directory names (set in the `outputPath` parameter in `Job.setOutputData`) contained spaces. The directory got created succesfully, but I can't do anything with it via the File Catalog Client (including deleting it with `rm`) because the interface doesn't appear to be able to handle spaces in the names.

I know spaces in filenames aren't recommended anyway, but I thought this might be worth noting...

Cheers, Tom

**Comment by chaen** [comment]
This can probably be closed too ?
