### ISSUE TITLE
ReplicaManager: define catalog to use at intanciation time

### ISSUE THREAD

**Issue by sposs** [DIRACGrid/DIRAC#212]
For the moment, the ReplicaManager creates a FileCatalog instance, where all catalogs are resolved. I have a use case where it's needed to be able to set which catalog to use: we are going in the direction to have 2 community of users (but same VO and thus resources) that do not share the same catalog (because they have there own) but still want to use the same grid framework (DIRAC). I have the idea that the catalog to use could be a workflow parameter (or JDL) (with a default that is the current behavior) and then only one catalog would be used. If I understand properly, that means setting a parameter in the __init__ of the ReplicaManager class and passing this parameter to the FileCatalog() instance...

Do you think this is possible?

Thanks.
SP

**Comment by chaen** [comment]
@fstagni you can close it is already in the DM
