### ISSUE TITLE
Core: plot the average/mean processing time of a service call

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#2138]
The RequestHandler has a method __logRemoteQueryResponse which systematically writes in the log the time it took to DIRAC to answer a query. I'd love to have the average or mean time plotted with gMonitor. All the information are there, it just needs to be sent. 

Could you please assign to the appropriate person Andrei? I suppose that would be Adri.

**Comment by fstagni** [comment]
This is something that can be part of the "dynamic component monitoring". I assign it to Sergio for the moment.

**Comment by Sbalbp** [comment]
Just making sure, has this been worked on since the issue was opened?
If not, what about reading from the CS which methods will have their average response time monitored?

**Comment by fstagni** [comment]
I really doubt that there have been any work on this task yet.

The other possibility is to have a decorator. It is less flexible, but at the same time I don't think we need a fully configurable system, since this is mostly a developer metric.

**Comment by chaen** [comment]
Was this actually implemented ?

**Comment by fstagni** [comment]
Done in https://github.com/DIRACGrid/DIRAC/pull/4120
