### ISSUE TITLE
TransformationDB.getTransformation() parameters

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#2169]
As a quick optimization, we should add the possibility to select a restricted list of parameters when calling, e.g. getTransformation()

e.g. getTransformations inside TransformationAgent only needs TransformationID, Status, Plugin, then GroupSize in TransformationPlugin, SourceSE, TargetSE, Destination, MaxFiles

The XML blob should be returned only if needed (there are not many cases)

**Comment by chaen** [comment]
@fstagni is that still needed ?
