### ISSUE TITLE
Ease large configuration changes

### ISSUE THREAD

**Issue by ahaupt** [DIRACGrid/DIRAC#2214]
Hi,

on large installations with many configured CEs and queues it is some kind of complicated and error-prone to change settings of a larger number of similar instances. Two ideas come into my mind to improve the situation:
- introduce a default section for e.g. queues / CEs / SEs, etc., so that common settings just need to be done once
- provide better scripting capabilities to modify the configuration (e.g. with dirac-configuration-cli) like: SET option x=y ON queue matching ''wildcard"

Cheers,
Andreas

**Comment by chaen** [comment]
This is in a large fraction addressed with the SE inheritance.
I will close, re-open if more user input
