### ISSUE TITLE
Pilot reference mismatching on LocalComputingElement type jobs

### ISSUE THREAD

**Issue by hmiyake** [DIRACGrid/DIRAC#2226]
Hello,

Inside DIRAC pilot, it creates pilot reference based on specific environment variables:

if os.environ.has_key( 'CONDOR_JOBID' ):
  cliParams.flavour = 'SSHCondor'
  pilotRef = 'sshcondor://'+cliParams.ceName+'/'+os.environ['CONDOR_JOBID']

However, if we use LocalComputingElement type CE (e.g. condor), the reference is generated as condor://...
and doesn't match with the reference above.

On v6r11, I found CurrentJobID is missing on pilot monitor.
Could you have the reference ID match?

Best Regards,
Hideki

**Comment by hmiyake** [comment]
Dear Andrei,

Thank you for addressing to the issue.
Actually, we also found several additional issues relevant to LocalComputingElement and condorce script.

- In LocalComputingElement._getJobStatus(), sometimes systemCall timeout occurs when SiteDirector handles lots of pilots.
Could you increase its timeout (say 100sec) or divide the jobIDList to small chunks?
If the number is configurable by CS, it is also appreciated.

- In condorce.getJobStatus(), HOLD state ("H") is not accounted and results in too much job submission if many jobs are in HOLD.
If the status is recognized as 'Waiting', SiteDirector wouldn't submit pilots more than necessary even in such case.

Regards,
Hideki

**Comment by atsareg** [comment]
Dear Hideki,
      
        Yes, this part is considerably reworked to be release in v6r13.
      I will take your observations into
      account in polishing it.
      
        Thanks a lot,
        Andrei
      
      On 04/02/15 00:48, hmiyake wrote:
    
    
      Dear Andrei,
      Thank you for addressing to the issue.
        Actually, we also found several additional issues relevant to
        LocalComputingElement and condorce script.
      
        
          In LocalComputingElement._getJobStatus(), sometimes
            systemCall timeout occurs when SiteDirector handles lots of
            pilots.
            Could you increase its timeout (say 100sec) or divide the
            jobIDList to small chunks?
            If the number is configurable by CS, it is also appreciated.
        
        
          In condorce.getJobStatus(), HOLD state ("H") is not
            accounted and results in too much job submission if many
            jobs are in HOLD.
            If the status is recognized as 'Waiting', SiteDirector
            wouldn't submit pilots more than necessary even in such
            case.
        
      
      Regards,
        Hideki
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by fstagni** [comment]
Hi, this is rather old, and without updates lately. Is it still a valid issue or it has been addressed in previous releases?

**Comment by fstagni** [comment]
Too old, no comments, maybe solved. Closing.
