### ISSUE TITLE
New SE attribute required

### ISSUE THREAD

**Issue by phicharp** [DIRACGrid/DIRAC#2267]
Currently we do not allow any job to use the Failover replica of a file. However we may also be willing to e.g. disallow using the tape replica of a file, without banning the tape SE. 
For this purpose we propose to add an attribute to the SE:
UsableByWMS
for example... The default would be True, but it would be set to False in all FAILOVER SEs and possibly others (e.g. ARCHIVE), which would allow to remove the permanent banning of ARCHIVE in read (this would  be useful for restoring archived datasets).

**Comment by phicharp** [comment]
Andrei, please assign it to me...

I'll add here info on the implementation we are discussing with Chris.

Thanks!

**Comment by atsareg** [comment]
We should discuss the implementation. A single boolean UsableByWMS is probably not informative enough and certainly VO dependent. I would better consider a list, let say, Propeties which can have values like Failover, Tape, etc. Then these properties are interpreted by the WMS code with some "usability" rule.

**Comment by phicharp** [comment]
After discussion with Chris, the proposed implementation is to not have this information in the Resources section as it is an operational parameter.
For testing I have implemented it as a list of SEs or SEGroups as (names can be changed)
/Operations/<whatever>/DataManagement/SEsNotToBeUsedForJobs
/Operations/<...>/DataManagement/SEsUsedForFailover

It is then possible to define it with an SEGroup, if you already have a group like in LHCb Tier1-FAILOVER, you define it based on this and adding a new SE will require to add it at only one place.

You can look at how it is defined in the Operations section of LHCb:
      #@@-phicharp@lhcb_admin - 2015-02-16 15:06:31
      SEsUsedForFailover = Tier1-FAILOVER
      #@@-phicharp@lhcb_admin - 2015-02-16 15:06:09
      SEsNotToBeUsedForJobs = Tier1-FAILOVER
      SEsNotToBeUsedForJobs += Tier1-ARCHIVE

The usage would be like:

In [1]: from DIRAC.DataManagementSystem.Utilities.CSHelpers import CSHelpers
In [2]: h = CSHelpers()
In [3]: h.isSEForJobs('CERN-ARCHIVE')
Out[3]: False
In [4]: h.isSEForJobs('CERN-DST-EOS')
Out[4]: True
In [5]: h.isSEFailover('CERN-DST-EOS')
Out[5]: False
In [6]: h.isSEFailover('CERN-EOS-FAILOVER')
Out[6]: True

**Comment by fstagni** [comment]
Can this be considered as closed?

**Comment by phicharp** [comment]
I have to check! ;-)

**Comment by chaen** [comment]
yes it can, please close
