### ISSUE TITLE
Different methods between DFC and LFC

### ISSUE THREAD

**Issue by phicharp** [DIRACGrid/DIRAC#2284]
We have a major problem with the method getDirectoryMetadata that has two different meanings in LFC and DFC an return completely different information..

* LFC: this is the metadata (in the POSIX sense) of the directory, similar to getFileMetadata
* DFC: returns the user metadata of the metadata part of the DFC

This was completely overlook.
Fortunately it is only used in LHCbDirac at one place and we will try and find a workaround.

However it is not acceptable to have the asme method implemented for different purposes in 2 catalogs... We didn't check for other catalogs...

**Comment by phicharp** [comment]
Also getDirectorySize doesn't return the same information... Here the LFC implementation was a bit "ad-hoc" in returning also the number of subdirectories and files, but this is what it is :(

**Comment by phicharp** [comment]
To illustrate these are the keys of the returned dictionaries for LFC and DFC

In [13]: lfc['Value']['Successful'] ['/lhcb/data/2012/RAW/FULL/LHCb/COLLISION12'].keys()
Out[13]: ['Files', 'TotalSize', 'SubDirs', 'ClosedDirs', 'SiteUsage']

In [14]: dfc['Value']['Successful'] ['/lhcb/data/2012/RAW/FULL/LHCb/COLLISION12'].keys()
Out[14]: ['LogicalFiles', 'LogicalDirectories', 'LogicalSize']

Clearly the functionality is not the same!
Even worse for getDirectoryMetadata:

In [19]: lfc
Out[19]: 
{'OK': True,
 'Value': {'Failed': {},
  'Successful': {'/lhcb/data/2012/RAW/FULL/LHCb/COLLISION12': {'Checksum': '',
    'ChecksumType': '',
    'CreationDate': datetime.datetime(2013, 4, 9, 8, 43, 45),
    'GUID': '',
    'Mode': 365,
    'ModificationDate': datetime.datetime(2012, 12, 6, 1, 56, 1),
    'NumberOfSubPaths': 3679,
    'OwnerDN': '/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=rsantana/CN=691977/CN=Renato Santana',
    'OwnerRole': 'lhcb/Role=production',
    'Size': 0,
    'Status': '-'}}}}

In [20]: dfc
Out[20]: 
{'MetadataOwner': {},
 'MetadataType': {},
 'OK': True,
 'Value': {},
 'rpcStub': (('DataManagement/FileCatalog',
   {'delegatedDN': '/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=charpent/CN=381668/CN=Philippe Charpentier',
    'delegatedGroup': 'lhcb_prmgr',
    'keepAliveLapse': 150,
    'skipCACheck': False,
    'timeout': 120}),
  'getDirectoryMetadata',
  ('/lhcb/data/2012/RAW/FULL/LHCb/COLLISION12',))}

**Comment by atsareg** [comment]
To keep the symmetry with the LFC and File/Directory case I suggest:
1. Rename in the DFC getDirectoryMetadata() -> getDirectoryUserMetadata()
2. Expose a new  getDirectoryMetadata() equivalent to LFC. For the moment there is no such method in the service interface in the DFC although there are equivalent methods in the underlying DB classes ( getDirectoryParameters() ).

**Comment by phicharp** [comment]
Continuing with listDirectory(), again different information returned:

In [50]: lfcRes['Value']['Successful'][d].keys()   
Out[50]: ['Files', 'SubDirs', 'Links']

In [51]: dfcRes['Value']['Successful'][d].keys()
Out[51]: ['Files', 'Datasets', 'SubDirs', 'Links']

Up to here nothing special, just 'Datasets' added, but...

In [46]: dfcRes['Value']['Successful'][d]['Files'].values()[0]
Out[46]: 
{'MetaData': {'Checksum': '42263431',
  'ChecksumType': 'Adler32',
  'CreationDate': datetime.datetime(2012, 12, 4, 5, 21, 59),
  'FileID': 78043757L,
  'GID': 2695L,
  'Mode': 436,
  'ModificationDate': datetime.datetime(2012, 12, 4, 5, 21, 59),
  'Owner': 'rsantana',
  'OwnerGroup': 'lhcb_prod',
  'Size': 3145742292L,
  'Status': 'AprioriGood',
  'Type': 'File',
  'UID': 20038L}}

In [47]: lfcRes['Value']['Successful'][d]['Files'].values()[0]
Out[47]: 
{'MetaData': {'GUID': 'f716e720-3df0-11e2-8985-00259011312c',
  'Mode': 436,
  'Size': 2985803532},
 'Replicas': {'CERN-RAW': {'PFN': 'srm://srm-lhcb.cern.ch/castor/cern.ch/grid/lhcb/data/2012/RAW/FULL/LHCb/COLLISION12/133629/133629_0000000035.raw',
   'Status': '-'},
  'RAL-RAW': {'PFN': 'srm://srm-lhcb.gridpp.rl.ac.uk/castor/ads.rl.ac.uk/prod/lhcb/data/2012/RAW/FULL/LHCb/COLLISION12/133629/133629_0000000035.raw',
   'Status': 'U'}}}

**Comment by phicharp** [comment]
Another very annoying feature of the DFC:

In [72]: d = '/lhcb/data/2012/RAW/FULL/LHCb/'
In [74]: dfcRes = dfc.listDirectory(d)
In [82]: dfcRes['Value']['Successful'].keys()
Out[82]: ['/lhcb/data/2012/RAW/FULL/LHCb']

As you can see the key of the returned value is not the value used to call the method... This is really nasty. It is not complicated to keep internally the list and create the expected return dictionary even though internally there is no / at the end.
It is easier than always normalizing the directories...

**Comment by atsareg** [comment]
As for the listDirectories() in DFC you can call it with a second argument "verbosity" ( False by default ) which returns more or less information. In non-verbose case it is not returning replicas, for example. LFC client always returns replicas. So, this flag is not interpreted the same way.

**Comment by atsareg** [comment]
As for the LFN normalization - there was a long discussion on that in #1951. So, the views are varying. Please, have a look at it, and come up with your suggestion afterwards.

**Comment by phicharp** [comment]
This is not the most important... The most important is that the functionality is different...
How do I get the owner of a directory in the DFC, its creation date.. anything usually called metadata? getDirectoryMetadata() doesn't, so what?
That method should return the directory metadata and not the "user metadata"

For the LFC:
In [199]: lfc.getDirectoryMetadata(d)
Out[199]: 
{'OK': True,
 'Value': {'Failed': {},
  'Successful': {'/lhcb/data/2012/RAW/FULL/LHCb': {'Checksum': '',
    'ChecksumType': '',
    'CreationDate': datetime.datetime(2013, 4, 9, 8, 42, 44),
    'GUID': '',
    'Mode': 365,
    'ModificationDate': datetime.datetime(2012, 12, 15, 17, 24, 26),
    'NumberOfSubPaths': 8,
    'OwnerDN': '/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=rsantana/CN=691977/CN=Renato Santana',
    'OwnerRole': 'lhcb/Role=production',
    'Size': 0,
    'Status': '-'}}}}

**Comment by phicharp** [comment]
Another strange feature:
when calling getDirectorySize(d), I understand one can call it with additional arguments to get the storage usage... However these cannot be passed as keyed arguments 
getDirectorySize(d, longOut = True) doesn't work and doesn't fail...
getDirectorySize(d, True) works

I strongly suggest to implement all methods in the FileCatalogClient. Firstly it will document the signature, allow ipython to tab-complete and parse optional arguments correctly... It should not be that a big deal, right?

**Comment by phicharp** [comment]
Can't you just change getDirectoryMetadata into getDirectoryUserMetadata (as for files) and implement a getDirectoryMetadata() that returns the real metadata?

I have almost reimplemented the StorageUsageAgent using the DFC, just missing getting the owner and the creation date....

**Comment by atsareg** [comment]
I suggested to do that (implement getDirectoryMetadata) in the above comment, I think this is what you want. So, far nobody using DFC needed the getDirectoryMetadata(). 

As for the getDirectorySize(), what you suggest can be done. Note that the semantics of getDirectorySize() in LFC and DFC turned to be different ( non-recursive vs recursive summary )

**Comment by andresailer** [comment]
We are using getDirectoryMetadata in ILCDIRAC. But as long as it is clearly mentioned in the release notes.

**Comment by chaen** [comment]
I believe this can be closed as well
