### ISSUE TITLE
RequestFinalizationAgent cleaning Replicas while they are inserted to the DB

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRAC#2314]
The RequestFinalizationAgent is removing entries in the CacheReplicas table while they are being inserted via the dirac-stager-stage-files script. This is especially prevalent when a large list of files is requested to be staged. 
Would it be reasonable to add a delay for the Cleanup of CacheReplicas for entries younger than an hour or so? (e.g., this line https://github.com/DIRACGrid/DIRAC/blob/rel-v6r12/StorageManagementSystem/DB/StorageManagementDB.py#L1076)

**Comment by andresailer** [comment]
Bump.
Can someone confirm this is a bug?

**Comment by fstagni** [comment]
Daniela is, I believe, not anymore in the loop. I assign Chris.

**Comment by chaen** [comment]
oops, sorry I only see this now... Looking at the Line you mention, isn't the problem coming from a too short PinExpiryTime ?

**Comment by andresailer** [comment]
Where is that PinExpirySet? What is the default?
As far as I remember: I was doing dirac-stager-stage-files and looking at the db table of the StagingRequests. And while it was being filled with the new requests, the RequestFinalizationAgent was removing the Requests already.

**Comment by andresailer** [comment]
I just checked: I do have the triggers that are updating CacheReplicas.Links
So I had guessed that the CR.Links is updated too late and the Agent comes in and removes the files before the Trigger can update the Link.

**Comment by chaen** [comment]
It comes from the option PinLifetime of the StageRequestAgent

**Comment by andresailer** [comment]
I don't have this option defined and the default is 1 day. So that cannot be the problem. because the entries were removed  within a few minutes of being added to the system.

**Comment by chaen** [comment]
Hum, I must say it is a system I don't really know, and I hadnt looked much further than the line you mention, but in that case, I would say it comes more from https://github.com/DIRACGrid/DIRAC/blob/rel-v6r12/StorageManagementSystem/DB/StorageManagementDB.py#L1115

Yes we could add a WHERE clause here regarding the SubmitTime time. Would you have the mean to test it if I give you a fix ?

**Comment by andresailer** [comment]
Yes, I can test it.

**Comment by fstagni** [comment]
Dear @chaen  and @andresailer can this issue be considered closed?

**Comment by andresailer** [comment]
Uhh, no I still need to test this

**Comment by fstagni** [comment]
2 years after, can this be closed?

**Comment by andresailer** [comment]
Yes, If it happens again, I'll pick up things...
