### ISSUE TITLE
MySQL configuration

### ISSUE THREAD

**Issue by hmiyake** [DIRACGrid/DIRAC#2342]
Hello,

I realized recent DIRAC doesn't allow MySQL tuning by configuration file:

https://github.com/DIRACGrid/DIRAC/pull/2146

However, --no-defaults is too tight for us since our DIRAC server has large memory and we'd apply some tuning items.
How about if it is replaced with --defaults-file=/opt/dirac/mysql/.my.cnf ?

Regards,
Hideki

**Comment by atsareg** [comment]
My understanding is that adding
      --no-defaults was introduced for skipping the application of
      /etc/my.cnf
      which is often present for the system mysql installation.
      Absolutely that /opt/dirac/mysql/.my.cnf must
      be taken into account. Are you sure that these settings are not
      applied ?
      
        Cheers,
        Andrei
      
      On 24/04/15 09:30, hmiyake wrote:
    
    
      Hello,
      I realized recent DIRAC doesn't allow MySQL tuning by
        configuration file:
      #2146
      However, --no-defaults is too tight for us since our DIRAC
        server has large memory and we'd apply some tuning items.
        How about if it is replaced with
        --defaults-file=/opt/dirac/mysql/.my.cnf ?
      Regards,
        Hideki
      —
        Reply to this email directly or view it
          on GitHub.

**Comment by hmiyake** [comment]
At least it doesn't work on our environment. 
I have tried many possible paths but any my.cnf and .my.cnf were read by mysql.

Cheers,
Hideki

**Comment by graciani** [comment]
Hi Hideki,

the reading of this file (/opt/dirac/mysql/.my.cnf) is trigger by setting
HOME to /opt/dirac/mysql/ in the file mysql//share/mysql/mysql.server (that
get's fixed during the installation).

You should have something like:

# If you change base dir, you must also change datadir. These may get
# overwritten by settings in the MySQL configuration files.

basedir=
datadir=/opt/dirac/mysql/db
export HOME=/opt/dirac/mysql


Ricardo



On 24 April 2015 at 12:21, hmiyake <notifications@github.com> wrote:

> At least it doesn't work on our environment.
> I have tried many possible paths but any my.cnf and .my.cnf were read by
> mysql.
>
> Cheers,
> Hideki
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DIRACGrid/DIRAC/issues/2342#issuecomment-95883006>.
>



-- 
================================================================================

Ricardo Graciani Diaz

Dept. Estructura i Constituents de la Materia
Facultat de Fisica                              Tel:  +34 93 403 9183
Universitat de Barcelona                 Fax: +34 93 403 7063

Diagonal, 645
E-08028 Barcelona

================================================================================

**Comment by hmiyake** [comment]
Hi Ricardo,

Our mysql.sever already points the /opt/dirac/mysql as HOME.

basedir=/opt/dirac/versions/v6r12p28_1425405947/Linux_x86_64_glibc-2.12
datadir=/opt/dirac/mysql/db
export HOME=/opt/dirac/mysql

We haven't modified any relevant file other than .my.cnf, thus both basedir and datadir are given value by InstallTools.

Cheers,
Hideki

**Comment by graciani** [comment]
And what does "my_print_defaults" reports, typically you should see towards
the end something similar to:

Default options are read from the following files in the given order:
/etc/my.cnf /etc/mysql/my.cnf  ~/.my.cnf


where HOME=/opt/dirac/mysql implies that the last file becomes:

/opt/dirac/mysql/.my.cnf

This will work provided that there are not conflicting settings in the
other .cnf files that appear before.

Regards

Ricardo


On 27 April 2015 at 11:52, hmiyake <notifications@github.com> wrote:

> Hi Ricardo,
>
> Our mysql.sever already points the /opt/dirac/mysql as HOME.
>
> basedir=/opt/dirac/versions/v6r12p28_1425405947/Linux_x86_64_glibc-2.12
> datadir=/opt/dirac/mysql/db
> export HOME=/opt/dirac/mysql
>
> We haven't modified any relevant file other than .my.cnf, thus both
> basedir and datadir are given value by InstallTools.
>
> Cheers,
> Hideki
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DIRACGrid/DIRAC/issues/2342#issuecomment-96587645>.
>



-- 
================================================================================

Ricardo Graciani Diaz

Dept. Estructura i Constituents de la Materia
Facultat de Fisica                              Tel:  +34 93 403 9183
Universitat de Barcelona                 Fax: +34 93 403 7063

Diagonal, 645
E-08028 Barcelona

================================================================================

**Comment by hmiyake** [comment]
Hi Ricardo,

My point is "What is read by mysqld_safe under --no-defaults".
If $HOME/.my.cnf is read in correct system, something should be wrong in our environment.

Cheers,
Hideki

**Comment by graciani** [comment]
Hi Hideki,

the script that it is used by DIRAC to start mysql is

$DIRACROOT/mysql//share/mysql/mysql.server

and given the same environment "my_print_defaults" should report the actual
values used by "mysqld_safe"

How are you starting MySQL in your installation?

Ricardo


On 27 April 2015 at 19:54, hmiyake <notifications@github.com> wrote:

> Hi Ricardo,
>
> My point is "What is read by mysqld_safe under --no-defaults".
> If $HOME/.my.cnf is read in correct system, something should be wrong in
> our environment.
>
> Cheers,
> Hideki
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DIRACGrid/DIRAC/issues/2342#issuecomment-96757894>.
>



-- 
================================================================================

Ricardo Graciani Diaz

Dept. Estructura i Constituents de la Materia
Facultat de Fisica                              Tel:  +34 93 403 9183
Universitat de Barcelona                 Fax: +34 93 403 7063

Diagonal, 645
E-08028 Barcelona

================================================================================

**Comment by hmiyake** [comment]
Hi Ricardo,

We are using control script given by DIRAC installation page:
http://diracgrid.org/files/docs/AdministratorGuide/InstallingDIRACService/index.html

The script invokes mysql.server which was modified by InstallTools.

$ my_print_defaults --no-defaults --basedir=/opt/dirac/versions/v6r12p28_1425405291/mysql --datadir=/opt/dirac/mysql/db --user=dirac --log-error=/opt/dirac/mysql/db/can66.cc.kek.jp.err --pid-file=/opt/dirac/mysql/db/can66.cc.kek.jp.pid
$

Cheers,
Hideki
