### ISSUE TITLE
The FileCatalogCLI doesn't work for certain actions

### ISSUE THREAD

**Issue by phicharp** [DIRACGrid/DIRAC#2363]
Due to an inconsistency in the way to change owner or set permissions to files and directories in the DFC, the CLI command chown or chmod doesn't work properly...
Could this be fixed please?

**Comment by chaen** [comment]
To be more specific, changing a directory (Mode, Owner, Group) does not have the same interface as the files. 
For directory, the parameter should be  { 'myLFN' : {'Mode' : 0o755} }, while for Files it should be {'myLFN' : 0o755}. Same goes for Owner and Group

**Comment by phicharp** [comment]
In addition the "recursive = True" options should be implemented in an efficient way.

Any assignment of this issue? Is it considered normal?

**Comment by atsareg** [comment]
I have the recursive implementation already coded but not yet properly tested to go in v6r13. It is quite a lot of code changes. So, normally should go into v6r14.

**Comment by phicharp** [comment]
Thanks Andrei!
What about the initial issue that is a real pain...

**Comment by atsareg** [comment]
Yes, this one I will try to fix quickly

**Comment by atsareg** [comment]
Fixed in v6r13
