### ISSUE TITLE
Error for Replication Transformation (broadcast plugin) and parameters as Tuples

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRAC#2405]
If one creates a Replication Transformation and passes the source or target SE as tuples (instead of lists), things start to break (the sql statements is broken because the tuple is weirdly interpreted later on.

Maybe Transformation.__setSE should check for tuples and convert them to lists?

Also the version in v6r11 and v6r12 are different, but it seems this is only due to the different merging of the same branch...

**Comment by phicharp** [comment]
Frankly, this is awful code, right!
I'll try and include a quick fix in my current PR...
B.t.w. thanks for commenting it ;-)

**Comment by fstagni** [comment]
I guess this can be closed now, right?

**Comment by andresailer** [comment]
I think there is still something wrong with the _Broadcast function in TransformationPlugin.
(https://github.com/DIRACGrid/DIRAC/blob/rel-v6r13/TransformationSystem/Agent/TransformationPlugin.py#L69)
Why are sourceSE and targetSE parameter treated differently?
```python
    targetseParam = self.params['TargetSE']
    targetSEs = []
    sourceSEs = eval( self.params['SourceSE'] )
    if targetseParam.count( '[' ):
      targetSEs = eval( targetseParam )
    elif type(targetseParam)==type([]):
      targetSEs = targetseParam
    else:
      targetSEs = [targetseParam]
```
sourceSEs is just eval'ed but targetSEs lots of things are checked.

**Comment by sposs** [comment]
Hi Andre,
AFAIR, this is because the Source SE isn't really used... I added the other
checks because eval is evil.

Cheers,
S Poss

Le jeu. 25 juin 2015 à 13:49, andresailer <notifications@github.com> a
écrit :

**Comment by sposs** [comment]
Ok, sorry, it is used in line 100. There is another reason: the way those
are stored in the DB. They aren't handled the same way...

**Comment by andresailer** [comment]
To me the two variables' contents look very similar when they are being defined.
There used to be checks for sourceSEs as well
https://github.com/DIRACGrid/DIRAC/blob/rel-v6r11/TransformationSystem/Agent/TransformationPlugin.py#L86
But they were just ignored because in line 100 sourceSEs gets overwritten again.
Maybe the checks for targetSE params can be dropped as well?

**Comment by sposs** [comment]
I remember there were some nasty effects with the eval. Now some parts of
the TransformationAgent have been changed and it's very possible that none
of this is needed anymore. At least I hope, because it's ugly code...

Le jeu. 25 juin 2015 à 14:28, andresailer <notifications@github.com> a
écrit :
