### ISSUE TITLE
Feature Request: FileCatalogCLI: execfile, EOF

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRAC#2432]
As I requested at the 4th (SIC) Dirac user workshop it would be nice to have a execfile method to execute a list of commands for the FC-CLI.
It would also be good if (all) the CLIs would understand the EOF (CTRL-D) character(?).

Currently I do
```
dirac-dms-filecatalog-cli < inputfile > output
```
which works nicely, as long as I don't forget to add "exit" as the last line of inputfile.

**Comment by afortiorama** [comment]
Hi - I have the same problem.
