### ISSUE TITLE
VOMSProxy table not cleaned properly

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#2496]
When removing a proxy from the web portal (but most probably not only), it only cleans the "DIRAC only" proxy, but the proxy with the VOMS extension stored in the separate table is not removed, and still picked up.

**Comment by chaen** [comment]
Any progress on this ? It is quite a problematic bug

**Comment by chaen** [comment]
This has severely screwed us again with the RFC/VOMS proxy bug of yesterday's release. I guess I will fix it at some point... then whoever can assign it to me, I guess...

**Comment by atsareg** [comment]
fixed in v6r15

**Comment by fstagni** [comment]
For reference: is this fixed in https://github.com/DIRACGrid/DIRAC/pull/2648 ? This one https://github.com/atsareg/DIRAC/commit/6111ae1d0c24648b514dda67d14107091831dbad specifically ?

**Comment by atsareg** [comment]
Yes, the VOMS proxy deletion is fixed
      here, it is mixed with some other stuff which was not good
      actually.
      I think this part cn be ported back to v6r14. I will see to do it
      together with the next patch.
      
        Cheers,
        Andrei
      
      On 03/02/16 10:29, fstagni wrote:
    
    
      For reference: is this fixed in #2648
        ? This one atsareg@6111ae1 specifically
        ?
      —
        Reply to this email directly or view
          it on GitHub.
