### ISSUE TITLE
[v6r12/v6r13] Different SEs Classes return different file Metadata, DownloadInputData fails

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRAC#2502]
In this file: DIRAC/WorkloadManagementSystem/Client/DownloadInputData.py (both v6r12 and 13 very similar)

``` python
        result = StorageElement( seName ).getFileMetadata( lfn )
        if not result['OK']:
          self.log.error( "Error getting metadata", result['Message'] )
          failedReplicas.add( lfn )
          continue
        if lfn in result['Value']['Failed']:
          self.log.error( 'Could not get Storage Metadata for %s at %s: %s' % ( lfn, seName, result['Value']['Failed'][lfn] ) )
          failedReplicas.add( lfn )
          continue
        metadata = result['Value']['Successful'][lfn]
        if metadata['Lost']:
          error = "PFN has been Lost by the StorageElement"
        elif metadata['Unavailable']:
          error = "PFN is declared Unavailable by the StorageElement"
        elif seName in tapeSEs and not metadata['Cached']:
          error = "PFN is no longer in StorageElement Cache"
        else:
```

It tries to access the metadata keys: Lost, Unavailable and Cached
which are available for files on SRM SEs (SE Class SRM2Storage)

```
{'OK': True,
 'Value': {'Failed': {},
           'Successful': {'/ilc/prod/clic/365gev/sscssc_o/ILD/REC/00005447/000/sscssc_o_rec_5447_9.slcio': {'Cached': 1,
                                                                                                            'Checksum': 'e4558c2a',
                                                                                                            'Directory': False,
                                                                                                            'File': True,
                                                                                                            'Lost': 0,
                                                                                                            'Migrated': 1,
                                                                                                            'Mode': 420,
                                                                                                            'Size': 357496972L,
                                                                                                            'Unavailable': 0}}}}
```

However, the EOS SEs give different metadata.
in v6r13 using the GFAL2_XROOT Storagelement I get this from getFileMetadata

```
{'OK': True,
 'Value': {'Failed': {},
           'Successful': {'/ilc/prod/clic/1.4tev/tt/gen/00005486/000/tt_gen_5486_84.stdhep': {'Checksum': '',
                                                                                              'Directory': False,
                                                                                              'Executable': False,
                                                                                              'File': True,
                                                                                              'FileSerialNumber': 1152921504606898943,
                                                                                              'GroupID': 1018,
                                                                                              'LastAccess': '2015-07-14 19:01:30',
                                                                                              'Links': 1,
                                                                                              'ModTime': '2015-07-14 19:01:30',
                                                                                              'Mode': 256,
                                                                                              'Readable': True,
                                                                                              'Size': 1484196L,
                                                                                              'StatusChange': '2015-07-14 19:01:30',
                                                                                              'UserID': 45181,
                                                                                              'Writeable': False}}}}
```

in v6r12 with the same StorageElement defined as XROOT I get this from getFileMetadata

```
{'OK': True,
 'Value': {'Failed': {},
           'Successful': {'/ilc/prod/clic/1.4tev/tt/gen/00005486/000/tt_gen_5486_84.stdhep': {'Directory': False,
                                                                                              'Executable': False,
                                                                                              'File': True,
                                                                                              'Id': '1152921504606898943',
                                                                                              'ModTime': 1436893290,
                                                                                              'ModTimeStr': '2015-07-14 17:01:30',
                                                                                              'Offline': False,
                                                                                              'Other': False,
                                                                                              'PoscPending': False,
                                                                                              'Readable': True,
                                                                                              'Size': 1484196,
                                                                                              'Writable': False}}}}
```

No Lost, Cached, Unavailable keys in the dictionary.

Should the Xroot getFileMetadata functions be changed to add these keys to their metadata dicts?

Here is my testscript for v6r12 (in v6r13 add vo parameter for SE)

``` python
import pprint
def run():
  from DIRAC.Core.Base.Script import parseCommandLine
  parseCommandLine()
  from DIRAC.Resources.Storage.StorageElement                         import StorageElement
  se = StorageElement( "CERN-DST-EOS" )
  lfn = "/ilc/prod/clic/1.4tev/tt/gen/00005486/000/tt_gen_5486_84.stdhep"
  result = se.getFileMetadata(lfn)
  print "Result EOS"
  pprint.pprint(result)

  se = StorageElement( "CERN-SRM" )
  lfn = "/ilc/prod/clic/365gev/sscssc_o/ILD/REC/00005447/000/sscssc_o_rec_5447_9.slcio"
  result = se.getFileMetadata(lfn)
  print "Result SRM"
  pprint.pprint(result)

if __name__ == "__main__":
  run()
```

**Comment by chaen** [comment]
The point here is that there is no way in xroot to interact with tape so far, so "Cached" does not make sense. I am not sure either what would "Lost" and "Unavailable" mean, since contrary to SRM, there is no metadata server in front of the storage. 
From there, there are different approaches. What I think is the correct one is to define a minimum set of information that should always be present; then, all the extra information that we can give are bonus, and should not be considered as granted by the client (unless specifying a protocol).

Adding @phicharp  for opinion

**Comment by andresailer** [comment]
Maybe I wasn't clear enough. At the moment the DownloadInputData fails with an exception, because of metadata['Lost'], when I have input data (only?) on the XROOT storage. I would like a fix for this soon.
So the least intrusive change is to change the getFileMetadata of the XROOT Storage classes.

Alternative is to check every time the metadata dict is accessed if the key exists and decide on the default action to take.

**Comment by chaen** [comment]
Either that, or replace metadata[X] with metadata.get(X) in the DownloadInputData, which I believe is more logical, since as I said, these fields do not make sense for xroot

**Comment by andresailer** [comment]
The Dirac StorageElement returns a dict including Cached, Lost, Unavailable.
https://github.com/DIRACGrid/DIRAC/blob/rel-v6r13/DataManagementSystem/Service/StorageElementHandler.py#L120
Probably more consistent to do it similarly for XRoot, instead of hunting down every place this function is used.

**Comment by chaen** [comment]
and so in the four new plugins on their way (S3, HTTP, File and GSIFTP) I should introduce this non sense as well ? 
I just checked, the only places where it is used are the Stager (obviously), the workflow, the DataIntegrity and the FTSRequest (to disappear very very soon).

In any case, as a general comment. For sake of following the ongoing evolutions, we will have to be much more flexible on the client side, and work on the best effort bases, since there are protocols that are coming (HTTP, S3, Xroot...) that do not answer specific requests. So unless on the client side we specify a protocol, we can't expect the answer to be always there.

**Comment by andresailer** [comment]
Why can't the StoragElements offer a uniform interface instead of making protocol dependent code in  other places, unless absolutely necessary?

**Comment by chaen** [comment]
I agree that a minimum set should be made uniform. But the metadata is by essence something protocol/storage specific. Don't you think so ?

**Comment by chaen** [comment]
And to be a bit more specific, there are cases where the client must ask for specific protocols. For example FTS, or Storage.  
Also, this is very new and no code is ready yet, but if we want to start supporting more generic storage than the incestuous world we are in currently (dCache, DPM, Storm and so on), we will have to start making the code aware of the capabilities of the storage which it is talking too. And the metadata which we retrieve are a specific example of this

**Comment by andresailer** [comment]
What do you mean in Storage the client has to ask for protocols? Obviously the different child classes of StorageElement implement protocol specific behaviour. In the end everybody outside of the StorageElements should be able to use a set of well defined interfaces and not care about the implementation details. So for compatibility at the moment the metadata has to contain these "nonsensical" entries.

Probably the DownloadInputData shouldn't need to worry about the metadata at all, but just ask the storageElement if the replica is ready for download, if that is because the file is cached, or anyway always on disk doesn't matter.

**Comment by phicharp** [comment]
My 2 cents: I tend to agree with André that the plugins should at least return the elements that are expected by other modules in DIRAC. As for ‘Cached’ it makes sense for any protocol that is not supporting tape to return True although it may not be true (e.g. using the XROOT plugin on Castor) but this is the best one can do. Using get(‘Cached’,???) requires a default value that can only be  True, therefore the result is the same. For ‘Lost’ or ‘Unavailable’ one can return ‘Unknown’?

**Comment by atsareg** [comment]
I would suggest to have a DIRAC
      "standard" set of elements in this dictionary that are necessary 
      for the logic of the DIRAC clients of this method. Once this is
      defined, then all the implementations
      must map any standard or specific field onto the DIRAC "standard"
      set of fields whereever appropriate
      or return some default value is the field is irrelevant for the
      implementation. This will fix the interface
      to be the same for all the implementations.
      
        Cheers,
        Andrei  
      
      On 15/07/15 19:42, Philippe Charpentier wrote:
    
    My 2 cents: I tend to agree with André that the
      plugins should at least return the elements that are expected by
      other modules in DIRAC. As for ‘Cached’ it makes sense for any
      protocol that is not supporting tape to return True although it
      may not be true (e.g. using the XROOT plugin on Castor) but this
      is the best one can do. Using get(‘Cached’,???) requires a default
      value that can only be True, therefore the result is the same. For
      ‘Lost’ or ‘Unavailable’ one can return ‘Unknown’?
      
      > Le 15 juil. 2015 à 18:41, andresailer
      <notifications@github.com> a écrit :
      > 
      > What do you mean in Storage the client has to ask for
      protocols? Obviously the different child classes of StorageElement
      implement protocol specific behaviour. In the end everybody
      outside of the StorageElements should be able to use a set of well
      defined interfaces and not care about the implementation details.
      So for compatibility at the moment the metadata has to contain
      these "nonsensical" entries.
      > 
      > Probably the DownloadInputData shouldn't need to worry about
      the metadata at all, but just ask the storageElement if the
      replica is ready for download, if that is because the file is
      cached, or anyway always on disk doesn't matter.
      > 
      > —
      > Reply to this email directly or view it on GitHub
<https://github.com/DIRACGrid/DIRAC/issues/2502#issuecomment-121673557>.
      > 
      
      
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by chaen** [comment]
Correct me if I am wrong, but I have the feeling we all agree that there should be a minimum set of metadata always returned by the plugin, and the question is "should Lost, Cached, Unavailable" be part of it ? If so, how about we define one entry, let say randomly "Accessible" (or you name it), which will always be returned, by default True, and for specific case like SRM, it could be computed as " not Lost and Cached and Not Unavaialble" ? And then in specific places like the stager, where we know we ask explicitly SRM, we could use "Cached" and so on ? How does that sound ? 
To make it easy, I could even implement the method in the StorageBase that merges it this base metadata with the output of the specific plugins.

**Comment by atsareg** [comment]
I think we are speaking about the same thing. I just suggest to look at this from the side of the caller of the getFileMetedata(): what values are needed/useful for the current and possibly future clients. Then make an abstraction of this values and implement it for each plugin by mapping specific internal plugin values onto this generic abstraction. Of course all the mentioned clients must be reviewed then to use the same abstraction.

**Comment by chaen** [comment]
Yes, then we totally agree. 
There are exceptions though. For example, in the stager, you want specific information regarding the "cached" status. But then, in the stager, we should specifically ask for srm protocol. But the general case should indeed be using these abstractions.
Andre, does that sound correct to you ?

**Comment by andresailer** [comment]
Yes, having the abstraction sounds very reasonable, as this sounds like a somewhat delicate operation, this should probably be done for v6r14 or 15?
To get EOS working in v6r12 and 13 can I again propose that we just add the the three entries to the dictionaries in XROOT and GFAL2_XROOT getFileMetadata, which is just a small patch.

**Comment by chaen** [comment]
Okay, sounds reasonable. Can I let you do the patch, and I do the final implementation ?

**Comment by andresailer** [comment]
Works for me.

**Comment by fstagni** [comment]
Can this be considered as solved?

**Comment by andresailer** [comment]
I think @chaen still wants to do a proper implementation (unless I missed it), but for me things are working

**Comment by chaen** [comment]
No no, you did not miss it, it is still on my todo list

**Comment by chaen** [comment]
Standard metadata implemented. Now it needs to be used :-) Will be done once the multiprotocol PR is merged

**Comment by fstagni** [comment]
Shall we close this task once https://github.com/DIRACGrid/DIRAC/pull/2982 will be merged?

**Comment by chaen** [comment]
No. This PR will help to make it even cleaner, but then all the client code still need to be adapted

**Comment by fstagni** [comment]
I am not sure what (and if) is left to do here. Can you comment briefly? Otherwise we close the issue.

**Comment by chaen** [comment]
It is pretty much used, although in a conservative way https://github.com/DIRACGrid/DIRAC/pull/3267
So you can close
