### ISSUE TITLE
[v6r12, 13, integration] JobDescription, JobManifest: Values taken from TaskQueueDirector Section

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRAC#2519]
When I tried to submit a job with "mode='agent'" I couldn't because I had removed the TaskQueueDirector from the CS, because the Agent is not used any more.
This resultet in an "unknown submitpool" or something message.

There are options taken from the TaskQueueDirector section.
https://github.com/DIRACGrid/DIRAC/blob/rel-v6r12/WorkloadManagementSystem/Client/JobDescription.py#L146
```python
    for option in [ "DefaultSubmitPools", "SubmitPools", "AllowedSubmitPools" ]:
      allowedSubmitPools += gConfig.getValue( "%s/%s" % ( getAgentSection( "WorkloadManagement/TaskQueueDirector" ),
                                                          option ),
                                             [] )
```
Same code in v6r13 and integration. This code is also in the JobManifest.
These options should probably be taken from somewhere else?

**Comment by fstagni** [comment]
Fixed in https://github.com/DIRACGrid/DIRAC/pull/2712 (v6r15)
