### ISSUE TITLE
RSS DonwtimeCache to be updated with removed downtimes

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#2572]
The case is the following:
- Downtime xyz is registered in GOCDB
- CacheFeederAgent cache it in ResourceManagementDB/DowntimeCache
- Downtime xyz is removed from GOCDB before it starts (or during its active period)

At the moment, downtime xyz is NOT removed from ResourceManagementDB/DowntimeCache

CacheFeederAgent (via DowntimeCommand().doNew()) should remove dowtime xyz

**Comment by avedaee** [comment]
https://github.com/avedaee/DIRAC/commit/29dd3fba3aad6619d2dace0682e04b485df04428

**Comment by fstagni** [comment]
PR: https://github.com/DIRACGrid/DIRAC/pull/2608
