### ISSUE TITLE
[integration,v6r14,v6r13,v6r12] Conditional Expressions in dirac-install.py

### ISSUE THREAD

**Issue by hmiyake** [DIRACGrid/DIRAC#2627]
Hello,

I realized recently following code was added to dirac-install.py (for integration, v6r14, v6r13, v6r12)

terminfoLocations = [ defaultLocation ] if defaultLocation else []

However the code does not work on SL5 since python 2.4 doesn't recognize the conditional expressions.
Do you still support SL5? If so, could you modify the code above?

Best Regards,
Hideki

**Comment by chaen** [comment]
Hi Hideki,

this form of code is used everywhere in DIRAC, so I would say that de facto python 2.4 is not supported.

Cheers,
Chris

**Comment by andresailer** [comment]
dirac-install.py is run to install dirac, so there is no guarantee yet that python 2.6 or 2.7 is used.
I added this ternary operator and did not realise that it would cause problems, but it can be easily replaced.

**Comment by hmiyake** [comment]
Thank you for quick reply!
Usually we are using bundled python (2.7 in case of us), but some initial scripts run on system python.

Cheers,
Hideki

**Comment by chaen** [comment]
Oh I see, sorry I misunderstood that point. Thanks for correcting me Andre

**Comment by andresailer** [comment]
@atsareg et al.
Is dirac-install.py always picked up (wget ...) from the integration branch, or is there any case where this is used from one of the release branches? Just wondering if this needs to be fixed in the release branches as well.

**Comment by andresailer** [comment]
So the SiteDirector bundles the local dirac-install.py when submitting pilots, so it needs to be fixed in v6r12 as well.
