### ISSUE TITLE
[v6r14, 15] __init__.py incorrect version number

### ISSUE THREAD

**Issue by sfayer** [DIRACGrid/DIRAC#2677]
Hi,

We've noticed on the rel-v6r14 & rel-v6r15 branches, the version number in the top-level \_\_init\_\_.py (specifically the minorVersion constant) is out-of-date, which causes the wrong version to be displayed in various places. Would it be possible for this to be fixed?

Thanks,
Simon

**Comment by fstagni** [comment]
Fixed in https://github.com/DIRACGrid/DIRAC/pull/2712 (v6r15)
