### ISSUE TITLE
Add pilot wrapper parameter for setting the pilot execution directory

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#2746]
Certain sites (CEs) needs to run pilots (and jobs) in a specific directory. This directory is set by the pilot wrapper, which is written by the SiteDirector.

We suggest that the SiteDirector checks if there is an option defined for the CE, named for example "PilotRunDirectory", and if it exists, use it for setting the run directory.

Note: it already exists a "WorkDirectory" parameter that does this job, but it's at the agent level, while it should be per-CE.

**Comment by andresailer** [comment]
Doesn't the WorkDirectory for the SiteDirector set the working directory of the SiteDirector agent and not of the pilots it submits?

One can already set some parameters (ExtraPilotOptions) at the Queue level for CEs, it would be great if these could be set at the CE/Site level as well.

**Comment by fstagni** [comment]
Yes that's the point: setting these parameters at the CE level
