### ISSUE TITLE
Provide modern, minimal build system

### ISSUE THREAD

**Issue by drbenmorgan** [DIRACGrid/DIRAC#2763]
With Dirac being (seemingly?) pure python, it would be useful if this repository could provide an installer script here using a standard Python tool like setuptools/pip. It should also allow selection of full and server or client components only.

Working through the other installer scripts, these have installed a full Python plus other components that I already have installed. It's not so much that full vendoring shouldn't be provided, just that there should be the option to install Dirac in way that can reuse existing installs. In particular, this would help in packaging it in a portable way.

I'm happy to start looking at this and submit pull requests, but would need guidance on which Python submodules belong where, what parts are client/server and a list of any external dependencies.

**Comment by fstagni** [comment]
I concur with everything said. There are, of course, historical reasons for which the situation is what it is right now, but it's not important right now. There are also some technical reasons, or at least there were. I don't know if these technical reasons still apply.  Anyway, we need to start looking better into it today, as you say. I am happy to give you all the guidance I can.

First and foremost, I don't know exactly what is your level of expertise. Anyway, you have already noticed that we have a very "old" way of doing the installations. This is done by providing 2 pre-compiled library tarballs, what we call "externals", and the "lcg bundle". The externals is what is provided by ourselves by running scripts on https://github.com/DIRACGrid/Externals, which is our old tool, developed prior to "setup.py", to create this tarball. This file https://github.com/DIRACGrid/Externals/blob/master/builds.cfg defines what goes in what tarball (I have re-worked it in this PR https://github.com/DIRACGrid/Externals/pull/8 which will be merged soon, have a look at that).

I would say that providing the "client" version would be quite possible. Regarding the "server" version, I think you may encounter harder issues, but devil is in the detail so we have to see.

Regarding the "pre-compiled" python version: this, as odd as it may seem, have some reason, mainly the fact that some old worker node (SLC5) still has as default python version 2.4. And we need at least 2.7. This creates some odd coding requirements that we better not discuss here. 

Let's keep discussing here (it would serve also as reference later) but for specific question you may contact me directly (I am the technical coordinator)

**Comment by drbenmorgan** [comment]
Thanks for the info, these look a good starting point! I'm by no means an expert on Python packaging (some experience with macports/homebrew and the various Linux tools), though I can understand the historic context of Python versions. From a cursory glance at the [Python packaging guide](https://python-packaging-user-guide.readthedocs.org/en/latest/distributing/) I *think* it should be possible to handle Python version checks and dependencies at least at the packaging level.

I think a possible starting point would be for me to try and get a `setup.py` working that just packages up all Python packages in the Dirac repo, ignoring the client/server distinction. I can also use the info supplied to see if dependency resolution would work. Does that sound reasonable? There's also the issue of the various scripts/commands like `dirac-proxy-init`, but first things first.

**Comment by fstagni** [comment]
Yes, good idea, and thanks for your kind support, appreciated! When you 
have something, don't be afraid to ask, or making directly a PR.

**Comment by chaen** [comment]
Can we close this one too ?

**Comment by fstagni** [comment]
I still want to at least change the structure of the repository. Let's leave it here as a reminder.

**Comment by chaen** [comment]
I think this relates also with the other issue I opened: https://github.com/DIRACGrid/DIRAC/issues/3523

**Comment by chaen** [comment]
Thinking of it....
I've already created a setup.py, which installs DIRAC, but without dependency. 
For unit tests, we have to install DIRAC, and then the requirements.txt
When we use DIRACOS, all what is in requirements.txt will already be installed, so we might as well install requirements.txt from the setup.py.

**Comment by fstagni** [comment]
This is on Chris Burr agenda as we have seen in https://indico.cern.ch/event/956902/

**Comment by fstagni** [comment]
Being addressed. Closing as duplicate.
