### ISSUE TITLE
[Multi VO] Trying to retrieve files from a differet VO throws a misleading error

### ISSUE THREAD

**Issue by twhyntie** [DIRACGrid/DIRAC#2790]
Hello all,

Replicating an issue I had using the GridPP DIRAC instance here:

https://github.com/ic-hep/GridPPDIRAC/issues/28

`/gridpp/userguide/WELCOME.md` was uploaded with a `-g gridpp_user` proxy. Trying to download with a different VO proxy (e.g. `-g cernatschool.org_user`) fails - _as it should_ - but with the wrong error.

``` bash
$ dirac-dms-get-file /gridpp/userguide/WELCOME.md
Failures occurred during rm.getFile 
{'Failed': {'/gridpp/userguide/WELCOME.md': 'Failed to get local copy from any replicas\nError getting file from storage: /gridpp/userguide/WELCOME.md from UKI-LT2-QMUL2-disk, LFN does not follow the DIRAC naming convention /gridpp/userguide/WELCOME.md'},
 'Successful': {}}
ERROR {'Successful': {}, 'Failed': {'/gridpp/userguide/WELCOME.md': 'Failed to get local copy from any replicas\nError getting file from storage: /gridpp/userguide/WELCOME.md from UKI-LT2-QMUL2-disk, LFN does not follow the DIRAC naming convention /gridpp/userguide/WELCOME.md'}}
```

@sfayer points out that this is technically correct, but leaves the user in the dark on how to solve it (i.e. DIRAC is expecting the VO name at the start of the LFN).

Is there a way to make the error message clearer please?

Thanks, @twhyntie

**Comment by chaen** [comment]
What error message would you have expected ? permission denied ? if you did not have it, it means your catalog allows it. So it's more a configuration issue it seems

**Comment by sfayer** [comment]
I haven't looked at this for a while, but I think you get this error if the LFN doesn't start with the VO name before any other permissions checks. Perhaps this special case could have an error along the lines of "LFN path must start with VO name" to distinguish it more clearly from any other conventions?

**Comment by chaen** [comment]
It would need to be tested, but the LFN convention is ensured by the `StorageElement` object. Before using the SE, you need to know which one SE to instantiate, and this is the `FileCatalog` telling you. And since the FileCatalog is responsible for permission checking, I would suspect a problem along these lines.

I am not sure what you mean. You want to replace `LFN does not follow the DIRAC naming convention` with `LFN path must start with VO name` ?

**Comment by sfayer** [comment]
Yes, I think we would simply like the error message changing... We occasionally get a user that has multiple VO memberships and uses the wrong one to access a file. They don't know what "LFN does not follow the DIRAC naming convention" means, so they have to ask. If they see "LFN path must start with VO name", I think they'll be able to figure it out themselves.

**Comment by chaen** [comment]
Ah ! No problem with me. I'll do it in one of the coming PR then.

**Comment by fstagni** [comment]
@chaen was this one done? (see your last reply...)

**Comment by fstagni** [comment]
Ping @chaen
