### ISSUE TITLE
Replace suds with a maintained library

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#2834]
SOAP "suds" client support seem to have stalled. Please replace it everywhere with "SOAPpy", or any other library that is actively maintained and would do the job.

**Comment by fstagni** [comment]
Actually, this package may be a better option: https://pypi.python.org/pypi/suds-jurko

It also has python 3 support.

**Comment by vipersec** [comment]
After doing some research and acording to some users in [stackoverflow](http://stackoverflow.com/a/31079508/2335593), I discovered that we can use `suds-jurko` without changing anything in the code. We just have to uninstall the old suds and install suds-jurko using `pip install suds-jurko`

**Comment by fstagni** [comment]
Ok thanks! assigning to myself then

**Comment by fstagni** [comment]
In https://github.com/DIRACGrid/Externals/pull/12
