### ISSUE TITLE
Proxy format different with openSSL 1.0.2XX

### ISSUE THREAD

**Issue by closier** [DIRACGrid/DIRAC#2838]
In certification we notice that the proxy generated with DIRAC v6r15 series is not able to use with "lcg-" commands.
To reproduce the behaviour, you login to the certification box and you do the following sequence:

ssh lbtestvobox
source /opt/dirac/bashrc
lhcb-proxy-init
lcg-ls -l -b -T srmv2 srm://srm-lhcb.gridpp.rl.ac.uk:8443/srm/managerv2?SFN=/castor/ads.rl.ac.uk/prod/lhcb/user/c/chaen/File1

and no result.

The same sequence on a production VOBOX give the information about the file.

**Comment by atsareg** [comment]
This is serious, it means that the openssl 1.0.2f library used in the v6r15 associated Externals is somehow not compatible with the current SRM service. As such, the version of the openssl in the externals should be rolled back and all the Externals rebuilt. Is it possible to look on the SRM side if there is any indication of a ssl related problem in the logs in this case ?

**Comment by atsareg** [comment]
Is there any progress in understanding this case ? Is it something to tune on the SRM server side or we have to roll back the openssl version ?

**Comment by closier** [comment]
Who is looking at it on the openssl side and on SRM side ???

**Comment by fstagni** [comment]
I assigned to Chris just to provide info. 

From basic trials, it seems it is a compatibility problem with Castor, so Chris will open a ticket against it. (please, link it from here)

**Comment by chaen** [comment]
https://cern.service-now.com/service-portal/view-incident.do?n=INC0975312

**Comment by fstagni** [comment]
Answer from developers in case you don't see the ticket:

> Most likely the issue is that the CASTOR SRM endpoint is still running on a very old SL5-based stack. In particular, the openssl RPM is openssl-0.9.8e-37.el5_11.
 

> Now  the good news is that we have just released CASTOR 2.1.16 that includes a fully integrated SRM end-point, thus compiled against the latest stack of libraries. We can plan the upgrade rather soon, at latest just after Easter. Possibly to be discussed offline.

**Comment by atsareg** [comment]
Assuming that this is the reason - is it blocking the v6r15 release ( using openssl 1.0.2f ) or we can proceed ?

**Comment by chaen** [comment]
yes, it blocks using openssl 1.0.2f

**Comment by fstagni** [comment]
Well, it does not block v6r15. But it blocks the deployment of v6r15 in 
LHCb production - and not only.

Anyway, we may think to be on the "safe" side and re-set the version of 
OpenSSL to what was before (sigh!) for v6r15, and start with newer 
version later.

**Comment by fstagni** [comment]
Can we think about upgrading openSSL version (again!) with the externals that go with DIRAC v6r19?

**Comment by chaen** [comment]
I think so. It should also help for centos7

**Comment by atsareg** [comment]
We should check that the proxy on CentOS7 and/or with the more recent openssl is still valid. There was a report from Chris about errors in the interpreting of the proxy extensions

**Comment by chaen** [comment]
Indeed. Can you please make a version of the externals with it, I will try it .

**Comment by fstagni** [comment]
Review this please: https://github.com/DIRACGrid/Externals/pull/27

I have been quite aggressive with bumping versions.

**Comment by fstagni** [comment]
Should be fixed with v6r19.
