### ISSUE TITLE
Create method to use the RSS status for all the resources

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#2856]
The RSS computes the status of several resources. As of today, these include Storage Elements, Computing Elements (CEs), FTS (FileTransfer Service), and Catalogs.

The status of Storage Elements is accessed via: 

```
from DIRAC.ResourceStatusSystem.Client.ResourceStatus import ResourceStatus
rss = ResourceStatus()
rss.getStorageElementStatus()
```

This call is used in few scripts, while the single most important place it's used is in 

```
DIRAC.Resources.Storage.StorageFactory
```

There is nowhere a method `rss.getComputingElementStatus()` nor anything for FTS and Catalog. 

As of today, the only RSS status used is the one for Storage Elements.

In order to make it possible that the RSS status for the other resources is used, we suggest to create similar methods for the other resource types.

Start by the ComputingElements, e.g. `rss.getComputingElementStatus()`. A `self.ceCache` should be used (see how `self.seCache` is used now).

**Comment by vipersec** [comment]
Pull request created: https://github.com/DIRACGrid/DIRAC/pull/2863
