### ISSUE TITLE
"dirac-rss-sync" script: sync the sites status

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#2858]
The "dirac-rss-sync" script is used for initial population of RSS "ResourceStatus" tables. It's a script to be used one and only one time: when a VO starts using RSS, or in other words when RSS is activated.

The "initSEs" function inside the script takes the status of the SEs as it appear in the CS, and populates the RSS tables. A similar function should be developed for the sites:
- `initSites()` should make the initial population of the RSS "SiteStatus" table, taking what's the current status from the "SiteMask" table (see https://github.com/DIRACGrid/DIRAC/issues/2857 for reference). The logging should be possibly also synced.

**Comment by vipersec** [comment]
Pull request created: https://github.com/DIRACGrid/DIRAC/pull/2871

**Comment by fstagni** [comment]
Merged, in prod.
