### ISSUE TITLE
Use RSS "SiteStatus" instead of "siteMask"

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#2859]
The completion of this task relies on the completion of https://github.com/DIRACGrid/DIRAC/issues/2857  first.

Once the status of the sites is in sync between SiteStatus and SiteMask, the RSS can be activated and the status inside RSS should be used: the suggestion is that, basically, everywhere there is a "getSiteMask" call (or a giteSiteMaskLogging, or its set\* counterparts) the `DIRAC.RSS.Client.SiteStatus` module is used instead of it. 

This means changing several files, but it's doable.

One note regarding the module `DIRAC.Interfaces.API.DiracAdmin`, which is part of the APIs: this module contains a few calls that indirectly look in the SiteMask, like the "getSiteMask" method: this and the other methods inside this module should not disappear, and their signature should not change.

**Comment by vipersec** [comment]
Pull request created: https://github.com/DIRACGrid/DIRAC/pull/2943

**Comment by fstagni** [comment]
Looking at the PR after today's discussion: this PR does not touch, yet, the "dirac-admin-ban-site" script, which, as of today, even after this PR, would still use the old JobDB table. These scripts all call the API `DIRAC.Interfaces.API.DiracAdmin` which didn't change: but, what was suggested was to keep these calls, while at the same time move to the `SiteClient()` methods.

Also:
- the `dirac-admin-ban-site` and `dirac-admin-allow-site` script should be renamed `dirac-admin-ban-full-site` and `dirac-admin-allow-full-site`, and should warn the user of what the script would do (waiting for a confirmation).

**Comment by vipersec** [comment]
It's done: https://github.com/DIRACGrid/DIRAC/pull/2943/commits/1b26675cd60f987f9171a590c5a4f536a17e9936
