### ISSUE TITLE
Use RSS "Computing Element" status in SiteDirector

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#2874]
The WorkloadManagementSystem SiteDirector agent submits pilot jobs to Computing Elements.

As of today, a status of a computing element does not exist, and RSS introduces it. For this reason, the SiteDirector sometimes ends up submitting to CEs that are in donwtime. 

Modify the SiteDirector to check the status of the computing element from the RSS before submitting pilot jobs.

CC @VladimirRomanovsky

**Comment by vipersec** [comment]
Pull request created: https://github.com/DIRACGrid/DIRAC/pull/2886

**Comment by fstagni** [comment]
In v6r18.
