### ISSUE TITLE
dirac.status :: take as input the output of dirac.submit

### ISSUE THREAD

**Issue by adriansev** [DIRACGrid/DIRAC#2944]
Hi! It would be useful for DIRAC users if there is an easy method for saving to file the job id (number or all output)  and the job status and get output would easily read the file and act recursively on all lines.. 
(in the same way as glite-ce-job-{output,status,submit}) work.
Thank you!

**Comment by pigay** [comment]
Hi,

The [COMDIRAC](../../COMDIRAC) module intends to ease user experience with comprehensive client commands. The `dsub` job submission command already outputs JobIDs in a comma separated list. I just wrote a PR [#58](../../COMDIRAC/pull/58) that allows `dstat`, `dinput` and `doutput` job management commands to handle this kind of lists from command line option or from a file (`-i` option).

Please, have a try and tell me if it fits.

**Comment by adriansev** [comment]
Hi! In which version should this feature appear? I use v6r15p8 and i dont see "-i" option to dstat.
Moreover, i would think that all facilities (commands or DIRAC API) should have the same output.
I use DIRAC API for job submission so it would be great if dstat/doutput  could consume a file with content like :   
{'OK': True, 'Value': 43814485}  
{'OK': True, 'Value': 43814487}  
{'OK': True, 'Value': 43814489}

**Comment by pigay** [comment]
Hi, it's available in `COMDIRAC:v0r15` which should be included in v6r15p9. I just checked with a fresh installation and got:
 ```
$ dstat -h
[...]
  -i  --input-file <value>     : read JobIDs from file 
```

Concerning the output of DIRAC API output, as I stated in #3044, JSON is not a standard output.

But it would be nice indeed if we had such a exchange format.

Maybe @atsareg or @fstagni have an idea on this?

**Comment by fstagni** [comment]
There is a slow move towards JSON in many ways, but this is far from becoming a reality any time soon.

**Comment by adriansev** [comment]
regrading -i option : 
dirac-info | grep "DIRAC version"
DIRAC version          v6r15p9

head -n 6 $DIRAC/COMDIRAC/release.notes
[v0r9]

FIX: doutput - backward compatibility with dirac.getOutputSandbox
FIX: dstat - memory footprint with many jobs
CHANGE: dget drepl dput - return non-zero error codes
CHANGE: dfind - suppress verbose output

dstat -h

Retrieve status of DIRAC jobs
Usage:
  dstat [option|cfgfile]
Arguments:

General options:
  -o  --option <value>         : Option=value to add
  -s  --section <value>        : Set base section for relative parsed options
  -c  --cert <value>           : Use server certificate to connect to Core Services
  -d  --debug                  : Set debug mode (-ddd is extra debug)
  -   --autoreload             : Automatically restart if there's any change in the module
  -   --license                : Show DIRAC's LICENSE
  -h  --help                   : Shows this help

Options:
  -u  --User <value>           : job owner
  -S  --Status <value>         : select job by status
  -a  --StatusAll              : display jobs of any status
  -g  --JobGroup <value>       : select job by job group
  -n  --JobName <value>        : select job by job name
  -f  --Fmt <value>            : display format (pretty, csv, json)
  -D  --JobDate <value>        : age of jobs to display
  -F  --Fields <value>         : display list of job fields

the update is done with : 
./dirac-install -r v6r15p9

did i missed something in update method?
Thank you!
Adrian

**Comment by pigay** [comment]
If you updated an old client installation, there are chances that the COMDIRAC module was not upgraded in the meant time. This is why you are stuck with COMDIRAC:v0r9.

I don't know if there a way to upgrade a module with dirac-install, but you should at least be able to get the correct version with a fresh client installation.

**Comment by fstagni** [comment]
Deferred to DiracX.
