### ISSUE TITLE
Proxy bug?

### ISSUE THREAD

**Issue by msapunov** [DIRACGrid/DIRAC#297]
in old dirac v6r0-pre11

[msapunov@marmatv ~]$ dirac-proxy-init -g glast_user
Generating proxy... 
Enter Certificate password:
Failed adding VOMS attribute: Can't load proxy at /glast.org
Proxy generated: 
timeleft     : 23:59:59
DIRAC group  : glast_user
path         : /tmp/x509up_u500
username     : msapunov 

[msapunov@marmatv ~]$ dirac-wms-job-submit simple.jdl 
JobID = 40990

in new dirac v6r0-pre15

[msapunov@marmatv ~]$ dirac-proxy-info 
Generating proxy... 
Enter Certificate password:
Proxy generated: 
timeleft     : 23:59:59
DIRAC group  : glast_user
path         : /tmp/x509up_u500
username     : msapunov
properties   : NormalUser

Please note that the message "Failed adding VOMS attribute" is disappeared

JobLaunchpad is not allowing me to submit a job though
P.S. I'm not registered in that VO

**Comment by chaen** [comment]
What is the status of this ?

**Comment by atsareg** [comment]
I think this can be closed. The proxy upload logic can be configured. On the other hand the lack of the VOMS registration of the user will result in Failed jobs with "Can not download proxy" error. So, the problem can be understood
