### ISSUE TITLE
Sending mail to multiple recipients does not work

### ISSUE THREAD

**Issue by ahaupt** [DIRACGrid/DIRAC#3007]
Sending mail to multiple recipients (e.g. from Bdii2CSAgent) does not work. Only the first recipient will receive the mail.

Looks like a bug in the utility module DIRAC/Core/Utilities/Mail.py to me. It expects the recipients either as a list or as a string. However, the other modules simply take the value of "MailTo" from the CS - which is a comma-separated string in case of multiple values. DIRAC/Core/Utilities/Mail.py contains a check for that:

```
if not type( self._mailAddress ) == type( [] ):
    addresses = [self._mailAddress]
```

However, the solution should look like this to properly handle comma-separated recipients:

```
if not type( self._mailAddress ) == type( [] ):
    addresses = self._mailAddress.split(", ")
```
Do you agree here?

**Comment by chaen** [comment]
I would be even more precise :-)

```    
if isinstance( self._mailAddress, basestring):
  addresses = self._mailAddress.split(", ")
```

**Comment by ahaupt** [comment]
OK, then let's do it this way :-) Do you want a PR again?

**Comment by chaen** [comment]
I'd love too :-) 
But just to say, I have not checked the logic of this bug fix, I don't know if this is really the bug or not. I am just commenting on the actual code change. Have you tried it in your environment ?

**Comment by ahaupt** [comment]
The fix is not roughly tested, yet! Just verified that smtplib is fed with recipients like this currently:

```
["aaa@example.com, bbb@example.com" ]
```

In this case it just sends to the first recipient.

I'll apply the proposed fix to the system our Bdii2CSAgent runs on to verify that everyone gets mail. Results later :-)

**Comment by chaen** [comment]
This obviously looks wrong :-)

I assume it should be quite easy to test by hand. Something like

```
from DIRAC.Core.Utilities.Mail import Mail
mail = Mail()
mail._subject = 'Pink Floyd'
mail._message = "We don't need no education"
mail._fromAddress = "ahaupt@somewhere.com"
mail._mailAddress = "aaa@example.com, bbb@example.com" 
mail._send()
```
bbb should not receive before the fix, and it should after

**Comment by ahaupt** [comment]
OK, applied that fix to our instance and all of us are finally receiving mails :-)
