### ISSUE TITLE
[v6r14p22] [v6r14p26] Issues with SSH Site Director at SLAC

### ISSUE THREAD

**Issue by sviscapi** [DIRACGrid/DIRAC#3014]
Dear DIRAC team,

I'm sorry to report that the issues I told you about (huge number of files in JobExecDIr, SharedArea, and BatchOutput directories on an NFS partition at SLAC + creation / deletion rate of those files) during the last workshop are back:

"The computer center folks are concerned both about the number of inodes and the rate at which they are created/deleted.  Here is a file that documents the rate of inode creation/deletion every ~30 seconds.  What one sees is there are extended periods (hours) in which the **inode creation/deletion rate is ~50/s with spikes of >700/s (creation) and >1800/s (deletion)**."

Could you please have a look at the relevant piece of code ?

Best regards,

Samuel

**Comment by chaen** [comment]
Hi Samuel,

I am not going to look myself into that, but I am pretty sure that the document you mention, together with the log of the DIRAC components during the same period, will be of great help

**Comment by sviscapi** [comment]
Hi Christophe,

Here is the file I mentioned (the partition of interest is "u44"):

[gpfsio.zip](https://github.com/DIRACGrid/DIRAC/files/331900/gpfsio.zip)

I'll try to find the corresponding DIRAC logs ASAP.

Best, Samuel

**Comment by sviscapi** [comment]
Hi again,

And here are the logs from the 22nd of June:

[ssh_site_director_2016_06_22_logs.zip](https://github.com/DIRACGrid/DIRAC/files/332020/ssh_site_director_2016_06_22_logs.zip)

Best, Samuel

**Comment by fstagni** [comment]
@VladimirRomanovsky can you please check if we suffer similar problems in LHCb with Yandex?

**Comment by sviscapi** [comment]
Hi all,

Any news regarding this issue ?

Cheers, Samuel

**Comment by fstagni** [comment]
I close this ticket due to inactivity. On top, the mentioned version is old and unsupported.
