### ISSUE TITLE
delete the latest x release

### ISSUE THREAD

**Issue by zmathe** [DIRACGrid/DIRAC#3035]
When a new version of DIRAC is installed, then the latest x release automatically deleted. This functionality by default is disabled.

**Comment by fstagni** [comment]
Add a parameter for setting how many versions should be deleted.

**Comment by fstagni** [comment]
PR: https://github.com/DIRACGrid/DIRAC/pull/3333 (for v6r17p20)

**Comment by fstagni** [comment]
Out.
