### ISSUE TITLE
Creating simple parametric jobs using the python API

### ISSUE THREAD

**Issue by alexanderrichards** [DIRACGrid/DIRAC#3038]
I am testing a simple parametric job (parametric on the arguments not inputsandbox/data) created using the python API. I want to create three test jobs that run the following
```bash
echo testing one
echo testing two
echo testing three
```
---
I am using v6r15p6 and my API script looks like the one below but this doesn't work. I see three jobs created but the jobNames are all `testjob_1` rather than testjob_one etc as I would expect. Also all these jobs fail. What am I doing incorrectly? Any Ideas?

```python
from DIRAC.Core.Base.Script import parseCommandLine
parseCommandLine()
from DIRAC.Interfaces.API.Dirac import Dirac
from DIRAC.Interfaces.API.Job import Job
dirac = Dirac()
j = Job()

j.setName('testjob_%s')
j.setExecutable('/usr/bin/echo', arguments="testing %s", logFile='output.log')
j.setParameterSequence("arguments", ['one', 'two', 'three'], addToWorkflow=True)

# submit the job to dirac
j.setPlatform( 'ANY' )
dirac.submit(j)
```

**Comment by alexanderrichards** [comment]
I should add that using the interactive Job Launchpad from the DIRAC instance web UI this is trivial as i just set the parameters field to
```
Parameters: {one, two, three}
```

But I think perhaps I have not correctly found how to do this with the API.

**Comment by fstagni** [comment]
Hi, to be honest I never used this functionality, and I don't see anything wrong in what you've done, so I assign @atsareg for detailed answer.

**Comment by atsareg** [comment]
In the API you can now define multiple parameter sequences of the same length. But now you have to distinguish these sequences that each has a name. So you code should rather be:

from DIRAC.Core.Base.Script import parseCommandLine
parseCommandLine()
from DIRAC.Interfaces.API.Dirac import Dirac
from DIRAC.Interfaces.API.Job import Job
dirac = Dirac()
j = Job()

j.setName('testjob_%(arguments)s')
j.setExecutable('/usr/bin/echo', arguments="testing %(arguments)s", logFile='output.log')
j.setParameterSequence("arguments", ['one', 'two', 'three'], addToWorkflow=True)

# submit the job to dirac
j.setPlatform( 'ANY' )
dirac.submit(j)

**Comment by alexanderrichards** [comment]
ah fantastic, thanks guys I'll give it a go.

**Comment by alexanderrichards** [comment]
So this almost worked, now where ever the parameter is substituted in I get it surrounded by curly braces { }
my script looks like below:
```python
from DIRAC.Core.Base.Script import parseCommandLine
parseCommandLine()
from DIRAC.Interfaces.API.Dirac import Dirac
from DIRAC.Interfaces.API.Job import Job
dirac = Dirac()
j = Job()

j.setName('testjob_%(arguments)s')
j.setExecutable('echo', arguments="testing %(arguments)s", logFile='output.log')
j.setParameterSequence("arguments", ['one', 'two', 'three'], addToWorkflow=True)

# submit the job to dirac
j.setPlatform( 'ANY' )
dirac.submit(j)
```

e.g. I see job testjob_{three}
```
2016-07-22 10:20:31 UTC dirac-jobexec/Script   INFO: Command is: /local/1244943.1.ecdf/CREAM742953801/DIRAC_Uo4dDHpilot/957648/echo testing {three}
```

**Comment by alexanderrichards** [comment]
interestingly if I resubmit with the executable `echo` rather than giving the full path then the command at least works and the parameter is not wrapped with curly braces even though the job name is:

testjob_{three}
```
2016-07-22 10:28:02 UTC dirac-jobexec/Script   INFO: Command is: echo three
```

**Comment by atsareg** [comment]
Well, the sequence name that you have chosen is conflicting with the reserved key word "arguments" used internally to pass the arguments to your executable. This is an interesting side effect and somehow the code should protect from that. In the meanwhile just change your code like:

    from DIRAC.Core.Base.Script import parseCommandLine
    parseCommandLine()
    from DIRAC.Interfaces.API.Dirac import Dirac
    from DIRAC.Interfaces.API.Job import Job
    dirac = Dirac()
    j = Job()

    j.setName('testjob_%(args)s')
    j.setExecutable('echo', arguments="testing %(args)s", logFile='output.log')
    j.setParameterSequence("args", ['one', 'two', 'three'], addToWorkflow=True)

    # submit the job to dirac
    j.setPlatform( 'ANY' )
    dirac.submit(j)

**Comment by alexanderrichards** [comment]
Thanks again @atsareg I'll give that a go

**Comment by alexanderrichards** [comment]
worked perfectly, many thanks guys
