### ISSUE TITLE
DIRAC API :: dirac.submit output not a proper JSON

### ISSUE THREAD

**Issue by adriansev** [DIRACGrid/DIRAC#3044]
Hi! It would seem that the output of dirac.submit is not a proper JSON and in order to parse it
i need to do something like : 
line = line.replace("True","true").replace("False","false")
line = line.replace("'","\"")

is it possible for this to be corrected?
Thank you!

**Comment by pigay** [comment]
Hi, `dirac.submit()` doesn't output JSON, but a Python object return code (a dictionary).

I suppose you have handle conversion yourself with something like `json.dump(retVal)`.

**Comment by adriansev** [comment]
does not work.  see:
 http://stackoverflow.com/questions/38568371/python-howto-parse-json-and-access-element 

but i can do json.loads if i do the filtering from my post .. given that it is a simple thing (and hoping that does not break anything) it would be nice to have this minor changes implemented .. 

Thank you!

**Comment by chaen** [comment]
Hi,
I think there is just a misunderstanding here. 
What ```dirac.submit``` returns follow the DIRAC convention, that is a dictionnary with a well defined structure, and not a string. 
So you do not need to parse its output, you can use it directly, since it is a python object.

Maybe if you can show an exemple of what you are trying to achieve, we could give further help

**Comment by adriansev** [comment]
well, i needed to record the output of job submit in order to use it "as is" as input for job monitoring and sandbox downloading (like one can do with glite-* commands) .. 
job submission script : 
https://github.com/adriansev/auger-dirac/blob/master/dirac.job_submit.py
job monitoring : 
https://github.com/adriansev/auger-dirac/blob/master/dirac.job_list_mgr.py

Thank you!
Adrian

**Comment by pigay** [comment]
You could try to dump ids into json like this: https://github.com/pigay/auger-dirac/commit/53df841484311d1006a243d922b48cc392f8e621

Alternatively, you could only dump actual raw JobID into the file like this: https://github.com/pigay/auger-dirac/commit/6d512babea3f91558baa8438d2d8689d764432b3 and modify dirac.job_list_mgr.py accordingly.

The last solution has the advantage to be directlycompatible with `dstat -i`.

Pierre

**Comment by atsareg** [comment]
I think this question is cleared. If more discussion is needed, please start a thread in the DIRAC user forum https://groups.google.com/forum/?hl=en#!forum/diracgrid-forum
