### ISSUE TITLE
RSS: Update "DowntimeCache" when start/end time changes

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#3080]
The "ResourceManagementDB DowntimeCache" keeps a cache of downtimes, normally announced in GOC DB (https://goc.egi.eu/). Sometimes, this is what happens:
1. A downtime for resource "Res_A" is set, from, e.g., 10:00 - 18:00 (ID: 123)
2. The CacheFeederAgent sees it, and record a line in DowntimeCache table about it
3. The downtime above (ID: 123) change time, e.g. moved to be starting at 12:00 instead of 10:00
4. RSS cache is not updated

So, we need an enhanced logic that would update this line.

**Comment by vipersec** [comment]
Pull request created: https://github.com/DIRACGrid/DIRAC/pull/3129

**Comment by fstagni** [comment]
Done. Unsure how to properly verify anyway: need to keep monitoring.
