### ISSUE TITLE
[v6r15] mysql stored procedure "ps_rebuild_directory_usage" susceptible to duplicate key errors

### ISSUE THREAD

**Issue by ahaupt** [DIRACGrid/DIRAC#3097]
This is a follow-up to the forum thread https://groups.google.com/forum/#!topic/diracgrid-forum/bXH45l-9ofw

The mysql procedure "ps_rebuild_directory_usage" defined in DataManagementSystem/DB/FileCatalogWithFkAndPsDB.sql consists of 2 INSERT statements. As it uses SEID=1 when summing up files from the FC_Files, it is susceptible to key errors in the second INSERT statement. In case the FC_Replicas table contains an SE with SEID=1 duplicate keys are likely and the statement fails.

**Comment by chaen** [comment]
As I said in this thread, the SEID 1 should never have any replica on it, since it is a special SEID used only for accounting.

**Comment by fstagni** [comment]
I guess this can be closed...
