### ISSUE TITLE
[v6r15] Bugs in all datasets commands

### ISSUE THREAD

**Issue by arrabito** [DIRACGrid/DIRAC#3100]
Errors appear for every 'dataset' command line. Here below the details:

1/ FC:/> dataset show
ERROR: failed to get datasets

doesn't show the existing datasets.

2/ FC:/> dataset show -l Paranal_gamma_South_20deg_HB9
Traceback (most recent call last):
  File "/Users/arrabito/swCTADIRAC/versions/v1r37p4_1472818045/DIRAC/DataManagementSystem/scripts/dirac-dms-filecatalog-cli.py", line 53, in <module>
    cli.cmdloop()
  File "/Users/arrabito/swCTADIRAC/versions/v1r37p4_1472818045/Darwin_x86_64_10.10/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/Users/arrabito/swCTADIRAC/versions/v1r37p4_1472818045/Darwin_x86_64_10.10/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/Users/arrabito/swCTADIRAC/versions/v1r37p4_1472818045/DIRAC/DataManagementSystem/Client/FileCatalogClientCLI.py", line 2006, in do_dataset
    self.dataset_show( argss )  
  File "/Users/arrabito/swCTADIRAC/versions/v1r37p4_1472818045/DIRAC/DataManagementSystem/Client/FileCatalogClientCLI.py", line 2159, in dataset_show
    dsAnnotations = resultAnno['Value']['Successful']
TypeError: string indices must be integers, not str

3/ FC:/> dataset update Paranal_proton_South_40deg_HB9
ERROR: failed to update dataset: Server error while serving updateDataset: too many values to unpack

4/ FC:/> dataset add Paranal_electron_South_40deg_HB9 thetaP=40.0 particle=electron array_layout=full site=Paranal outputType=Data MCCampaign=PROD3 phiP=0.0 tel_sim_prog=simtel
Successfully added dataset /Paranal_electron_South_40deg_HB9

but the added dataset is empty.

Also private scripts working with v6r14 and using:

fc = FileCatalogClient()
result = fc.getDatasets( datasetName )
result = fc.getDatasetFiles( datasetName )

to retrieve datasets informations and dataset content don't work anymore.

By debugging, I've discovered that this is due to the fact that the returned dictionary has changed.

For instance in v6r14 these lines were working:

fc = FileCatalogClient()
result = fc.getDatasets( datasetName )
datasetDict = result['Value']
numberOfFiles = datasetDict[datasetName]['NumberOfFiles']

while in v6r15, these lines should be modified as follows:

fc = FileCatalogClient()
result = fc.getDatasets( datasetName )
datasetDict = result['Value']
res = datasetDict['Successful'][datasetName][datasetName]
numberOfFiles = res['NumberOfFiles']

I don't know if this change is wanted or if it is a bug. In any case, 'dataset' commands should be modified accordingly.

**Comment by fstagni** [comment]
I am not really aware of changes in this area. I assign it to @chaen for the moment.

**Comment by chaen** [comment]
Please assign it rather to @atsareg , since we are not using the same DFC managers, and I never looked at the dataset functionalities

**Comment by fstagni** [comment]
I guess we can close this.
