### ISSUE TITLE
dirac-rss-policy-manager corrupts CS

### ISSUE THREAD

**Issue by wirespecter** [DIRACGrid/DIRAC#3124]
The command [`dirac-rss-policy-manager update`](https://github.com/DIRACGrid/DIRAC/blob/rel-v6r16/ResourceStatusSystem/scripts/dirac-rss-policy-manager.py#L344) makes CS corrupted.

The problem lies in the line 344 where the `getAsDict()` is used. It converts everything that is loaded from the CS to a dictionary but the correct order is lost and when the script tries to write back to the CS the file becomes a mess.

**Comment by andresailer** [comment]
If this is still a problem I recently added a `getAsCFG` function, which preserves the order:
https://github.com/DIRACGrid/DIRAC/blob/8a75a83bb64ee9bc0a86205f7531a9ddd78d4114/Core/Utilities/CFG.py#L442

**Comment by fstagni** [comment]
removed in #4419
