### ISSUE TITLE
Move RSS DB and RMS DB to slqlalchemy

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#3135]
Consider the case of extensions: possibly maintain the backward compatibility, and if not possible or too complicated, add instructions.

**Comment by chaen** [comment]
RMS ? This is the first of all DB that went to SQL alchemy

**Comment by vipersec** [comment]
@chaen Personally I don't see any SQL alchemy usage here: https://github.com/DIRACGrid/DIRAC/blob/rel-v6r16/ResourceStatusSystem/DB/ResourceManagementDB.py

**Comment by chaen** [comment]
Ah, RMS not like in RequestManagementSystem... The ResourceManagement system needs another acronym ! :D

**Comment by vipersec** [comment]
I created 2 pull requests that need to be merged simultaneously.
One for DIRAC: https://github.com/DIRACGrid/DIRAC/pull/3161
And another one for LHCb DIRAC: https://github.com/DIRACGrid/DIRAC/pull/3161

**Comment by fstagni** [comment]
v6r18 is out.
