### ISSUE TITLE
Add checkSEStatus to API

### ISSUE THREAD

**Issue by mesmith75** [DIRACGrid/DIRAC#3152]
Would it be possible to add the __checkSEStatus from the DataManagement code to the DIRAC API? Or at least a function that fulfills the purpose of checking if an SE is writeable?
Thanks

**Comment by phicharp** [comment]
Hi Mark,
Sure, this is a trivial change...
Will be coming soon in a release
Cheers, Philippe

**Comment by phicharp** [comment]
Is this OK with you:
method checkSEAccess( se, status='Write')

In [1]: from DIRAC.Interfaces.API.Dirac import Dirac

In [2]: d = Dirac()

In [3]: d.checkSEAccess( 'CERN-RAW')
Out[3]: True

In [4]: d.checkSEAccess( 'CERN-RAW', access = 'Remove')
Out[4]: False

In [5]: d.checkSEAccess( 'CERN-RAW', access = 'Read')
Out[5]: True

In [6]: d.checkSEAccess( 'CERN-USER', access = 'Read')
Out[6]: True

**Comment by mesmith75** [comment]
Hi Phillipe,
Thanks, that looks good. Do you know when this will be propagated to LHCbDirac?
Mark

**Comment by phicharp** [comment]
hopefully next week

**Comment by fstagni** [comment]
I guess this went into a release, but I don't see a PR linked. Can the task be closed?

**Comment by phicharp** [comment]
Added in https://github.com/DIRACGrid/DIRAC/pull/3153

**Comment by phicharp** [comment]
but I cannot close an issue... Can be closed!
