### ISSUE TITLE
Invocation of dirac-install

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#3171]
The `dirac-install.py` script invocation (and development) is problematic for few reasons:

- when `install_site.sh` (what's used for server installation, see [the documentation](http://dirac.readthedocs.io/en/latest/AdministratorGuide/InstallingDIRACService/index.html?highlight=install_site)) it gets the integration version of the dirac-install [script](https://raw.githubusercontent.com/DIRACGrid/DIRAC/integration/Core/scripts/install_site.sh). This means that changes introduced for solving issues on version `N`, may result in incompatibilities with version `N-1`. This is therefore a risky procedure which is known to have in several cases led to problems. 
- on the contrary, on invocation of dirac-install when updating version from N to N+1, the version used will be the local one. Which can be outdated or incompatible. It'd be therefore better to always keep an up-to-date version of dirac-install

CC @chaen @atsareg @closier @andresailer

**Comment by fstagni** [comment]
Point 1 above is fixed in https://github.com/DIRACGrid/DIRAC/pull/3182

Point 2 is instead a bit different story: what was advised to do was that dirac-install would self-download itself, then re-invokes itself. This is in practice the same as having a first script that, upon invocation, parses all the arguments passed in, but don't use any of them but one (the release). Then invokes a second script in a subprocess (the fact that it would have the same name adds to the confusion) with the same arguments to which the first has been called, parses all them, before using them for real this time. This is not impossible but requires some careful coding.

**Comment by andresailer** [comment]
So is the install_site.sh also used when doing update via dirac-admin-sysadmin-cli ?

**Comment by fstagni** [comment]
No, it's not.

**Comment by fstagni** [comment]
This is being superseded by other tasks and developments. So, closing.
