### ISSUE TITLE
Make FileCatalog metadata related methods compatible with LFN conventions

### ISSUE THREAD

**Issue by atsareg** [DIRACGrid/DIRAC#3191]
Several metadata related methods in the FileCatalogClient, e.g. setMetadata(), getDirectory/FileUserMetadata, and some others are not following the calling sequence convention where the first argument is a dictionary keyed by LFNs. This must be brought to the standard calling sequence where appropriate and all the FileCatalog client objects updated accordingly

**Comment by chaen** [comment]
Fixed by https://github.com/DIRACGrid/DIRAC/pull/2992
