### ISSUE TITLE
Can't install dirac-client

### ISSUE THREAD

**Issue by kenenbek** [DIRACGrid/DIRAC#3194]
Sorry for this question. 
I follow instruction as described [here](http://dirac.readthedocs.io/en/latest/UserGuide/Tutorials/ClientInstallation/index.html).

In the step `./dirac-install -V formation` I change formation to `LHCb`, because I belong to lhcb VO. But I have an error:
```
 - Executing '/tmp/ExtDIRACig_DTE/Externals/clientLibReqs/dirac-make.py' -p '/home/ubuntu/LHCb/Dirac/Linux_x86_64_glibc-2.23'
Oops! Error while compiling clientLibReqs
Take a look at /tmp/ExtDIRACig_DTE/Externals/clientLibReqs/build.out for more info
2016-12-02 16:15:29 UTC dirac-install [ERROR] Could not compile binaries
```
Most likely, it is due to 
 ```
dirac-install [ERROR] http://lhcbproject.web.cern.ch/lhcbproject/dist/Dirac_project/installSource/Externals-client-v6r4p2-Linux_x86_64_glibc-2.23-python27.tar.gz does not exist
2016-12-02 16:14:57 UTC dirac-install [ERROR] Cannot download Externals-client-v6r4p2-Linux_x86_64_glibc-2.23-python27.tar.gz
```

How can I overcome this problem?

**Comment by atsareg** [comment]
First, you can try again, I have added the lacking distribution tar files.
Second, LHCb defines a special procedure for the members of the Collaboration for the installation and use of the LHCbDIRAC client. Please, consult the LHCb user documentation for that
