### ISSUE TITLE
Error registering installation into database: Can't find proxy ( 1101 : )

### ISSUE THREAD

**Issue by iarspider** [DIRACGrid/DIRAC#3201]
Hello,

I'm trying to install Dirac (v6r16p3) for multiVO configuration following tutorials [here](http://diracgrid.org/files/docs/AdministratorGuide/InstallingDIRACService/index.html) and [here](http://diracgrid.org/files/docs/AdministratorGuide/MultiVO/index.html). 
For some reason, web portal components are not installed: 
```
Executing: /opt/dirac/versions/v6r16p3_1481021073/DIRAC/Core/scripts/dirac-configure.py install.cfg 
Checking DIRAC installation at "/opt/dirac/versions/v6r16p3_1481021073"
Installing Master Configuration Server
Loading configuration template /opt/dirac/versions/v6r16p3_1481021073/DIRAC/ConfigurationSystem/ConfigTemplate.cfg
Loading configuration template /opt/dirac/versions/v6r16p3_1481021073/DIRAC/ConfigurationSystem/ConfigTemplate.cfg
service Configuration_Server already installed
Registering System instances
Adding Configuration system as Production self.instance for MyDIRAC-Production self.setup to dirac.cfg and CS
Adding Framework system as Production self.instance for MyDIRAC-Production self.setup to dirac.cfg and CS
Loading configuration template /opt/dirac/versions/v6r16p3_1481021073/DIRAC/FrameworkSystem/ConfigTemplate.cfg
Adding to CS service Framework/SystemAdministrator
Installing MySQL
MySQL already installed
Loading Framework/SystemAdministrator
Trying to autodiscover Framework/SystemAdministrator
Can not connect to DB will use Monitoring/Monitoring
Loaded module Framework/SystemAdministrator
Installing service Framework/SystemAdministrator
Loading configuration template /opt/dirac/versions/v6r16p3_1481021073/DIRAC/FrameworkSystem/ConfigTemplate.cfg
2016-12-06 10:45:08 UTC Framework/SystemAdministrator   INFO: Loading Framework/SystemAdministrator
2016-12-06 10:45:08 UTC Framework/SystemAdministrator   INFO: Trying to autodiscover Framework/SystemAdministrator
2016-12-06 10:45:08 UTC Framework/SystemAdministrator   INFO: Can not connect to DB will use Monitoring/Monitoring
2016-12-06 10:45:08 UTC Framework/SystemAdministrator NOTICE: Loaded module Framework/SystemAdministrator
2016-12-06 10:45:08 UTC Framework/SystemAdministrator   INFO: Initializing Framework/SystemAdministrator
2016-12-06 10:45:08 UTC Framework/SystemAdministrator   INFO: Found 1 initialization methods
2016-12-06 10:45:08 UTC Framework/SystemAdministrator ALWAYS: Listening at dips://diracgeant.cern.ch:9162/Framework/SystemAdministrator

Creating startup link at /opt/dirac/startup/Framework_SystemAdministrator
Error registering installation into database: Can't find proxy ( 1101 : )

Status of installed components:

   Name                          Runit Uptime PID   
====================================================
 1 Configuration_Server          Run       32 10826 
 2 Framework_SystemAdministrator Run        9 10915 
```

I'm mainly worried by "Can not connect to DB will use Monitoring/Monitoring" and "Error registering installation into database: Can't find proxy ( 1101 : )" messages, and lack of web components in the list of installed components (WebPortal is set to True in install.cfg).

**Comment by zmathe** [comment]
You are not using the updated documentation. Please try to use: http://dirac.readthedocs.io/en/latest/AdministratorGuide/InstallingDIRACService/index.html
@atsareg Could you please delete the old documentation, because it is creating problems! or keep it updated!

**Comment by iarspider** [comment]
I have redone the server using the guide @zmathe linked, but I still get the same error. Here is my config file: https://gist.github.com/iarspider/b359f15931c26645b7292968f62d0652

**Comment by fstagni** [comment]
I suggest you to use this install.cfg: https://gist.github.com/fstagni/b756f5a1561cfe9bd0e9e83d95736836
If this works for you, I will update the documentation. And you can ignore the "Can't find proxy" line.

BTW, I see you are at CERN: I suggest you to use the dbod MySQL CERN service instead of installing MySQL by yourself.

**Comment by iarspider** [comment]
I have tried installting the server once more, but I still see "Can not connect to DB will use Monitoring/Monitoring" messages in the log, and the list of installed components still doesn't include web portal. Install log: https://gist.github.com/iarspider/31a9c1096d5cf368db2bbd8b5382ba3d . No processes are listening on 8080/8443 ports:
```
$ netstat -ant | grep LISTEN
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN     
tcp6       0      0 :::9190                 :::*                    LISTEN     
tcp6       0      0 :::9160                 :::*                    LISTEN     
tcp6       0      0 :::9162                 :::*                    LISTEN     
tcp6       0      0 :::3306                 :::*                    LISTEN     
tcp6       0      0 :::9135                 :::*                    LISTEN     
tcp6       0      0 :::111                  :::*                    LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
tcp6       0      0 ::1:631                 :::*                    LISTEN     
```

**Comment by zmathe** [comment]
please make sure that the following lines are in the install.cfg file:
Extensions = WebApp
WebPortal = yes
WebApp = yes

**Comment by iarspider** [comment]
Extensions and WebPortal were already present, reinstalling with "WebApp = yes" didn't change anything.

**Comment by zmathe** [comment]
What is your configuration file?

**Comment by iarspider** [comment]
https://gist.github.com/iarspider/ede73e0a4aba5529f756a00a80724402

**Comment by zmathe** [comment]
You have in the configuration file: Externals = WebApp
You need: Extensions = WebApp
As I mentioned earlier.
Could you please try again?

**Comment by fstagni** [comment]
For the rest, things look fine: the services requested are installed. The "Can not connect to DB will use Monitoring/Monitoring" is not an error, it's just an info message (and a correct one).

**Comment by iarspider** [comment]
OK, it works now. Thanks a lot!
