### ISSUE TITLE
Probably useless stuff (can it be removed?)

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#3202]
This is just a list waiting for comments of stuff in DIRAC that can (probably) be removed without any damage:

- dirac-pilot_1.py
- ftsSSLWrapper.py
- LFCvsSEAgent.py
- SEvsLFCAgent.py
- TopErrorMessageReporter
- FTS2Graph.py

Comments?

**Comment by chaen** [comment]
ftsSSLWrapper & FTS2Graph -> big damages :-) 
ftsSSLWrapper is used until we use the latest FTS rest api release.
FTS2Graph can still be used by other VO. I propose to drop it when the new FTS3 system will be out (PR pending but need update)
