### ISSUE TITLE
Clean RSS cache tables

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#3210]
We discovered that ResourceManagementDB.DowntimeCache table contains entries for resources that are not (anymore) in the CS (and thus, not even in ResourceStatusDB tables. We may not exclude that this affects also other tables.

A proper removal should take place (maybe triggered by the CS synchronization).

**Comment by vipersec** [comment]
Pull request created: https://github.com/DIRACGrid/DIRAC/pull/3218

**Comment by fstagni** [comment]
Merged, in prod.
