### ISSUE TITLE
Make RSS vo-aware

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#3260]
Make RSS to store the status in a VO-aware dependent. This won't be an easy one.

**Comment by fstagni** [comment]
This feature request is waiting for a developer. The developer should better come from a manager of a multi-VO installation.

**Comment by fstagni** [comment]
Is #4720 enough for closing this task? @martynia

**Comment by fstagni** [comment]
Work on v7r2, as several changes went it and merging would be complex.

**Comment by martynia** [comment]
OK, more work is needed on the WebApp, but this is a different issue.
