### ISSUE TITLE
unattended dirac-install-client

### ISSUE THREAD

**Issue by vincent-legoll** [DIRACGrid/DIRAC#3269]
Following page:
http://dirac.in2p3.fr/DIRAC/?view=desktop&theme=Grey&url_state=0|

The installer available through:
http://diracgrid.org/files/tools/dirac-install-client

There's no easy way to automate dirac client installation
That would be really useful additions...

I can modify this python script to allow the use of command line parameters to provide answers to the interactive questions.

Would such an addition be useful / wanted / acceptable ?

**Comment by fstagni** [comment]
Hi,
any improvement is well accepted, so please, if you have ideas, don't be afraid to code them, or simply express them with more details. 

May I ask you what are the requirements that you are trying to address? And what would be your suggestions?

Federico

**Comment by vincent-legoll** [comment]
I want a scriptable (without need to use ```expect```) installer, without interaction.
Maybe this is already doable...

**Comment by fstagni** [comment]
The script was removed, suggestion is to simply use dirac-install script.
