### ISSUE TITLE
Setup crash on missing .globus dir

### ISSUE THREAD

**Issue by vincent-legoll** [DIRACGrid/DIRAC#3273]
In DIRAC/Core/scripts/dirac-install-client.py

$ ./dirac-install-client.py 

  Welcome to the DIRAC client installer !

  This tool will guide you through the installation process
  asking for the necessary details.
  
Do you want to continue ? [default=yes] [yes|no]: 

Choose the DIRAC client installation directory
[default=/home/vip/dirac]: 

Choose which pre-configured service your client will be connected to
or choose to make a custom installation [default=custom, help=?] 

Enter the project name [default=DIRAC]: 

Enter the project version (e.g. v6r13p8): v6r13p8

Enter a comma separated list of extensions [default=no extensions] : 

Enter the lcg bindings version (e.g. 2015-06-26) [default=no bindings]: 

Installing DIRAC client software in /home/vip/dirac ...
Done
Traceback (most recent call last):
  File "./dirac-install-client.py", line 391, in <module>
    globusFiles = os.listdir( globusDir )
OSError: [Errno 2] No such file or directory: '/home/vip/.globus'

The code could check that condition and tell the user something helpful, like installing package XXX...

**Comment by atsareg** [comment]
Fixed in #3348
