### ISSUE TITLE
Request protocol for getAccessURL

### ISSUE THREAD

**Issue by mesmith75** [DIRACGrid/DIRAC#3280]
Would it be possible for the `getAccessURL' function in the API:

https://github.com/DIRACGrid/DIRAC/blob/integration/Interfaces/API/Dirac.py#L1458

to be able to request the protocol? It would be useful for Ganga.

Thanks!

**Comment by fstagni** [comment]
I am not the expert but it seems it's already possible if you call directly https://github.com/DIRACGrid/DIRAC/blob/integration/DataManagementSystem/Client/DataManager.py#L1739 which is what the method in the API does.

Do you want this exposed in the API or can you call directly the DataManager class?

**Comment by chaen** [comment]
I would not recommend calling directly the DM class. Ganga should stick to the API.

**Comment by mesmith75** [comment]
@fstagni Yes at the moment we do take it directly from the DM class but I would prefer to use the API.

It is partly because I also want the LHCbDirac version in the API as well so I can use it in the LHCb plugin to request root and xroot together by default.

**Comment by chaen** [comment]
It is very easy to add, no problem. For v6r18 though, since it is an API change. However I don't understand what you mean with this LHCbDIRAC version in the API ?

**Comment by mesmith75** [comment]
@chaen LHCbDirac has its own version of the getAccessURL function. It looks to me as if that one has some extra code around the root/xroot protocol request that would be useful to have for the LHCb plugin in Ganga.

**Comment by chaen** [comment]
well, alternatively we could put this in the low level plugin. But this is really ugly anyway :-/

**Comment by phicharp** [comment]
Mark is correct: we may add "mdf:" in front of the URL which is a pure LHCb "feature". I can add such a method in the LHCbDirac API, this is not a big deal... No need to wait for a major release although it is a change of API, since it is an addition I think it can safely be added as a preview, right?

**Comment by phicharp** [comment]
Fixed in LHCbDirac https://gitlab.cern.ch/lhcb-dirac/LHCbDIRAC/merge_requests/304

**Comment by fstagni** [comment]
In production.
