### ISSUE TITLE
Cleanup of the StorageElement proxy

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#3292]
It seems that there is no cleaning done in the StorageElementProxy. When a client wants to access a file, the proxy downloads it locally and then serves it, but it seems to me it is never deleted. 
This should be done automatically. 
Now we can have two policies: 
* the file is deleted immediately after the client got it
* the Proxy acts as a buffer, and the file could be cleaned after a period of time

**Comment by fstagni** [comment]
What'd be wrong with the first option?

**Comment by chaen** [comment]
Absolutely nothing. 
I am just saying that it is 2 (non mutually exclusive) options

**Comment by chaen** [comment]
Hum, in fact I see in the code that it should already be doing it. Then we have another problem with the BOINC Proxy SE

**Comment by chaen** [comment]
@CinziaLu the Proxy is supposed to remove it, can you check why it does not seem to happen on the BOINC machine ?

**Comment by CinziaLu** [comment]
I found the problem, I was not setting the BASE_PATH for the StorageElementProxy in the WMSGatewayGW so the 
if os.path.exists(file_path):
      os.remove( file_path )
of the transfer_toClient method was never executed. 
I fixed it and it is working. I'll do a MR.
