### ISSUE TITLE
Truncation issue in InstalledComponentDB

### ISSUE THREAD

**Issue by vbpnl** [DIRACGrid/DIRAC#3331]
I see these lines

2017-05-07 04:14:56 UTC Framework/ComponentMonitoring  DEBUG: RPC to export_updateLog
/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/site-packages/sqlalchemy/engine/default.py:469: Warning: Data truncated for column 'CertificateDN' at row 1
  cursor.execute(statement, parameters)
/opt/dirac/pro/Linux_x86_64_glibc-2.12/lib/python2.7/site-packages/sqlalchemy/engine/default.py:469: Warning: Data truncated for column 'CertificateIssuer' at row 1
  cursor.execute(statement, parameters)
2017-05-07 04:14:56 UTC Framework/ComponentMonitoring NOTICE: Returning response ([::ffff:142.51.70.227]:32911)[hosts:mc-surface.snolab.ca] (0.15 secs) OK

mysql> select CertificateIssuer from HostLogging;
+------------------------------------------------------------------+
| CertificateIssuer                                                |
+------------------------------------------------------------------+
| /C=US/ST=Washington/L=Richland/O=MiniCLEAN/OU=Computing/CN=Malac |
| /C=US/ST=Washington/L=Richland/O=MiniCLEAN/OU=Computing/CN=Malac |
+------------------------------------------------------------------+
2 rows in set (0.00 sec)

mysql> select CertificateDN from HostLogging;
+------------------------------------------------------------------+
| CertificateDN                                                    |
+------------------------------------------------------------------+
| /C=US/ST=Washington/L=Richland/O=MiniCLEAN/OU=Computing/CN=dirac |
| /C=US/ST=Washington/L=Richland/O=MiniCLEAN/OU=Computing/CN=mc-su |
+------------------------------------------------------------------+
2 rows in set (0.00 sec)

I wonder if it matters that the fields are truncated anywhere?

**Comment by fstagni** [comment]
Hi, this is not a good sign. Can you please do
```
DESCRIBE HostLogging
```
?

**Comment by vbpnl** [comment]
I did look at it but did not post it before. Of course field size is small in v6r17p11

mysql> describe HostLogging;
+---------------------+-------------+------+-----+---------+-------+
| Field               | Type        | Null | Key | Default | Extra |
+---------------------+-------------+------+-----+---------+-------+
| HostName            | varchar(32) | NO   | PRI | NULL    |       |
| DIRACVersion        | varchar(32) | YES  |     | NULL    |       |
| Extension           | varchar(64) | YES  |     | NULL    |       |
| Load1               | varchar(32) | YES  |     | NULL    |       |
| Load5               | varchar(32) | YES  |     | NULL    |       |
| Load15              | varchar(32) | YES  |     | NULL    |       |
| Memory              | varchar(32) | YES  |     | NULL    |       |
| DiskOccupancy       | varchar(32) | YES  |     | NULL    |       |
| Swap                | varchar(32) | YES  |     | NULL    |       |
| CPUClock            | varchar(32) | YES  |     | NULL    |       |
| CPUModel            | varchar(64) | YES  |     | NULL    |       |
| CertificateDN       | varchar(64) | YES  |     | NULL    |       |
| CertificateIssuer   | varchar(64) | YES  |     | NULL    |       |
| CertificateValidity | varchar(64) | YES  |     | NULL    |       |
| Cores               | int(11)     | YES  |     | NULL    |       |
| PhysicalCores       | int(11)     | YES  |     | NULL    |       |
| OpenFiles           | int(11)     | YES  |     | NULL    |       |
| OpenPipes           | int(11)     | YES  |     | NULL    |       |
| OpenSockets         | int(11)     | YES  |     | NULL    |       |
| Setup               | varchar(32) | YES  |     | NULL    |       |
| Uptime              | varchar(64) | YES  |     | NULL    |       |
| Timestamp           | datetime    | YES  |     | NULL    |       |
+---------------------+-------------+------+-----+---------+-------+
22 rows in set (0.01 sec)

**Comment by fstagni** [comment]
OK thanks. I fixed the code, but you may want to act operationally enlarging these fields even now.
