### ISSUE TITLE
Use ElasticSearch for JobParameters

### ISSUE THREAD

**Issue by phicharp** [DIRACGrid/DIRAC#3364]
There are several reasons why we must be able to identify which job was running at a given worker node (or with a given local batch ID) at a given time:
1. Traceability as requested by WLCG and EGI in case of incident
2. When we receive information from a site about a job and we want to identify which Dirac job it was

Currently these informations are stored in the JobParameters table which is a key-value pair and therefore it is impossible to query it.

A new table must be created or a column added to an existing table containing these informations with an index such that it can be efficiently queried.

This is very urgent

**Comment by zmathe** [comment]
I think it is simpler to send the information to Elasticseach. In principle the jobParameters can be send to EL

**Comment by phicharp** [comment]
If this is an easier solution, just fine with me... My impression was that not all communities would be ready to use ElasticSearch in their setup... although the traceability requirement si true for everybody.

**Comment by fstagni** [comment]
Not all the (smaller) communities have the requirements that larger communities have. I think that using ElasticSearch for these type of information make a lot of sense (and looks like we have more and more use cases for increasing the use of ES.

**Comment by zmathe** [comment]
I think this also we have to take into account: The other communities can use MySQL directly as they do not have that much jobs. We can not retrieve the information, because we are having to many jobs.
Personally, I prefer to go to the direction of NoSQL. If we integrate Hadoop (this is also provided by CERN), we can run very complex analysis.

**Comment by phicharp** [comment]
I am not sure that even with few jobs they can get this information from the current JobParameters table... This is a real pain in the neck, while a dedicated table would be OK for them certainly

**Comment by fstagni** [comment]
Few more things, taking some notes too:
- currently the "life" of the JobParameters depends from the life of the jobs. I guess that ideally we'd like to keep these info "forever"
- currently, if a job is rescheduled, the info about the last "match" will override the info about the previous match. Again, I think ideally we should keep the whole history.

Technically:
- the JobStateUpdate service is right now what exposes "setJobParameter(s)" call. And the table hosting the JobParameters is in JobDB. So, the entry point is here, and it looks quite easy (needs a flag, as usual).

**Comment by fstagni** [comment]
One more note: we have no proper accounting of where "Input Data Resolution" happens (it's only in the log right now). It should be seen if we can add this info too.

**Comment by phicharp** [comment]
The information is reported in the job Parameters. I made a PR to include what went wrong since before only what went right was reported... If job parameters are reported in ES, it should be easy to get it. Here an exemple, unfortunately can only be found easily for jobs that go to "Maximum of rescheduling reached" (awful English ;-))
```
[localhost] ~ $ dirac-wms-job-parameters 189741993
{'AgentLocalSE': 'RAL-ARCHIVE,RAL-BUFFER,RAL-DST,RAL-FAILOVER,RAL-RAW,RAL-RDST,RAL-USER,RAL_MC-DST',
 'CPUNormalizationFactor': '11.6',
 'CPUScalingFactor': '11.23',
 'DownloadInputData': 'Successfully downloaded 5 LFN(s) from local SEs:\n/lhcb/LHCb/Collision15/EW.DST/00069077/0000/00069077_00006498_1.EW.dst\n/lhcb/LHCb/Collision15/EW.DST/00069077/0000/00069077_00006538_1.EW.dst\n/lhcb/LHCb/Collision15/EW.DST/00069077/0000/00069077_00006541_1.EW.dst\n/lhcb/LHCb/Collision15/EW.DST/00069077/0000/00069077_00006544_1.EW.dst\n/lhcb/LHCb/Collision15/EW.DST/00069077/0000/00069077_00006551_1.EW.dst\nFailed to download 1 LFN(s):\n/lhcb/LHCb/Collision15/EW.DST/00069077/0000/00069077_00006528_1.EW.dst',
 'JobPath': 'JobPath,JobSanity,InputData,JobScheduling',
 'JobSanityCheck': '6 LFNs | Assigned 1 ISBs',
 'JobWrapperPID': '93',
 'LocalBatchID': 'None',
 'PilotAgent': 'v9r1',
 'Pilot_Reference': 'gsiftp://arc-ce01.gridpp.rl.ac.uk:2811/jobs/O44NDmpgAkrnCIXDjqiBL5XqABFKDmABFKDmFQ4ODmABFKDmlPdlAn'}
```
It could be printed better, and one can put the failure on top...

**Comment by fstagni** [comment]
Merged, to be tested.
