### ISSUE TITLE
API :: v6r18 :: dirac.submit(j,mode='local') not working

### ISSUE THREAD

**Issue by adriansev** [DIRACGrid/DIRAC#3370]
dirac.submit(j,mode='local')  gives the following error : 
Submission Result:  {'Errno': 0, 'Message': 'Can not copy InputSandbox file /home/adrian/AUGER-GRID/auger-dirac/jobDescription.xml', 'OK': False, 'CallStack': ['  File "./dirac.job_submit.py", line 236, in <module>\n    jobID = dirac.submit(j,mode=\'local\')\n', '  File "/home/adrian/DIRAC/DIRAC/Interfaces/API/Dirac.py", line 280, in submit\n    return self.submitJob( job, mode = mode )\n', '  File "/home/adrian/DIRAC/DIRAC/Interfaces/API/Dirac.py", line 346, in submitJob\n    result = self.runLocal(job)\n', '  File "/home/adrian/DIRAC/DIRAC/Interfaces/API/Dirac.py", line 879, in runLocal\n    return S_ERROR( \'Can not copy InputSandbox file %s\' % isFile )\n']}

v6r17p20 works as expected

**Comment by fstagni** [comment]
Indeed, there's an issue with that. Thanks for reporting. I will look at it ASAP.

**Comment by fstagni** [comment]
Hopefully fully fixed in #3387

**Comment by andresailer** [comment]
The problem still exists

**Comment by fstagni** [comment]
In the #3480 I think it's fixed, can you review it?

**Comment by fstagni** [comment]
Should be OK now.

**Comment by andresailer** [comment]
Still (again) not working for me., I'll make another PR
