### ISSUE TITLE
dirac-install ignores failures in installing lcgBundles? 

### ISSUE THREAD

**Issue by iueda** [DIRACGrid/DIRAC#3388]
Is there a reason to make dirac-install say "properly installed", even when DIRAC-lcg is not properly installed?
installExternals() tells ERROR
      logERROR( "Check that there is a release for your platform: DIRAC-lcg-%s" % verString )
but returns True.

There were some users who didn't notice the ERROR, and believed they have "properly installed" DIRAC (and BelleDIRAC), and then failed in further actions (of course).

**Comment by chaen** [comment]
I also encountered such things and wondered the same ! Also, when you perform a successful installation, you still get an error message. Some tidying up here would be nice

**Comment by fstagni** [comment]
Fixed in #3390

**Comment by iueda** [comment]
There was a comment on the PR https://github.com/DIRACGrid/DIRAC/pull/3390.
Sorry for my ignorance and going back and forth between the two...

> Should it be just a warning ? In most cases the installation of LCG bindings fails for clients on platforms for which LCG software is not compiled. In this case some functionality subset is indeed not available but the client is functional for most cases. This is why the installation is declared successful even if the LCG bindings are not available

What are the use cases where dirac clients are functional without the LCG tools? For ordinary users, they cannot submit jobs and cannot download files without a VOMS proxy. When a user came to me saying he successfully made dirac-install but cannot submit a job, I found LCG installation had failed and there were no voms commands installed. There was also a related discussion on the forum for a similar user with ubuntu.  ("lcg bundles for Linux_x86_64_glibc-2.18").
If someone such as an expert needs to use DIRAC client on a platform without any LCG bundles, shouldn't they explicitly specify the installation of LCG should/can be skipped?

**Comment by atsareg** [comment]
For job submission users do not need VOMS proxy. If this is the case for your users, it would be nice to understand the reason. Direct data access indeed requires VOMS proxies but also protocol libraries shipped with the LCG bindings. The DIRAC solution in this case ( using Proxy services ) is not scalable but still can be used for occasional file downloads/uploads. So, in most cases for the clients LCG bindings are not absolutely necessary. 
The LCG bindings availability for all the platforms is not in the hands of the DIRAC project. So, the users must be notified that its installation failed but it does not mean that they can not proceed. May be the message can be more detailed stating what functionality will not be available, but it is definitely not a complete failure

**Comment by chaen** [comment]
I am more in favor of Ueda's approach. You cannot just say "part of it failed but it is okay". And it is a perfectly valid use case to have the users using data management command, LHCb users do it all the time. 
But as you said, we can't build the LCG bindings for all the platform, hence the *full* client installation is only supported for SLC6 (soon CC7). And I think this should be a clear statement from us.
Now, if people want to use a more "exotic" platform like ubuntu, they should be given an option to do a partial installation if you wish. 
But from the conceptual point of view, I agree with Ueda: if by default we do dirac-install, it should succeed only if everything was successful

**Comment by arrabito** [comment]
I also agree with Ueda's approach, in CTA for instance there are almost no users who just need occasional interactions with SEs. I also agree that we should clearly state that the full client installation is only supported for SLC6 (soon CC7). Indeed, I've always advertised that most Linux platforms are supported, but then I encounter problems with users using Ubuntu or other platforms.

**Comment by atsareg** [comment]
Alternatively, the client can be
      installed as a Docker container. I think it should be easy to run
      it
      with the data naturally stored on the local out-of-container disk.
      
        Cheers,
        Andrei 
      
      On 29/06/17 16:17, arrabito wrote:
    
    
      I also agree with Ueda's approach, in CTA for instance there
        are almost no users who just need occasional interactions with
        SEs. I also agree that we should clearly state that the full
        client installation is only supported for SLC6 (soon CC7).
        Indeed, I've always advertised that most Linux platforms are
        supported, but then I encounter problems with users using Ubuntu
        or other platforms.
      —
        You are receiving this because you commented.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DIRACGrid/DIRAC","title":"DIRACGrid/DIRAC","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/DIRACGrid/DIRAC"}},"updates":{"snippets":[{"icon":"PERSON","message":"@arrabito in #3388: I also agree with Ueda's approach, in CTA for instance there are almost no users who just need occasional interactions with SEs. I also agree that we should clearly state that the full client installation is only supported for SLC6 (soon CC7). Indeed, I've always advertised that most Linux platforms are supported, but then I encounter problems with users using Ubuntu or other platforms."}],"action":{"name":"View Issue","url":"https://github.com/DIRACGrid/DIRAC/issues/3388#issuecomment-311980528"}}}

**Comment by chaen** [comment]
Hum, it might be tricky because if you want to write you need to have the same UID. 
But in any case it is certainly fesable. 
It remains that I think it is correct to fail the installation if the LcgBundle is not installed successfully.

**Comment by atsareg** [comment]
Right now we have several global client installation configuration for several DIRAC services like FG-DIRAC where the LcgVer parameter is specified assuming the need for lcg bindings. This configuration is the same for all the platforms. So, with the fix when client installation is considered failed if no lcg bindings are available, all the non-SL6/CC7 clients will definitely fail in this case. We have in fact two distinct cases: lcg bindings are available but fail to install and lcg bindings are not available for the client platform. The two cases should be treated differently: error in the former case and warning in the latter.

**Comment by chaen** [comment]
Then I propose the following:
dirac-install by default *must* have the LcgBundle installed. If it is not there, or if the installation fails, it is an error. If the bundle is not there, we can print an advice saying that the LcgBundle is not available for that platform, and that a partial installation can be done with the flag ```--no-lcg-bundle```. And with this flag, no attempt will be done. This calls for a clear message on the wiki saying that the full client is only supported for slc like platform.

I think this proposition matches all the requirements.

**Comment by atsareg** [comment]
If the lcg bundles are attempted to install always, there should be a way to know the default version of it. Now, this should be specified explicitly. We can consider to put it into the releases.cfg

**Comment by iueda** [comment]
For me, installation of lcg bundle is to be attempted when the version is specified.
In the global configuration of FG-DIRAC, LcgVer is specified, so it is expected to be installed. Then it should be attempted by default and dirac-install should fail when it is not installed.
In some other global configurations, LcgVer is not specified, then, we can consider they don't need lcg bundles and skip its installation. Even for those, lcg bundle can be installed if it is specified with the option.
Currently its installation is tried only under the condition
` if lcgVer:`
So, this should be work as is.

I had other comments/questions concerning how to proceed with `--no-lcg-bundle`, which I wrote a few days ago, but apparently they were lost while (or before) I was submitting them. I will have to re-compose them...

**Comment by iueda** [comment]
1) Currently installation of LCG bundle is a part of installExternals.
Should we separate them so that skipping of LCG bundle can be controlled in the main?
Or, should LCG bundle be necessarily considered as Externals?

2) I also observed a case where dirac-externals-requirements failed and dirac-install finished successfully.
```
dirac-install [ERROR] Requirements installation script .../dirac-externals-requirements failed. Check .../dirac-externals-requirements.err
dirac-install [NOTICE]  DIRAC properly installed
```
What should we do for this? Similarly as for LCG bundle?

3) As I wrote before, can we consider that LCG bundle is required only when LcgVer is specified in the cfg, or with the option -g or --grid?
i.e. it is mandatory by default for LHCb, EGI, gridfr, CTA, ILC, Belle, etc. and not for NeCTAR, ALDIRAC

**Comment by fstagni** [comment]
1) I am OK with separate
2) I think the dirac-externals-reqiorements script right now doesn't return anything but 0. Which is wrong, of course: so, this should fixed in first place, and then the result interpreted in dirac-install
3) I agree with considering it mandatory.

**Comment by iueda** [comment]
Committed some changes as agreed. https://github.com/DIRACGrid/DIRAC/pull/3390
Tested with and without the suggested new option `--no-lcg-bundle`, on a node where LcgBundle installation fails.
I haven't tested it yet where LcgBundle should succeed, yet..., for currently I have no access to a SL6 machine, but committed the code so that you can see what I did.

**Comment by iueda** [comment]
Tested with LcgBundle installation (on SL6), and it seems to work as before.

**Comment by fstagni** [comment]
Released together with DIRAC v6r17 series.
