### ISSUE TITLE
LocalComputingElement and pilotCommands pilotRef mismatch

### ISSUE THREAD

**Issue by iueda** [DIRACGrid/DIRAC#3392]
In Resources/Computing/LocalComputingElement.py
`jobIDs = [ self.ceType.lower()+'://'+self.ceName+'/'+_id for _id in resultSubmit['Jobs'] ]`
but WorkloadManagementSystem/PilotAgent/pilotCommands.py sets `ssh` without caring if it is ssh or local, eg.
`    if 'CONDOR_JOBID' in os.environ:
      self.pp.flavour = 'SSHCondor'
      pilotRef = 'sshcondor://' + self.pp.ceName + '/' + os.environ['CONDOR_JOBID']
`
The simplest solution could be to change LocalComputingElement.py 
`jobIDs = [ 'ssh'+self.batchSystem.lower()+'://'+self.ceName+'/'+_id for _id in resultSubmit['Jobs'] ]`
but is it what we would like in "Local" Computing Element?

cf. Computing/SSHComputingElement.py
`jobIDs = [ '%s%s://%s/%s' % ( self.ceType.lower(), self.batchSystem.lower(), ceHost, _id ) for _id in batchIDs ]`

**Comment by fstagni** [comment]
Good question. To be honest I don't know exactly in which contest the `LocalComputingElement` has been used lately, I guess mostly for HPC environment. I don't think we have been using this in LHCb so far. Maybe @atsareg can comment.

**Comment by iueda** [comment]
https://github.com/DIRACGrid/DIRAC/pull/3422

**Comment by iueda** [comment]
Answering to this point:
> I don't know exactly in which contest the LocalComputingElement has been used lately, I guess mostly for HPC environment.
It is used in Belle II where we run a SiteDirector and Condor batch system on the same node.

**Comment by fstagni** [comment]
Specific issue solved.
