### ISSUE TITLE
Move of runsv to a version independant location

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#3393]
There is a bug in runsv which results in libraries from already deleted DIRAC version to be still used in memory. 

New installations should be easy, but existing one will need a clear procedure on how to update.

The proposition is to move the binaries from Linux directory to sbin: @closier will try to change it in the External tarball. It will also require to modify the bashrc to include sbin in the PATH

**Comment by closier** [comment]
The runsvdir-start script has been modified to find the location of the RUNIT binaries and use them.
It checks first in /opt/dirac/sbin and after in /opt/dirac/pro/LinuxYYYYY/bin

**Comment by closier** [comment]
Now we can check the proper approach to change the location of the RUNIT binaries.

**Comment by closier** [comment]
Either you install RUNIT from http://smarden.org/runit/ or you could also use the RPMs provided by LHCb (http://cern.ch/lhcbproject/dist/rpm/lhcbdirac/[slc6/runit-2.1.2-1.el6.x86_64.rpm, centos7/runit-2.1.2-1.el7.cern.x86_64.rpm]). All the RUNIT commands will be installed in /sbin for SLC6 and in /usr/sbin in CENTOS7. You can provide the file /etc/init/dirac.conf for SLC6 or the file /etc/systemd/system/multi-user.target.wants/dirac.service for CENTOS7. You should have in /opt/dirac/sbin/runsvdir-start that will be aclled to start the services/agents and use the 'which' feature to get the proper RUNIT distribution.
Something similar to :
cd /opt/dirac
source /opt/dirac/bashrc
RUNSVCTRL=`which runsvctrl`
echo $RUNSVCTRL
chpst -u dirac $RUNSVCTRL d /opt/dirac/startup/*
killall runsv svlogd
RUNSVDIR=`which runsvdir`
exec chpst -u dirac $RUNSVDIR -P /opt/dirac/startup 'log:  DIRAC runsv'

As already in the Documentation (http://dirac.readthedocs.io/en/latest/AdministratorGuide/InstallingDIRACService/index.html#post-installation-step), if you install on your own RUNIT, we are not obliged to distribute it via the Externals.

**Comment by fstagni** [comment]
Test, and doc is produced. Closing.
