### ISSUE TITLE
Add CloseSEs and LocalSEs to TaskQueue definition

### ISSUE THREAD

**Issue by graciani** [DIRACGrid/DIRAC#340]
Following external discussion we have concluded that there is a valid use case to Target certain types of Jobs, mostly those dealing with massive data processing, not to Sites, but rather to StorageElements. In this way, at any time Sites can be added or removed from the Site to SE association and additional computing power provided when necessary.

The way to achieve this functionality is to add 2 (optional) options in the payload description that will be interpreted by the WMS Optimizers and used in the TaskQueue definition. Finally pilots have to be instrumented to publish this information and allow the match making.

**Comment by fstagni** [comment]
5 years later... 
This is somewhat already solved if using "ByType" TS TaskManager plugin. Also there's a notion in DMSHelper about close and local SEs.
