### ISSUE TITLE
Wrong counting of errors for files in TS

### ISSUE THREAD

**Issue by phicharp** [DIRACGrid/DIRAC#3446]
Intrigued by the behavior of the MaxReset, I have investigated how the ErrorCount of TS files is incremented.
The current pattern is the following in LHCb (`maxResetCounter` set to 2):
* File goes to MaxReset after 3 Failed jobs
* Resetting the file `Unused`, it goes to MaxReset after one more job

The reason is that the `ErrorCount` is incremented **every time** the status is changed, except for the transition `Unused` to `Assigned` that doesn't go through the method `setFileStatusForTransformation()`.

This is incorrect and indeed `ErrorCount` should only be incremented when a file moves from `Unused` to any other status which is not `Processed`. This is easy to implement in the `TransformationClient`.

Assign to me for implementation please (as I cannot assigne issues)

**Comment by phicharp** [comment]
Shouldn't it be v6r19?

**Comment by fstagni** [comment]
yep, thanks
