### ISSUE TITLE
Create RFC proxies by default

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRAC#3472]
As discussed in the last BiLD meeting the proxies should be RFC by default.
Need to change this line

https://github.com/DIRACGrid/DIRAC/blob/fe3c350b12c250272a23e660ae7bf71040b693a0/FrameworkSystem/Client/ProxyGeneration.py#L31

And add a flag to disable RFC proxies.
Flag "-R" ?
Or is there already a flag for that in "lhcb-proxy-init"? Then we should maybe use the same.

**Comment by fstagni** [comment]
lhcb-proxy-init is as simple as https://gitlab.cern.ch/lhcb-dirac/LHCbDIRAC/blob/master/LHCbDIRAC/Core/scripts/lhcb-proxy-init.py
and there's no special flag fo "no RFC proxies". 

What about flag -L (legacy):
```
Script.registerSwitch( "L", "legacy", "Create an RFC proxy", self.setNoRFC )
```
?

Would you take of the PR?

**Comment by andresailer** [comment]
I though about that as well, but there is already a lower case `l` flag for limited. 

Yes, you can assign me.
