### ISSUE TITLE
HTCondorCEComputingElement WorkingDirectory

### ISSUE THREAD

**Issue by iueda** [DIRACGrid/DIRAC#3475]
With these coding in HTCondorCEComputingElement.py;
`DEFAULT_WORKINGDIRECTORY = '/opt/dirac/pro/runit/WorkloadManagement/SiteDirectorHT'`
`  workingDirectory = gConfig.getValue( "Resources/Computing/HTCondorCE/WorkingDirectory",
                                       DEFAULT_WORKINGDIRECTORY )
`
We can run only a single SiteDIrector for HTCondorCE (per node), otherwise multiple Agents would share the same WorkingDirectory.

Isn't it possible to configure this per SiteDirector instance, or per Site?

**Comment by andresailer** [comment]
There are a few FIXME's in the HTCondorCE code that explain the problem of the working directory.
The problem with setting the working directory is that as a CE parameter it is only set once the SiteDirectory has instantiated the computing element. But if the CE is instantiated from the WMSAdministrator to get some pilot output files it won't work at the moment.

However, this is the directory where HTCondor puts the pilot output, error, condor log files, if run with a local schedd. It is not per se the directory of the SiteDirectors using HTCondorCEs.
(I am not sure where the files are placed when no local schedd is used).

**Comment by iueda** [comment]
Probably related to this, I get the following error when I try to retrieve Pilot Output via the Web portal even though we specify a different directory in Resources/Computing/HTCondorCE/WorkingDirectory:
`No such file or directory ( 2 : Could not find 302266.2.out in directory /opt/dirac/pro/runit/WorkloadManagement/SiteDirectorHT)`

Setting GetPilotOutput to True or False doesn't matter, it seems.

We run the SiteDirector on a different node from the one running the WebApp.

**Comment by andresailer** [comment]
It depends if the WMSAdministrator is running on the same node as the SiteDirector

**Comment by fstagni** [comment]
What shall we do about this task?

**Comment by iueda** [comment]
The error "No such file or directory" I mentioned as "related" should be solved by the PR #4027.
The original issue -- sharing the working directory -- was discussed with @andresailer at the last DUW:
a) the file names should be unique and sharing the directories with multiple CEs would not be a problem -- to be confirmed.
b) the directory names -- there are too many directories created by this scheme and they are not easy to clean up. Possible improvements: start the directory structure with the "date", then with smaller number of letters in the directory names and with smaller levels of sub-directories.
We will look into this.

**Comment by fstagni** [comment]
There have been a few PRs for HTCondor that should solve the initial issue: #4360, #4588, #4620 all for v7r0. I close this task.
