### ISSUE TITLE
Square brackets problem in JDL attributes

### ISSUE THREAD

**Issue by Andrew-McNab-UK** [DIRACGrid/DIRAC#3494]
I can submit the following JDL as a job, but if I use the Arguments attribute containing a left square bracket, dirac-wms-job-submit hangs. (I'm reporting this because I want to be able to put a regular expression in a JDL attribute and it hangs if I use a regex contain square brackets.)

[
Site = "VAC.Manchester-dev.uk";
JobName = "BracketJob";
Executable = "/bin/echo";
StdOutput = "StdOut";
StdError = "StdErr";
OutputSandbox = {"StdOut","StdErr"};

#This causes submission to hang:
#Arguments = "[123";

#This works fine
Arguments = "123";
]

**Comment by fstagni** [comment]
Thanks for the report. I guess it doesn't change from DIRAC v6r17 to v6r19, right?

**Comment by Andrew-McNab-UK** [comment]
I haven't tried. Does anyone have an idea where in the code this is likely to be happening? I'm happy to try to make a PR to fix it, but searching for '[' in the code produces lots of matches :-)
