### ISSUE TITLE
Publish all CPU flags as DIRAC tags?

### ISSUE THREAD

**Issue by Andrew-McNab-UK** [DIRACGrid/DIRAC#3513]
We have a situation in the SKA/AENEAS prototyping where the application we're using to test the system (from the LOFAR telescope array) needs Intel AVX instructions. These are available on some machines at some sites. On Linux, the presence of these instructions is readily available by just looking for any of the "flags:" lines in the file /proc/cpuinfo:

    flags	:       fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush 
    dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts
    rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl
    vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes
    xsave avx lahf_lm epb tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts

The most straightforward way of allowing us to target the jobs on machines with those cpu instructions would just for the pilot to add all of the flags as CPU DIRAC tags. For example with the prefix cpuinfo. So AVX would be represented by the tag "cpuinfo.avx", and can be requested in the JDL of jobs that need it. 

Does the above sound like a reasonable design? I'll make PRs for Pilot 2 and 3.0 if so.

**Comment by atsareg** [comment]
I would say this is what the tags are
      made for. I guess you want these tags to be evaluated
      by the pilot itself. It means that the tags are not known at the
      point of the pilot submission.
      It means in turn that jobs with this flag requirement will never
      trigger the pilot submission.
      If all the CPUs in the given queue are the same, these flags can
      be published statically in the
      CS, then they will be used for choosing a site for the pilot
      submission. Otherwise, such jobs can
      be only picked up by chance if there are other less demanding jobs
      of the same VO in the task
      queue.
      
        Cheers,
        Andrei
      
      On 25/10/17 23:53, Andrew McNab wrote:
    
    
      We have a situation in the SKA/AENEAS prototyping where the
        application we're using to test the system (from the LOFAR
        telescope array) needs Intel AVX instructions. These are
        available on some machines at some sites. On Linux, the presence
        of these instructions is readily available by just looking for
        any of the "flags:" lines in the file /proc/cpuinfo:
      flags	:       fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush 
dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts
rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl
vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes
xsave avx lahf_lm epb tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts

      The most straightforward way of allowing us to target the jobs
        on machines with those cpu instructions would just for the pilot
        to add all of the flags as CPU DIRAC tags. For example with the
        prefix CpuInfo. So AVX would be represented by the tag
        "CpuInfo.avx", and can be requested in the JDL of jobs that need
        it.
      Does the above sound like a reasonable design? I'll make PRs
        for Pilot 2 and 3.0 if so.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DIRACGrid/DIRAC","title":"DIRACGrid/DIRAC","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/DIRACGrid/DIRAC"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Publish all CPU flags as DIRAC tags? (#3513)"}],"action":{"name":"View Issue","url":"https://github.com/DIRACGrid/DIRAC/issues/3513"}}}

**Comment by Andrew-McNab-UK** [comment]
Hi Andrei. Yes, I implicitly had an LHCb-like situation where you have lots of more generic jobs passing through the system and a smaller number of jobs which require specific CPU features, and so have the opportunity to match in amongst all that activity.  There are a couple of solutions I can see for when that isn't true. 

1) We could ensure the features are transmitted to the CS somehow as you say, which would either mean making sure they are added to the BDII (for instance, and tricky since it involves persuading all the grid CE projects to publish it) and collected and added by us; or we collect what the JobAgents are reporting to the matcher, and put that in the CS; or people just do it manually if we're talking about a small number of sites.

2) We could have a Vacuum mode in the SiteDirectors for relevant sites, which has been mentioned before: always submit pilots, but throttle the rate if they are not finding any matches. That way you can discover that actually a site which has specific CPU features does find lots of matches even though you can't tell from the CS that the features are there. At Manchester, we have an experimental CREAM-CE vacuum pilot factory plugin for Vcycle which achieves a similar thing with GPU requirements.

(For VM- and container-based Vac and Vcycle sites, they're always in Vacuum mode so we get scenario 2 automatically.)

I'll go ahead and look at doing a PR so we can see what this would look like in practice. We do need some kind of solution since specific CPU extensions (and GPUs) are appearing in people's requirements more and more.

**Comment by fstagni** [comment]
Hi,
In LHCb we have a similar situation, meaning LHCb jobs now need to know the microarchitecture of the WN. Matching then needs to be precise enough.

The solution adopted is maybe LHCb specific, but can possibly be used also by other users, like SKA. We didn't use the tags for this purpose. Rather, we embed the information about the microarchitecture in the "platform", determined at runtime by the pilot. The `dirac-platform` script (invoked by the pilot, see https://github.com/DIRACGrid/Pilot/blob/master/Pilot/pilotCommands.py#L809) is replaced in LHCb by the invocation of the following script:

```
>>> import LbPlatformUtils
>>> LbPlatformUtils.dirac_platform()
'x86_64-slc6.avx2+fma'
```
The above says that the current host is an slc6 and has avx2 and fma instructions. Through the same library we also get the list of "equivalent" platforms.

LbPlatformUtils is pure python and can be installed with 
```
pip install LbPlatformUtils --trusted-host=lhcb-pypi.web.cern.ch --extra-index-url=https://lhcb-pypi.web.cern.ch/lhcb-pypi/simple
```

We didn't go for the solution with Tags because we often see situations of non-homogeneous queues, containing WNs with different microarchitectures.

**Comment by fstagni** [comment]
I close this as it was more of a question than a feature request, and also because there have been no more interactions in 3 years.
