### ISSUE TITLE
[DEPRECATION:v7r1] Base-SE will not be looked up anymore in StorageElements section

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#3516]
The lookup will be performed exclusively in StorageElementBases section

@fstagni please assign to me, set a milestone for v7r1 and add the DMS/Resources label. Thanks !

**Comment by fstagni** [comment]
@chaen was there a PR merged already for solving this issue?

**Comment by fstagni** [comment]
Just bumping on this one, asking for news.

**Comment by fstagni** [comment]
Bumping this one, as it's marked for v7r1.

**Comment by chaen** [comment]
Ah I had forgotten that ! I will make a PR
