### ISSUE TITLE
dirac-install-plus

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#3517]
There's the need for a more powerful dirac-install that would take solve at least the following use case:

- Install a not-released release, e.g. a branch, like integration or master branch

Probably it should be a script that downloads itself. It should be parametrizable, and maybe plugin based.

**Comment by fstagni** [comment]
Following today's discussion in BiLD-Dev meeting: please write down here what is the use case you want to solve. Try, if possible, to stick with the "AS someRole I WANT TO do xyz beacuse blahblah"

**Comment by andresailer** [comment]
As a developer/tester, I want to quickly install an installation of (iLC)DIRAC where the software folders (DIRAC, ILCDIRAC) are checkouts of the git repositories.
```
dirac-install -V ILCDIRAC -r v28r0p7 -g v14r2 -m http://github.com/DIRACgrid.... ,https://gitlab.cern.ch/...
```
right now I do `dirac-install`, followed by replacing the DIRAC and ILCDIRAC folders by git clone
This would also be used in the CI installations where we test against the HEAD of various DIRAC branches. As far as I understand this is already possible with the changes Zoltan has done. It would be cumbersome to write this into a cfg file first.

**Comment by chaen** [comment]
As a Developper, as a tester, I WANT to be able to give a config file to DIRAC install:

```
BaseURL = http://lhcbproject.web.cern.ch/lhcbproject/dist/LHCbDirac_project
DIRACOSURL=https://myURL
OTHERMODULE=git+https://myrepo
LASTMODULE=/my/loca/path/
LocalInstallation
{
  Project = LHCb
  LcgVer = 2016-06-27
  Release = v8r3p2
  PythonVersion = 27
  ConfigurationServer = dips://lhcb-conf-dirac.cern.ch:9135/Configuration/Server
  Setup = LHCb-Production
  SkipCAChecks = True
  SkipCADownload = True 
 ######## THIS IS NEW ######
  DIRACOS=vX 
  OTHERMODULE=vY
  LASTMODULE=vZ
}
```

I would like to trigger it with something like

```
dirac-install -t server --configFile = myConfigFile.cfg
```

By default, each module should be taken from the `BaseURL + moduleName + version`

But if I specify `MODULEURL`, I want the module to be taken there. The url can be

* a local path: This is obviously for testing purpose, so I just expect the whole directory to be copied. There, the version becomes irrelevant 
* a git url: I would want a clone and checkout. The branch is the version indicated in LocalInstallation
* a standard url: then it works like baseURL, but from a specific url `url + moduleName + version`

**Comment by chaen** [comment]
As a VO, I must be able to give a specific URL to be used for DIRACOS, because as a VO, I might have my own DIRACOS

**Comment by zmathe** [comment]
I finalised dirac-install.py You can install DIRAC and its extension various ways. For example:

-giving a config file:
```
DIRACOS = http://lhcb-rpm.web.cern.ch/lhcb-rpm/dirac/DIRACOS/
WebAppDIRAC = https://github.com/zmathe/WebAppDIRAC.git
DIRAC=https://github.com/DIRACGrid/DIRAC.git
LocalInstallation
{
  # Project = LHCbDIRAC
  # The project LHCbDIRAC is not defined in the globalsDefaults.cfg
  Project = LHCb
  Release = v9r1p20
  Extensions = LHCb
  ConfigurationServer = dips://lhcb-conf-dirac.cern.ch:9135/Configuration/Server
  Setup = LHCb-Production
  SkipCAChecks = True
  SkipCADownload = True
  WebAppDIRAC=extjs6
  DIRAC=rel-v6r20
}
```
dirac-install -l LHCb -e WebApp,LHCbWeb -r v9r2-pre8 -t server --dirac-os --dirac-os-version=0.0.6 /home/zmathe/install.cfg 

If you do not want to use a local configuration file, you can use the options what I already presented. More details are in the dirac-install.py file

**Comment by fstagni** [comment]
Just reminding about including requirements in https://github.com/DIRACGrid/DIRAC/issues/3478.

**Comment by fstagni** [comment]
Merged in v7r0-pre8
