### ISSUE TITLE
Review JobDescription Module and Operations/JobDescription Doc.

### ISSUE THREAD

**Issue by graciani** [DIRACGrid/DIRAC#352]
There are some inconsistencies in the Module (ie, it checks CPUTime instead of MacCPUTime which is the payload option relevant for the scheduling).
This is a rather powerful tool that needs to be maintained.

**Comment by chaen** [comment]
@phicharp this is part of what you revisited, isn't it ?

**Comment by phicharp** [comment]
No, this is part of what SOMEONE should revisit... I don't feel courageous enough.... but it is just a mess (although I don't fully understand which Module Ricardo was taking about in this issue ;-)

**Comment by fstagni** [comment]
Way too old, anyway fixes in (what was probably Ricardo's direction...?) in https://github.com/DIRACGrid/DIRAC/pull/4799
