### ISSUE TITLE
Update MyProxyRenewalAgent

### ISSUE THREAD

**Issue by graciani** [DIRACGrid/DIRAC#353]
This Agent has to be revisited in order to be able to use it. The idea is that DIRAC ProxyManager will only keep short term proxies and this agent will keep them up-to-date by getting new delegations from a myproxy server. This requires users to delegate "dirac" proxies to a myproxy server with proper naming.
Do we want to keep this functionality?

**Comment by chaen** [comment]
Since there was a PR merged, can this be closed ?
