### ISSUE TITLE
[v6r19] Accounting Plots inconsistent

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRAC#3546]
The WMS History plots are showing inconsistent distributions. For example: showing Running jobs vs. Site/User/JobGroup (WMSHistory, NumberOfJobs, Group By Site/User/Jobgroup, MajorStatus=Running) gives three different total distributions, although they should be the same.
![image](https://user-images.githubusercontent.com/2115797/33023556-db56def2-ce08-11e7-9453-5d220a1914ef.png)
![image](https://user-images.githubusercontent.com/2115797/33023588-f0baec48-ce08-11e7-8e1b-42c5e5c8f470.png)
![image](https://user-images.githubusercontent.com/2115797/33023573-e49c88ea-ce08-11e7-94d9-c2daa75d50cf.png)

**Comment by zmathe** [comment]
Yes, we have noticed and I put back the old code. If you moved to mysql 5.7, you have to wait until the fix will be provided. Hopefully, it will be very soon.

**Comment by zmathe** [comment]
this is the commit, which is causing the problem: https://github.com/DIRACGrid/DIRAC/commit/899f5ebbb1d91142db9d1dacc356d08a8c17e401#diff-47b843d162c50bf7ede1ca54b1fa8fa2

**Comment by andresailer** [comment]
So if I didn't move to mysql 5.7 there should be a fix? Or should I revert the commit you mention as a hot fix?

**Comment by andresailer** [comment]
I reverted the commit as a hot fix

**Comment by zmathe** [comment]
the bug is fixed in: https://github.com/DIRACGrid/DIRAC/pull/3550

**Comment by fstagni** [comment]
Merged, release.
