### ISSUE TITLE
New DIRAC job time strategy

### ISSUE THREAD

**Issue by Andrew-McNab-UK** [DIRACGrid/DIRAC#3549]
I'm posting this idea after discussions during the LHCb Computing
Workshop this week. We believe this will work for us, but what about
the wider DIRAC community?

At the moment time and work ("normalized time") appear in many
places in the Pilot and JobAgent, and in their associated scripts.
I'm in the process of using the new MJF module throughout, wherever
Machine/Job Features are used. I was going to propose reusing the
existing TimeLeft code to get the job slot limits from the batch
systems where they aren't available from MJF, but Philippe suggested
that there was little point to this as the information is so 
unreliable at sites (hidden scaling of CPU time etc.)

So this is my simplified proposal in light of that:

The Pilot will attempt to discover the wallclock limit from 
MJF. If that isn't available then a global wallclock limit will 
be taken from the DIRAC CS (eg 48 hours), with the option to 
override this with per-queue or per-CE wallclock limits from the 
DIRAC CS. However it is obtained, this wallclock limit will be 
used when deciding whether to send the StopSig signal to warn 
payloads to stop, and when deciding if there is enough time 
left to request another payload.

It will also be used in the matching, by calculating the 
maximum CPU work available equal to (wallclock time limit in 
seconds) * (CPU power) * (processors) and this value will be the 
one given to the matcher. That allows for a worst case of payloads
needing 100% CPU.

This means that the dependencies on TimeLeft() can be removed, and
in its place the MJF module will be used, either relying on values
from Machine/Job Features or from defaults in the DIRAC CS as above.

The less radical way of implementing this would be to have a 
switch that turns TimeLeft() (ie trying to interrogate the 
batch systems) off and on.

**Comment by fstagni** [comment]
While still largely valid, I close this issue for a few reasons:

1. It's already partly implemented
2. there's an actual discussion going on in https://github.com/DIRACGrid/DIRAC/issues/4544 on this topic, that also includes the case of multi-processors (and now the 2 issues are linked)
3. MJF unfortunately is not in our hands, and we still rely on the batch systems.
