### ISSUE TITLE
Rounding in DEncode acceptable ?

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#3551]
Hi,

DEncode is not reliable for numerical data:

```
In [1]: from DIRAC.Core.Utilities.DEncode import encode, decode

In [2]: d = 133143986190.0

In [3]: import sys

In [4]: sys.maxint > d
Out[4]: True

In [5]: encode(d)
Out[5]: 'f1.3314398619e+11e'

In [6]: decode(encode(d))
Out[6]: (133143986190.00002, 18)
```

notice that  `133143986190.0 != 133143986190.00002 `

Are we happy with that ??

**Comment by atsareg** [comment]
Interesting. However, we are in the process of migration from DEncode to a json based solution. So, json should be inspected for the same kind of problem

**Comment by chaen** [comment]
That's how I found it. I am writing the unit tests.

**Comment by zmathe** [comment]
json is more standard than DEncode and used by lot of communities not only us. JSON can not have this kind of problem.

**Comment by zmathe** [comment]
>>> d = 133143986190.0
>>> json.loads(json.dumps(d))
133143986190.0
>>>

**Comment by chaen** [comment]
We have much worse with json... I start wondering whether JSON is the solution for us. This btw is not an implementation limitation, but a standard limitation
```
In [1]: import json

In [2]: d = { 0 : 0 }

In [3]: json.loads(json.dumps(d))
Out[3]: {u'0': 0}
```

**Comment by zmathe** [comment]
Yes, the developer has to know about what she/he is doing. I have no problem with json. We are using it for the web and for the bkk.  In addition it is used most of the web portals... Yes, I know we also can have more fun with the dates.

**Comment by chaen** [comment]
I am not sure that this is an acceptable behavior. 
In any case, the more I think of it, the less I am convince we should focus on the serialization first. We should rather consider first the RPC libraries, and maybe the serialization is bundled with it. 
But you are right, this is the most used for "inter-connection" with web portals and so on.

**Comment by chaen** [comment]
A "detail" but still interesting (I*love* hypothesis :D)
Using the strftime method, one cannot have date before 1900.  I guess that's fine... :-) 
```
ValueError: year=1899 is before 1900; the datetime strftime() methods require year >= 1900
```

**Comment by chaen** [comment]
I close that one, since there is no real resolution to come, and we know of JSON limitations now
