### ISSUE TITLE
Heavy queries to RequestDB

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#3581]
Through the Request Manager Web App one can potentially submit VERY heavy queries, that can take several hours to complete and that would end up completely blocking the DB. This is a danger that, I believe, lies in the RequestManager service. Can we avoid it?

**Comment by fstagni** [comment]
This PR: https://github.com/DIRACGrid/WebAppDIRAC/pull/283 removes the RequestManager WebApp, but this is obviously a non-solution.

**Comment by chaen** [comment]
I am not sure how one could avoid it since in order to infer if it is big or not, you have to do the same query. The only thing is that it will only read the keys (primary and foreign) but not the data itself. 

However, how about making the web.cfg NOT part of the release ? :)

**Comment by chaen** [comment]
There was a bug in the query though. Fixed in https://github.com/DIRACGrid/DIRAC/pull/3584

**Comment by chaen** [comment]
Can be closed now ?
