### ISSUE TITLE
[v6r19] Logging: space added after message

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRAC#3587]
If there is no variable message the new logging adds a space at the end of the message, this breaks the output from, e.g., dirac-dms-find-lfns when redirected to a file and then passing the file to, e.g., dirac-dms-lfn-replicas. Because the last lfn has an additional space in the line it cannot be found.

**Comment by chaen** [comment]
Hum, looking at how logging works, I am not really sure how one could avoid that. You define an abstract format against which you then map a dictionary containing the various information. For example see https://github.com/DIRACGrid/DIRAC/blob/integration/Resources/LogBackends/AbstractBackend.py#L76
So the format cannot be conditional.
However, I'd say that whatever script tries to be clever by taking input like this should correctly strip down spaces.
In LHCbDIRAC, we have a fantastic sets of tools that perform all this, and we extended all the scripts to make use of them. @phicharp wrote them and tried to port them to DIRAC. Unfortunately, they all rely on the fact that the last occurrence of the VO name in the file path is the beginning of the LFN. And this was breaking things for ILC (I can't find the discussion anymore)

**Comment by andresailer** [comment]
"Discussion" for the LFN naming convention problem for ILC: https://groups.google.com/forum/?hl=en#!topic/diracgrid-forum/qG2suaGbIrQ

Yes, would be nice if all the dirac scripts reading files of LFNs would cleanup the input, though there might be external scripts where these things will be piped to or other complications outside of dirac.

I think I found a solution... PR coming up

**Comment by andresailer** [comment]
Fixed
