### ISSUE TITLE
Link not put up in dirac.readthedocs.io for installing DIRAC client.

### ISSUE THREAD

**Issue by rtanmay** [DIRACGrid/DIRAC#3607]
Hi,
The link is not there for a in-depth explanation of lcgBundle package and its versions on client installation in dirac.readthedocs.io , it shows [put link] instead of the link.

link-->http://dirac.readthedocs.io/en/latest/UserGuide/GettingStarted/InstallingClient/index.html
Attaching the screenshot.

![screenshot from 2018-01-28 09-59-11](https://user-images.githubusercontent.com/34454817/35479011-f280db52-0411-11e8-930e-294ec879dd61.png)

If this is not the correct place for this issue, then I apologize for any inconvenience caused.

I looked at the source code and this is written within the paragraph tag.
![new](https://user-images.githubusercontent.com/34454817/35507389-9443ed20-0512-11e8-9eed-fc19b8789fb6.png)

I found this while reading, so thought would share this :)

**Comment by fstagni** [comment]
Thanks. Fixed in https://github.com/DIRACGrid/DIRAC/pull/3613
