### ISSUE TITLE
[lcgBundle] incorrectly packaged gfal2 library

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#3614]
v13r0 on SL6, v6r19p10 dirac UI

```
lx01:2018_Jan_04_1602_gridpp_EL6 > gfal-ls
Traceback (most recent call last):
  File "/home/hep/dbauer/check_dirac/2018_Jan_04_1602_gridpp_EL6/Linux_x86_64_glibc-2.12/bin/gfal-ls", line 24, in <module>
    from gfal2_util.shell import Gfal2Shell
ImportError: No module named gfal2_util.shell
```
This is because past of the gfal library is installed in the python 2.6 site-packages instead of 2.7.

On SL7 this works, though this might be by coincidence as the system version is 2.7:
```
x02:check_dirac > cd 2018_Jan_08_1535_gridpp_EL7
lx02:2018_Jan_08_1535_gridpp_EL7 > source bashrc
lx02:2018_Jan_08_1535_gridpp_EL7 > gfal-ls
usage: gfal-ls [-h] [-V] [-v] [-D DEFINITION] [-t TIMEOUT] [-E CERT]
```

**Comment by fstagni** [comment]
Hi Daniela,
what is the content for the etc/bashrc file?

@closier @chaen what do you think?

**Comment by chaen** [comment]
That Daniela said it all :-)  Some things of the bundle indeed still go to python 2.6

```
[chaen@localvm6 ~]$ ls dirac/Linux_x86_64_glibc-2.12/lib/python2.6/
glite_wmsui_AdWrapper.py    glite_wmsui_SdWrapper.pyc  wmsui_checks.pyc
glite_wmsui_AdWrapper.pyc   glite_wmsui_SdWrapper.pyo  wmsui_checks.pyo
glite_wmsui_AdWrapper.pyo   glite_wmsui_UcWrapper.py   wmsui_listener.py
glite_wmsui_LbWrapper.py    glite_wmsui_UcWrapper.pyc  wmsui_listener.pyc
glite_wmsui_LbWrapper.pyc   glite_wmsui_UcWrapper.pyo  wmsui_listener.pyo
glite_wmsui_LbWrapper.pyo   site-packages              wmsui_utils.py
glite_wmsui_LogWrapper.py   wmsui_api.py               wmsui_utils.pyc
glite_wmsui_LogWrapper.pyc  wmsui_api.pyc              wmsui_utils.pyo
glite_wmsui_LogWrapper.pyo  wmsui_api.pyo
glite_wmsui_SdWrapper.py    wmsui_checks.py
```

**Comment by fstagni** [comment]
The lcgBundle v14r1 (NOT v14r0, which will never go to production) is still in testing so I wouldn't advise to use it (although it looks OK for us).

The "temporary fixes" usually end up like we know: https://i.pinimg.com/564x/fa/a8/7d/faa87dd3a0e961df7474310035dd6945.jpg
that they stay "forever". 

Anyway, unless @closier or @atsareg or @chaen have a better idea... we can go for it.

**Comment by chaen** [comment]
Unless manually moving the files when building he bundle, there's no other way for the time being

**Comment by atsareg** [comment]
Hi Chris,
      
        How difficult is it ? Can we do it at least once as an emergency
      measure ? We have quite a lot of requests
      for the gfal2/SE access in CC7 environment coming from various
      places.
      
        Cheers,
        Andrei 
      
      On 11/04/18 08:08, chaen wrote:
    
    
      Unless manually moving the files when building he bundle,
        there's no other way for the time being
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DIRACGrid/DIRAC","title":"DIRACGrid/DIRAC","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/DIRACGrid/DIRAC"}},"updates":{"snippets":[{"icon":"PERSON","message":"@chaen in #3614: Unless manually moving the files when building he bundle, there's no other way for the time being "}],"action":{"name":"View Issue","url":"https://github.com/DIRACGrid/DIRAC/issues/3614#issuecomment-380338185"}}}

**Comment by chaen** [comment]
I am not in favor of doing it in the bundle because it impacts everyone, and even if I do not think that it will have nasty effect, we do not have the time to test it extensively. So I'd rather ask the VO that wants to use it on centos7 to slightly change their bashrc. 

DIRACOS is clean from that point of view.

**Comment by fstagni** [comment]
I checked on lcgBundle v14r2 (the production version). `gfal2_util` is only in python2.6:

```
[dirac@lbtestvobox pro]$ ll Linux_x86_64_glibc-2.12/lib/python2.6/site-packages/ | grep gfal
-rwxr-xr-x. 1 dirac z5  621928  7. Jun 15:14 gfal2.so
drwxr-xr-x. 2 dirac z5    4096  7. Jun 15:14 gfal2_util
-rw-r--r--. 1 dirac z5     487  7. Jun 15:14 gfal2_util-1.4.0-py2.6.egg-info
-rw-r--r--. 1 dirac z5    8659  7. Jun 15:14 gfal.py
-rw-r--r--. 1 dirac z5   13760  7. Jun 15:14 gfal.pyc
-rw-r--r--. 1 dirac z5   13760  7. Jun 15:14 gfal.pyo
-rwxr-xr-x. 1 dirac z5   70280  7. Jun 15:14 _gfal.so
-rwxr-xr-x. 1 dirac z5   70280  7. Jun 15:14 _gfal.so.0
-rwxr-xr-x. 1 dirac z5   70280  7. Jun 15:14 _gfal.so.0.0.0
-rw-r--r--. 1 dirac z5    9040  7. Jun 15:14 gfalthr.py
-rw-r--r--. 1 dirac z5   13967  7. Jun 15:14 gfalthr.pyc
-rw-r--r--. 1 dirac z5   13967  7. Jun 15:14 gfalthr.pyo
-rwxr-xr-x. 1 dirac z5   70280  7. Jun 15:14 _gfalthr.so
-rwxr-xr-x. 1 dirac z5   70280  7. Jun 15:14 _gfalthr.so.0
-rwxr-xr-x. 1 dirac z5   70280  7. Jun 15:14 _gfalthr.so.0.0.0
[dirac@lbtestvobox pro]$ 
[dirac@lbtestvobox pro]$ ll Linux_x86_64_glibc-2.12/lib/python2.7/site-packages/ | grep gfal
-rwxr-xr-x.  1 dirac z5  883112  7. Jun 15:14 gfal2.so
-rw-r--r--.  1 dirac z5    8659  7. Jun 15:14 gfal.py
-rw-r--r--.  1 dirac z5   13729  7. Jun 15:14 gfal.pyc
-rw-r--r--.  1 dirac z5   13729  7. Jun 15:14 gfal.pyo
-rwxr-xr-x.  1 dirac z5   70280  7. Jun 15:14 _gfal.so
-rwxr-xr-x.  1 dirac z5   70280  7. Jun 15:14 _gfal.so.0
-rwxr-xr-x.  1 dirac z5   70280  7. Jun 15:14 _gfal.so.0.0.0
-rw-r--r--.  1 dirac z5    9040  7. Jun 15:14 gfalthr.py
-rw-r--r--.  1 dirac z5   13936  7. Jun 15:14 gfalthr.pyc
-rw-r--r--.  1 dirac z5   13936  7. Jun 15:14 gfalthr.pyo
-rwxr-xr-x.  1 dirac z5   70280  7. Jun 15:14 _gfalthr.so
-rwxr-xr-x.  1 dirac z5   70280  7. Jun 15:14 _gfalthr.so.0
-rwxr-xr-x.  1 dirac z5   70280  7. Jun 15:14 _gfalthr.so.0.0.0
```

is the decision "won't fix, wait for DIRACOS?"

**Comment by chaen** [comment]
I'd go this way yes... Maybe in the wiki we can put a note saying that if you want to have it working in the meantime, you can use the hack provided by Daniela

**Comment by fstagni** [comment]
So... "Won't fix, wait for DIRACOS". Closing.
