### ISSUE TITLE
AuthManager not correctly forwarding hardcoded properties

### ISSUE THREAD

**Issue by ddossett** [DIRACGrid/DIRAC#3642]
https://github.com/DIRACGrid/DIRAC/blob/56f53245086fc0dbc02456b1b2618dfea45d0087/Core/DISET/AuthManager.py#L78

I noticed some odd behaviour, where if you specify a hardcoded `auth_myservicefunc = ["SomeProperty"]` and nothing in the configuration (except a Default). Then when you try to access this service from a webserver handler (WebAppDIRAC) then the required properties fall back to whatever is in the configuration and ignores the hardcoded one.

I believe the line above is to blame, because it doesn't forward the `defaultProperties` argument of the original authQuery onto the new authQuery once the forwarded credentials are unpacked. I'm hesitant to change this as it's such a fundamental piece of code that I may be misunderstanding. But it feels like simply adding the `defaultProperties` to this function's arguments should be fine e.g.

`return self.authQuery( methodQuery, credDict, defaultProperties )`

In the meantime, I think that specifying the authorization of the service functions explicitly in the configuration should clear this up, if anyone else runs into it.

**Comment by zmathe** [comment]
We do not want to overwrite the CS values with the hardcoded values. The authorisation properties must be defined in the CS. We do not want to release DIRAC, when you want to change the properties.

**Comment by ddossett** [comment]
True and I agree. Which then begs the question of why the `auth_funcname` rules are allowed at all? Why are they discovered and forwarded in the first place in Service.py? And then ignored by the webserver.

https://github.com/DIRACGrid/DIRAC/blob/56f53245086fc0dbc02456b1b2618dfea45d0087/Core/DISET/private/Service.py#L387

Are they supposed to be only for local testing/development of services? If so the documentation should reflect that...

Basically there seems (to me) to be a difference in permissions/behaviour when using the same service from a user's client RPC call and from the webserver handler. If you define a hardcoded `auth_funcname` you can't rely on it when using the webserver. Which could easily get you in trouble if you didn't know about that, and just defined a "Default" authorization for a service overall in CS.

I'm fine with saying that this isn't an actual issue, _if_ the hardcoded auth_ rules are then going to be superseded by the ones in the CS always. I'm not certain if that is true right now. Does this make sense?

**Comment by zmathe** [comment]
Why you want to hardcode the roles? Every time when you have to modify the role you have to release the code. It is not clear to me what you want to do. You should not use hardcoded authorisation roles.

**Comment by ddossett** [comment]
If no-one should be hardcoding roles then why do they still exist? And why are they the main documented way to authorize roles? (at least for new developers)

http://dirac.readthedocs.io/en/latest/DeveloperGuide/AddingNewComponents/DevelopingServices/index.html

I don't use them now, because I realised the mistake. So my question is, can they be removed entirely? If they can't be removed, then they should work consistently between client and webserver. Because right now I'm not sure that they do.

**Comment by fstagni** [comment]
Hi, this is a very good question, thanks for asking it. 

Authorization rules can be, as of today, specified in the code, as well as in CS. This is because of a general rule within DIRAC that is that everything that is "configurable", can be specified in the CS, as well as in the code. I don't think the "auth_" rules in the code should be removed, while I believe that the documentation should better express it. I will update the documentation with that.

**Comment by ddossett** [comment]
Cheers Federico. Let me know what changes get made from this issue.

Per the original comment, I think that checking that the auth rules behave consistently when calling from the webserver compared to other ways to call the Service is probably necessary.

**Comment by zmathe** [comment]
This line is correct:

https://github.com/DIRACGrid/DIRAC/blob/56f53245086fc0dbc02456b1b2618dfea45d0087/Core/DISET/AuthManager.py#L78

We do not want to overwrite the service roles with the web one. We can have in web handler authorization=all. Consequently, if we use 
return self.authQuery( methodQuery, credDict, defaultProperties )
this will allow to connect to the service everyone.
What is the role of the web server machine? It must be only TrustedHost!
Could you please describe what you did?

**Comment by ddossett** [comment]
The Webserver machine has TrustedHost in the Host properties. I believe the situation was something like this (I may be remembering wrong as I didn't end up committing the code that failed my tests).

My DIRAC Service had only the Default authorization set in the CS `Default="ProductionManagement"`. For a small number of `export_` functions which didn't affect my DB entries I had hardcoded `auth_FuncName = ["authenticated"]`.

When calling from a DIRAC script this worked fine as the hardcoded `auth_` properties were being forwarded. So I correctly couldn't access any functions except for the hardcoded "authenticated" ones unless I changed to a proxy with the right property.

In the WebApp handler I had set `AUTH_PROPS = "authenticated"`. Several of the `web_FuncName` methods were calling (via RPCClient and threadTask) the special `auth_FuncName=["authenticated"]` functions of the service to retrieve some data. So in my understanding anyone who could connect to the WebApp should be able to run those functions.

However, what actually happened was that the hardcoded `auth_FuncName` properties of the service weren't forwarded to the second `authQuery` call because the connection came from the webserver. This meant that `authQuery` then used the CS to find out the allowed properties, which then found the `Default="ProductionManagement"` and no specific authorization for individual functions. Then those RPC calls from the webhandler failed as unauthorized, because I was connected to the webserver using a group without the "ProductionManagement" property.

Does this sound plausible? I may have mixed up something. This (possible?) problem disappears entirely if you never hardcode auth rules and only use the CS. But I imagine having `Default="authenticated"` as the only CS defined authorization, and then having hardcoded ones for special functions is probably quite common in the real world. Which if I'm right (I'm not sure) means that the webhandler would never fail to authorize any RPC call to a Service configured in this way i.e. no CS defined authorizations except a default. I just got lucky that I defined my default authorization as more exclusive than normal, instead of the other way round, so I noticed it when things failed on the webapp.

**Comment by zmathe** [comment]
Okay. It is clear now. First of all let me clarify one thing:
You can specify the auth_FuncName = [something] in the code, but this will be overwritten by the CS value... 
This is already explained by Federico.
When you use WebApp it is the same. AUTH_PROPS is used by the web handler. We use all or authenticated:
-all: everyone without proxy can access to the portal
-authenticated: need a valid certificate, this certificate needs to be registered in DIRAC.
You can have AUTH_PROPS = "all" in WebApp, but you will be not able to connect to a DIRAC service.
When you use WebApp the user credential is forwarded to the DIRAC service and the authorisation is based on the user certificate.
Probably, when you were able to connect to the DIRAC service, you were using the correct role. For example:
https://lhcb-cert-dirac.cern.ch/DIRAC/s:LHCb-Certification/g:lhcb_user/LHCbJobMonitor/getStatisticsData?JobID=%5B%5D&RunNumbers=%5B%5D&limit=25&startDate=&startTime=&endDate=&endTime=&owner=%5B%22zmathe%22%5D&statsField=Status
In that case if the lhcb_user has the ProductionManagent role can access to the service otherwise can't.
I have a feeling when you used the DIRAC client you used different group than the web browser. But again I do not see any problem with WebApp. It behaves as expected.

**Comment by zmathe** [comment]
The web server authorisation is different than the DIRAC service. If you want to restrict the web server access, you have to add to the CS:
WebApp
{
   Access
  {
    methodName = role
  }
}

**Comment by fstagni** [comment]
I have simply updated the doc in https://github.com/DIRACGrid/DIRAC/pull/3649

**Comment by ddossett** [comment]
Hi Federico, I like the doc changes you've made. Much more spelled out for novices like me :)

Ok so I've created and attached a mini DIRAC extension to test what I believe is the weird behaviour. I actually ran this code as part of an existing extension so hopefully I put it together in a working state. Anyway, the output is below, and if after reading this you still think it's correct behaviour then that's fine. I'll just be the minority.

[MyExtensionDIRAC.tar.gz](https://github.com/DIRACGrid/DIRAC/files/1839969/MyExtensionDIRAC.tar.gz)

Basically, the extension just has a Service with two methods, once with no `auth_` rule (so it falls back to the CS always) and one with a hard-coded `auth_` rule for the "ProductionManagement" property. So the behaviour I expect is that because there is no explicit CS entry for that function it should **always be impossible for me to run that method unless I am connected using a group with that property**. The ConfigTemplate.cfg file only contains a `Default="authenticated"` entry so the hard-coded `auth_` will not be overwritten and should always be used. The function without an `auth_` rule will fall back to the CS and use the `Default="authenticated"`.

I have included a unittest which should fully succeed if you are running it using a group with "ProductionManagement", and one of the two tests will fail if you don't have that property. Running the test myself without the right property gives this Service logging (slightly edited to remove my details):

> 2018-03-23 01:50:31 UTC DIRACAuthTest/DIRACAuthTester[GZ9q]  DEBUG: Received action from client RPC/failsWithoutProductionManagement
2018-03-23 01:50:31 UTC Framework/Authorization[GZ9q]   VERB: Trying to authenticate DN=MyDN
2018-03-23 01:50:31 UTC Framework/Authorization[GZ9q]   VERB: Using hardcoded properties for method failsWithoutProductionManagement : ['ProductionManagement']
2018-03-23 01:50:31 UTC Framework/Authorization[GZ9q]   WARN: Client is not authorized
2018-03-23 01:50:31 UTC Framework/Authorization[GZ9q]   WARN: Valid properties: ['ProductionManagement']

Great! Everything works correctly, the hard-coded rule prevented me from running the method. Now lets try with the correct property and see if we succeeded in the Service log.

> 2018-03-23 02:09:50 UTC Framework/Authorization[LFj4]   VERB: Trying to authenticate DN=MyDN
2018-03-23 02:09:50 UTC Framework/Authorization[LFj4]   VERB: Using hardcoded properties for method failsWithoutProductionManagement : ['ProductionManagement']
2018-03-23 02:09:50 UTC DIRACAuthTest/DIRACAuthTester[LFj4]   INFO: DIRACAuthTesterHandler ...
2018-03-23 02:09:50 UTC DIRACAuthTest/DIRACAuthTester[LFj4]  DEBUG: Executing RPC:failsWithoutProductionManagement action
2018-03-23 02:09:50 UTC DIRACAuthTest/DIRACAuthTester[LFj4] NOTICE: Executing action ([::ffff:115.146.84.190]:38274)RPC/failsWithoutProductionManagement(<masked>)
2018-03-23 02:09:50 UTC DIRACAuthTest/DIRACAuthTester[LFj4]  DEBUG: RPC to export_failsWithoutProductionManagement
2018-03-23 02:09:50 UTC DIRACAuthTest/DIRACAuthTester[LFj4]   INFO: You ran DIRACAuthTester.failsWithoutProductionManagement()
2018-03-23 02:09:50 UTC DIRACAuthTest/DIRACAuthTester[LFj4] NOTICE: Returning response ([::ffff:115.146.84.190]:38274)[belle_mcprod:ddossett] (0.02 secs) OK

Right again! Using the correct property allowed me access to the Service function that had a hard-coded rule. No problems on the command line side of things.

Now the weird part. I also included a simple WebApp which just has a couple of buttons which run `web_` functions from Ajax requests. Each one tries to run the corresponding DIRACAuthTester function from an RPC client threadTask. The WebApp only has `AUTH_PROPS="authenticated"` and in the web.cfg it has **no Access configuration for the web_ methods**. I think this may be where we differ in expectations. I would expect the calls to the `web_` functions to run for every authenticated user, **but** I expect the actual RPC call to the Service function to fail when I'm not using the right group in the webserver. So I'm allowed to click the button and run the python handler function, but the python handler shouldn't actually succeed in running the Service function when I don't have "ProductionManagement" as one of my roles. It should allow me to run the webhandler, but not the service.

Here's the WebApp log when I run it with "ProductionManagement" as one of my roles (we expect no issues)

> 2018-03-23 02:21:03 UTC WebApp   INFO: Caller's group is belle_mcprod
2018-03-23 02:21:03 UTC WebApp   INFO: Caller's properties are ['NormalUser', 'JobSharing', 'AlarmsManagement', 'ServiceAdministrator', 'CSAdministrator', 'JobAdministrator', 'FullDelegation', 'ProxyManagement', 'Operator', 'FileCatalogManagement', 'ProductionManagement']
2018-03-23 02:21:03 UTC WebApp   INFO: You must have had ProductionManagement in your properties

Ok great, as expected I can run both the web_ and contained RPC functions successfully and my properties are being sent to the WebApp. Now look what happens when I deliberately instead use a role that doesn't have "ProductionManagement"

> 2018-03-23 02:23:41 UTC WebApp   INFO: Caller's group is belle
2018-03-23 02:23:41 UTC WebApp   INFO: Caller's properties are ['NormalUser']
2018-03-23 02:23:41 UTC WebApp   INFO: You must have had ProductionManagement in your properties

Uh Oh! My user group and properties are correctly found in the WebApp handler, but the RPC service call succeeded! It shouldn't have succeeded because I hard-coded it not to. But because I failed to provide a CS entry for this `auth_` rule the webserver circumvented the authentication and fell back to the `Default="authenticated"` entry in the CS. What about the Service log when this happened?

> 2018-03-23 02:23:41 UTC Framework/Authorization[LFj4]   VERB: Trying to authenticate DN=MyDN extraCredentials=('MyDN', 'belle')
2018-03-23 02:23:41 UTC Framework/Authorization[LFj4]   VERB: Using hardcoded properties for method failsWithoutProductionManagement : ['ProductionManagement']
2018-03-23 02:23:41 UTC Framework/Authorization[LFj4]   VERB: Query comes from a gateway
2018-03-23 02:23:41 UTC Framework/Authorization[LFj4]   VERB: Trying to authenticate DN=MyDN group=belle
2018-03-23 02:23:41 UTC Framework/Authorization[LFj4]   VERB: Method failsWithoutProductionManagement has no properties defined using /Default
2018-03-23 02:23:41 UTC DIRACAuthTest/DIRACAuthTester[LFj4]   INFO: DIRACAuthTesterHandler ...
2018-03-23 02:23:41 UTC DIRACAuthTest/DIRACAuthTester[LFj4]  DEBUG: Executing RPC:failsWithoutProductionManagement action
2018-03-23 02:23:41 UTC DIRACAuthTest/DIRACAuthTester[LFj4] NOTICE: Executing action ([::ffff:43.240.99.205]:35306)[belle:ddossett] RPC/failsWithoutProductionManagement(<masked>)
2018-03-23 02:23:41 UTC DIRACAuthTest/DIRACAuthTester[LFj4]  DEBUG: RPC to export_failsWithoutProductionManagement
2018-03-23 02:23:41 UTC DIRACAuthTest/DIRACAuthTester[LFj4]   INFO: You ran DIRACAuthTester.failsWithoutProductionManagement()
2018-03-23 02:23:41 UTC DIRACAuthTest/DIRACAuthTester[LFj4] NOTICE: Returning response ([::ffff:43.240.99.205]:35306)[belle:ddossett] (0.01 secs) OK

This confirms what I said in the first comment on the issue. The service identifies the correct user group, and then it identifies the hard-coded properties. **But** then it identifies that the query was from a gateway and re-runs `authQuery` without the discovered hard-coded properties. Basically forgetting they exist. This forces the `authQuery` to then find the correct method Authorization rule from the CS, but there isn't an explicit rule in the CS, it was only hard-coded. So it goes to the `Default="authenticated"` one, identifies me as authenticated and runs it succesfully.

So by wrapping a Service call in a Webhandler function and not defining auth_ rules for the service explicitly in the CS, I can accidentally run Service functions my group was hard-coded to not be authorized for.

However, this does assume that my WebHandler function also doesn't have a rule preventing the user's group from running the Ajax request. So this is where we differ in opinion possibly? I think that the webhandler function permissions and the service permissions are separate. And that if you've hard-coded a service `auth_` rule, the webhandler threadTask shouldn't be able to run it without the right property. I think that the webhandler threadTask should have failed in this case. I find this to be an inconsistent bit of behaviour, even if it's only likely to occur for lazy people like me who are playing fast and loose with `auth_` rules.

Cheers,
Dave

**Comment by zmathe** [comment]
You are right according to the log it does not work correctly when we have hardcoded rules... I am going to fix it.

**Comment by zmathe** [comment]
Thanks again for reporting. Indeed, this can be a security hole, if someone was using hardcoded properties.  It is fixed in #3651

**Comment by ddossett** [comment]
Great, thanks for the quick fix Zoltan. Feel free to close the issue once the PR goes through.

**Comment by zmathe** [comment]
fixed in v6r20
