### ISSUE TITLE
Input from LSST on porting from Python 2 to Python 3

### ISSUE THREAD

**Issue by airnandez** [DIRACGrid/DIRAC#3696]
As discussed in the [8th DIRAC Users Workshop](https://indico.cern.ch/event/676817) in Lyon, here are some inputs on the experience of [LSST](https://lsst.org) on porting its code from Python 2 to Python 3:

* [Overview of the process](https://project.lsst.org/meetings/lsst2016/sites/lsst.org.meetings.lsst2016/files/201608-LSST2016-py3_0.pdf), Aug. 2016
* [Porting the LSST Data Management Pipeline Software to Python 3](https://arxiv.org/abs/1611.00751) by [Tim Jenness](https://github.com/timj), Nov. 2016
* [Porting the LSST DM Stack to Python 3](https://sqr-014.lsst.io)

**Comment by ptrktn** [comment]
Let me then ask what are the current plans to port DIRAC to Python 3?

**Comment by fstagni** [comment]
First "real" python3 support coming in with #4732 in DIRAC v7r2 following recommendations in #4521 .
This task (for "porting support") can be closed.
