### ISSUE TITLE
Bug in job status logic when it is updated by two sources with same timestamp (v6r0)

### ISSUE THREAD

**Issue by hamar** [DIRACGrid/DIRAC#372]
A user submitted a job with InputSandbox than can't be downloaded for the job wrapper.

JobWrapper failed to download input sandbox 
== EXCEPTION ==
:{'/vo.formation.idgrilles.fr/user/d/doantrungtung/panam/inputs/g-panam-split.tar.gz': 'ReplicaManager.getFile: Failed to get local copy from any replicas.'}
  File "/var/spool/pbs/tmpdir/123901.prabi-ce3.ibcp.fr/DIRAC_pJqpnkpilot/job/Wrapper/Wrapper_41671", line 71, in execute
    raise JobWrapperError( result['Message'] )
===============
Failure during Input Sandbox Download 
Creating a new JobReport Object 
Job will be rescheduled after exception during execution of the JobWrapper

So the job was rescheduled, , changed to running status, after to received and finally stalled, looks like a timestamp problem and status logic when is updated by two different sources, as showed by LoggingInfo:

JobWrapper       Running           Downloading InputSandbox LFN(s)  Unknown                                     2011-12-13 10:49
JobWrapper       Rescheduled   Input Sandbox Download                  Unknown                                     2011-12-13 10:49
JobWrapper       Running          Application                                         Failed Input Sandbox Download 2011-12-13 10:49
JobManager       Received        Job Rescheduled                               Unknown                                     2011-12-13 10:49
StalledJobAgent Stalled            Downloading InputSandbox LFN(s)   Unknown                                     2011-12-13 12:50

**Comment by atsareg** [comment]
The problem with the clock desync, not a DIRAC issue
