### ISSUE TITLE
[v6r20] Documentation inconsistencies

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRAC#3741]
Some files are there but not referenced and therefore not really reachable, not clear to me if they should be referenced or a deprecated.

- [x] /docs/source/AdministratorGuide/GettingStarted/index.rst: WARNING: document isn't included in any toctree
- [x] /docs/source/AdministratorGuide/Systems/DataManagement/data_logging_system.rst: WARNING: document isn't included in any toctree
- [x] /docs/source/AdministratorGuide/Systems/RequestManagement/rms.rst: WARNING: document isn't included in any toctree
- [x] /docs/source/AdministratorGuide/Systems/ResourceStatus/baptism.rst: WARNING: document isn't included in any toctree
- [x] /docs/source/AdministratorGuide/Systems/ResourceStatus/design.rst: WARNING: document isn't included in any toctree
- [x] /docs/source/CodeDocumentation/ResourceStatusSystem/Client/SiteStatus.rst: WARNING: document isn't included in any toctree
- [x] /docs/source/DeveloperGuide/PilotsLogging/index.rst: WARNING: document isn't included in any toctree
- [x] /docs/source/DeveloperGuide/Systems/RequestManagement/index.rst: WARNING: document isn't included in any toctree

One file is referenced by doesn't exist, not sure if this file still exists on someone's hard drive or if the reference should be removed

- [x] /docs/source/AdministratorGuide/Systems/WorkloadManagement/index.rst:48: WARNING: toctree contains reference to nonexisting document u'AdministratorGuide/Systems/WorkloadManagement/PilotsLogging/index

PS: I thought I had posted this already, but I cannot find this any more, so maybe my browser crashed before I could hit submit :frowning:

**Comment by chaen** [comment]
I take care of the RMS/DMS

**Comment by chaen** [comment]
and many more fixes here https://github.com/DIRACGrid/DIRAC/pull/3747

**Comment by fstagni** [comment]
Looking into it --- PR shortly.

**Comment by fstagni** [comment]
Shall this be closed?
