### ISSUE TITLE
[v6r20] Bug in StorageManager checkFilesToStage

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRAC#3764]
Every  once in a while the JobScheduling executor has problems to get the StorageMetadata for some inputs to some jobs. I finally tracked this down to these lines (putting a traceback printout in the writeProxyToFile function):

https://github.com/DIRACGrid/DIRAC/blob/894421bccf2a23300f5fdab6611056006c7fc694/StorageManagementSystem/Client/StorageManagerClient.py#L142-L143
...
https://github.com/DIRACGrid/DIRAC/blob/894421bccf2a23300f5fdab6611056006c7fc694/StorageManagementSystem/Client/StorageManagerClient.py#L161-L165

This separation of StorageElement with and without userProxy doesn't work, because of the gfal2 context, which caches the proxy location, that is part of the StorageElement.

The StorageElement instance needs to be obtained/created when the userProxy exists, and not before.
Thus we either have to wrap this call in another function that gets decorated with `@executeWithUserProxy`, which isn't very nice, or we need to create a contextManager to run
```python
with userProxy(proxyUserName....) as proxyResult:
  if proxyResult['OK']:
    StorageElement(...).getFileMetadata(...)
```

**Comment by andresailer** [comment]
PS: I think there is a race condition in the executeWithUserProxy logic, the os.environ.get("X509_USER_PROXY") is done outside the lock, so it could be changed by another threads executeWithUserProxy, and then restored to a bad value after the other one finished

**Comment by andresailer** [comment]
So I have two solutions (thanks to @chaen for discussions)
1) Minimal changes, but the getFileMetadata is not wrapped by executeWithUserProxy...

https://github.com/DIRACGrid/DIRAC/compare/integration...andresailer:v6r20_smanFix_Minimal?expand=1

2) Creating a contextManager, refactoring the executeWithUserProxy so that most of the code can be re-used, also fixing the race condition.
https://github.com/DIRACGrid/DIRAC/compare/integration...andresailer:v6r20_smanfix?expand=1#diff-9e3fad0049c45575a101f73473d09329R160

**Comment by chaen** [comment]
I like solution 2, very neat. 
I am just wondering whether we could not mix together the decorator and the context using a class that would implement `__calll__`, `__enter__` and `__exit__` ? Wouldn't that factorize the code more ?

**Comment by fstagni** [comment]
Please don't use the generator syntax: I think simply implementing `__enter__` and `__exit__` is much neater and readable.

**Comment by chaen** [comment]
Why not using the generator syntax in general ?

**Comment by fstagni** [comment]
Personal taste, maybe, but the generator syntax is if you want to implement a generator. If you want to implement a context manager, there's the context manager syntax. 
Using a generator for a context manager means generating "once", IMHO this is not intuitive.

**Comment by andresailer** [comment]
I am not sure either syntax is "intuitive", it is just the syntax that has to be used, `yield`, vs `__enter__`/`__exit__`.

```python
class UserProxy(object):
  """Implement a Context Manager to execute functions with a userProxy."""

  def __init__(self,
               proxyUserName=None,
               proxyUserGroup=None,
               proxyUserDN=None,
               proxyWithVOMS=True,
               proxyFilePath=None,
               executionLock=False,
              ):

    if not ((proxyUserName or proxyUserDN) and proxyUserGroup):
      self.result = S_OK()
    else:
      self.result = _putProxy(userDN=proxyUserDN,
                              userName=proxyUserName,
                              userGroup=proxyUserGroup,
                              vomsFlag=proxyWithVOMS,
                              executionLockFlag=executionLock,
                              proxyFilePath=proxyFilePath,
                              )

  def __enter__(self):
    return self.result

  def __exit__(self, _type, _value, _traceback):
    if self.result['OK']:
      originalUserProxy, useServerCertificate, executionLock = self.result['Value']
      _restoreProxyState(originalUserProxy, useServerCertificate, executionLock)
```

**Comment by andresailer** [comment]
Solved
