### ISSUE TITLE
[v6r20] CleanReqDBAgent not kicking it any more (it = assigned requests)

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRAC#3770]
The CleanReqDBAgent does not seem to kick `Assigned` requests. I had many assigned requests stuck in the DB.

As far as I can tell the value for `getRequest.LastUpdate` is always `utcnow()`, and not the `lastUpdate` time of the request taken from the database.

https://github.com/DIRACGrid/DIRAC/blob/4110230189c943cf86b6b26eb83bfc1d91436e3b/RequestManagementSystem/Agent/CleanReqDBAgent.py#L112

**Comment by chaen** [comment]
Hum, that's really surprising. We are still using v6r19, did it use to work correctly then ?

**Comment by andresailer** [comment]
Ahh, no, I messed things up during debugging, that caused the LastUpdate time to be reset. I did not have any assigned requests kicked, but the reason must have been something else... 
I will keep an eye on the requests if the problem pops up again.
