### ISSUE TITLE
LocalComputingElement bug for SLURM queues

### ISSUE THREAD

**Issue by schr476** [DIRACGrid/DIRAC#3799]
Current code has a batchDict with:
``batchDict = {'Executable': submitFile,
                 'NJobs': numberOfJobs,
                 'OutputDir': self.batchOutput,
                 'ErrorDir': self.batchError,
                 'SubmitOptions': self.submitOptions,
                 'ExecutionContext': self.execution,
'JobStamps': jobStamps}
``
However,  SLURM.py required:
 ``   MANDATORY_PARAMETERS = [ 'Executable', 'OutputDir', 'ErrorDir', 'Queue', 'SubmitOptions' ]``

This is  true for all SLURM methods.
Therefore, I believe we need to add ``batchDict = { 'Queue': self.queue, ...}`` in all methods in LocalComputingElement.py

**Comment by fstagni** [comment]
I don't know much about this `LocalComputingElement` and how to use it. At the same time, in the batch LSF there is:

```
    MANDATORY_PARAMETERS = [ 'Executable', 'OutputDir', 'ErrorDir',
                             'WorkDir', 'SubmitOptions', 'Queue' ]
```
and in Torque.py:
```
    MANDATORY_PARAMETERS = ['Executable', 'OutputDir', 'ErrorDir',
                            'Queue', 'SubmitOptions']
```

so, to me they all look similar, and maybe it's a problem of not only SLURM. Do you have evidence it's only for SLURM?

**Comment by schr476** [comment]
Based on your post, it looks like this problem applies to the other queues too.

**Comment by schr476** [comment]
It should be noted that this problem also appears for Host.py

**Comment by schr476** [comment]
The `getJobStatus` doesn't look right either

**Comment by fstagni** [comment]
I committed some changes in #3824 , I can't tell they are enough. Please have a look.

**Comment by fstagni** [comment]
I close this right now, as the PR linked above is merged and released. Please let me know of more issues.
