### ISSUE TITLE
[Doc] Error in the Developer Guide - DevelopingDatabases

### ISSUE THREAD

**Issue by louisjdmartin** [DIRACGrid/DIRAC#3809]
On `DIRAC/docs/source/DeveloperGuide/AddingNewComponents/DevelopingDatabases/index.rst` [(here)](https://dirac.readthedocs.io/en/latest/DeveloperGuide/AddingNewComponents/DevelopingDatabases/index.html) it looks that there is an error:

In the code example you can see `DB.__init__(self, 'AtomDB', 'Test/AtomDB', 10)` and later you can read

> 3. Maximum number of requests to queue. 10 is a good value for this setting.

This example use a class which inherit from `DIRAC.Core.Base.DB` and in this module `__init__` is defined with `def __init__( self, dbname, fullname, debug = False )`. The last argument is debug, not a number of requests to queue.

**Comment by fstagni** [comment]
Fixed in #3824
