### ISSUE TITLE
Bug in reporting replicas 

### ISSUE THREAD

**Issue by atsareg** [DIRACGrid/DIRAC#3811]
When using SE definitions with the VOPath section for setting specific paths per VO, the PFNs constructed on the fly by the FC client always use the common path and not the VO-specific one. Even if this is only for reporting, this is misleading. Example:

   FZK-disk
    {
      BackendType = dCache
      Description = gridka-dCache.fzk.de
      VO = auger
      GFAL2_SRM2
      {
        Access = remote
        Host = gridka-dcache.fzk.de
        Path = /pnfs/gridka.de/auger
        Port = 8443
        Protocol = srm
        SpaceToken = 
        WSUrl = /srm/managerv2?SFN=
        VOPath
        {
          auger = /pnfs/gridka.de/auger/disk-only
        }
      }
    }

And the replica report:

  $ dls -L /auger/prod/d0001/DAT973074_03.offline-v2r8le_SDSIMULATIONRECONSINFILL.tar.bz2
/auger/prod/d0001/DAT973074_03.offline-v2r8le_SDSIMULATIONRECONSINFILL.tar.bz2:
-rwxrwxr-x 2 chudoba auger_prod 41445235 2018-04-24 14:17:28 DAT973074_03.offline-v2r8le_SDSIMULATIONRECONSINFILL.tar.bz2
   UNAM-disk       srm://tlapiacalli.nucleares.unam.mx:8446/srm/managerv2?SFN=/dpm/nucleares.unam.mx/home/auger/prod/d0001/DAT973074_03.offline-v2r8le_SDSIMULATIONRECONSINFILL.tar.bz2
   FZK-disk        srm://gridka-dcache.fzk.de:8443/srm/managerv2?SFN=/pnfs/gridka.de/auger/auger/prod/d0001/DAT973074_03.offline-v2r8le_SDSIMULATIONRECONSINFILL.tar.bz2

**Comment by fstagni** [comment]
Still valid in v6r21?

**Comment by fstagni** [comment]
Up?

**Comment by chaen** [comment]
Fixed in https://github.com/DIRACGrid/DIRAC/pull/3814
