### ISSUE TITLE
confirmBulkSubmission through API?

### ISSUE THREAD

**Issue by alexanderrichards** [DIRACGrid/DIRAC#3823]
Looking at commit 843b62ea04c7570bbdaceb587dcae88870279164

It appears that parametric jobs now need confirmation. Is the [export_confirmBulkSubmission](https://github.com/DIRACGrid/DIRAC/blob/843b62ea04c7570bbdaceb587dcae88870279164/WorkloadManagementSystem/Service/JobManagerHandler.py#L197) function exported to the [API](https://github.com/DIRACGrid/DIRAC/tree/integration/Interfaces/API)? If not can I request it's addition otherwise I simply cannot use the API for parametric jobs any more.

**Comment by alexanderrichards** [comment]
sorry for the noise, I think this might not be needed as the confirmation should be done automatically through the submit. I think that maybe my client is too old. I will try updating and reopen this if the issue persists.

**Comment by fstagni** [comment]
Hi @alexanderrichards we removed the need for a confirmation that was added at some point. Please work with v6r20p12 which is the latest production release.

**Comment by alexanderrichards** [comment]
yes thanks I think it was that my API was too old.
