### ISSUE TITLE
Compatibility issues with python 3.6/7

### ISSUE THREAD

**Issue by scarlehoff** [DIRACGrid/DIRAC#3849]
Hi guys,
The problem I'm encountering has to do with the file 
https://github.com/DIRACGrid/DIRAC/blob/integration/Core/Utilities/Platform.py

In order to reproduce it you can get that file alone and just do

    import Platform
    Platform.getPlaformString()

The error I get is below

    >>> Platform.getPlatformString()
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
     File "Platform.py", line 95, in getPlatformString
    reM = ldre.match( line )
    TypeError: cannot use a string pattern on a bytes-like object

I don't know whether this is a known issue or whether there will be more incompatibilities with python 3.6 beyond this function. I'm saying 3.6/7 because I've tested both python 3.6 and 3.7 in two different computers.

**Comment by fstagni** [comment]
Hi,
in general: DIRAC is python 2.7. We have plans to move to python 3 but not too quickly.

At the same time, this specific file may need to be compatible also with python 3, but for specific reasons. What were your reasons to point and try this specific file?

One more thing: for using different versions of python on the same machine, I suggest "Conda" (miniConda).

**Comment by scarlehoff** [comment]
Oh, I see. Forget my comment then. I’ll close the issue!
As a suggestion, it would be great to indicate that Dirac is only python 2.7 compatible in the readme (or even changing the shebang to python2, but that’s a tad more dangerous :P) 

Wrt the file, that was just the first file that failed when I tried to use Dirac after making python3 the default in my machine so I thought I’d point at it just in case.

Thanks!
