### ISSUE TITLE
Sandbox download has return value None

### ISSUE THREAD

**Issue by mesmith75** [DIRACGrid/DIRAC#3866]
The value returned when downloading sandbox (`getOutputSandbox` in the API) is `None`. It would be useful to have this filled in with the location it was put in.

Also, when selecting to leave the sandbox packed it only ends up in some temp directory and cannot be directed anywhere. Again the return value is `None` so it cannot be found.

Could at least the return be filled in with the location? Many thanks.

**Comment by fstagni** [comment]
Done in https://github.com/DIRACGrid/DIRAC/pull/3867

**Comment by mesmith75** [comment]
Thanks!
