### ISSUE TITLE
Data too long for column 'DiskOccupancy'

### ISSUE THREAD

**Issue by kfox1111** [DIRACGrid/DIRAC#3881]
Looks like the dirac is trying to gather metrics about mounts on the system. it is cramming usage of all mounts into one string then trying to put it into a row. If you have any docker or other container stuff on the system or its containerized, it often exceeds the column size.

**Comment by chaen** [comment]
What do you think should be correct behaviour ?

**Comment by fstagni** [comment]
I modified the length of the field ( I did it in https://github.com/DIRACGrid/DIRAC/pull/3946/commits/c09271984b48e1b2d06a52ea4f83cac7bfb1af72). 
If you want to do it yourself before release, modify MySQL table `HostLogging` of DB `InstalledComponentsDB`.
