### ISSUE TITLE
Unable to delete files with .cfg extension

### ISSUE THREAD

**Issue by simonspa** [DIRACGrid/DIRAC#3896]
Using the `dirac-dms-remove-files` tool, I am unable to remove files which have a `.cfg` file extension in their name. It works well for other files:

```bash
$ dirac-dms-remove-files <path>/filename>.txt
Successfully removed 1 files
```

and fails for `.cfg` files:

```bash
$ dirac-dms-remove-files <path>/<file>.cfg
There were errors when loading configuration 
Can't load a cfg file '<path>/<file>.cfg'
```

The tool apparently silently parses this as configuration file instead of requiring an additional flag such as `--config` for defining configuration files. This leaves me with an undeletable file on EOS.

**Comment by fstagni** [comment]
Well that's a quite funny one! I can only say... indeed... :)

To get around it, you can also pass as input to the script the path to a local file which contains one or more LFNs (1 LFN per line, no spaces, no commas).

**Comment by simonspa** [comment]
Thanks, a colleague pointed me at that feature and it worked. 

However, I find this magic-guessing interface quite dangerous. Imagine I have a file listing all my datafiles used for a certain analysis. Now I want to delete that file - what happens instead is, that all my data files are gone.

Wouldn't it be better to require explicit CLI flags for this kind of operation, e.g. `--file-list` or similar?

**Comment by chaen** [comment]
Not really, because if you specify something that looks like an LFN, it will take it as such

**Comment by fstagni** [comment]
We can probably close this one. @simonspa thanks for reporting, we decided to not change the current scheme.
