### ISSUE TITLE
About DError and Failed dict

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#3898]
At the time of introducing DError, the original approach was to have it as a class behaving both as a string and as a dict. The main advantage of that was to be able to immediately use DError in the "Failed" dictionary structure.
However, we decided to simply add one field in the S_ERROR structure (for performance reasons mostly, DError class being very slow to serialize).

At that time, I seem to remember that @atsareg  had an idea about how we could introduce this error number into the Failed dictionary. However I can't recall it.
The reason I am asking is because we currently have an issue for which having this error number in Failed would be very helpful (in fact, it would avoid having dark data, but well...)

From the top of my head, I can't think of any way of integrating an error number to the Failed dict. Maybe an extra dict FailedErrno indexed on the same keys as the LFN, but that's not ideal....

**Comment by chaen** [comment]
After one month without activity, let me just stress that if no one reacts, I will code a solution that I deem the best, and no one will be allowed to criticize it or refuse its merging :-)

**Comment by fstagni** [comment]
... a bit more time passed now ;-)

**Comment by fstagni** [comment]
I think we'll leave with what we have.
