### ISSUE TITLE
Install script has non-standard package

### ISSUE THREAD

**Issue by mesmith75** [DIRACGrid/DIRAC#3906]
The install script imports a non-standard package (six) which breaks our tests as they run in a pristine docker instance.

https://github.com/DIRACGrid/DIRAC/blob/2e0ea3da797198b1c075eb9c31772fb97b7e859d/Core/scripts/dirac-install.py#L131

**Comment by fstagni** [comment]
Thanks: https://github.com/DIRACGrid/DIRAC/pull/3907

**Comment by mesmith75** [comment]
Thanks!
