### ISSUE TITLE
[WIP] What is missing to have SRM free storage

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#3908]
In view of Echo, I am going through the code to hunt every calls that hardcode srm as a protocol. Some are legit, some are not. I reference them here. I am NOT going to fix all of them because I do not know all of that. For some of the tasks bellow, we may want to create separate issues.

ConfigurationSystem
=================

- [x] getSEsFromCS & Bdii2CSAgent: the agent calls getSEsFromCS with no argument, meaning that only SRM storage are considered. Moreover, this method parses the SE section directly, thus not performing any lookup for alias or base SE. In general, the Bdii2CSAgent is targeted at SRM only.
- [x] dirac-admin-add-resources.py: SRM only resources 

Core
====

- [x] getDIRACSesForSRM legitimately is SRM only. But again it goes through the CS by hand. The client of this is the Bdii2CSAgent (and a script). [Moved to generic getDIRACSesForHostName in #4098]

DataManagementSystem
====================

- [x] old fts system: not a problem, is about to disappear
- [x] FTSRequest: way to do FTS transfer by hand -> will go too

yeah, all clean ! :-)

Interfaces
========

- [x] `DiracAdmin.getExternalPackageVersions` what the hell is that ? :)
- [x] `DiracAdmin.getSiteProtocols`: some hardcoded non sense. The only client of this looks like the script `dirac-admin-get-site-protocols` which is maybe a duplicate by now.
- [x] `Dirac.py` only comments are 'oriented', the actual feature seems to be all right

ResourceStatusSystem
==================

@fstagni 
Here, I must say it is not quite clear to me if the srm specific parts are legit or not, and if the system will handle SRM free storages

- [x] `CSHelpers`: there are a few methods that, although not explicitly bind to SRM, need to be adapted (`getSEParameters`, `getSEHost`, `getStorageElementEndpoint`, `getStorageElementsHosts`) All these methods only return one value, which is protocol dependant. `getSEParameters` give precedence to SRM, which is OK. But what SRM should do for downtime is to get ALL the hostname, and if any of those is down, the SE is down. I will take care of `getStorageElementEndpoint` because I need it for accounting

TransformationSystem
==================

- [x] `Utilities.isSameSE`: this one is rather tricky, I will take care of it. 

And then we are left with the directory operations on the SE that should go. @fstagni said he will look into that (Consistency and Output Validation  agent)

**Comment by fstagni** [comment]
I removed `DiracAdmin.getExternalPackageVersions` in https://github.com/DIRACGrid/DIRAC/pull/3947

**Comment by fstagni** [comment]
@chaen please check this commit for RSS: https://github.com/DIRACGrid/DIRAC/pull/4098/commits/bb32d46610521b694324b1708cedd1c85cc07ab9

**Comment by fstagni** [comment]
I added more commits in https://github.com/DIRACGrid/DIRAC/pull/4098 for the core part. I am editing the issue too.
