### ISSUE TITLE
BDII and MultiProcessor slots

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#3926]
This issue is about streamlining down some tasks for "institutionalizing" MP jobs.
The mechanism internally would use TAGs, and this is already "in production" for some communities. The generic tag mechanism is described in https://dirac.readthedocs.io/en/rel-v6r20/AdministratorGuide/Systems/WorkloadManagement/tagsAndJobs.html and since tags are generic they can be used also for MP jobs requirements and matching.

We would need anyway to decide:

- which TAGs to use, effectively. The specificity of the case suggests that we should use some defined tags. "MultiProcessor" is maybe one of them, and should maybe added automatically.
- how users should specify their requirements: users should not be exposed directly to the choice of TAGs, rather the APIs should make it simple to specify MP requirements that would be later translated into TAGs.
- how to specify the max and/or min number of processors required by the jobs
- If BDII2CSAgent should do more (add tags in CS based on what is found in Glue1/Glue2 schema). And same is true for possible other "xxxxx2CSAgent(s)" for when BDII is not there.

**Comment by atsareg** [comment]
Elaborating on what Federico has started,  the following is already available for the users:

Users can specify in the job descriptions NumberOfProcessors and WholeNode parameters, e.g.

...
NumberOfProcessors = 16;
WholeNode = True;
...

This will be translated internally into 16Processors and WholeNode tags. 

MultiProcessor tag is added automatically to the job description (PR is in preparation) if more than 1 processor is specified. This would allow resources (WN's) to put flexibly requirements on jobs to be taken, for example, avoiding single-core jobs on a multi-core nodes.

**Comment by atsareg** [comment]
As for specifying min/max number of processors, I do not think this is a good idea. Job should define the exact number of processors which the user application will be configured to use. Otherwise, the application will likely try to evaluate the number of available cores and most likely will miss the target.
Or we should somehow invent a way to communicate to the application, e.g. in the environment, how many processors it is allowed to use. This will be very problematic, I am afraid, since it will put extra complication on the application configuration.

**Comment by fstagni** [comment]
From the list above, the only bullet still to expand is the last, on Bdii2CSAgent. Suggestions there? Honestly I didn't check what's published in the Bdii and how it could be used. Any suggestion?

**Comment by andresailer** [comment]
As far as I understand the GlueV2 the `GLUE2ComputingShareMaxSlotsPerJob` should contain this information. In GlueV1 GlueCEPolicyMaxSlotsPerJob sounds very similar.
The content of this field is usually questionable. (int max, 999..., ...)

**Comment by fstagni** [comment]
That's quite typical. Maybe we should just say that:
- when it's > 1 we add the "MultiProcessor" tag
- when it's a "reasonable" number we set the #Processors tag. With "reasonable" being something less than 256? (this is just a number...). Otherwise we set the "WholeNode" tag?
