### ISSUE TITLE
Query status of multiple pilots in pilot monitor on the DIRAC portal

### ISSUE THREAD

**Issue by rajanandakumar** [DIRACGrid/DIRAC#3963]
In the job monitor on the DIRAC portal, I can query the status of a set of jobs simultaneously using comma separated job IDs.

In the pilot monitor, if I request the status of multiple pilots (comma separated), I get the result of only the first one in this list. It would be useful to be able to query a list of pilots simultaneously, instead of having to do it one-by-one.

Thanks,
Raja.

**Comment by zmathe** [comment]
@rajanandakumar Could you please send me an example? It works for me see the attached screen shoot.
![screenshot 2019-02-19 at 16 23 57](https://user-images.githubusercontent.com/981448/53026276-e0889e80-3462-11e9-8f36-0051571c8cdb.png)

**Comment by fstagni** [comment]
So, is this an issue or can we close?

**Comment by fstagni** [comment]
Well, closing for now. Re-open if needed.
