### ISSUE TITLE
pytest-cov vs python-coveralls

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#3984]
we have these two in the requirements.txt, but they have contradictory requirements for coverage
```
  python-coveralls==2.9.1   requires coverage==4.0.3, PyYAML, requests, six
  pytest-cov==2.6.1         requires coverage>=4.4, pytest>=3.6
```
Are they used somewhere ? Can we get rid of one of them ?
@atsareg @fstagni @andresailer @petricm

**Comment by fstagni** [comment]
I would say to keep only `pytest-cov`

**Comment by andresailer** [comment]
This is related to #3971, we drop coveralls (and python-coveralls) and use the other service instead

**Comment by chaen** [comment]
OK, and we still need pytest-cov if we have codecov ?

**Comment by andresailer** [comment]
Yes, pytest-cov is still needed. That is the plug-in for pytest which produces the coverage information

**Comment by fstagni** [comment]
Solved, I think.
