### ISSUE TITLE
Upgrading an existing dirac installation should preserve DIRACOS

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#3993]
When making a new installation of dirac, we have the `--dirac-os` flag if we want to install it with DIRACOS. For the following updates of version, it would be desirable that the installation is done preserving that choice. I think it is clear for everybody that the conversion from one to the other will not be done by the tools. I guess this should be assigned to @zmathe  ?

**Comment by fstagni** [comment]
@zmathe  Is this fixed? It should have been tried out at the last certification hackhathon

**Comment by zmathe** [comment]
yes, this is already implemented and already using it in our production
