### ISSUE TITLE
SEManager unhappy with inheritence

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#3994]
The DFC manager for SE crawls through the CS to build some prefix path. As usual, this breaks aliases and inheritance. We should either
* fix it
* be able to disable this feature altogether, since normally we do not use the url send by the catalog

To reproduce: configure a storageelement bases, and inherit from it, without redefining the Plugins

Call: dfc.getReplicas()

**Comment by fstagni** [comment]
Should we keep this task open now?

**Comment by fstagni** [comment]
Ping for this task.

**Comment by chaen** [comment]
it's done in v7r1
