### ISSUE TITLE
Date format in dirac-dms-lfn-metadata

### ISSUE THREAD

**Issue by axlbonnet** [DIRACGrid/DIRAC#3995]
I had a surprise about the date fields in `dirac-dms-lfn-metadata` response :
```
$ dirac-dms-lfn-metadata /biomed/user/c/creatis/[...]
{'Failed': {},
'Successful': {'/biomed/user/c/creatis/[...]': {'Checksum': 'b77f833c',
          'ChecksumType': 'Adler32',
          'CreationDate': datetime.datetime(2019, 3, 20, 14, 24),
          'FileID': 41731L,
          'GID': 1,
          'GUID': '9B71B1B8-9311-8F4C-9A41-5FCA2F2C523E',
          'Mode': 509,
          'ModificationDate': datetime.datetime(2019, 3, 20, 14, 24),
          'Owner': 'creatis',
          'OwnerGroup': 'biomed_user',
          'Size': 2403L,
          'Status': 'AprioriGood',
          'UID': 5}}}
```
The date is `2019-03-20 14:24:00`.The seconds field is missing because it is zero. I wasn't expecting it and i would have preferred the field to be present with `0`. If it is the desired behavior, I have some questions anyway :
* if the seconds and minutes fields are both zero, would both be absent ? (and the same with hours)
* if the minutes fields is zero but not the seconds, what would be returned ?

Thanks !

**Comment by chaen** [comment]
That's the behaviour of the `datetime` module:
```
In [9]: datetime.datetime.strptime("2019-03-20 14:24:00","%Y-%m-%d %H:%M:%S")
Out[9]: datetime.datetime(2019, 3, 20, 14, 24)
```

However, if you print the datetime object, you get what you want
```
In [10]: print datetime.datetime.strptime("2019-03-20 14:24:00","%Y-%m-%d %H:%M:
    ...: %S")
2019-03-20 14:24:00
```

**Comment by chaen** [comment]
@axlbonnet I think your question is answered so I will close. Feel free to re-open if needed
