### ISSUE TITLE
Cleaning directory problem if several levels

### ISSUE THREAD

**Issue by axlbonnet** [DIRACGrid/DIRAC#4012]
I want to be able to clean any directory, regardless of its content, but it doesn't work perfectly on a directory that has sub-directories.

I tested with the following folder/files setup :

niv1
- plop.txt
- niv2
- - plop.txt

If I do a `dirac-dms-clean-directory` on the `niv1` directory, the two `plop.txt` files are deleted, but the `niv1` and `niv2` directories still exist.

On the same original setup, a `dirac-dms-clean-directory` on the `niv2` directory works well, deleting the folder and the file.

**Comment by fstagni** [comment]
A couple questions:

- which DIRAC version are you using?
- when you say "it doesn't clean the directory", are you talking about the directory on the DFC (I assume you are using the DIRAC file catalog, correct me if I am wrong) or on the storage element?
- which storage element are you using?

In general: directory operations on certain SEs are not available, so we are moving towards directory operations possible only at the catalog level.

**Comment by axlbonnet** [comment]
> A couple questions:
> 
> * which DIRAC version are you using?

I'm using dirac version v6r21p1, and the DFC

> * when you say "it doesn't clean the directory", are you talking about the directory on the DFC (I assume you are using the DIRAC file catalog, correct me if I am wrong) or on the storage element?

I don't really know the difference. It still exist when I do a `dirac-dms-lfn-metadata` or a `dls`.

> * which storage element are you using?

I don't know if it's what you mean, but I used NIKHEF-disk.

> In general: directory operations on certain SEs are not available, so we are moving towards directory operations possible only at the catalog level.

What's bother me is that `dirac-dms-clean-directory` works on a simple directory but doesn't on a directory with subdirectories. Maybe it's specific to this SE, I could try on other SEs. Is there another way to delete a directory (and all its subdirectories and subfiles).

**Comment by fstagni** [comment]
OK we probably have enough info. 

@atsareg @chaen @andresailer would you please have a look? It seems like a DFC issue.

**Comment by andresailer** [comment]
Should be fixed by #4192 (v6r21p14)
