### ISSUE TITLE
SiteDirector fails to register pilot via WMSAdministrator

### ISSUE THREAD

**Issue by hmiyake** [DIRACGrid/DIRAC#4014]
Recently SiteDirector has been changed to use keyword arguments like 

      result = pilotAgentsDB.addPilotTQReference(pilotRef=pilotsList,
                                                 taskQueueID=tqID,
                                                 ownerDN=self.pilotDN,
                                                 ownerGroup=self.pilotGroup,
                                                 broker=self.localhost,
                                                 gridType=self.queueDict[queue]['CEType'],
                                                 pilotStampDict=stampDict)

However, it produces following error when SiteDirector runs on remote site, i.e. via WMSAdministrator:

2019-04-02 21:12:57 UTC WorkloadManagement/SiteDirectorUVic WARN:  Cycle had an error: Exception while calling <bound method SiteDirector.execute of <SiteDirector.SiteDirector object at 0x7f08291e7190>> method: __call__() got an unexpected keyword argument 'gridType' 

If the API is called by no keyword like previous SiteDirector, no error happens.
Is it possible to revert the code to previous style, or is something wrong in our environment?

**Comment by atsareg** [comment]
Yes, this change should be reverted. Which DIRAC version you are currently using ? This is to know which DIRAC release should be patched

**Comment by hmiyake** [comment]
Thanks a lot!
We are now using v6r20p26.

**Comment by fstagni** [comment]
Keyword arguments are a good coding practice. I don't know the situation so I don't understand the issue here. Can you add more info?

**Comment by andresailer** [comment]
As far as I remember, RPC calls do not support keyword arguments. If the server the sitedirector is running on cannot directly use the PilotsLoggingDB, it falls back to using the WMSAdministractor via an RPC Client

**Comment by fstagni** [comment]
Aaah yes. Understood.

**Comment by fstagni** [comment]
Question to @hmiyake : I know you have just moved to v6r20, and congrats for the effort! At the same time, are you planning to move to v6r21? As moving to it is rather simple (much simpler than moving to v6r20)

**Comment by hmiyake** [comment]
@fstagni , yes our next (base) DIRAC update is aiming at v6r21, though the date is not scheduled yet. Thus even if the patch is applied to only r21 we can move to the new patch release.

**Comment by fstagni** [comment]
Should be fixed by https://github.com/DIRACGrid/DIRAC/pull/4020
