### ISSUE TITLE
Error listing a directory

### ISSUE THREAD

**Issue by axlbonnet** [DIRACGrid/DIRAC#4015]
Hi,
I have an issue to list the content of a DFC directory. I had the error originally with COMDIRAC (`Error: FileCatalog error ( 1604 : Failed to perform listDirectory from any catalog)`, and i reproduced it with `dirac-dms-filecatalog-cli`.
```
dirac-dms-filecatalog-cli -f BiomedFileCatalogStarting BiomedFileCatalog client

File Catalog Client $Revision: 1.17 $Date: 
            
FC:/> ls /biomed/user/c/creatis/[...]
Error: Server error while serving listDirectory: 'FileID'
```
This directory contains only one file that I can download with`dget`.
This is specific to some directories in the same parent directory, but other directories in the same parent work fine.

Here are more info about the problematic directory :

```
$ dirac-dms-lfn-metadata /biomed/user/c/creatis/[...]
{'Failed': {},
 'Successful': {'/biomed/user/c/creatis/[...]': {'CreationDate': datetime.datetime(2019, 4, 3, 6, 21, 5),
           'DirID': 10382,
           'GID': 1,
           'Mode': 509,
           'ModificationDate': datetime.datetime(2019, 4, 3, 6, 21, 5),
           'Owner': 'creatis',
           'OwnerDN': '/O=GRID-FR/C=FR/O=CNRS/OU=CREATIS/CN=Robot: vip.creatis.insa-lyon.fr - Sorina Camarasu',
           'OwnerGroup': 'biomed_user',
           'OwnerRole': '/biomed',
           'Status': 0,
           'UID': 5}}}
```

And for its only file : 
```
$ dirac-dms-lfn-metadata /biomed/user/c/creatis/[...]/[...]
{'Failed': {},
 'Successful': {'/biomed/user/c/creatis/[...]/[...]': {'Checksum': '7cb36c5f',
           'ChecksumType': 'Adler32',
           'CreationDate': datetime.datetime(2019, 4, 3, 6, 21, 57),
           'FileID': 69112L,
           'GID': 1,
           'GUID': '5E2C2097-707A-E20E-2701-7CB0950E1302',
           'Mode': 509,
           'ModificationDate': datetime.datetime(2019, 4, 3, 6, 21, 57),
           'Owner': 'creatis',
           'OwnerGroup': 'biomed_user',
           'Size': 18320539L,
           'Status': 'AprioriGood',
           'UID': 5}}}
```
Thanks !

**Comment by andresailer** [comment]
Can you, or the DIRAC instance administrator, have a look at the log file of the FileCatalogService?
There is probably an exception in the service happening.

**Comment by atsareg** [comment]
There is indeed an exception in the service logs. Can you please provide the full directory path for which you see the problem, please ?

**Comment by fstagni** [comment]
Can the OP or @atsareg comment?

**Comment by axlbonnet** [comment]
@atsareg corrected it

There was another file in the folder which had a complete path with more than 128 characters, and that was the cause of the errors.

It's not a good practice to have filenames that big and it's also not good performance-wise. But I guess @atsareg increased this limit so it's ok now.
