### ISSUE TITLE
Tagging - annotated vs. lightweight

### ISSUE THREAD

**Issue by petricm** [DIRACGrid/DIRAC#4025]
Currently the DIRAC release procedure uses lightweight tags
```sh
$ git for-each-ref refs/tags | grep v6r20
eb0286feaea85e6112bbe8de6c4f01a378b5ec89 commit	refs/tags/v6r20
f529123e8453735b22ef4067e0ce5c91d96ab308 commit	refs/tags/v6r20-pre1
101301c5960df1005aa09d4543db9adaadda4f65 commit	refs/tags/v6r20-pre10
d53835b1a1d497ba5c78d5eb15c6d3944767a34c commit	refs/tags/v6r20-pre11
9d2aaea9c2679460152f34fc16d97faeb5f84b9b commit	refs/tags/v6r20-pre12
febf7a4c712f003549c045956d4ee3ed72ebcf11 commit	refs/tags/v6r20-pre13
d352825312b267eb4aa272b3e02ef33e94f1aedc commit	refs/tags/v6r20-pre14
f32f9b8f0b53f79bde431c045014979ca884c107 commit	refs/tags/v6r20-pre15
81f900195fe0ff3d94d46fd7ae70a44d04145952 commit	refs/tags/v6r20-pre16
bf2ba752f1bbd61994cd3d9da6ef481ca416ed7a commit	refs/tags/v6r20-pre18
7b25aa154cfca2f76014d6d71ac5771e8f40226b commit	refs/tags/v6r20-pre19
```
An annotated tag would have `tag` instead of `commit` in the output line.

I would however like to suggest that we use switch to annotated tags, because as it's written in the [git manual](https://git-scm.com/book/en/v2/Git-Basics-Tagging)

> A lightweight tag is very much like a branch that doesn’t change — it’s just a pointer to a specific commit.
> 
> Annotated tags, however, are stored as full objects in the Git database. They’re checksummed; contain the tagger name, email, and date; have a tagging message; and can be signed and verified with GNU Privacy Guard (GPG). It’s generally recommended that you create annotated tags so you can have all this information; but if you want a temporary tag or for some reason don’t want to keep the other information, lightweight tags are available too.
>

In addition to the above mentioned you can then also sort tags etc. while it's only a minimal change in the release procedure.

```
$ git tag v7r0
vs
$ git tag -a v7r0 -m "my annotated tag v7r0"
```
Is this acceptable?

**Comment by chaen** [comment]
I vote for it !

**Comment by atsareg** [comment]
The only difference in what the release manager should do is -a -m switches while tagging (just to be sure) ?

**Comment by petricm** [comment]
Yes, the only difference is the addition of `-a` and `-m"tag message"`

**Comment by atsareg** [comment]
OK, I will then start doing it with the next patch release. Thank you for this suggestion !

**Comment by fstagni** [comment]
Added in doc in https://github.com/DIRACGrid/DIRAC/pull/4033
