### ISSUE TITLE
Log URL error for accounting to WARNING instead of ERROR

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#4030]
On fresh installation, whenever performing data operations, you get all your command outputs full of 
```
Error sending accounting record Cannot get URL for Accounting/DataStore in setup MyDIRAC-Production: RuntimeError('Option /DIRAC/Setups/MyDIRAC-Production/Accounting is not defined',)
```
I think error in sending/committing accounting records should be logged as `warning` in the `DataStoreClient`. The error is anyway returned to the client, which can decide to log it if he wishes.

**Comment by fstagni** [comment]
In https://github.com/DIRACGrid/DIRAC/pull/4033
