### ISSUE TITLE
make test error on ubuntu

### ISSUE THREAD

**Issue by patrashantigopal** [DIRACGrid/DIRAC#4036]
I have the following error:

The following tests FAILED:
         46 - lucita_large (Failed)
         47 - mcscf_energy (Failed)
         64 - bss_energy (Failed)
        100 - lucita_short (Failed)
        115 - lucita_q_corrections (Failed)
        118 - operators_mo_mtx_elements (Failed)
Errors while running CTest

all other test passed. Please help.

**Comment by atsareg** [comment]
What is it about ? Are you sure that you have chosen the right project to report your problem ?

**Comment by patrashantigopal** [comment]
Sorry, my mistake. You can close this issue.
