### ISSUE TITLE
lcgBundle is missing the libboost_python-mt.so

### ISSUE THREAD

**Issue by JacekHoleczek** [DIRACGrid/DIRAC#4040]
I tried the last version "DIRAC-lcg-v14r9-Linux_x86_64_glibc-2.17-python27.tar.gz" on a CentOS 7 / x86_64 machine and, its "Linux_x86_64_glibc-2.17/lib/python2.7/site-packages/gfal2.so" library internally requires "libboost_python-mt.so.1.53.0", which is not provided.
Could you, please, include this library in the bundle.
It is provided by the "boost-python-1.53.0-27.el7.x86_64.rpm" package but, this package is not installed on CentOS 7 by default so, a copy in the bundle would really be helpful.

**Comment by fstagni** [comment]
Do you see the same issue with v14r2 version of the lcgBundle? The difference between v14r2 and v14r9 are some LHCb specific libraries that you certainly won't need.

At the same time, I think that boost won't be provided ever (you get this library, you'll need several others too).

**Comment by chaen** [comment]
Boost was never provided and never will be, it is part of the libraries you must have on your system.
Future version of DIRAC using DIRACOS aim at solving that.

**Comment by JacekHoleczek** [comment]
I now checked many available "DIRAC-lcg-v\*r\*-Linux_x86_64_glibc-2.17-python27.tar.gz" versions and in all cases the provided "gfal2.so" needs the "libboost_python-mt.so.1.53.0", which is not provided.
Note that is is not about providing "boost". This missing library does NOT need "boost" (at least that is what "ldd" says for it) but its lack breaks the whole dirac suite.

**Comment by chaen** [comment]
I agree, it does not require the rest of Boost, but still. It will not be added to LcgBundle.

If you urgently need to run DIRAC on a CentOS 7 box and use v6r21, you can test as early adopter DIRACOS (https://github.com/DIRACGrid/DIRACOS)

**Comment by fstagni** [comment]
Just to complete the answer above: there's a new way of installing DIRAC dependencies, that is as of today in testing phase, which is using the the "DIRACOS". DIRACOS can be seen as a drop-in replacement of lcgBundle+Externals.

It can be installed using "--dirac-os" switch in dirac-install: https://dirac.readthedocs.io/en/integration/AdministratorGuide/CommandReference/dirac-install.html

**Comment by fstagni** [comment]
I am closing, as we will not take specific actions on this one.
