### ISSUE TITLE
export_getReplicasByMetadata fails

### ISSUE THREAD

**Issue by martynia** [DIRACGrid/DIRAC#4058]
The export method calls `getReplicasByMetadata `method from the code (_DataManagementSystem/DB/FileCatalogComponents/FileManagerBase.py_) below.
https://github.com/DIRACGrid/DIRAC/blob/cc180c57fa8537204468b3e2264e6ba139288160/DataManagementSystem/DB/FileCatalogComponents/FileManagerBase.py#L1023-L1048

This in turn expects the statement:

`fileIDLFNs = result['Value'] ` (line 1032)

to deliver a dict required by the call to (line 1034):

`self.__getReplicasForIDs(.......)`, however it returns a list. The error reported is:

  _File "/opt/dirac/DIRAC/DataManagementSystem/DB/FileCatalogComponents/FileManagerBase.py", line 1034, in getReplicasByMetadata
    result = self.__getReplicasForIDs(fileIDLFNs, allStatus, connection)
  File "/opt/dirac/DIRAC/DataManagementSystem/DB/FileCatalogComponents/FileManagerBase.py", line 976, in __getReplicasForIDs
    res = self._getFileReplicas(fileIDLfnDict.keys(), fields_input=fields,
AttributeError: 'list' object has no attribute 'keys'_

**Comment by fstagni** [comment]
This went under my radar. Is it being taken care?

**Comment by atsareg** [comment]
Yes, this is a bug I still have to fix. Just could not get to it in the last days

**Comment by martynia** [comment]
Hi,

I made a lot of multi-VO related changes to user metadata code which has not yet been merged in. I still have to implement some corrections discussed with Andrei during the Dirac workshop. So maybe in order to avoid possible conflicts we could wait a bit ?

 thanks JM

**Comment by atsareg** [comment]
Fixed in #4101
