### ISSUE TITLE
extensions should be able to define their own Properties

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#4077]
Currently, the Properties are all hardcoded in `Core/Security/Properties.py` with no possibility for the extension to add one. 
@marianne013 would love that

**Comment by chaen** [comment]
I've got the feature coded, will push it once v7 is out

**Comment by fstagni** [comment]
No need to code (see discussion in the linked PR above)

@atsareg should just add documentation on how to extend the Properties. Re-assigned.

**Comment by fstagni** [comment]
I guess it can be closed.

**Comment by chaen** [comment]
Not really, @atsareg did not add the doc yet
