### ISSUE TITLE
Documentation: Document Operation Options

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRAC#4081]
Options are defined for the Operations section pretty much anywhere.

It would be great if there were some way to find all these places and ensure they are properly documented.

**Comment by IgorPelevanyuk** [comment]
True. To check which option is working I have to create the same option in different sections with different values.

**Comment by kanishk16** [comment]
Don't mind but it would be a little easier for me and effectively document if you compile all the options you test and out of them which are working in this issue...
