### ISSUE TITLE
letsencrypt

### ISSUE THREAD

**Issue by kfox1111** [DIRACGrid/DIRAC#4107]
What is the proper way to get dirac to reload its certificates once they are rotated? Letsencrypt in particular refreshes regularly.

**Comment by fstagni** [comment]
This is an operational question, I see now you also asked it on the forum. I will try to answer there, and in the meantime close this task.

**Comment by fstagni** [comment]
This is an operational question, I see now you also asked it on the forum. I will try to answer there, and in the meantime close this task.
