### ISSUE TITLE
Default configuration inside code is tricky

### ISSUE THREAD

**Issue by IgorPelevanyuk** [DIRACGrid/DIRAC#4115]
DIRAC has some default configuration hardcoded. It can make life tricky.
Example. I was not aware that /Operations/DataManagement/RegistrationProtocols so dramatically important to operate work StorageElements using root protocol. By default, it is only [dips, srm]. Once you add root protocol SE it is not gonna work out of the box. You will have to add root protocol to AccessProtocols, and WriteProtocols. 
Another point is that AccessProtocols and WriteProtocols may be configured directly under SE configuration. RegistrationProtocols cannot be configured there (do not know why. I tried and it did not work). 
I had to spend several hours to understand that I cannot write file to the EOS using root with default configuration even when I add SE. It also required looking inside the code. 

Proposal Small: can we move more default configuration to the default dirac.cfg which is shipped during initial DIRAC installation?
For example, /Operations/DataManagement/RegistrationProtocols may still be [dips, srm], but at least it will be easier to guess what to change when you see:
DEBUG: Failed to generate destination PFN. Protocol not supported ( 93 : No storage plugins matching the requirements (operation getTransportURL protocols ['srm', 'dips'] inputProtocol None)

Grand Proposal: 
Inside ConfigurationClient class inside the method getValue: https://github.com/DIRACGrid/DIRAC/blob/cc180c57fa8537204468b3e2264e6ba139288160/ConfigurationSystem/private/ConfigurationClient.py#L67
Is it possible to add 
```python
if not retVal['OK']:
    log.debug("For option %s the default value is used: %s" % (optionPath, defaultValue))
```

**Comment by andresailer** [comment]
See also #4081
