### ISSUE TITLE
DIRAC certification: setup centralized logging

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#4117]
All in the title

**Comment by zmathe** [comment]
please use: es-lhcb-dev.cern.ch
more details are in etc/dirac.cfg

**Comment by fstagni** [comment]
If I look at instructions in https://dirac.readthedocs.io/en/latest/AdministratorGuide/centralizedLogging.html the first thing I read is that I should register a broker in Resources/MQServices. Then I looked in the LHCb conf to see an example and there's no broker registered for that (it's only in the LogBackends). Am I looking in the correct place?
And, which broker should be used in this case?

**Comment by chaen** [comment]
The brokers are defined in the server's dirac.cfg since they contain password.
we maybe should ask for a DIRAC resources to the MQ guys

**Comment by chaen** [comment]
done
