### ISSUE TITLE
MySQL 8.0 support

### ISSUE THREAD

**Issue by antolu** [DIRACGrid/DIRAC#4123]
Installation using fullInstall in [DIRAC/tests/Jenkins/dirac_ci.sh](https://github.com/DIRACGrid/DIRAC/blob/integration/tests/Jenkins/dirac_ci.sh) fails when the script wants to create a new DB in MySQL. It seems like MySQL 8 changes default authentication plugin from `mysql_native_password` to `caching_sha2_password`, as mentioned [here](https://stackoverflow.com/questions/49963383/authentication-plugin-caching-sha2-password).
Install log is here: [log.txt](https://github.com/DIRACGrid/DIRAC/files/3300247/log.txt).

The following environment variables were used:
```
DEBUG=True
DIRAC_RELEASE=v6r22-pre3
DB_USER=Dirac
DB_PASSWORD=Dirac
DB_ROOTUSER=admin
DB_ROOTPWD=password
DB_HOST=172.18.0.4
DB_PORT=3306
DIRACOSVER=v1r1

NoSQLDB_HOST=172.18.0.5
NoSQLDB_PORT=9200

repository=DIRACGrid
branch=rel-v6r22
DIRACBRANCH=rel-v6r22
```
as well as having MySQL 8.0 and ElasticSearch 6.6.0 in separate Docker containers. The server was also installed in a Docker container. The admin user in docker was created using

```
CREATE USER 'admin'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
quit
```

Solutions to this include:
1. Upgrading MySQL client in DIRACOS to 8.0 or higher and implement backwards compatibility for 5.X. (DIRACOS bundling + DIRAC code)
2. Changing authentication method for both Dirac and admin users using `ALTER USER admin
IDENTIFIED WITH mysql_native_password
BY 'password';` (DIRAC code)

**Comment by fstagni** [comment]
@ltomassetti is doing a few tests. 

Regarding the authentication: a MySQL server setting was enough to make MySQL 8 to accept old encriptions. 

Ran the "Test_TaskQueueDB" test and passed without problems.

**Comment by ltomassetti** [comment]
used a local installation of MySQL 8.0.16

Had to change the authentication plugin used at user creation to the 'old' `mysql_native_password` (because the Dirac user was created within the new version):
```
ALTER USER 'Dirac'@'%'
  IDENTIFIED WITH mysql_native_password
  BY 'password';
```

In addition mysql server has been launched with the option in the `my.cfg` file:
```
[mysqld]
default_authentication_plugin=mysql_native_password
```

**Comment by ltomassetti** [comment]
USERS cannot be created anymore with the `GRANT` statements.
Before granting privileges to them, the user must be created with `CREATE USER`... first.

So, some .sql files (dumps) and python code used to create DB and users must be updated accordingly

**Comment by ltomassetti** [comment]
MySQL 8 introduced several new `keywords` and `reserved words`. For example `SYSTEM`, that breaks the `Components` table of the `InstalledComponentsDB`.

```
mysql> describe Components;
+-------------+-------------+------+-----+---------+----------------+
| Field       | Type        | Null | Key | Default | Extra          |
+-------------+-------------+------+-----+---------+----------------+
| ComponentID | int(11)     | NO   | PRI | NULL    | auto_increment |
| System      | varchar(32) | NO   |     | NULL    |                |
| Module      | varchar(32) | NO   |     | NULL    |                |
| Type        | varchar(32) | NO   |     | NULL    |                |
+-------------+-------------+------+-----+---------+----------------+
4 rows in set (0,01 sec)
```

The following query doesn't work anymore:
```
mysql> SELECT `Components`.`ComponentID` AS `Components_ComponentID`, `Components`.`System` AS `Components_System`, `Components`.`Module` AS `Components_Module`, `Components`.`Type` AS `Components_Type`  FROM `Components`  WHERE System = 'Framework';
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'System = 'Framework'' at line 1
```

**Comment by ltomassetti** [comment]
According to the [MySQl 8 manual](https://dev.mysql.com/doc/refman/8.0/en/keywords.html):
> Nonreserved keywords are permitted as identifiers without quoting. Reserved words are permitted as identifiers if you quote them as described in Section 9.2, “Schema Object Names”:

so, in the previous post, the reserved word `system` in the `WHERE` clause must be quoted, 
the identifier quote character is the backtick (`):

```
mysql> SELECT `Components`.`ComponentID` AS `Components_ComponentID`,
              `Components`.`System` AS `Components_System`,
              `Components`.`Module` AS `Components_Module`,
              `Components`.`Type` AS `Components_Type`
       FROM `Components` 
       WHERE Type = 'service' AND `System` = 'Framework';
```

while the keyword `Type`, which in not a reseved word, does not need quoting

**Comment by fstagni** [comment]
#4166 is a first step. Not all tests could be done, yet.

**Comment by chaen** [comment]
Tool suggested by the DBOD guys: https://www.percona.com/blog/2019/09/27/mysql-8-shell-upgrade-checker-utility/

**Comment by fstagni** [comment]
All the tests are passing on v7r1, but we didn't run a full certification with it. We can say that we will do it when testing v7r2, and only at that point declare it as supported.

**Comment by fstagni** [comment]
We ran a certification hackathon without issues. Consider it closed.
