### ISSUE TITLE
[v6r22] Add setNumberOfProcessors() function for Job interface

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRAC#4127]
We have to add one more function setNumberOfProcessors() with an int argument, similar to setCPUTime(). It can set MultiProcessor tag inside just in case. MultiProcessor tag can be considered to be for internal purposes, not on the user level

_Originally posted by @atsareg in https://github.com/DIRACGrid/DIRAC/pull/4119_

**Comment by fstagni** [comment]
In v6r22p1.
