### ISSUE TITLE
Remove Pilot2 code

### ISSUE THREAD

**Issue by petricm** [DIRACGrid/DIRAC#4162]
From v7 Pilot2 does not exist anymore, remove code form DIRAC repo

**Comment by fstagni** [comment]
In #4163 I simply modified the default from the SiteDirectors (Pilot3 flag = True by default). Which means that if anyone still wants to use Pilot2 would need to explicitly set the Pilot3 flag to false in CS.

If that's fine for v7r0, then I would target the removal to v7r1 (or v7r2, we'll see). Would that be OK?

**Comment by fstagni** [comment]
Done with https://github.com/DIRACGrid/DIRAC/pull/4577
