### ISSUE TITLE
[RFC] LFN Replicas without physical files behind them

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRAC#4168]
For the "Archiving" operation I am working on, I need to be able to just store an LFN and related meta data, descendants, ancestors, etc. In this way I can keep the meta data for production files available, and also keep ancestor information for files derived from the archived files, or I can register the tar ball the archived file ended up in as a descendant.

While one can register replicas at will in the FileCatalog:
```
FC:/> register replica /tutoVO/data/Trans_01/File_3 foo ARCHIVE-DFC
Replica added successfully: True
FC:/> replicas /tutoVO/data/Trans_01/File_3
lfn: /tutoVO/data/Trans_01/File_3
ARCHIVE-SE      dfc://tutoVO/data/Trans_01/File_3
ARCHIVE-DFC     /tutoVO/data/Trans_01/File_3
```

The `dirac-dms-lfn-replicas` command will not display the replica information
```
dirac-dms-lfn-replicas /tutoVO/data/Trans_01/File_3
StorageFactory._getConfigStorageName: Failed to get storage options Path /Resources/StorageElements/ARCHIVE-DFC does not exist or it's not a section
LFN                          StorageElement URL
===============================================
/tutoVO/data/Trans_01/File_3 ARCHIVE-SE     dfc://tutoVO/data/Trans_01/File_3
```
Either because there is no ARCHIVE-DFC section in the Config System, or if there is, because there is no Plugin associated to the SE.

So I propose to implement a StoragePlugin, which would allow one to register LFNs in the DFC, but nothing else. Then one just needs to implement a few methods which would allow one to still use things like `dirac-dms-lfn-replicas`, `dirac-dms-remove-files/replicas` and the `RegisterReplica` operation

What do people think?

Current implementation:

```python
"""The DFCOnly storage can only be used to register replicas in the DFC.

It is used to preserve LFN metadata, no actual file content will be stored.
"""

__RCSID__ = "$Id$"

from DIRAC import gLogger, S_OK
from DIRAC.Resources.Storage.Utilities import checkArgumentFormat
from DIRAC.Resources.Storage.StorageBase import StorageBase


class DFCOnlyStorage(StorageBase):
  """MetaData Storage, only for registering LFNs, nothing else."""
  _INPUT_PROTOCOLS = ['dfc']
  _OUTPUT_PROTOCOLS = ['dfc']

  def __init__(self, storageName, parameters):
    """ c'tor

    :param self: self reference
    :param str storageName: SE name
    """
    StorageBase.__init__(self, storageName, parameters)
    self.log = gLogger.getSubLogger(__name__, True)

    self.pluginName = 'DFCOnly'
    self.protocol = []

  def getTransportURL(self, pathDict, protocols):
    res = checkArgumentFormat(pathDict)
    if not res['OK']:
      return res
    urls = res['Value']
    successful = {}
    failed = {}

    for url in urls:
      successful[url] = url

    resDict = {'Failed': failed, 'Successful': successful}
    return S_OK(resDict)

  def getURLBase(self, withWSUrl=False):
    return S_OK(self.basePath)

  def removeFile(self, path):
    successful = {}
    for lfn in path:
      successful[lfn] = True
    resDict = {'Successful': successful, 'Failed': {}}
    return S_OK(resDict)

```

**Comment by chaen** [comment]
I think this hack would work to store the info
But from the operational point of view, you would have to make sure that this SE is never used for your jobs, or considered as "last replicas" when removing files, etc.

**Comment by andresailer** [comment]
It works :tm: :) that part I tested.

Regarding the "last replica", this is kind of the whole point. I want to remove all physical replicas of the LFNs after I stored a copy of them in a tar ball. When I have to de-archive files, I can put the file to some physical storage and register that as a replica.

Regarding jobs:
I agree that this DFCOnly SE cannot be used for jobs, but it would only result in a lot of errors if someone were to try to upload to an SE of this type as output from their jobs.
And as far as I understand the job matching, jobs would never be executed as long as the input data were only on SEs like this.

**Comment by phicharp** [comment]
Is the use case only when those files are physically archived?
Don't you have also the problem of registering temporary files that are not physically saved? You probably need those as well to ensure the filiation / provenance continuity?
Wouldn't it be simpler that the DFC holds files without replicas?

**Comment by andresailer** [comment]
@chaen @phicharp thanks for your comments and taking the time to think about this problem!

> Is the use case only when those files are physically archived?

At the moment, yes

> Don't you have also the problem of registering temporary files that are not physically saved? You probably need those as well to ensure the filiation / provenance continuity?

At least for now we don't have that in our workflow. But using the "DFCOnly" SE would also work for those cases.

> Wouldn't it be simpler that the DFC holds files without replicas?

I am not sure that would be simpler. Most tools simply expect there to be a replica at a StorageElement, and if that StorageElement cannot be instantiated there are errors.
Thus one would have to treat cases of LFNs without replicas different to cases of LFNs with replicas. 
It is also more explicit to have a replica at the "Virtual" SE instead if not having a replica at all.

Not having a replica might also cause more headaches when one does de-archive an LFN, because then there would be a replica and then would there still be the archive entry?

**Comment by chaen** [comment]
I am trying to think about out workflow too to see if we could integrate that here :-)

There might also be the use case of archiving several files into one archive. Do you see that fitting ?

**Comment by andresailer** [comment]
Yes, the "Archiving" is putting few hundred files into one tarball.

**Comment by chaen** [comment]
Ah ok ! I did not understand that from this ticket. And so you use the metadata of the DFC to resolve in which archive a given file has been stored ?

**Comment by andresailer** [comment]
Sorry for not giving the whole context,

The idea if "dirac-dms-create-archive-request" most things can be done in vanilla dirac (with addition of the "ArchiveFiles" and "CheckMigration" operations, but the "Archive Replica" is what I wanted to discuss here.

List of operations:

1.  Optionally replicate files to SourceSE (because SourceSE is closest to the machine doing the archiving
2.  ArchiveFiles: Create a tarball from input files by downloading the files to a local folder, upload tarball  to some storage element
3.  ReplicateAndRegister Tarball to TargetSE (tape, e.g, castor)
4.  Optionally: Add LFNs to an ArchiveSE (the DFCOnly discussed here) (RegisterReplica operation)
5.  Optionally: Check for Tarball Migration to tape (new CheckMigration Operation)
6.  Remove all other replicas for these files, or remove all files (RemioveReplica, RemoveFile)
7.  Remove original replica of Tarball (remove replica)


Yes, the tarball would be registered as the "special" ancestor/descendent metadata

**Comment by chaen** [comment]
OK I see. maybe one piece of information a bit specific to CERN but which might show useful:
EOS has an archiving capability. Basically, it creates a tarball of a tree and stores it on tape. We were considering using that for archiving so logs. In your workflow, providing all your LFNs are among the same directory, it would translate into a `ArchiveFilesEOS` operation I guess...

**Comment by andresailer** [comment]
I hope we can discuss this at tomorrow's BiLD meeting

**Comment by andresailer** [comment]
Following discussion at the BiLD meeting, renamed to FCOnlyStorage. 
Further discussion can take place in #4171
