### ISSUE TITLE
Multi-Mechanize is not available for Python 3. Switch to Locust

### ISSUE THREAD

**Issue by 97amarnathk** [DIRACGrid/DIRAC#4172]
Currently, for database and service performance testing, DIRAC uses [Multi-Mechanize](https://multi-mechanize.readthedocs.io/en/latest/). However, this framework is not available for Python 3.

As DIRAC will be migrated to Python 3 in the near future, a Python 3 alternative to Multi-Mechanize is required.

[Locust](https://locust.io/) is one such framework. Some advantages of Locust are:

* Supports Python 2.7, 3.x
* Has a very active dev community
* A more Pythonic way of writing tests, quite similar to the unit test module.
* Gives more flexibility since it has setup, teardown and sequential test constructs.
* Although it does not provide plots and analytics, it does give results in a CSV format.
* [jenkins performance-plugin](http://jenkinsci.github.io/performance-plugin/RunTests.html) is a tool to run Locus tests on Jenkins easily and visualise/analyse data

All the performance tests in tests/Performance will required to be shifted to work on Locust.

**Comment by fstagni** [comment]
Deferred to DiracX.
