### ISSUE TITLE
Detect if a path is a file or folder

### ISSUE THREAD

**Issue by axlbonnet** [DIRACGrid/DIRAC#4178]
I've got an issue detecting if an absolute path corresponds to a file or to a directory.
I've tried with the `dls` command or with `dirac-dms-filecatalog-cli` that have the same behavior.

To illustrate, I've created a folder like `/absolute/path/temp` and a unique file inside also named `temp`, so its path is `/absolute/path/temp/temp`.
So here the output of `dls -l` or these 2 paths :
```
$ dls -l /absolute/path/temp
/absolute/path/temp:
-rwxrwxr-x 1 creatis biomed_user 4 2019-07-23 12:51:44 temp
$ dls -l /absolute/path/temp/temp
/absolute/path/temp/temp:
-rwxrwxr-x 0 creatis biomed_user 4 2019-07-23 12:51:44 temp
```
The issue is with the first command : how can I know if `/absolute/path/temp` is a file (and the `temp` listed is the file itself), or a folder (and the `temp` listed is a subfile)

If I compare the 2 detail lines of the 2 command, they are almost the same, and that's logic because it's the same file. But there's a slight difference, in the second column that corresponds to the number of hard links in the classic `ls` command. Here I assume it corresponds to another thing but what ? I've also seen the value `2` for the second column for other files, but I've experienced it's always `0` for a folder or when the path corresponds to a file. 

So my questions are :
- can I rely on this second column to detect if the path is a directory. Like if there's only one line and the first char of the permissions is not a `d` and the second column is `0` then it's a file. Otherwise it's a folder
- otherwise, what is the easier way ? use `dirac-dms-lfn-metadata` ?

Thanks !

**Comment by andresailer** [comment]
The second column seems to be the number of replicas for a file, and it might be a bug that "0" is displayed for files when directly running `ls` on a file

```
[snip]
-rwxrwxr-x 2 sailer ilc_user   4615748 2017-10-04 17:29:31 test.stdhep                   
-rwxrwxr-x 1 sailer ilc_user   4766924 2015-07-13 11:51:15 testEOS.stdhep                
FC:/ilc/user/s/sailer>replicas test.stdhep                                               
lfn: /ilc/user/s/sailer/test.stdhep                                                      
CERN-EOS-TEST   srm://srm-eospublic.cern.ch:8443/srm/v2/server?SFN=/eos/experiment/clicdp/grid/test/ilc/user/s/sailer/test.stdhep
CERN-DST-EOS    root://eospublic.cern.ch/eos/experiment/clicdp/grid/ilc/user/s/sailer/test.stdhep                                
FC:/ilc/user/s/sailer>ls -l /ilc/user/s/sailer/test.stdhep                                                                       
-rwxrwxr-x 0 sailer ilc_user 4615748 2017-10-04 17:29:31 test.stdhep                                                             
FC:/ilc/user/s/sailer>replicas testEOS.stdhep                                                                                    
lfn: /ilc/user/s/sailer/testEOS.stdhep                                                                                           
CERN-EOS-TEST   srm://srm-eospublic.cern.ch:8443/srm/v2/server?SFN=/eos/experiment/clicdp/grid/test/ilc/user/s/sailer/testEOS.stdhep
````

Can you explain what you want to do with the information if an LFN path is file or folder? That might affect the best way to figure out one thing or the other.

There are API functions in the FileCatalog to check for isDirectory etc.

https://dirac.readthedocs.io/en/latest/CodeDocumentation/Resources/Catalog/FileCatalogClient.html?highlight=isDirectory

**Comment by axlbonnet** [comment]
> The second column seems to be the number of replicas for a file, and it might be a bug that "0" is displayed for files when directly running `ls` on a file

Yeah, it seems like a bug

> Can you explain what you want to do with the information if an LFN path is file or folder? That might affect the best way to figure out one thing or the other.
>
> There are API functions in the FileCatalog to check for isDirectory etc.
> 
> https://dirac.readthedocs.io/en/latest/CodeDocumentation/Resources/Catalog/FileCatalogClient.html?highlight=isDirectory

What I want to implement is a file-browser like feature using command-line tools. Given a DFC path I would like to know with `dls` if it's a file, or if it's a folder and expose the sub-folders and sub-files.

Normaly, the linux `ls -l` allows to make the difference because it prints the whole path when it's a file :

```
$ ls -l /tmp/plop.txt 
-rw-r--r-- 1 abonnet creatis 12 Sep  3 19:15 /tmp/plop.txt
```
The LFC also worked like that, but not the DFC.

I currently only use command line methods so I would like to avoid using an python script and the API functions you mentioned. I think I'll finish by using `dirac-dms-lfn-metadata` to check if it's a directory before every call to `dls -l`  but it would be nice if only calls to `dls -l` were enough.

**Comment by fstagni** [comment]
@atsareg or @martynia can you have a look at this? IIUC this is a bug.

**Comment by atsareg** [comment]
I think this issue was fixed. For example:

```
$ dls -l /biomed/user/a
/biomed/user/a:
drwxrwxr-x 0 akress  biomed_user 0 2019-03-16 01:55:52 akress
drwxrwxr-x 0 atsareg biomed_user 0 2018-07-06 11:47:47 atsareg
$ dls -l /biomed/user/a/atsareg
/biomed/user/a/atsareg:
-rwxrwxr-x 1 atsareg biomed_user 197771 2019-04-30 08:55:26 24148801.mat.bz2
-rwxrwxr-x 1 atsareg biomed_user 340838 2018-11-28 11:30:26 cas.pem
$ dls -l /biomed/user/a/atsareg/cas.pem
/biomed/user/a/atsareg/cas.pem:
-rwxrwxr-x 0 atsareg biomed_user 340838 2018-11-28 11:30:26 cas.pem
```

The directories are marked with **d** in the first field of the output
