### ISSUE TITLE
[Documentation] LoadName in agent configuration

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRAC#4215]
There are these LoadName parameters in the Transformation examples, but the only place where I can find LoadName is in that file

https://github.com/DIRACGrid/DIRAC/blob/b2ad824a059ee92922f7c585ca6e203d91f18842/docs/source/AdministratorGuide/Systems/Transformation/index.rst#L175-L190

Initially I just wanted to ask if the value was wrong because it is the same in both sections, but it seems to me that the option name might be wrong as well...

**Comment by fstagni** [comment]
In fact it might be that's not needed at all. I don't see it used anywhere.

**Comment by andresailer** [comment]
Ok, I will remove it in one of me next PRs.

**Comment by andresailer** [comment]
Removed entries
