### ISSUE TITLE
user suspension is lifted when it is lifted in VOMS

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#4216]
If a user is suspended in voms, it is correctly suspended in DIRAC. But if the suspension is not in VOMS at the next VOM2CSAgent run, then the user will be un-banned. 
This goes against the idea we had to be able to manually ban a user.
It was even mentioned in the original ticket: https://github.com/DIRACGrid/DIRAC/issues/3990#issuecomment-478987813

**Comment by andresailer** [comment]
Do you have AutoLiftSuspendedStatus = False?

https://dirac.readthedocs.io/en/integration/CodeDocumentation/ConfigurationSystem/Agent/VOMS2CSAgent.html#id1

**Comment by chaen** [comment]
had overlooked that option, sorry ! 
Maybe it would be worth mentioning this Agent in here btw: https://dirac.readthedocs.io/en/latest/AdministratorGuide/Authentication/index.html

**Comment by andresailer** [comment]
There is also the `dirac-admin-check-config-options` command to compare the configuration system with the ConfigTemplates to find options that were added after a service or agent was installed.
E.g, it might have printed
```
$ dirac-admin-check-config-options  -O -S Configuration 
[snip]
Option 'Configuration/Agents/VOMS2CSAgent/AutoLiftSuspendedStatus' not found in current configuration. Default value is 'True'
```

**Comment by andresailer** [comment]
Link in configuration added, other problem answered
