### ISSUE TITLE
Pilots Submission accounting --> pilot submission monitoring.

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#4226]
Pilot submission accounting (introduced within https://github.com/DIRACGrid/DIRAC/pull/4205) should be moved to monitoring (so, ES backend).

**Comment by fstagni** [comment]
Running pilot monitoring can also go to ES.

**Comment by fstagni** [comment]
As of now, there's also a bug:

![image](https://user-images.githubusercontent.com/785576/111184391-37fd8800-85b1-11eb-9a14-8c72bf6e2393.png)

is not reflected when plotting "by Site" nor "by Site Director":

![image](https://user-images.githubusercontent.com/785576/111184521-56638380-85b1-11eb-8786-08a4c93558f6.png)

![image](https://user-images.githubusercontent.com/785576/111184542-59f70a80-85b1-11eb-8d94-ab34d72f2b05.png)

**Comment by rubenpozzi97** [comment]
Where should it be created? Open distro for certification (es-dirac-certification.cern.ch)?
