### ISSUE TITLE
SEPrefix:  why should I not doom it ? 

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#4227]
I've realized today that when calling `fc.getReplicas`, 90% of the time is spent updating the *cache* (a cache which is refreshed at every call... :-) ) of the StorageElements definition in the FileCatalog `SEManager`. It takes for ever because every thread is competing for the lock. The lock is even acquired for read operations. 

So, for one, I will change that *cache* behaviour, because it simply is an unacceptable performance killer. 

For two, this SEPrefix which is added to the return dict:
* goes against the separation that we enforce between SE and FC
* is broken with respect to aliases and inheritance (https://github.com/DIRACGrid/DIRAC/issues/3994)
* and does not even seem to be consumed anywhere

So please give me arguments why I would not remove it altogether ? 

- [x] improve the cache
- [x] delete SEPrefix

**Comment by fstagni** [comment]
PR merged. Closing the issue.
