### ISSUE TITLE
Fix Python 3 incompatibilties

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRAC#4240]
As discussed on slack we can log Python 3 incompatibilities with the recipe below. This probably won't be comprehensive but should catch most issues. I'll give it a try soon using the integration tests and make a plan how to deal with the various issues.

### Steps for logging Python 3 incompatibilities

1. Add a directory to `PATH` containing an executable called `python` containing:
```bash
#!/usr/bin/env bash
# Wrap the second occourance of python, adding '-3' to enhance warnings
exec $(which --all python | sed -n 2p) -3 "$@"
```
2. Add a directory to `PYTHONPATH` containing a file called `usercustomize.py` containing:
```python
import warnings

original_showwarning = warnings.showwarning

def showwarning(message, category, filename, lineno, file=None, line=None):
    if isinstance(message, DeprecationWarning):
        # Write Python 3 incompatibilities to the logging
        import DIRAC
        DIRAC.gLogger.warn('Python 3 incompatibility', '; '.join(message.args + (filename, str(lineno))))
    else:
        return original_showwarning(message, category, filename, lineno, file, line)

warnings.showwarning = showwarning
```
3. Finally the `bashrc` should be modified to not suppress depreciation warnings:
```
export PYTHONWARNINGS=ignore,once::DeprecationWarning
```

**Comment by chrisburr** [comment]
I'll keep track of warnings that I haven't found a solution to in this comment.

1. Overriding \_\_eq\_\_ blocks inheritance of \_\_hash\_\_ in 3.x
```bash
$ python -3 -c 'from DIRAC.Core.Utilities import CFG'
/Users/christopherburr/miniconda3/envs/analysis-productions/lib/python2.7/site-packages/DIRAC/Core/Utilities/CFG.py:68: DeprecationWarning: Overriding __eq__ blocks inheritance of __hash__ in 3.x
  class CFG( object ):
```

**Comment by fstagni** [comment]
What's left here? What needs to be done in `TransformationSystem/Client/Utilities.py:getPluginParam`?
