### ISSUE TITLE
HostName way too short

### ISSUE THREAD

**Issue by kfox1111** [DIRACGrid/DIRAC#4245]
We have some hostnames that are failing to work with dirac as they are greater then 32 characters. I believe hostnames are allowed to actually be up to 253 characters long.

**Comment by chaen** [comment]
how and where does it fail ?

**Comment by fstagni** [comment]
Close as no reply from OP.

**Comment by kfox1111** [comment]
Sorry. I didn't see the followup question. I've kind of lost context though as its been so long. I'll try and dig up what the real hostname in question was and what config it was in. We only use mysql as the backend at the movement though. If I remember correctly, we went into the database and altered some columns to have more characters.

We have hostnames already like:
project8-dirac-constance.hep.pnnl.gov

This is already over the 32 character limit and isn't really all that long.

**Comment by fstagni** [comment]
I will re-open if needed. It would also help to know what DIRAC version you are using now.

**Comment by kfox1111** [comment]
Looking back through some old notes I think I found the issue. Trunk is still affected:
https://github.com/DIRACGrid/DIRAC/blob/integration/FrameworkSystem/DB/InstalledComponentsDB.py#L97
And:
https://github.com/DIRACGrid/DIRAC/blob/integration/FrameworkSystem/DB/InstalledComponentsDB.py#L243
