### ISSUE TITLE
[v7r0] Error with the pilotFileServer option installing dirac from scratch

### ISSUE THREAD

**Issue by aldbr** [DIRACGrid/DIRAC#4264]
I was installing the DIRAC server from scratch when I got an issue with the `ConfigurationServer`:

`Can't commit new configuration data The /Operation/<Setup>/Pilot/pilotFileServer option is not defined`

The point is that we have a bootstrap issue here. 
This option is used to update the pilot files at each commit within the CS and thus is necessary to send pilots. 
The option by default is `''` and returns an error because is not defined but we cannot update the CS to add the option since we have this error.
Here is the part of the code that causes the error: 

https://github.com/DIRACGrid/DIRAC/blob/integration/WorkloadManagementSystem/Utilities/PilotCStoJSONSynchronizer.py#L68

What should we do? 
Set a fixed value to the `pilotFileServer` in the `__init__` method of `PilotCStoJSONSynchronizer` to avoid the error?
Do you have any suggestion? 

Thanks

**Comment by fstagni** [comment]
Thinking a bit about this: the Jenkins jobs do install the server (and the CS) from scratch. This was already encountered and fixed (for Jenkins case) in https://github.com/DIRACGrid/DIRAC/pull/4249/files (where basically what's done is to set `/Operations/Defaults/Pilot/UpdatePilotCStoJSONFile=False`)

What I wonder is if we need another fix on top or if instead we just need to make sure that the instructions are correct.

**Comment by fstagni** [comment]
IIUC this is sorted out already.

**Comment by andresailer** [comment]
This is still causing issues:
See https://groups.google.com/forum/?hl=en#!topic/diracgrid-forum/7nkb6ivxr4k
Basically creating very subtly broken installations of new DIRAC servers.

**Comment by chrisburr** [comment]
This is now also being seen in the CI. I think it's appeared since https://github.com/DIRACGrid/DIRAC/pull/4340 was merged.

See: https://github.com/DIRACGrid/DIRAC/commit/f5a54945a0cf748a36de303ca9a057b47d4b2b17/checks?check_suite_id=339419456

**Comment by fstagni** [comment]
Yes I noticed this one yesterday, and I created https://github.com/DIRACGrid/DIRAC/pull/4358
Even though I am not convinced #4340 was the reason. 

Anyway, #4358 also fails, I am having a look at why, you might of course be right.

**Comment by fstagni** [comment]
Hopefully finally fixed
