### ISSUE TITLE
Too many application statuses for job monitor

### ISSUE THREAD

**Issue by rajanandakumar** [DIRACGrid/DIRAC#4267]
The job monitoring has a string for the "application status". In case of failure, there are too many application statuses which are identical, but differ by user name. This messes up the portal which hits (http) errors as one cannot select too many such values.

As an example : the following application statuses are essentially identical.

Device or resource busy ( 16 : antonio.romero exited with status 16)
Device or resource busy ( 16 : amoedden exited with status 16)
Device or resource busy ( 16 : alseuthe exited with status 16)
Device or resource busy ( 16 : nraja exited with status 16)

I would think that all the above errors should be the same and the specific user name should not be a part of the error.

Fixing this will make the application status cleaner and lighter (in terms of number of statuses available to select) and make job debugging possible without needing to select multiple statuses specificly by hand.

**Comment by fstagni** [comment]
I close as not DIRAC related.
