### ISSUE TITLE
Move Operations option Productions/ProductionFilesMaxResetCounter

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRAC#4305]
Maybe this should be moved/renamed to Transformations/FilesMaxResetCounter ?

https://github.com/DIRACGrid/DIRAC/blob/05d239dbd575eb0fc469f41e51fdcb30dbe0b728/TransformationSystem/Client/TransformationClient.py#L21

**Comment by fstagni** [comment]
I think so

**Comment by andresailer** [comment]
v7r0 hasn't been announced, so for v7r0?
