### ISSUE TITLE
diracdocstools improvments

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#4345]
As per discussion with @andresailer 

* This help is misleading https://github.com/DIRACGrid/DIRAC/blob/ed17628277a889266c1dbd63227f6f47ab3c9525/docs/docs.conf#L6

* The `ignore` directive should become an `exclude`, and just mean "do not put that command in the index.rst"

**Comment by andresailer** [comment]
All requested features implemented
