### ISSUE TITLE
bashrc options: create a commented rc option file

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#4351]
There are several variables that could be set in (bash)rc, sometimes only for client or server. We need a place where to collect them all. 

This is about documentation, but also we could modify dirac-install so that it creates a commented bashrc, with those options that are not strictly necessary commented out.

**Comment by andresailer** [comment]
The variables are documented here:
https://dirac.readthedocs.io/en/rel-v7r0/AdministratorGuide/ServerInstallations/environment_variable_configuration.html

See this comment:
https://github.com/DIRACGrid/DIRAC/pull/4335#issuecomment-548297937

**Comment by fstagni** [comment]
Right, I forgot again.So, it's about creating this sample bashrc.

**Comment by chaen** [comment]
No, we said that we should rather add in the generated bashrc a link to this documentation page

**Comment by andresailer** [comment]
I had understood to add all the variables, potentially commented, and a link to the documentation page in the bashrc. But just adding a link to the documentation is better and reduces the places that have to be changed when variables are added or removed.

**Comment by fstagni** [comment]
My understanding was the same as Andre', and IMHO it's better than just a link.

**Comment by andresailer** [comment]
Which branch should I target? `integration` as dirac-install is always taken from there?

**Comment by fstagni** [comment]
dirac-install is not always taken from the `integration` branch: the pilots take what's in the currently running tag. Anyway yes, target `integration` as this is going to be only for new installations.

**Comment by fstagni** [comment]
In PR
