### ISSUE TITLE
Should we remove the SecurityLogging ?

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#4365]
Similarly to the system logging, the security logging is made obsolete by the centralized logging. 

This line in the security logging file 
```
2019-12-11 14:36:26.063077, True, ::ffff:134.158.49.148, 38930, [fstagni:lhcb_mcproc](/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=fstagni/CN=693025/CN=Federico Stagni), lbvobox102.cern.ch, 9166, Accounting/DataStoreHelper, RPC/commitRegisters
```

appears in the centralized logging as such

```
{
  "_index": "lhcb-dirac-logs-accounting-datastorehelper-2019.12.11",
  "_type": "doc",
  "_id": "-g5j9W4Bkahmagh1xKRD",
  "_version": 1,
  "_score": null,
  "_source": {
    "hostname": "lbvobox102.cern.ch",
    "varmessage": "([::ffff:134.158.49.148]:38930)[lhcb_mcproc:fstagni] RPC/commitRegisters(<masked>)",
    "levelname": "NOTICE",
    "exc_info": "",
    "@timestamp": "2019-12-11T14:36:26.000Z",
    "customname": "",
    "componentname": "Accounting/DataStoreHelper",
    "componentindex": "accounting-datastorehelper",
    "message": "Executing action",
    "spacer": " ",
    "asctime": "2019-12-11 14:36:26",
    "@version": "1",
    "type": "stomp"
  },
  "fields": {
    "@timestamp": [
      "2019-12-11T14:36:26.000Z"
    ]
  },
  "sort": [
    1576074986000
  ]
}
```

So, should we remove it along with the System Logging ?

**Comment by atsareg** [comment]
Security logging should be kept for a certain while according to legal requirements. This was never explicitly requested so far, but should be checked if anybody is asking for this info to be stored for a certain period (6 or 12 months or ...)

**Comment by chaen** [comment]
we can keep the data, but we could remove the service

**Comment by fstagni** [comment]
Flag added in https://github.com/DIRACGrid/DIRAC/pull/5760. Should

- [x] check for instructions once more
- [ ] remove the service in a later stage

**Comment by fstagni** [comment]
https://github.com/DIRACGrid/DIRAC/pull/6561 swaps the default flag.
Service will be removed from 8.2

**Comment by fstagni** [comment]
There won't be any 8.2, and the SecurityLogging service won't be added to diracx. Enough to close this issue.
