### ISSUE TITLE
"WaitingToRunningRatio" and "MaxWaitingJobs" set in /Resources/Computing/CEDefaults not refrected in SiteDirector?

### ISSUE THREAD

**Issue by yujikato** [DIRACGrid/DIRAC#4368]
We (Belle II operation) set "WaitingToRunningRatio" and "MaxWaitingJobs" in /Resources/Computing/CEDefaults. However, these values are not reflected in SiteDirector?
These variables are set in following:
https://github.com/DIRACGrid/DIRAC/blob/54cddcf5caa359e41223d7d867eadd7753176d89/Resources/Computing/ComputingElement.py#L172-L175

And SiteDirector use "WaitingToRunningRatio" and "MaxWaitingJobs" as follows.
These values are seem independent of values in /Resources/Computing/CEDefaults
https://github.com/DIRACGrid/DIRAC/blob/54cddcf5caa359e41223d7d867eadd7753176d89/WorkloadManagementSystem/Agent/SiteDirector.py#L975-L977

Is this intended behavior?
We are using **v6r21p16**

**Comment by fstagni** [comment]
In my understanding these values should be the same. Also in LHCb we set them he same way you do. Why do you think they are not reflected? 

CC @VladimirRomanovsky

**Comment by yujikato** [comment]
In Belle II environment, we set the values as follows.

![CEDefaults_Belle](https://user-images.githubusercontent.com/13082637/70985968-61a2d780-2100-11ea-950e-682d6f9669ef.PNG)

However, when we check WaitingToRunningRatio after the following line, the value is zero.
https://github.com/DIRACGrid/DIRAC/blob/54cddcf5caa359e41223d7d867eadd7753176d89/WorkloadManagementSystem/Agent/SiteDirector.py#L977

Do we make something wrong?

**Comment by fstagni** [comment]
Can you make a try please? 

Put `WaitingToRunningRatio` parameter in on queue option, e.g.  `Resources/Sites/<some>/<some.site.here>/CEs/<one.ce.here>/Queues/<name_of_queue>/WaitingToRunningRatio`

**Comment by yujikato** [comment]
Yes, we know WaitingToRunningRatio can be set in that way.
What we want to do is to set site-wide default parameter using 
/Resources/Computing/CEDefaults/WaitingToRunningRatio.

Following codes seems to intended to enable such a default value setting, 
but seems not working.
https://github.com/DIRACGrid/DIRAC/blob/54cddcf5caa359e41223d7d867eadd7753176d89/Resources/Computing/ComputingElement.py#L172-L173

**Comment by fstagni** [comment]
Than it's a bug somewhere, investigating this requires to put some printouts I am afraid. Would you be willing to look into it?

**Comment by andresailer** [comment]
Please have a look at #4414
which should solve this problem.

**Comment by yujikato** [comment]
> 
> 
> Please have a look at #4414
> which should solve this problem.

Thank you very much for the fix!

**Comment by andresailer** [comment]
Fixed in v6r22p19
