### ISSUE TITLE
Wrong version of the code used after install/update

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#4408]
When installing a new machine with `install_site`, the [CENSORED] `SystemAdministrator` will spawn a new `runsvdir` process despite there is already the system `runsvdir` process runing.
First of all, duplicating `runsvdir` is uncool.
But more importantly, when doing so, the `SystemAdministrator` already has in its environment the DIRAC `bashrc` sourced, which means that it will have in the `PATH` (and other env variables) a given version. So the spawned `runsvdir` will have it too. And so the DIRAC python process will have it as well. 
Which in turns means that when updating the version, it is still the old version of the code which will be used.

The `SystemAdministrator` should be fixed by:
- [x] Not spawning runsvdir if already there (in https://github.com/DIRACGrid/DIRAC/pull/4415)
- [ ] If spawning one, do it with a clean environment

From the operational point of view, detecting that is quite tricky because `lsof` won't tell you anything. The only way is to look at the `runsvdir` process spawned by your dirac user, and compare it to the `pro` link:

```
proLink=$(realpath /opt/dirac/pro/ | awk -F '/' {'print $NF'})
runsvdirVers=$(cat /proc/$(pgrep -u dirac runsvdir)/environ | tr '\00' '\n' | grep PYTHONPATH | sed -E 's|.*versions/(.*):.*|\1|g')
if [ "$proLink" == "$runsvdirVers" ]; then echo OK; else echo KO; fi
```

In any case, you should not have 2 `runsvdir` processes. If that's the case, stop everything, kill it all, restart clean (as `root`):

```
runsvctrl d /opt/dirac/startup/*
# wait till it's all down
pkill -9 runsv
systemctl restart runsvdir-start
runsvctrl u /opt/dirac/startup/*
```

**Comment by fstagni** [comment]
Looks like a good plan, can you take care of implementing it?

**Comment by chaen** [comment]
I'll have a look, but the best implementation would be `find DIRAC -name '*Installer*' -or -name '*SystemAdministrator*' -exec rm {} +` :-D

**Comment by fstagni** [comment]
...not today ;-)

**Comment by fstagni** [comment]
I think we'll leave with what we have.
