### ISSUE TITLE
"Completing" jobs, vs "Completed" jobs 

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#4412]
"Completed" jobs sometimes, depending on certain condition (e.g. when being killed within finalization) stay in the "Completed" status forever (basically, when they don't have any associated request). The suggestion is to use instead a "Completing" status by default, and use the "Completed" status only for those jobs that effectively have some requests. If this is the case, then the StalledJobAgent could work on statuses "Running" and "Completing"

**Comment by phicharp** [comment]
First attempt in https://github.com/DIRACGrid/DIRAC/pull/4416

**Comment by phicharp** [comment]
In the `StalledJobAgent`, jobs in `Running` status are checked and if found stalled, they are set into `Stalled` status, and later if still in this status, they eventually are set `Failed`.
For jobs in `Completing` status, they are directly set failed after an (admittedly longer) time (of the order of a day) without going through the status `Stalled`.
I see no reason why this is so and IMHO all jobs that are actually supposed to be active on the WN should be treated in a similar way).
If there is no objection I will thus treat the `Completing` jobs the same as `Running` jobs and set them `Stalled` as soon as they missed 2 heartbeat updates.

**Comment by atsareg** [comment]
My understanding is that we are going to replace Completed status with the Completing status everywhere. Completing status is a transient one and I agree that it should be treated in the same way as the Running status in the StalledJobAgent. But with one exception (as it is already done in the StalledJobAgent) that Completing Pending requests jobs are completely ignored by the StalledJobAgent, they should be managed by the RMS agents.

**Comment by atsareg** [comment]
There are indeed places where Completed Pending requests combo is treated as a final status (e.g. site summary, setting endExecTime). In order not to complicate the logic I tend to agree with Federico that we keep Completing status for jobs that are still in the worker nodes and Completed for jobs finished at WNs but still having pending requests. Then in some contexts Completed can be treated as a final state (e.g. defining the end of execution) or transient state (e.g. site summary)

**Comment by phicharp** [comment]
@atsareg: the plan was not to replace `Completed` with `Completing` everywhere: we keep "Completed" for jobs that have a pending request, this is the goal of this PR. Those will therefore not be considered by the `StalledJobAgent` but will be set in their final status by the `REA` when the request is successfully executed (note that it remains an unsolved case when the request is Failed: what do we do with the job?)

**Comment by atsareg** [comment]
Agreed. As for the job with Failed requests, this job should go to some final-final status, i.e. either Done or Failed. I think Failed job status is the most appropriate.

**Comment by phicharp** [comment]
Well, this is the problem with Failed requests: we may set the job as Failed as not everything was done that should have been done, but in several cases, the task executed by the job is just OK... but I agree we already have such cases of jobs that are set Failed but did their task...
This case should be handled by the conversion from Job status to Task status in the TS, which currently is just a copy of the status... although a Failed job may have executed a Done task ;-) and even we had cases when a `Done` job had indeed failed the task, but this normally should never happen...

**Comment by phicharp** [comment]
PR #4416, please review...

**Comment by fstagni** [comment]
Looks all good.
