### ISSUE TITLE
[v6r22] dirac-install now defaults to dirac-os

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRAC#4449]
https://github.com/DIRACGrid/DIRAC/blob/a7ff2f501cbf16d7ddb227f8645c59180be30d24/Core/scripts/dirac-install.py#L2643-L2645

Should this be an `and` between and parenthesis around the string type check and the version? Because every version (vXrYpZ) is a string? 

In any case it seems to me that dirac-install now always installs dirac-os even for v6r22

**Comment by fstagni** [comment]
I fail to see the error, honestly. This check is there for installing DIRACOS by default from v7 on.

IIUC this line 
```
isinstance(list(releaseConfig.prjRelCFG['DIRAC'])[0][1], str_type)
```
is specifically for those 2 versions that don't follow the vXrYpZ pattern (`master` and `integration` releases, which I remind are created by the nightly action.

**Comment by andresailer** [comment]
Ahh, I get it now, that check should be
```python
list(releaseConfig.prjRelCFG['DIRAC'])[0][1] not in '0123456789'
```
(or `... not in string.digits`)
Because
```python
list(releaseConfig.prjRelCFG['DIRAC'])[0][1]
```
takes the second character from the version string, e.g., `'v6r22p1'[1] ==  '6'`. That is '6' is still a string.
