### ISSUE TITLE
Enable RSS to handle multiple VOs

### ISSUE THREAD

**Issue by martynia** [DIRACGrid/DIRAC#4456]
Adding multi-VO functionality to the RSS would require modifying multiple tables in _ResourceStatusDB_ and _ResourceManagementDB_ by adding a _VO_ column. The code responsible for defining the schemas is in _ResourceStatusDB_ and _ResourceManagementDB_ modules and it is statically imported from relevant handlers. My suggestion is to dynamically load the DB modules as plugins which would maintain backward compatibility. The multi VO database schemas could be defined by classes inheriting from classes in _ResourceStatusDB_ and _ResourceManagementDB_modules respectively.
I have a simple patch where plugins are used _en lieu_ of static imports. I would create a PR targeting _rel-v7r1_. Does it make sense ? @fstagni

**Comment by fstagni** [comment]
It makes sense, yes, but it's maybe even too complicated: DB schema changes have been done in the past and can be done even now without much hassle. On top, these DBs are definded in sqlalchemy, for which we can use https://alembic.sqlalchemy.org/en/latest/index.html -- we never used it but it would be interesting to give it a go.

**Comment by fstagni** [comment]
This has been answered at BiLD meeting.
