### ISSUE TITLE
check if user is in VO upon proxy creation or upload time

### ISSUE THREAD

**Issue by msapunov** [DIRACGrid/DIRAC#446]
Is it possible to check if a user of a group belongs to VO on which this groups is referring to? I know that this issue is on the level of DIRAC administration but it could simplify the life of the beginners administrators and users. We have the cases  like that already.

**Comment by chaen** [comment]
does that still hold ? There is the getUsers or attGetUserNickname in VOMSService that can easily be instrumented

**Comment by chaen** [comment]
No reaction for the last 6 years, closing
