### ISSUE TITLE
Choice of ipv6 vs ipv4 can be better implemented?

### ISSUE THREAD

**Issue by rajanandakumar** [DIRACGrid/DIRAC#4470]
https://github.com/DIRACGrid/DIRAC/blob/da536726f87e161cac2e9101ab6dcbb0992808a3/Core/DISET/private/Transports/SSL/pygsi/SocketInfoFactory.py#L161

This line tries to open an ipv6 listening socket which can succeed even if the host machine does not have an ipv6 address. I would suggest that we can look at the output of

socket.getaddrinfo(socket.gethostname(),0)

to see if the system supports ipv6 addresses and open an ipv6 socket. Else open an ipv4 socket. And default to the exception as current.

An example of a machine where the listening socket succeeds listening to ipv6 even without an actual ipv6  host address is the IN2P3 VO-box. This then for example tries to connect by ipv6 to the PIC VO-box (which is dual stack) which then fails.

Opening an issue before creating a PR to check if someone has a smarter idea of this (or if my understanding is incorrect).

**Comment by chaen** [comment]
Well, clearly this means that the IN2P3 setup is wrong no ? 
We regularly have that issues with sites.

**Comment by rajanandakumar** [comment]
Formally speaking, I think it is okay. I will ask around and get back on that.

However, maybe the comment is still valid?

**Comment by rajanandakumar** [comment]
And checking with the ipv6 hepix mailing list, the behaviour is apparently correct in the IN2P3 VO-box. An exception is thrown only if IPV6 support is explicitly disabled in the kernel. So, the code has to be fixed at the DIRAC level. I think it needs to be something like

iplevel = -1
for x in socket.getaddrinfo("voboxlhcb.pic.es",0):
  iplevel = max(iplevel, x[0])

Then we can have an
if iplevel == 10 # ipv6 available
...

Any thoughts on if my suggestion is okay or there is a better option available?

**Comment by zmathe** [comment]
I would say this is a very strange behaviour even if is is coming from hepix mailing list. Why we should try to guess which address can be used? If the ipv6 address is not exits, ipv6 should not be enabled.  It seams in the future they can say we have an ipv6 address with ipv6 option, but you have to try out, if it is really working by sending few packets :)
I would say this direction is wrong, but probably I am wrong.
We can add a check in DIRAC code, but I would say this behaviour is not correct.

**Comment by sfayer** [comment]
Hi,

I think the existing behaviour is correct: For server code, an AF_INET6 socket is just as good as an AF_INET one, even if the node has no IPv6 addresses!... It's completely backwards compatible by default (which is the mode we use it in :-)

The client code (which I think is more relevant here) does have an "autodetection" loop:
https://github.com/DIRACGrid/DIRAC/blob/da536726f87e161cac2e9101ab6dcbb0992808a3/Core/DISET/private/Transports/SSL/pygsi/SocketInfoFactory.py#L53-L56

It gets all of the addresses for the server and tries them in order until one connects. This is the standard algorithm for supporting both IPv4 and IPv6, it basically works in every case unless something is seriously broken on the surrounding network (in which case, that should be fixed, not the code!).

In my opinion, the DIRAC server & client code here is all correct... We've tested it in a massive number of network environments over the past couple of years so I'd be quite suspicious of needing to change it to make something work.

Regards,
Simon

**Comment by chaen** [comment]
Thanks @sfayer for the comprehensive answer. Raja, if you want, I can try to dig some ggus tickets we had with some sites where Edouardo M. & cie had to intervene and tell the sites that their configuration was broken, just like you describe :D

**Comment by fstagni** [comment]
I close this ticket then (comments can still be added).

**Comment by rajanandakumar** [comment]
It turns out that the IN2P3 VO-box is trying to occasionally talk to vobox09.pic.es which has of course been turned off (and replaced by vobox10.pic.es). I will have to understand that and fix it.

Obviously the code is fine here. My apologies for the noise!

**Comment by chaen** [comment]
also, do be fair, the voboxes at sites do not need to be able to talk to each other absolutely... .

**Comment by rajanandakumar** [comment]
Sure - that is why it was not urgent and I was happy to discuss it before trying to submit a PR or something. 😃
