### ISSUE TITLE
Interface to Indigo IAM IdP

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#4485]
(from discussion happening in https://indico.cern.ch/event/893140/)

While the protocol support will be assured, we need to make sure that the information present in the token will be properly interpreted.

**Comment by TaykYoku** [comment]
Can you assign me here.

There is still no single token format for all IdPs, so there is a special class in `src/DIRAC/Resources/IdProvider/IAMIdProvider.py`(#5149) that describes IAM-specific token validation. Common to all algorithms are described in `src/DIRAC/Resources/IdProvider/OAuth2IdProvider.py`.

We need to read the user ID and its DIRAC group from the token. The user ID is passed to the standard `sub` claim. The DIRAC user group will be searched according to the token scope.

**Comment by aldbr** [comment]
Not entirely sure of what you wanted from this issue.
We are able to interact with the Indigo IAM IdP via the `OAuth2IdProvider` module.
Should we close this issue?

**Comment by fstagni** [comment]
Yes, the issue can be closed.
