### ISSUE TITLE
Handle token revocation

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#4488]
(from discussion happening in https://indico.cern.ch/event/893140/)

When the password changes, normally all tokens are revoked. How can this be handled in DIRAC?

**Comment by TaykYoku** [comment]
Need clarification on which side the password changes? You mean on IdP side?
If yes, then to revoke tokens decide IdP and we cannot influence it except by agreeing with IdP. So in this cause all user sessions will down and user must again to do authentication flow through IdP(with DIRAC).

**Comment by chrisburr** [comment]
> Need clarification on which side the password changes? You mean on IdP side?

Yes.

>  If yes, then to revoke tokens decide IdP and we cannot influence it except by agreeing with IdP. So in this cause all user sessions will down and user must again to do authentication flow through IdP(with DIRAC).

Exactly and this will never happen when using Google as the provider. So either we need to:

1. heavily restrict the list of providers
2. have a solution which allows pilots to not be entirely dependent on these tokens.

I think the 2. is needed as revoking tokens on password changes is increasingly seen as a best practice to make it easy resecure you account after a possible password leak.

**Comment by TaykYoku** [comment]
1. DIRAC will only registered providers.

**Comment by TaykYoku** [comment]
2. Would you modulate some situation to better understanding question, please.

**Comment by atsareg** [comment]
I have a strong feeling of "déjà vu" in this discussion. It is equivalent to certificate revocation for the user whose payloads are in the works in the system. In theory, certificates can be revoked at any time, but in practice this will be very limited to some flagrant cases only and for any practical need we can count on long certificates/proxies availability. The same is with the tokens. There will be a mechanism for storing and serving long living tokens analogous to MyProxy or ProxyManager services. If there will be no such mechanism, the whole grid system will simply fall apart.

**Comment by atsareg** [comment]
Right now in the Andrei's PR this mechanism is coded as special long-living sessions per user which are maintained on the server side. This is analogous to the ProxyManager. If this will be considered unsatisfactory by the WLCG community, some replacement to it should be suggested and then we will implement it.

**Comment by TaykYoku** [comment]
now this applies to v7r4 (hopefully this is final).

Currently, long-term tokens are written and updated in TokenManager in TokenDB. The user can remove them from there if desired. These tokens are used to create new tokens for issuance to the user or services for access to DIRAC or other resources. If long-term tokens are revoked on the side of the IdP (these can be various reasons determined by the IdP itself), then when you try to get a token for the user / group, the error will be returned and the user must log in again into DIRAC.

In the case of using tokens for pilots, there is still no clear solution. For now, I see this implementation using a "long access token" that would be considered valid while all jobs are running and only for certain requests. In this case, the original long-term tokens will only be used to obtain tokens for new jobs.

**Comment by fstagni** [comment]
I close this as most probably won't be tackled in DIRAC.
