### ISSUE TITLE
test_delegation fails with OpenSSL 1.1

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRAC#4489]

**Comment by chaen** [comment]
May be fixed with https://github.com/DIRACGrid/DIRAC/pull/4391 
(hard to tell without the actual failure :-) )

**Comment by fstagni** [comment]
I close this one but please do re-open it if you feel necessary.

**Comment by chrisburr** [comment]
Yeah this was fixed by https://github.com/DIRACGrid/DIRAC/pull/4391 and to a lesser extent https://github.com/DIRACGrid/DIRAC/pull/4863.
