### ISSUE TITLE
RucioFileCatalogClient plugin

### ISSUE THREAD

**Issue by cserf** [DIRACGrid/DIRAC#4495]
The Belle II experiment, that uses Dirac, plans to use Rucio as Distributed Data Management framework. In order to achieve that a new FileCatalog (RucioFileCatalogClient) implementation is needed.

**Comment by iueda** [comment]
For this RucioFileCatalogClient to work, there are a few requirements:
* rucio client needs to be installed where it is used, i.e. Rucio needs to be included in DIRAC OS.
* some environment variables need to be set, i.e. some changes needed in dirac-install

Belle II should first try this out in BelleDIRAC, while the code RucioFileCatalogClient itself may better be reviewed with a pull request without waiting for the above to be completed.

**Comment by fstagni** [comment]
- if Rucio is only python, and pip-installable, then it can be added easily to a DIRACOS extension. It's documented in https://diracos.readthedocs.io/80_extendingDIRACOS.html and you can see an example in https://gitlab.cern.ch/lhcb-dirac/LHCbDIRACOS/
- regarding the environment variables: are they needed by the pilots (and should they be steered by dirac-install?)

**Comment by fstagni** [comment]
I think this specific task can be closed now.
