### ISSUE TITLE
Create a DIRAC Enhancement Proposal process

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRAC#4522]
Many software packages uses an "enhancement proposal" system for providing a procedure for proposing and commenting on high-level changes, ideally before code is actually written. Some examples include:

* [python](https://www.python.org/dev/peps/)
* [conda-forge](https://github.com/conda-forge/cfep/blob/master/cfep-01.md)
* [jupyter](https://github.com/jupyter/enhancement-proposals)
* [numpy](https://numpy.org/neps/)
* [matplotlib](https://matplotlib.org/3.1.1/devel/MEP/index.html)
* [rust](https://github.com/rust-lang/rfcs)
* [kubernetes](https://github.com/kubernetes/enhancements/tree/master/keps)

I think DIRAC would benefit from such a system for changes such as the Python 3 migration, environment isolation, OAuth and JSON serialisation. It doesn't need to have a formal "approval" process, just provide a place to document and discuss changes easy.

This could be either implemented as:

1. A new repository in the DIRACGrid organisation
2. A section in the docs of the main DIRAC repository

Regardless of which home is chosen for them we should include them in the main DIRAC readthedocs website.

Any thoughts?

**Comment by fstagni** [comment]
We had a trial at this with the RFCs: https://github.com/DIRACGrid/DIRAC/wiki/DIRAC-Requests-For-Comments-%28RFC%29
Some of these translated into real code, others didn't.

**Comment by chaen** [comment]
And I disagree with the no need for a formal approval: it needs to be blessed at the BILD :-)

**Comment by chrisburr** [comment]
> And I disagree with the no need for a formal approval: it needs to be blessed at the BILD :-)

I agree. I was meaning we don't have to a process like "at least 60% of people in the DIRAC team on github must vote to approve". Instead the less formal process of "we have to come to a consensus at a BiLD" is good enough.
