### ISSUE TITLE
Use GitHub actions to automatically update master branch

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRAC#4530]
Rather than manually pushing `rel-v7r0` to master we could easily use GitHub actions to do it automatically and ensure they're always kept in sync.

Are they any issues with this idea that I'm not aware of or should I implement it?

**Comment by fstagni** [comment]
That's OK of course, but how do you plan to tell GitHub Actions to know which branch should be the `master` branch?

**Comment by chrisburr** [comment]
I assume I shouldn't take the `rel` branch corresponding to the latest non-pre-release in `releases.cfg`?

If so I think that probably has to be hard coded any referenced in the docs (as is the case for the README): https://dirac.readthedocs.io/en/integration/DeveloperGuide/ReleaseProcedure/index.html#propagating-patches

**Comment by fstagni** [comment]
Yes it's the last non-pre-release of course. The doc is already built on the content of the `master` branch (it becomes _latest_ : https://dirac.readthedocs.io/en/latest/). But I am not sure I fully understand your last sentece...

**Comment by chrisburr** [comment]
In that case the second sentence doesn't matter. One more question to make sure I'm understanding correctly. Assuming `v7r0pX` is the latest release:
1. It should always be in sync with `rel-v7r0`?
2. It should always be in sync with the latest tagged commit from `rel-v7r0`?

**Comment by fstagni** [comment]
1. not necessarily
2. yes
