### ISSUE TITLE
/Resources/FileCatalogs should be setup-dependent

### ISSUE THREAD

**Issue by phicharp** [DIRACGrid/DIRAC#454]
All instances of <VO>-DIRAC get their list of catalogs from /Resources/FileCatalogs. It makes it impossible to test for example a new catalog in the Certification setup without impacting severely the Production setup. There should be a way to enable/disable catalogs at the setup level.

**Comment by chaen** [comment]
There is now a separation between Resources and Operations for the FC as well, can we close ?

**Comment by atsareg** [comment]
Yes, any setup/VO dependent parameters of catalogs must now be defined in the Operations section. This should be documented
