### ISSUE TITLE
add feature to add checksum to file registration in filecatalog cli

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#4548]
We have users that have uploaded a small number of files outside the DIRAC file catalogue and would like to register them in the catalogue. Currently the cli does not support adding a checksum. 
register file <lfn> <pfn> <size> <SE> [<guid>]
Would it be possible to add this ? It's rather hard for our users to work their way through the python API for a single file.

**Comment by chaen** [comment]
This is a design choice, since having discrepancies between FC and SE is the worse. We even had a campaign few years back where we removed all the scripts acting only on one of the two.

**Comment by marianne013** [comment]
So what is my user to do (short of diving into the API) ? Download the file, delete it from the SE and re-upload it with the DIRAC tools ?

**Comment by atsareg** [comment]
How many files like those are there ?

**Comment by marianne013** [comment]
He's apparently now at 34 files and this whole thing is turning into a disaster.
I don't know what is worse, user who don't try or user who try really hard.

**Comment by atsareg** [comment]
Well, I would say that for 34 files making a script of several lines to download, remove and reupload files would be the simplest solution. We certainly can add a command to perform such operations (adding checksum) but we risk to enter religious wars whether this is the right way to do which tend to last long.

**Comment by marianne013** [comment]
I still think users should be allowed to deal with their files as they see fit. As this is possible through the API (and is needed, we regularly import existing files into the DIRAC file catalogue on a large scale), so the CLI should just be consistent with the API.

**Comment by chaen** [comment]
> I still think users should be allowed to deal with their files as they see fit.

Sure, but then we (as admin) should feel free to tell them to get lost when things do not work because they did something stupid :-)

> As this is possible through the API (and is needed, we regularly import existing files into the DIRAC file catalogue on a large scale), so the CLI should just be consistent with the API.

Technically, the `FileCatalog` is NOT a public API.

Anyway, as Andrei said, it easily turns into religious war.

**Comment by marianne013** [comment]
This all makes sense if you run a central DIRAC server integrated into an experiment. That's not  what the multi-VO server does. I do want to be in the position to have to edit the catalogue for an experiment I am not an active member of. Then these problems get logged as DIRAC problems rather than experiment problems. User like browsing the cli, as it looks like a unix system and they feel comfortable with it.

**Comment by fstagni** [comment]
Shall we conclude that this will not be implemented in vanilla DIRAC?

**Comment by chaen** [comment]
An alternative is to keep a "what you should not do but is possible" list of scripts, not distributed, but centralized here. This way, when a user has such issue, Daniela or whoever can point the user to this list of script, which would contain all the warnings and blames that we want them to have...

**Comment by chaen** [comment]
Just like this :-)

**Comment by fstagni** [comment]
A new repo of "DIRAC scripts"?

**Comment by sfayer** [comment]
How about including this feature in vanilla DIRAC, but only enable it if the "DataManagement/AllowUserReplicaManagement" option is set to true? We've used that in other places before (remove-catalogue-files) to let the admins decide how much power to give to the end users.

**Comment by chaen** [comment]
that would be a very coarse granularity. Although, we may want to put non dms related script in this dark-magic repo, so that flag would not cover everything

**Comment by marianne013** [comment]
This was actually fixed by Andrei in #5211
