### ISSUE TITLE
What we want from the plotting

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#4574]
Currently, there is a lot of code to generate the plots (accounting, etc) in the WebApp.
There are nowadays tools that are defacto standard. I want this task to be a requirement list of what we want in terms of features.
Then later, the idea is to see if we could move to something standard (grafana/kibana to name them)
I start, please feel free to edit

1. Save image: I want to be able to save a plot as an image format 
2. Share snapshot plot: I want to be able to share a link the generates the exact same plot (with the same timestamps)
3. Share plot generation: I want to be able to share a link that regenerate the plot with the relative time (for example, failed transfer at site X in the last 24h)
4. Save dashboard: I want to be able to generate a collection of plots, and save this as a dashboard
5. Share dashboard as a link: I want to be able to share the dashboard as a link
6. Make the dashboard usable by other VO: I want that the dashboard I designed can be imported by other VOs
7. Types of plots: histograms, stacked lines, (please fill in)

**Comment by phicharp** [comment]
May I refer also to https://github.com/DIRACGrid/WebAppDIRAC/issues/426 that needs to be implemented

**Comment by chaen** [comment]
One more:
* I want that dashboard can be editable by more people than just the creator

**Comment by marianne013** [comment]
GridPP does not use a dashboard, instead we and our users generate the plots as needed. Both the admins and the users like that the plot generation is relatively straight forward and that you can choose the time period to match whatever period you actually want to show (less questions that way). We mainly use CPU usage (by VO, user, site) and Running jobs (similar selection).

**Comment by aldbr** [comment]
- Select specific data to plot, but also select specific data to not plot: I want to see a plot aggregating all data except some specific elements

**Comment by chaen** [comment]
Hard deadline for comments: 15th of June

**Comment by aldbr** [comment]
- The ability to create plots from a CLI?

**Comment by fstagni** [comment]
Deferred to DiracX (which will not implement plotting!)
