### ISSUE TITLE
dirac-install should take defaults from cvmfs and fall back to webserver if cvmfs not available

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#4604]
Worker nodes will generally have cvmfs available, but users installing a UI would still need to be able to take the defaults from the web server.

**Comment by IgorPelevanyuk** [comment]
Same request from us. Right now, in our infrastructure, we are DDOSing EOS with https://diracos.web.cern.ch//diracos/releases/diracos-v1r10.tar.gz download. It would be nice to download it from any CVMFS (lhcb, egi).

**Comment by fstagni** [comment]
We need to decide how to tackle this. First, this is how it works right now:

The `globalDefaults.cfg`
- As explained in https://github.com/DIRACGrid/DIRAC/blob/integration/Core/scripts/dirac-install.py. dirac-install.py can take a url to a cfg file (can be local), but by defaults it looks for http://diracproject.web.cern.ch/diracproject/configs/globalDefaults.cfg
- the file above is basically a collection of links to where to get the sources. E.g. for LHCb it points to http://lhcb-rpm.web.cern.ch/lhcb-rpm/lhcbdirac/lhcb.cfg that holds links to locations of where to find the LHCb tarballs.
- if your VO/community is not in the globalDefaults.cfg http://diracproject.web.cern.ch/diracproject/configs/globalDefaults.cfg file, then you end up using the defaults 

tarballs (including DIRACOS): 
- the tarballs (if not already locally cached) are downloaded from egi CVMFS, if available: https://github.com/DIRACGrid/DIRAC/blob/integration/Core/scripts/dirac-install.py#L1426
- if not, they are downloaded from the web server

The current issue of @IgorPelevanyuk is that DIRACOS was not on egi CVMFS. So @atsareg is uploading them there now. 

At the same time, as pointed out: 
1. the content of globalDefaults.cfg might not be updated. And right now the karma for updating it is in the hands of the usual subset of the LHCb crew.
2. CVMFS is not everywhere, especially EGI mount.
3. the globalDefaults.cfg currently sit on the infamous single-point-of-failure
4. The way we "sneak" CVMFS as an location inside the dirac-install.py script isn't ideal, nor flexible

To fix point 1 I would do the following:
- put its content in the https://github.com/DIRACGrid/management code, and deploy to its current (and future) location(s) with the usual dirac-distribution container (like in https://github.com/DIRACGrid/Pilot/blob/master/.github/workflows/nightly.yml). Would you agree with this?

Fixing points 2, 3, and 4 IMHO means simply that we should have multiple locations for where to get the `cfg` and the tarballs. And these locations should be all listed in the cfg file, and that its order is meaningful. This of course means that we need to modify dirac-install.py
And one last point: we should always, for each release we do, push it to not only to the EOS web servers, but to CVMFS, and to whatever other locations we feel to add.
What do you think?

**Comment by chaen** [comment]
I agree with all you say, and I would even add one more point which is that there should be a way to run completely without the `globalDefaults.cfg`. That is, if a site/user wants to specify a location for that file, we should use that file. If I am not mistaken, `dirac-install` is already instrumented for that, but we need to be able to inject that in the pilot installation chain

**Comment by marianne013** [comment]
I agree with Chris. Then we could put it on our own server (I realize it would be our responsibility to maintain it).

**Comment by IgorPelevanyuk** [comment]
Tar download from CVMFS works. Thanks!

I also noticed that cfg file for LHCb (http://lhcb-rpm.web.cern.ch/lhcb-rpm/lhcbdirac/lhcb.cfg) has the following fields:
BaseURL = http://lhcb-rpm.web.cern.ch/lhcb-rpm/lhcbdirac/tars
DIRACOS = http://lhcb-rpm.web.cern.ch/lhcb-rpm/LHCbDIRACOS/releases/

Before the problem was solved, could I put diracos-v1r10.tar.gz file on some web server in JINR and provide the address in DIRACOS field in our local JINR-defaults file(http://dirac-ui.jinr.ru/defaults/JINR-defaults.cfg)? Like: DIRACOS = http://dirac-ui.jinr.ru/defaults/releases/
Would it solve the problem with downloading tars from http://diracproject.web.cern.ch by dirac pilots?

**Comment by sfayer** [comment]
Hi,

As I mentioned on the user forum, it would also be good if we could get dirac-install and the Pilot repo checked out onto the CVMFS repo nightly too. Would that be possible?

Regards,
Simon

**Comment by atsareg** [comment]
Yes, this should be possible. I will take care of that.

**Comment by marianne013** [comment]
Hi Andrei, any luck with this ? We'd like to point the cloudinit script to pilot3 on cvmfs if possible.

**Comment by marianne013** [comment]
@atsareg @fstagni What about the PIlot repo ? At the moment we are downloading it from github, but it doesn't scale.

**Comment by fstagni** [comment]
@marianne013 The content of the pilot repo is uploaded nightly here: http://diracproject.web.cern.ch/diracproject/tars/Pilot/ by this [Pilot GA workflow](https://github.com/DIRACGrid/Pilot/blob/master/.github/workflows/nightly.yml) which in turn uses this [script in the management repo](https://github.com/DIRACGrid/management/blob/master/dirac-distribution/pilot_tarball_upload.sh)

If you have more locations where to upload it would be great.

**Comment by atsareg** [comment]
The pilot files from http://diracproject.web.cern.ch/diracproject/tars/Pilot/DIRAC/master/ are available also from /cvmfs/dirac.egi.eu/pilot directory.

**Comment by marianne013** [comment]
@atsareg 
Something has gone horribly wrong (I can see the cvmfs repo as I have access to it through some other VO):
[supernemosgm@cvmfs529 dirac.egi.eu]$ ls -l pilot
total 288
-rw-r--r-- 1 diracsgm cvmfsvos 97630 Jul 16 15:45 checksums.sha512
-rw-r--r-- 1 diracsgm cvmfsvos 97630 Jul 16 15:45 pilot.json
-rw-r--r-- 1 diracsgm cvmfsvos 97630 Jul 16 15:45 pilot.tar
(note the sizes and the tar file is not a tar file)

**Comment by atsareg** [comment]
Oh, the last moment improvement... Sorry. It should be better now but will take time to propagate

**Comment by atsareg** [comment]
@fstagni: globalDefaults are used in dirac-install(-extension) scripts only which are here. So, I think it is better to keep the globaleDefaults.cfg also here

**Comment by fstagni** [comment]
> The pilot files from http://diracproject.web.cern.ch/diracproject/tars/Pilot/DIRAC/master/ are available also from /cvmfs/dirac.egi.eu/pilot directory.

How regularly do you sync them?

**Comment by atsareg** [comment]
I have set up a daily cronjob to update the whole cvmfs repo

**Comment by chaen** [comment]
@atsareg given the current disaster with the global cfg, could you please run the cron jobs more often (at least once an hour), such that we do not depend entirely on you for EGI update in case of emergency

**Comment by marianne013** [comment]
I think disasters can be dealt with by hand. Just don't update anything while Andrei is not around.

**Comment by atsareg** [comment]
I have set up the cron to run hourly for the moment (my poor mail box ...).

**Comment by atsareg** [comment]
But what is the disaster with the globalDefaults.cfg ? The LHCb settings in there were not changed. Am I missing something ?

**Comment by andresailer** [comment]
> 
> 
> I have set up the cron to run hourly for the moment (my poor mail box ...).

You need to fix your script to only produce output when it fails.

**Comment by atsareg** [comment]
I have to understand what fails. Right now I do not understand what triggered this exchange.

**Comment by chaen** [comment]
> Just don't update anything while Andrei is not around.
:laughing: 

> I have to understand what fails. Right now I do not understand what triggered this exchange.

I really believe it's just a typo that was introduced when you cleaned up the file before putting it in the repo.
Looking at the origin, that wasn't modified since April, you can see that this typo is not there

**Comment by chaen** [comment]
To give more details, this was the failure we had:
```
INFO:root:Loading global defaults from: /cvmfs/dirac.egi.eu/admin/globalDefaults.cfg
[...]
INFO:root:Defaults for Projects/LHCb are in c
INFO:root:Could not load defaults for project LHCb

```

And this was due to the following entry, which is clearly wrong, and really just look like a typo

```
LHCb
  {
    DefaultsLocation = c
  }
```

**Comment by atsareg** [comment]
OK, now I see. I did not notice the Federico's commit which indeed fixed the typo. Sorry. Now everything is propagated to cvmfs and I checked that the right values are obtained from there.

**Comment by chaen** [comment]
Sorry, I should have made it more explicit than just the link to the file&line. Now I understand the confusion !

**Comment by fstagni** [comment]
I close this issue, as the tasks went in https://github.com/DIRACGrid/management/issues and operationally it's solved.
