### ISSUE TITLE
[v7r1] Wrapper script sources non existing bashrc file

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#4609]
When executing a command
```
$ dirac-admin-get-proxy -a chaen lhcb_user
/opt/dirac/pro/scripts/dirac-admin-get-proxy: line 2: /opt/dirac/pro/bashrc: No such file or directory
```
The Wrapper look like that
```
#!/bin/bash
source "$DIRAC/bashrc"
export DCOMMANDS_PPID=$PPID
exec /usr/bin/env python $DIRAC/DIRAC/FrameworkSystem/scripts/dirac-admin-get-proxy.py "$@"
```
But `$DIRAC` is `/opt/dirac/pro`, while the `bashrc ` is in `/opt/dirac`, at least for the installations using this `pro/old` option.

This comes from 7f02ad149c and I guess relates to https://github.com/DIRACGrid/DIRAC/issues/4480
* the real install root is never exported anywhere, and is just used in `dirac-install`
* I am anyway not sure how you expect that to work, since if you start from a completely clean environment, `$DIRAC` is not defined. 

So maybe defining a `$BASEPATH` in bashrc and using it in your script would make the scripts work for environment that already sourced the `bashrc`, but for other, it still needs to be defined  before calling the script.

So not sure what you guys had in mind @marianne013 @chrisburr

**Comment by marianne013** [comment]
The /opt/dirac/pro quandary should be solvable with a well placed if statement. 
The idea was that once you setup DIRAC via sourcing bashrc you keep the DIRAC variable, and then you can reset the rest (PYTHONPATH etc), but if you need a DIRAC command it can be assured to be able to find the correct libraries/python etc.

**Comment by fstagni** [comment]
Discussion:
- symlink
or 
- add DIRACROOT env variable to client

**Comment by chaen** [comment]
@chrisburr Just to confirm that we are indeed seeing that in LHCb, since the pilot in certification fail:
```
2020-05-29 11:01:20 UTC WorkloadManagement/JobAgent INFO: No more agent modules to execute. Exiting
/cvmfs/lhcbdev.cern.ch/lhcbdirac/v10r1-pre1/scripts/dirac-agent: line 2: /cvmfs/lhcbdev.cern.ch/lhcbdirac/v10r1-pre1/bashrc: No such file or directory
```

**Comment by chaen** [comment]
>     * symlink (basically the same trick we've been using for ages)
If it works, why not, so we keep what is already there

>     * add DIRACROOT env variable to client
I like that one more because more generic and can show useful in the future without further changes.

So I'd propose to introduce anyway `DIRACROOT`.
in the meantime we can try to add the symlink. If it works, we add this as a fix for that specific case

**Comment by fstagni** [comment]
Is https://github.com/DIRACGrid/DIRAC/pull/4630 (part of) the solution to this issue?

**Comment by fstagni** [comment]
@chaen @chrisburr would you please confirm (or not) that this issue is solved?

**Comment by chrisburr** [comment]
I think this is fixed, I'll let @chaen re-open if he thinks something is missing.

**Comment by chaen** [comment]
I think so yes
