### ISSUE TITLE
Set XRD_RUNFORKHANDLER in RequestExecutingAgent and remove from the bashrc

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRAC#4616]
Having `XRD_RUNFORKHANDLER=1` set can cause subprocesses to be randomly aborted with `EPoll: Bad file descriptor polling for events` ([technical details are here](https://github.com/xrootd/xrootd/issues/1198)).

@chaen thinks this variable is only needed in the `RequestExecutingAgent` so I think it should be removed from the bashrc and set on demand as is done for:

https://github.com/DIRACGrid/DIRAC/blob/36bf69f69b52c081b223ce12ab37bea28a05f3cc/Resources/Storage/GFAL2_XROOTStorage.py#L63-L64

**Comment by chaen** [comment]
Actually, more agents could need it. Basically any agent or even service talking with xroot. So I would just set it in the `bashrc` of the servers, not on the client side.
Also looking a bit more in details, the issue probably does not happen with the `ProcessPool` that we use, as there is no `POpen` with `close_fds`. But I would need to check more the underlying details anyway

**Comment by chrisburr** [comment]
The place that I've mostly seen it crash is when launching payloads as `$DIRACROOT/scripts/dirac-jobexec` so `close_fds=True` is the right thing to do. It ultimately starts the new process from here:

https://github.com/DIRACGrid/DIRAC/blob/afb5276c24134cecb5340147972b061d85083bc3/Core/Utilities/Subprocess.py#L432-L439

**Comment by chaen** [comment]
Yes but I don't think that happens in the `REA`

**Comment by fstagni** [comment]
This was discussed a bit but I see no convergence. Is the strategy here simply to have the variable only on server side?

**Comment by chrisburr** [comment]
I'd like to see how the upstream XRootD issue gets resolved first. I just pinged them but there is no progress yet.

**Comment by marianne013** [comment]
Hi, we just had a user complain about exactly this issue. It looks like the xrootd ticket:
https://github.com/xrootd/xrootd/issues/1198
never went anywhere and it looks like there was never any consensus on this issue within DIRAC either. Any creative suggestions ?

**Comment by chaen** [comment]
GridPP will try running their pilot from CVMFS and remove the environment variable. If it works, we will change `dirac-install` to generate the `bashrc` with this variable only for server installs

**Comment by sfayer** [comment]
We tried removing XRD_RUNFORKHANDLER from the bashrc used by our pilots; the end user has confirmed that this fixes the issue. We haven't seen any new issues caused by this change.

**Comment by fstagni** [comment]
Closed after https://github.com/DIRACGrid/management/pull/39
