### ISSUE TITLE
Services integration with DIRAC Workload Manager

### ISSUE THREAD

**Issue by samuelbernardolip** [DIRACGrid/DIRAC#4623]
## Motivation:
Feature request: DIRAC REST API.
Allow better integration of DIRAC client when jobs are submitted by a service that works as a broker for requests posted by a provided frontend form.

## Use case:
For the common use cases of DIRAC we have the user submitting the jobs directly to DIRAC. But when there is a service entrusted to manage that asynchronously after a user request, we need to place the usual CLI commands embedded within the service software.
The provided DIRAC API SDKs are limited in language support and requires library dependencies and environment setup for GRID authorization that are adverse to the DIRAC protocol integration with service software.

## Integration success:

There are an interesting group of use cases that can start using the GRID, that now only run jobs standalone in the cloud. The key points of the service integration success using DIRAC REST API are:
- allows to bypass the dependencies required by the DIRAC SDK and environment details such as proxy authorization
- avoids clients with the requirement of creating a local REST service to run aside the main software
- reduce the integration code efforts and future maintenance for all interested use cases
- REST API provides an independent language solution (schema complaint), surpassing the SDK language centric limited support from DIRAC client

## Implementation proposal
Update interface to provide REST API and integrate it into the required regression tests for future releases.
Implement the support for OIDC and SAML authentication from external IdP for REST API access.
Map the user group attributes and proxy certificate for the job authorization, complying to the CE demands.

**Comment by fstagni** [comment]
Thanks for writing the issue. What you write is part of our mid term development strategy (this isn't just a bug report) so it might take quite some time before this is possible.

**Comment by fstagni** [comment]
What is in https://github.com/DIRACGrid/DIRAC/pull/4677 is a step forward in the direction. Just linking here, not elaborating on it more. OP is welcome to look at the PR.

**Comment by fstagni** [comment]
Just linking a few things here: 
- actual test in https://github.com/DIRACGrid/DIRAC/discussions/6121, using a DIRAC v8.0 server (would have worked the same with a v7.3 server properly configured)
- for a "no client" solution, need to wait for v8.1 and https://github.com/DIRACGrid/DIRAC/pull/6164

**Comment by fstagni** [comment]
While for a full REST APIs we'll need to wait for a first DiracX (https://github.com/DIRACGrid/diracx) release, there will be no further push for this in DIRAC.
