### ISSUE TITLE
[v7r1] Proxy group: forbit download of privileged group

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#4624]
When the groups were removed from the DB, we agreed that we should have a mechanism to prevent some group proxy to be downloaded. This does not exist yet and should be implemented

**Comment by TaykYoku** [comment]
It's implemented using the `Registry.isDownloadableGroup()` method. It read the group option ```DownloadableProxy```. By default, it's read as true.
More about it in `docs/source/AdministratorGuide/Configuration/ConfReference/Registry/Groups/index.rst`.

**Comment by chaen** [comment]
AH ! Thanks, we discussed it this morning and thought it was not implemented. This whole `ConfReference` is meant to disappear. Could you port that to the proper locations ? namely, it would be good that you add an example to the `dirac.cfg` at the root of the repo. For the rest, @andresailer where do you think we should put it ?

**Comment by chaen** [comment]
Also, can you please add these instructions to the Wiki of v7r1 ?

**Comment by TaykYoku** [comment]
I just added a little description about it to the Wiki.

**Comment by fstagni** [comment]
Should this task be closed?

**Comment by chaen** [comment]
no, we still need this somewhere in the doc.

**Comment by TaykYoku** [comment]
Where should this be described? i will do PR

**Comment by chaen** [comment]
In fact, I was about to open a github issue describing exactly all the documentation I am missing. So I will specify that in that other PR if that's fine with you

**Comment by fstagni** [comment]
> In fact, I was about to open a github issue describing exactly all the documentation I am missing. So I will specify that in that other PR if that's fine with you

Once done, please close this one (let's not duplicate issues)

**Comment by TaykYoku** [comment]
OK

**Comment by fstagni** [comment]
Close, as it should be included in https://github.com/DIRACGrid/DIRAC/issues/4702
