### ISSUE TITLE
Multi-VO Testing

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#4631]
As multi-VO installs of DIRAC become more common, this should be reflected both in the integrated test as well as the 'hackathons'. This issue is to collect the tasks necessary to introduce multi-VO testing for DIRAC code.
The gridpp VO has agreed to be the second VO (assuming dteam to be the other) and we can ask for membership for any DNs necessary. 
So far I have come up with:
- [x] Update the test server (https://lbcertifdirac70.cern.ch/DIRAC/ ?) configuration to include a second VO. (The certificate that is used for testing would have to join the gridpp VO).
  - [x] drop DIRAC/VirtualOrganization option
    - should check if by dropping it things would still work, even before introducing a second VO
- [x] Introduce VO specific test into the hackthons. I think it's best if the tests only do one VO at a time, so that even someone who is not in both VOs can run tests.
- [ ] Update the integration tests on github. Unfortunately I don't know how they are setup, however I believe @martynia  had made a start on writing multi-VO tests. 
- [ ] Update the tests/system tests to reflect the multi-VO setup. E.g. see comment in https://github.com/DIRACGrid/DIRAC/pull/4625#discussion_r432546746

Tagging the usual suspects, apologies if I have forgotten anyone. 
@sfayer @fstagni @chaen @andresailer @chrisburr @atsareg @IgorPelevanyuk

**Comment by marianne013** [comment]
Is there any reasons for the 2k's worth of ddavids in the users in dteam ? It always makes my browser hang.
I removed the VirtualOrganization in order for the UI to configure both VOs.
I had to specifically allow  dirac-admin-allow-se UKI-LT2-IC-HEP-disk for my upload test to work (we don't do that at GridPP, so that was a guess).
lxplus750:v7r1p14 :~] dirac-admin-allow-site LCG.UKI-LT2-IC-HEP.uk "enable for multiVO testing"
Site LCG.UKI-LT2-IC-HEP.uk is already Active
surprised me a bit, as we do it the opposite way around ;-)
I have a SiteDirector dilemma though. We use different SiteDirectors for different VOs, but I don't know if that is necessary. I tried just to add Imperial to the current site director, but in the pilot log I see:
"""
2020-10-15 12:57:35 UTC WorkloadManagement/SiteDirector VERBOSE: Evaluating queue ceprod00.grid.hep.ph.ic.ac.uk_ceprod00.grid.hep.ph.ic.ac.uk-condor
2020-10-15 12:57:35 UTC WorkloadManagement/SiteDirector VERBOSE: Skipping computing element: resource not usable ceprod00.grid.hep.ph.ic.ac.uk at LCG.UKI-LT2-IC-HEP.uk
"""
Not sure what to make of this ?

**Comment by andresailer** [comment]
I think the ceprod00 (etc.) needs to be enabled in the RSS, at least it isn't active at the moment. For example via the "Resource Summary" webapp setStatus -> Active (but there could be other things missing...).

**Comment by marianne013** [comment]
I didn't know you could do that. So I did and now the job fails with 
Failed to setup proxy: Error retrieving proxy
Looking at the proxy manager, I seem to have one proxy with dteam_user attached to it and one without anything. Any guesses ?

**Comment by andresailer** [comment]
With the new proxy management there is just one proxy without any group in the system. Once the Proxy is downloaded a group is added.
There is an error message in the ProxyManager that points towards dteam gridpp VO mixtures

**Comment by marianne013** [comment]
On our DIRAC we also have different submitpools for the different VOs. Do you know if this is necessary ? Because our config is so old I don't know which bits are compulsory. I managed to upload a file, but I guess that goes with the local proxy not the one on the server.

**Comment by marianne013** [comment]
I just realized the pilot was submitted as dteam pilot and then tried to run my gridpp job, bah.

**Comment by andresailer** [comment]
I pinged you on slack, which might be faster back and forth

**Comment by atsareg** [comment]
The SubmitPools should not be necessary any more. The pilot's VO is determined from the pilot group in the Matcher and only jobs from groups of the same VO are considered.

**Comment by atsareg** [comment]
Actually, the SubmitPool is not now put into the job description, so it can be scrapped from the VO configuration as well.

**Comment by marianne013** [comment]
No, here's my jdl:
lxplus750:v7r1p14 :~] cat dummy.jdl 
[
Executable = "/usr/bin/date";
StdOutput = "job.log";
StdError = "job.log";
OutputSandbox = "job.log";
Site = "LCG.UKI-LT2-IC-HEP.uk";
JobName = "DiracTest";
]

Andre mumbles something about  /opt/dirac/pro/etc/dirac.cfg on the server, but I can't see that file.

**Comment by andresailer** [comment]
@chaen 
I think we need to remove /DIRAC/VirtualOrganization from the server dirac.cfg
https://gitlab.cern.ch/ai/it-puppet-module-dirac/-/blob/qa/code/templates/diraccertif.cfg.erb#L31

**Comment by marianne013** [comment]
I thought the RSS wasn't really multi-VO, so I have no experience with this. After a suggestion from Andre I enabled my CEs in the web interface  and my SE by  using allow-se, but now I get a message every hour stating things like:
EXPIRING tokens ( RSS will take control of them )
dbauer Resource ceprod00.grid.hep.ph.ic.ac.uk all Active 2020-10-16 13:17:21
or
EXPIRING tokens ( RSS will take control of them )
dbauer Resource UKI-LT2-IC-HEP-disk CheckAccess Active 2020-10-16 12:37:05

How do I make that stop and tell the system that this stuff is ON and will stay ON ?

**Comment by andresailer** [comment]
In the Resource Summary, Right Click -> Set Token -> Release

**Comment by andresailer** [comment]
Removing `/DIRAC/VirtualOrganization` from the dirac.cfg solved the problem of the wrong VO showing up in the JDL.

Now need to install one SiteDirector per VO

**Comment by andresailer** [comment]
Manually copied the vomses and vomsdir for gridpp to the server.
Pilots are now being submitted with the proper group, and jobs successful.

**Comment by marianne013** [comment]
In summary, with Andre's help I was now able to submit jobs as dteam and as gridpp user. I can also upload files to my SE as a user of each VO. Unfortunately the RSS seems to have taken offence to my SE, so I had to reactivate it by hand, but this is beyond the scope of this issue. I guess both Andre and Andrei should be able to submit jobs as gridpp and dteam user now. The Imperial SE is enabled for both VOs.

**Comment by fstagni** [comment]
I think by now all the bullets in this task are done, aren't they? So I propose to close this one.

**Comment by marianne013** [comment]
You are right, this is probably as good as it gets,
