### ISSUE TITLE
[TODO] Force the socket closing in M2SSLTransport

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#4649]
m2Crypto's socket closing is not optimal to say the least. 
I've reported the issue (https://gitlab.com/m2crypto/m2crypto/-/issues/278) and done the MR upstream (https://gitlab.com/m2crypto/m2crypto/-/merge_requests/247)
In the meantime, I have implemented mitigation, but it is not bullet proof (https://github.com/DIRACGrid/DIRAC/pull/4642)

Once this get merged, we should use that

**Comment by fstagni** [comment]
I guess this can be closed now...? @chaen can you confirm?

**Comment by chaen** [comment]
yep
