### ISSUE TITLE
Does the FileCatalog SEManager(DB) need a periodic task calling refreshSEs?

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRAC#4653]
As far as I can tell the refreshSEs function is only called at startup or via __addSE, but that doesn't seem sufficient to synchronize across multiple FC services?

https://github.com/DIRACGrid/DIRAC/blob/8e7126c671d420a1eb091109fe26f5a24927f7bc/DataManagementSystem/DB/FileCatalogComponents/SEManager/SEManagerDB.py#L16

Should it be called periodically? Or is this triggered in some other way?

**Comment by chaen** [comment]
What branch are you looking at ? It used to be triggered by this insane `getSEPrefix` that was doomed  in v7r1 (https://github.com/DIRACGrid/DIRAC/issues/4227). 
In fact, it is enough to have it in `__addSE`, because when trying to get the `SEID`, if the `SEManager` does not find it in it's cache, it will always call `__addSE`, which would fail on duplicate entry if already inserted, but it's fine, because it's handled.....
The only "problem" is `FileMetadata.py` trying to access directly `db.SENames` but well....

**Comment by andresailer** [comment]
Thank you for the explanation! I am looking at v6r22. (also v7r0)

In v6r22 the sbDefinition was still present, so not only information from the DB was in that SEManager, but in v7r1 this is all gone, and it just contains SEName and SEID, so indeed nothing needs to be refreshed unless an SE is added.

**Comment by andresailer** [comment]
Added a new SE, uploaded a file to the SE. Tried downloading the file again.

Failure if the selected FileCatalog service wasn't the one that was used to upload the file.
Also for example:
```
2020-07-15 10:34 sailer@pclcd50:~$ dirac-dms-lfn-replicas /ilc/user/s/sailer/testSlac.test
LFN                              StorageElement URL
===================================================
/ilc/user/s/sailer/testSlac.test SLAC02-DISK    /ilc/user/s/sailer/testSlac.test

2020-07-15 10:34 sailer@pclcd50:~$ dirac-dms-lfn-replicas /ilc/user/s/sailer/testSlac.test
LFN                              StorageElement URL
```


I think in this case addSE is not called

https://github.com/DIRACGrid/DIRAC/blob/9a324b9406094b989fb64f90e2011ea301ea8f7d/DataManagementSystem/DB/FileCatalogComponents/FileManager/FileManager.py#L749-L758

Because getSEName only does:
https://github.com/DIRACGrid/DIRAC/blob/9a324b9406094b989fb64f90e2011ea301ea8f7d/DataManagementSystem/DB/FileCatalogComponents/SEManager/SEManagerDB.py#L121-L124


So in this the getSEName function we should probably call refreshSEs?

**Comment by andresailer** [comment]
Solved (I hope )
