### ISSUE TITLE
Update CODEOWNERS

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRAC#4662]
I don't know who is now responsible but the code owners for `AccontingSystem/` and `MonitoringSystem/` should probably be updated:

https://github.com/DIRACGrid/DIRAC/blob/da6eb9cb104140596df11746c0c517c80afa395e/.github/CODEOWNERS#L17-L18

**Comment by fstagni** [comment]
I guess me... at least for MonitoringSystem.

**Comment by fstagni** [comment]
In #4669
