### ISSUE TITLE
[v6r22] TLS protocol used by DIRAC

### ISSUE THREAD

**Issue by hmiyake** [DIRACGrid/DIRAC#4675]
Recently our vulnerability scanner started to warn us that DIRAC uses cipher suites may be used with SSLv3.
Specifically following cipher suites were pointed out:
AES128-SHA, AES256-SHA, CAMELLIA128-SHA, CAMELLIA256-SHA

Suggested solution is to use TLS 1.2.
We were then requested to take any action to solve the issue.

Our DIRAC release is v6r22, thus we use pyGSI.
As far as I checked, TLS 1.0 is designated in DIRAC/Core/DISET/private/Transports/SSL/SocketInfo.py

methodName = "TLSv1_%s" % ( methodSuffix )

with

contextOptions |= GSI.SSL.OP_NO_SSLv2 | GSI.SSL.OP_NO_SSLv3

Therefore we always use TLS 1.0.
Please correct me if I'm wrong.

We wonder if you agree to switch to TLS 1.2 (or at least 1.1) in the code.
Or can we switch TLS protocol by configuration?

If we migrate to v7r0 and use M2Crypto,
DIRAC/Core/DISET/private/Transports/SSL/M2Utils.py

    # SSL_OP_NO_SSLv2, SSL_OP_NO_SSLv3, SSL_OP_NO_TLSv1

Therefore TLS protocol is not 1.0, at least.
In this case, which TLS protocol is chosen, 1.1 or 1.2?

**Comment by chaen** [comment]
Pfiou... that's a tough one. 
Using anything different with pyGSI than the existing default is uncharted territory. And the original code base of pyGSI is so old (early 2000) that TLS > 1.0 were only starting. I can see traces of v1.1 and v1.2 in the code, but have no idea how sound there. 
So for these reason, I am not in favour of changing the default in the code. 
Making it a configuration option would be possible, but it would probably have to be an environment variable. 

For M2Crypto, which is still not 100% working unfortunately (smoothing being finished), it should be using the highest possible, and this depends on the openssl version underlying. I don't have that in the top of my head, but you can easily see that if you sniff the traffic and look at the client/server hello handshake

**Comment by chaen** [comment]
I've just done a test, here is the result:
```
| Client  | server |
| M2      | M2      | TLSv1.2
| M2      | pyGSI | TLSv1
| pyGSI | M2      | TLSv1
| pyGSI | pyGSI | TLSv1
```

**Comment by fstagni** [comment]
Shall we then simply say that "upgrade to v7r0 and use M2Crypto" is the (non-exact) solution to this thread?

**Comment by hmiyake** [comment]
Thank you for the information! I'm informing them to our cybersecurity team (with our migration status and plan...)
I hope the plan "upgrade to v7r0 and use M2Crypto" is accpeted.

**Comment by chaen** [comment]
Apparently it is still a problem for BelleII as we still accept `TLSv1`, although we do not use it.
@hmiyake can you please try the changes here: https://github.com/DIRACGrid/DIRAC/pull/4961  and do `export DIRAC_M2CRYPTO_SSL_METHODS=TLSv2:TLSv3` ?

**Comment by chaen** [comment]
Fixed in https://github.com/DIRACGrid/DIRAC/pull/4967
