### ISSUE TITLE
WebAppDIRAC version in __init__.py

### ISSUE THREAD

**Issue by iueda** [DIRACGrid/DIRAC#4689]
releases.cfg tells WebAppDIRAC:v4r0p26 for v7r1p7 and v7r0p29, and WebAppDIRAC:v4r0p22 for v6r22p32.

I see only v4r0p17 in the code: https://github.com/DIRACGrid/WebAppDIRAC/blob/rel-v4r0/__init__.py
```
majorVersion = 4
minorVersion = 0
patchLevel = 17 
preVersion = 0
```

Is this just the patchLevel not updated in the __init__.py, and the newer releases include newer codes?

**Comment by atsareg** [comment]
Yes, this is not automatic and was forgotten to be updated by hand. I will correct for that.

**Comment by fstagni** [comment]
Looks corrected to me.
