### ISSUE TITLE
 Stage out retry and how do I test this ? 

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#4694]
Moved from https://groups.google.com/forum/#!topic/diracgrid-forum/qVwwNnGWAXs

@marianne013 :
> I would like to implement a retry for the file stage out at the end of a job (OutputData). At the moment it tries once and then tries a fall back SE[*]. We have users without a failover SE (can this be even done by VO? As a job parameter?) and we've have seen stage outs fail due to short interruptions (read: reboot of a disk server) on the target SE.
I'd be happy to make that configurable and set the default to no retry, but ideally I would like it to try at least twice on the target SE, preferably with a 5-10 min sleep in between before giving up on it.
Which leads me to my next question: How could I test this ? I thought of putting the code in a git repo and then get the pilot to do the dirac-install from this (my) git repo, but I can't work out if (and if so how) I could set this in the ConfigurationSystem. (This is against v7r1 and Pilot3).
[*]WorkloadManagementSystem/JobWrapper/JobWrapper.py

@andresailer 

>I am not entirely sure which code path is taken in your case...
>
>Is it here:
>https://github.com/DIRACGrid/DIRAC/blob/integration/WorkloadManagementSystem/JobWrapper/JobWrapper.py#L914
>
>Because there was a retry added for FC problems
>
>https://github.com/DIRACGrid/DIRAC/pull/4528
>
>it should be fairly straight forward to allow retry for other cases as well.
>
>I guess one can  make the failover SEs VO dependent
>https://github.com/DIRACGrid/DIRAC/blob/integration/WorkloadManagementSystem/JobWrapper/JobWrapper.py#L127
>
>Testing:
>
>ExtraPilotOptions with --modules ?
>
>https://dirac.readthedocs.io/en/latest/AdministratorGuide/Configuration/ConfReference/Resources/Computing/index.html?highlight=ExtraPilotOptions#general-parameters
>
>https://github.com/DIRACGrid/Pilot/blob/master/Pilot/pilotTools.py#L543
>
>https://dirac.readthedocs.io/en/latest/AdministratorGuide/CommandReference/dirac-install.html?highlight=module

@marianne013 

>It's true I had not seen the file catalog error retry. Is there any reason other errors were excluded at that point (if result['OK'] or not cmpError(result, EFCERR))?
>That's probably a question for Chris.
>
>As for testing, I don't think the module option would work, as it's core DIRAC, or is there a specific syntax for it ? (Or do I have to write a module ?)
>Of course even generating temporary error conditions is a bit tricky, but we'll cross that bridge when we get to it.
>
>I had a look at the error codes, but I am not sure if there are actually suitable ones for everything. But I can't see the harm in retrying any error, it wastes a bit of CPU if .e.g. you run into a permissions issue, but it's such small fry that I wouldn't worry.
>
>So instead of:
>if result['OK'] or not cmpError(result, EFCERR):
>only break on result['OK']
>
>It seems to already log the error (self.log.verbose(result))) if we changed that to a higher level on failure, that should work, no ?

> While I am asking, is there a way for a user to specify a failover SE ?

**Comment by chaen** [comment]
For the retry part, you opened https://github.com/DIRACGrid/DIRAC/pull/4693 so we can discuss the details there, but I think there is no problem in retrying. Note that a trick to retry consists in repeating several time the same SE in a failover list, it is not factorized :-) 

>  Is there any reason other errors were excluded at that point 

This specific error was caught here because if the FC does not even answer to `hasAccess`, you have no way to know where you can even attempt to write. So you could not even upload to a failover SE. Hence waiting is what made the most sense. For the other cases, we considered that the failover system (in general, not only the failover SEs) was good enough

>     While I am asking, is there a way for a user to specify a failover SE ?

I am always a bit confused when you talk about "users". Do you mean the real end user submitting a job, or the super user for a given VO ? 

At the moment, at pointed at by Andre, it is quite static, but could easily be made VO dependant. In fact, in LHCb, we have a module (https://gitlab.cern.ch/lhcb-dirac/LHCbDIRAC/-/blob/master/LHCbDIRAC/Core/Utilities/ResolveSE.py) which allows for a more dynamic resolutions of SEs, which can prioritize depending on Countries, Site you are running on, etc. Since ILC is also using this module, and it is really useful, I intended to port that to vanilla DIRAC. So VO could also enter as a parameter in it.
However, all that is defined in the CS level. 

If you want the user to define that, I am not so sure where this would need to be done. Probably similar to the OutputSE :
https://github.com/DIRACGrid/DIRAC/blob/41c6ed285bd34ab573caa3651f3aa63d6c3df87b/Workflow/Modules/UploadOutputs.py#L59-L65
https://github.com/DIRACGrid/DIRAC/blob/integration/Interfaces/API/Job.py#L396

However, I fail at seeing the interest of a user specifying this ? This type of storage is more of an infrastructure and operational trick to make sure that the file reaches its final destination (specified or not in `outputSE`). The users do not need to know about it really.

**Comment by fstagni** [comment]
IIUC this issue can be closed. Please correcte me if I am wrong.
