### ISSUE TITLE
PilotCSToJSONSnchronizer is not thread safe

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#4697]
We observed a race condition where the `commitNewData` method from the CS was called twice, in a short amount of time, the first one being still ongoing when the second one started. Of course, that does not work. 

Two options: 
* lock the `commitNewData` method https://github.com/DIRACGrid/DIRAC/blob/41c6ed285bd34ab573caa3651f3aa63d6c3df87b/ConfigurationSystem/Service/ConfigurationHandler.py#L72
* lock the `sync` method https://github.com/DIRACGrid/DIRAC/blob/41c6ed285bd34ab573caa3651f3aa63d6c3df87b/WorkloadManagementSystem/Utilities/PilotCStoJSONSynchronizer.py#L73

One more option, and probably my favourite one: go back to an agent doing the work, instead of triggering from the CS. Much less error prone...
 
Opinions ?

**Comment by fstagni** [comment]
Locking the `commitNewData` would probably be a good idea independently of this issue. @atsareg what do you think?

**Comment by chaen** [comment]
We need to move on with this. If no objection/reply, I'll do it next week

**Comment by fstagni** [comment]
Which solution?

**Comment by fstagni** [comment]
I coded first stub here: https://github.com/DIRACGrid/DIRAC/compare/integration...fstagni:v7r2-useAgentForCSPilot

Please have a look.

**Comment by fstagni** [comment]
I believe this can be closed now.
