### ISSUE TITLE
Merge methods in FailoverTransfer

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#4700]
These two methods should be merged together:
 https://github.com/DIRACGrid/DIRAC/blob/41c6ed285bd34ab573caa3651f3aa63d6c3df87b/DataManagementSystem/Client/FailoverTransfer.py#L66
https://github.com/DIRACGrid/DIRAC/blob/41c6ed285bd34ab573caa3651f3aa63d6c3df87b/DataManagementSystem/Client/FailoverTransfer.py#L154

They largely overlap, and having them as a single method would allow for more clever retry mechanism. 
Triggered by https://github.com/DIRACGrid/DIRAC/pull/4699)

**Comment by fstagni** [comment]
`transferAndRegisterFileFailover` already calls `transferAndRegisterFile`. If they need to be merged, the `transferAndRegisterFile` would be the one merged in `transferAndRegisterFileFailover`.

**Comment by chaen** [comment]
why ? I'd keep that one opened. Indeed it's not planned, but it would still be nice to have :-/

**Comment by fstagni** [comment]
It opened in 2020, and "it does not seem urgent". We have many other important things to concentrate on, this does not look like one of them. But you are keen on it, re-open it.
