### ISSUE TITLE
FTS3Agent could fetch same unavailable FTS3Operations in each cycle

### ISSUE THREAD

**Issue by hmiyake** [DIRACGrid/DIRAC#4727]
In FTS3Agent, non finished FTS3Operations are fetched in treatOperationsLoop().

Recently we realized no new job was submitted after we banned write access of one destination SE, while we have many requests for other SEs.

Here is our guess:
1. the number of Operations relevant to the SE exceeded OperationBulkSize
2. All Operations are skipped since write access is banned
3. 2 happens in each loop and no new job is submitted

We increased OperationBulkSize to escape the infinite loop at that time.
However, it is convenient if FTS3Agent can automatically overcome this issue... for example compensate skipped Operations (retrieve more Operations) or make offset like TransformationClient.getTransformationFiles() to check all registered Operations

What do you think?

**Comment by andresailer** [comment]
Maybe it is enough to add an `ORDER BY lastUpdate ASC` to the `FTS3DB.getNonFinishedOperations` function?
Similar to
https://github.com/DIRACGrid/DIRAC/blob/34c753dc0cd827d7df262cd1989bc7adfbb05f1c/DataManagementSystem/DB/FTS3DB.py#L301

I think this would then cycle through all the operations, as lastUpdate is updated during the treatment. 

@chaen could maybe comment if OperationBulkSize was meant to limit the number of operations passed to the FTS server, or if everything should be submitted.

**Comment by chaen** [comment]
I think there is no perfect solution, because if you have such a big imbalance, and order by `lastUpdate` you will spend your time submitting transfers, but wait very long for them to be registered. I do think however that this is the least bad option. 

An alternative is to retrieve the operations in a random order (https://dev.mysql.com/doc/refman/5.6/en/mathematical-functions.html#function_rand `SELECT * FROM tbl_name ORDER BY RAND();`) but I don't like that idea.

The OperationBulkSize was to limit the number of operations treated by an FTS3Agent at once. This allows to block a minimal number of operations in case of crashes, but also to have multiple FTS3Agents in parallel !

**Comment by andresailer** [comment]
Using UNION (https://dev.mysql.com/doc/refman/5.7/en/union.html) to union two selects, one for 'Processed' one for 'Active'?
(The operation status gets updated by the monitor of the jobs, right?)
Or just a loop over the status and calling SELECT twice.

Then one could prefer treating the 'Processed' operations, or ensure some mixture.

**Comment by chaen** [comment]
No, the `Processed` state is normally only transient and does not make it to the DB. It is set when we monitor the operations, and realize that nothing is to be done anymore. Then we trigger the callback of the operation (i.e. update the RMS Request to add the registration operation). If there is a problem with the callback, then the `Processed` state makes it to the DB. But it should be a very rare case.

**Comment by andresailer** [comment]
I see, then nothing to be done except sorting.
@hmiyake  will you try implementing what I propose above https://github.com/DIRACGrid/DIRAC/issues/4727#issuecomment-681790524?

**Comment by hmiyake** [comment]
@andresailer , @chaen, thank you for the advices!
I'm testing the proposed patch on our DIRAC server...looks working!
Yes, let me make the PR later.

**Comment by fstagni** [comment]
@hmiyake just a reminder for the PR.

**Comment by fstagni** [comment]
Merged in DIRAC v6r22p34
