### ISSUE TITLE
v7r1: dirac-config has issue if certificates are read only

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#4734]
When testing the latest changes on our cloud we came across this error:
"""
Could not import BundleDeliveryClient
Traceback (most recent call last):
  File "/mnt/dirac/DIRAC/Core/scripts/dirac-configure.py", line 400, in <module>
    result = bdc.syncCAs()
  File "/mnt/dirac/DIRAC/FrameworkSystem/Client/BundleDeliveryClient.py", line 91, in syncCAs
    result = self.syncDir("CAs", casLocation)
  File "/mnt/dirac/DIRAC/FrameworkSystem/Client/BundleDeliveryClient.py", line 77, in syncDir
    tF.extract(tarinfo, dirToSyncTo)
  File "/mnt/dirac/diracos/usr/lib64/python2.7/tarfile.py", line 2118, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/mnt/dirac/diracos/usr/lib64/python2.7/tarfile.py", line 2202, in _extract_member
    self.makelink(tarinfo, targetpath)
  File "/mnt/dirac/diracos/usr/lib64/python2.7/tarfile.py", line 2279, in makelink
    os.unlink(targetpath)
OSError: [Errno 30] Read-only file system: '/mnt/dirac/etc/grid-security/certificates/01b5d333.0'
"""
It then happily continues, so it's more annoying than datal.

**Comment by atsareg** [comment]
Hi Daniela, the BundleDelivery client attempts to update the certificates synchronizing them with the reference DIRAC BundleDelivery service. In your case, the certificates directory is most likely managed by the standard LCG tools and not under the DIRAC responsibility. In this case, there is a flag -D to be given to the dirac-configure command to skip this syncing.

**Comment by marianne013** [comment]
Hi Andrei, we noticed that on our cloud. Presumably the certificates are present because we install CERN VM. But I don't think we can this always taken as a given, so we can't run with -D by default. Wouldn't it be better to catch the error and just proceed along the lines of:
"certificates are read only, not synching"

**Comment by fstagni** [comment]
> Hi Andrei, we noticed that on our cloud. Presumably the certificates are present because we install CERN VM. But I don't think we can this always taken as a given, so we can't run with -D by default. Wouldn't it be better to catch the error and just proceed along the lines of:
> "certificates are read only, not synching"

I think it would make sense.
