### ISSUE TITLE
dirac-dms-put-and-register-request and dirac-dms-add-file

### ISSUE THREAD

**Issue by Priyaa140624191** [DIRACGrid/DIRAC#4754]
I have a question regarding registering file without using dirac-dms-add-file because of the size of the file (1 TB) and dirac-dms-add-file breaks for longer files. So, I have gfal-cop(y) ied a local file to pfn and registered using “register” command. It is working fine. 
But I have following questions:
    1. Is there a dirac command that combines the functionality of gfal-copy and register? 
    2. Would like to know the difference between dirac-dms-put-and-register-request and dirac-dms-add-file? 
    3. I got to know about dirac-dms-put-register-request, and submitted the request, but keeps on waiting even for a small file(assuming it does the functionality, also there is no clear documentation about this as  far as I am aware). It would be great if anyone could clarify this.

Here is the request status (uses dirac-rms-request) for a request 'req1' which I submitted using dirac-dms-put-and-register-request:
 
dirac-rms-request req1
Request name='req1' ID=319813 Status='Waiting'
Created 2020-10-06 11:48:41, Updated 2020-10-06 11:48:41, NotBefore 2020-10-06 11:48:41
Owner: '/C=UK/O=eScience/OU=Manchester/L=HEP/CN=priyaa thavasimani', Group: skatelescope.eu_user
  [0] Operation Type='PutAndRegister' ID=290706 Order=0 Status='Waiting'
      TargetSE: UKI-NORTHGRID-MAN-HEP-disk - Created 2020-10-06 11:48:41, Updated 2020-10-06 11:48:41
    [01] ID=17727 LFN='/skatelescope.eu/user/p/priyaa.thavasimani/ramdom.txt' Status='Waiting' Checksum='01b700bc'

**Comment by andresailer** [comment]
1. Yes, that command _is_ dirac-dms-add-file
How does it break, what does it say when you add the "-ddd" flags?

2. dirac-dms-put-and-register-request creates a putAndRegister request. 
  Documentation is in the usual location:
  https://dirac.readthedocs.io/en/latest/UserGuide/CommandReference/DataManagement/dirac-dms-put-and-register-request.html
  the same information comes from "--help"
  This makes the RequestManagement system try to execute the upload for you, but for put and register to work it would need  access to the local file (local to the server!), which it probably doesn't? (This is also indicated in the documentation)

3. Why it is waiting would be a question for the dirac admins of your instance.

4. In what way is the documentation mentioned above lacking or unclear? Or could it not be found in the first place?

**Comment by Priyaa140624191** [comment]
Thanks for the comment. 
1. I executed the dirac-dms-add-file command longtime ago for transferring 1.3 TB dataset. I got the very long error message after waiting 3 days for the completion of the task. I am pasting portion of the same below which I assume to. be root cause of the issue:

```
dirac-dms-add-file/DataManager/putAndRegister` [140464623257408] DEBUG: Failed to put file to Storage Element. 1523464709_sdp.ms.tar.gz: Permission denied ( 13 : Failed to copy file 1523464709_sdp.ms.tar.gz to destination url root://bohr3226.tier2.hep.manchester.ac.uk:1094//dpm/tier2.hep.manchester.ac.uk/home/skatelescope.eu/skatelescope.eu/user/p/priyaa.thavasimani/MeerKAT_DataSets/1523464709_sdp.ms.tar.gz: [13] [gfalt_copy_file][perform_copy][gfal_xrootd_3rd_copy][gfal_xrootd_3rd_copy_bulk] Error on XrdCl::CopyProcess::Run(): [ERROR] Server responded with an error: [3010] Unable to close file ; permission denied
)_
```
Since it is failing, I used alternative way to transfer the file with gfal-copy and register. Back to the same question, is there any dirac command that combines the functionality of gfal-copy and register?

2, 3, 4: Yes, I have seen the documentation. I managed to run the command "dirac-dms-put-and-register-request" but would be great if there is an example for the usage of the command instead of just the syntax.

**Comment by andresailer** [comment]
1. Again, that command is dirac-dms-add-file. As you can see from the error message it comes from inside gfal_copy. 
I don't (want to) know the specifics for the gfal_copy command, but I would assume it uses the same underlying library.

> "waiting three days" [...] "permission denied"

Is the upload speed noticeably different in DIRAC and directly using gfal_copy?
Did you use the gfal_copy that is part of the DIRAC externals, or a separate one?
If separate, where those the same version?
Did you use the DIRAC proxy for gfal_copy or create it in a different way?
Does dirac-dms-add-file work for smaller files that are uploaded more quickly?
Did your proxy expire during the upload?
Did you try creating a longer lived proxy?
Did you try repeatedly? maybe some hickup on the StorageElement?

I would have initially thought there was a timeout in the Dirac side, but from the error message you post this was an issue with the underlying library or the storage element.

2. 4.: what do you mean by "usage of the command"?
How to execute the command, or how it works under the hood, or how it is supposed to be used or why?

Is the file you want to upload accessible from the DIRAC server you are using?


3. What do your instance admins say about the execution of this request? is the file you want to upload visible for the server?

**Comment by fstagni** [comment]
Should this ticket need a follow up? Otherwise, I would close it.

**Comment by fstagni** [comment]
Since I got no answer to my last post, I close this ticket.
