### ISSUE TITLE
Failover job state update request in the agents 

### ISSUE THREAD

**Issue by atsareg** [DIRACGrid/DIRAC#476]
In the end of the request execution, when it is done, the corresponding job is updated to Done status as well. The latter can fail and a DISET request should be set in this case

**Comment by fstagni** [comment]
I am not sure, but I believe this is already implemented: @chaen do you know?

**Comment by chaen** [comment]
We retry 10 times with a 10s pause between each attempt.

**Comment by fstagni** [comment]
So, this is not exactly finished. `ReqClient.finalizeRequest` is the place to look.

**Comment by chaen** [comment]
Coming back to that, there is a real risk of infinite storm. And when that happens, it is quite easy to fix from the operational point of view. So I would just close that.
