### ISSUE TITLE
Singlarity CE assumes DIRAC is installed in current working directory

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRAC#4764]
https://github.com/DIRACGrid/DIRAC/blob/33edec414b997d4b8f45afdc745c421d2022e86b/Resources/Computing/SingularityComputingElement.py#L297-L301

**Comment by fstagni** [comment]
...which IS, in case DIRAC is installed inside the container (this is one of the 2 modes of operation).

**Comment by chrisburr** [comment]
But this is copying `bashrc` from the pilot's current working directory which I guess only happens if you're not using CVMFS?

**Comment by fstagni** [comment]
Yes, correct, so that's the bug. Instead pilot.cfg should always be found in the working directory.

**Comment by chrisburr** [comment]
I've started fixing this in #4773 but there is another issue. Currently all environment variables are inherited by the container, including `$DIRAC` and `$DIRACOS`. As the `bashrc` prefers the existing values:

https://github.com/DIRACGrid/DIRAC/blob/6704bf1b0894c6fbcdd7d33276c36b3596266e69/Core/scripts/dirac-install.py#L2409-L2410

I think the DIRAC installation inside the container won't be used at all?

If so, is there a reason ever wanting to install DIRAC inside the container instead of mounting the host's installation as read only?

**Comment by fstagni** [comment]
@sfayer originally coded the the installation of DIRAC inside the container, and this is the reason:

> The reason for this was mainly to make sure the version inside the
container was actually compatible with the container image. When I wrote
it, DIRACOS didn't exist and the easiest way to ensure the correct
externals were available was to do a full install.

> The paths are also different inside and outside the container: I didn't
think things would like being "relocated", so an install was much safer
than trying to fixup the locations somehow.

IIUC in GridPP the installation inside the container is still the norm...? I let @sfayer comment.

**Comment by sfayer** [comment]
Yes, we still use the "secondary installation" inside the container method for GridPP, so please leave that code path intact.

When I wrote the original code, I was dubious of bind mounting anything to a host-defined path: This didn't work in some cases where the mount point didn't already exist in the container image (particularly in user namespace mode). I've just tested this again and it appears this is working in the newest singularity version, so it seems they may have fixed it now (at least on the config on our WNs at Imperial).

**Comment by chrisburr** [comment]
> Yes, we still use the "secondary installation" inside the container method for GridPP, so please leave that code path intact.

I'm not convinced this code path actually works as `$DIRAC` and `$DIRACOS` are already set. Am I missing something?

> When I wrote the original code, I was dubious of bind mounting anything to a host-defined path: 

Yeah this is one of the big reasons to only support Singularity 3. (I'm not sure how import user namespaces for this.)

**Comment by sfayer** [comment]
I suspect it's that we're still running a version <v7 inside the container with the older bashrc that overwrites the DIRAC/DIRACOS variables perhaps? @marianne013 may be able to remember what combinations of versions we've actually tested with our v7 testbed...

**Comment by marianne013** [comment]
There are too many variables involved. At the moment we run v7r1p13 for DIRAC, the pilots are apparently the same version (at least in the ConfigurationSystem) and we use v2r4p8 for VMDIRAC. I didn't see any local modifications on the server, so it should be the same as in git. 
Of course there are some dubious non-versioned bits in cloudinit:
if [ -f /cvmfs/dirac.egi.eu/pilot/pilot.tar ]; then
       tar xf /cvmfs/dirac.egi.eu/pilot/pilot.tar

**Comment by chrisburr** [comment]
In that case, how about 93bdf72?

**Comment by sfayer** [comment]
That seems reasonable to me.
