### ISSUE TITLE
Fix setuptools installation

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRAC#4774]
Currently `pip install` results in the scripts like `dirac-proxy-init` being installed as `dirac-proxy-init.py`. This is relatively simple to fix in the `setup.py` file however there is still a deeper issue when using extensions. In LHCbDIRAC the `dirac-dms-add-file` script is overridden and when `pip installing` both DIRAC and LHCbDIRAC, the installations will overwrite each other's files making it "random" as to which one is available.

The "correct" solution is probably to use [`entrypoints`](https://amir.rachum.com/blog/2017/07/28/python-entry-points/).

(See also https://github.com/DIRACGrid/DIRAC/issues/3523)

**Comment by chrisburr** [comment]
@andresailer @atsareg @chaen @remenska @fstagni @sfayer and anyone else who's possibly interested.

I've written down a proposal for how properly integrate DIRAC with setuptools [at this link](https://www.notion.so/Ideas-for-integrating-DIRAC-with-setuptools-106d461ad8fb444d96300a4c7b6d7cf8). Feedback would be particularly useful for the "Duplicated entrypoints" section and the handling of multiple VOs/extensions. If there are no strong objections, I'll open a PR at the beginning of next week with the initial implementation.

**Comment by fstagni** [comment]
I'll bring this up at tomorrow's BiLD meeting. @chrisburr you can briefly go through the points there, then we'll all need to do the homework anyway.
