### ISSUE TITLE
Token authorization for notebook.egi

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRAC#4779]
@TaykYoku opened a PR to the dirac-grid package on conda-forge to add a script which appears to be somehow related to using DIRAC from Jupyter: https://github.com/conda-forge/dirac-grid-feedstock/pull/32 As far as I'm concerned the recipe on conda-forge should only contain details related to packaging/installation and even those details should find their way back to `DIRACGrid/DIRAC` where possible. The options for solving Andrii's problem are therefore (roughly in order of my preference):

1. Add `dirac-notebook-proxy-init` to vanilla DIRAC
2. EGI uses a workaround in the notebooks/instructions for now, using something like:
```python
# Workaround until vanilla DIRAC supports OAuth authentication (probably v7r3)
!wget https://egi.something/something/dirac-notebook-proxy-init.py && chmod +x dirac-notebook-proxy-init.py
```
3. EGI create their own conda channel for distributing patched releases of DIRAC. The simplest way to do this would be to sign up to https://anaconda.org, build the binaries locally and then upload them.

**Comment by atsareg** [comment]
Point taken. Is it possible however to add COMDIRAC and VMDIRAC packages to the dirac conda environment ?

**Comment by chrisburr** [comment]
> Is it possible however to add COMDIRAC and VMDIRAC packages to the dirac conda environment ?

It definitely though I suggest moving that discussion to a separate issue: https://github.com/DIRACGrid/COMDIRAC/issues/72

**Comment by fstagni** [comment]
Honestly, I thought that COMDIRAC was running un-maintained. Is it really used (and useful)? (yes, I had this question before).

**Comment by TaykYoku** [comment]
As a quick workaround, I added a couple of lines to the docker file in [EGI-Foundation](https://github.com/EGI-Foundation/egi-notebooks-images/pull/24).

There is one question, as stated in the comments:

> Could you check the DIRAC installation as it seems to be broken in the last build: https://travis-ci.org/github/EGI-Foundation/egi-notebooks-images/builds/737454093#L4530
> 
> We removed the test notebook on the last PR, but it would be good to get it back: [a45b042](https://github.com/EGI-Foundation/egi-notebooks-images/commit/a45b04204328388912dd52584d4c4ac9b155fcb0)

Сould not this lead to changes in the ["Update and m2crypto" PR in conda feedstock](https://github.com/conda-forge/dirac-grid-feedstock/pull/31), perhaps a new version of the release?

**Comment by atsareg** [comment]
@fstagni: COMDIRAC is maintained by Pierre Gay from the Bordeaux University. It is working nicely and for an average user it is much nicer than dirac-XXX commands. Outside LHCb I think it is rather used,  at least the tutorials are mostly done with it.

**Comment by fstagni** [comment]
I think this one can be closed. It's referenced in https://github.com/DIRACGrid/COMDIRAC/issues/72 and does not affect directly vanilla DIRAC, IIUC.
