### ISSUE TITLE
ARC: countpernode needed for multiprocessor jobs?

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRAC#4785]
For the ARC CEs, along with 
https://github.com/DIRACGrid/DIRAC/blob/e5e05dc4538878cc8e315d78fbc0db89e43e4e40/Resources/Computing/ARCComputingElement.py#L169

Do we also need `countpernode` to require the slots to be on the same node?
http://www.nordugrid.org/documents/xrsl.pdf
> [countpernode] [s]pecifies amount of sub-jobs per node to be submitted for parallel tasks. Note: The count attribute must be specified when this attribute is specified.

vs. `count`
> Specifies amount of sub-jobs to be submitted for parallel tasks

**Comment by rajanandakumar** [comment]
From discussion with the ATLAS experts on this (David Cameron and Andrej Filipcic) : 

- count is the number of cores the job asks for in the batch system
- countpernode is the number of cores per node, so assuming you want to run on a single node set this to the same as "count"
- memory is per core, i.e. the memory requested in the batch system will be memory * count
- walltime is the clock time of the job independent of cores
- cputime is the total of all cores, i.e. set it to walltime * count

Though it is early times for DIRAC, a further useful note : Most of the sites are set for 8-core multi-core jobs. But it is better to design the submission system to respect the site and shape the jobs as the site prefers. For example some cpus are 6-core and 8-core jobs make it inefficient. Some nodes have 256 cores and 1GB mem/core and prefer 32-core jobs as a result

I am guessing we probably need to expand on the XRSL string taking the above into account ...

**Comment by fstagni** [comment]
Released.
