### ISSUE TITLE
[v7r1] MultiVO-RSS breaks interface

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#4789]
This PR https://github.com/DIRACGrid/DIRAC/pull/4720 breaks the interface of RSS.
More specifically, the `vo` information was added right in the middle of the arguments

https://github.com/DIRACGrid/DIRAC/blob/a15e06d3b1b8a479472d79519a256f8b6caf16d7/ResourceStatusSystem/DB/ResourceStatusDB.py#L183-L185

This breaks the methods relying on the order of the elements, like here

https://github.com/DIRACGrid/WebAppDIRAC/blob/b88d682bc65c6f8ce7669db0a72cbf20dad48608/WebApp/handler/ResourceSummaryHandler.py#L36-L41

Admittedly, relying on such order is not the most robust thing, but here we are.

Other part of the code are protected because they specify what column they are interested in. For example

https://github.com/DIRACGrid/DIRAC/blob/a15e06d3b1b8a479472d79519a256f8b6caf16d7/ResourceStatusSystem/Client/ResourceStatus.py#L148-L151

So there are several options:
1 Put the vo info at the end: easiest, ugliest, least breaking
2 Return an extra information containing the name and the order of the column returned (this allows to do a `zip` on the client)
3 Always query the information specifying the `meta` attribute

These options are actually not mutually exclusive. For the sake of v7r1, I would avoid breaking the interface even more so I would go for option 1.
But for v7r2, and in view of a more robust interface, I'd go with 2 AND 3. 

Any thoughts ? 

@martynia will you please take care ?

**Comment by martynia** [comment]
OK, I'll look into it.

**Comment by chaen** [comment]
No it's not equivalent, because by doing so, you break the compatibility in a patch release, including for all the extensions. 
I did not check if what I reported was the only place.

Yeah I understand why logically the VO is where it is now, unfortunately it is a breaking change, so better move it to the end :-/

**Comment by martynia** [comment]
https://github.com/DIRACGrid/DIRAC/blob/a15e06d3b1b8a479472d79519a256f8b6caf16d7/ResourceStatusSystem/DB/ResourceStatusDB.py#L183-L185

Since this toList method seems ot overwrite SQLAlchemy's object's toList is it sufficient to move `self.vo` to the end of the list thus retaining the order of the original columns?
 thanks, JM

**Comment by fstagni** [comment]
It's very likely, but I don't remember all details. Note that there are several `toList` methods.

**Comment by chaen** [comment]
@martynia and I had a phone call, where we agreed that this was the way to proceed

**Comment by fstagni** [comment]
Hopefully fixed.
