### ISSUE TITLE
runit in dirac is old

### ISSUE THREAD

**Issue by rajanandakumar** [DIRACGrid/DIRAC#4802]
Hi,

As pointed out by @marianne013 in a private email, the runit bundled within DIRAC is an old version. I am talking about the version at the link

https://dirac.readthedocs.io/en/latest/AdministratorGuide/ServerInstallations/InstallingDiracServer.html?highlight=runit#installing-runit

http://diracproject.web.cern.ch/diracproject/rpm/runit-2.1.2-1.el7.cern.x86_64.rpm

This version includes the commands "runsvctrl" and "runsvstat" commands which are apparently deprecated according to the smarden web page

http://smarden.org/runit1/

These commands do not appear in the "latest" version (?) of runit as seen on

http://smarden.org/runit/

I suppose that it is worth to update to the latest version. However, it is not completely clear to me how the above two commands will get replaced in this case.

Cheers,
Raja.

**Comment by fstagni** [comment]
The question is: is it worth updating? What do we gain?
How "newer" is the "new" runit?

**Comment by rajanandakumar** [comment]
Certainly runit is not new, but I just came to realise this. To answer your other question, certainly system administrators will be less worried!

**Comment by marianne013** [comment]
This appeared as Raja's sysadmin had installed runit-2.1.2-3.el7.centos.x86_64 which didn't contain those functions. Though I have to admit I can't quite work out if this package despite the "centos" in the name is in any way more or less official that the cern version.

**Comment by chaen** [comment]
I don't think we should update it. Too much work. 
* if you want the DIRAC sysadmin to work: use the version linked in the doc
* If you don't, use anything you like (e.g. systemd, for which we could possibly provide configuration file in the future)

**Comment by fstagni** [comment]
We also use `runsvctrl` and `runsvstat` extensively, and these command are hardcoded in several paths.

**Comment by rajanandakumar** [comment]
Should we consider shipping our version of runit with DIRAC (again)? I can imagine a system administrator saying that he is not happy to install our package as root.

I am happy with using systemd also, but presumably DIRAC will not be happy ...

**Comment by chaen** [comment]
Shipping it with DIRAC is not good because you end up mixing versions when updating (https://github.com/DIRACGrid/DIRAC/issues/3393)

And you always need a sysadmin anyway, since we need port opening for the services. 

I guess DIRAC has no problem if you run it with systemd. Just the SystemAdministrator will not work for you (but does it work reliably for anyone ? :-) )

**Comment by fstagni** [comment]
According to discussions here, and in the BiLD today, closing the issue.
