### ISSUE TITLE
Replication requests from DFC cli

### ISSUE THREAD

**Issue by sposs** [DIRACGrid/DIRAC#481]
It would be nice to be able to issue replication requests from the CLI: replicate a full set of files (content of a directory) directly. One way to deal with monitoring would be to return the request ID.

What do you think?

**Comment by chaen** [comment]
This exists, it can be closed

**Comment by atsareg** [comment]
There are commands to create replication requests already. The COMDIRAC commands can be instrumented with extra switches to generate requests rather than to perform in-line replication as well. The DFC CLI is not the right place to initiate replication of any kind
