### ISSUE TITLE
Optimizers running out of file descriptors

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#4819]
We have observed that the Optimizers sometimes run out of FD. The logs are flooded with

```
2020-11-10 08:52:09 UTC WorkloadManagement/Optimizers ERROR: Exception while selecting persistent connections
Traceback (most recent call last):
  File "/opt/dirac/pro/DIRAC/Core/DISET/private/MessageBroker.py", line 135, in __listenAutoReceiveConnections
    inList, _outList, _exList = select.select( [ pos[1] for pos in sIdList ] , [], [], 1 )
ValueError: filedescriptor out of range in select()
```

I could correlate that with the OptimizationMind rejecting connections 

```
2020-11-10 00:58:47 UTC WorkloadManagement/OptimizationMind ERROR: Error processing proposal Maximum number of connections reached. Try later
```

It is very likely that this only shows up since we migrated to M2Crypto. I would not blame it too early though, as I suspect it is rather pyGSI that took some freedoms that are not tolerated anymore. I will investigate to see if I can reproduce it and fix it. 
But frankly, I'd rather have this whole messaging business disappearing....

Dirac version: `v7r0p37`, `DIRAC_USE_M2CRYPTO=Yes`

**Comment by chaen** [comment]
I add a few more messages found in the `Optimizers` logs
`Connect error failed: Already connected `
`Connect error failed: Peer closed connection`
`Failed to reconnect. Sleeping for 5 seconds`
`Trying to reconnect to WorkloadManagement/OptimizationMind`

**Comment by andresailer** [comment]
For which DIRAC version is this?
 
This can list the number of file descriptors for each process (used for #4770)
```
for pid in [0-9]*; do echo "$(ls /proc/$pid/fd/ | wc -l) file descriptors for $pid"; done | sort -n | tail -n1
```

**Comment by chaen** [comment]
v7r0p37 (added in the bug report). 
Yeah I've done all these sorts of things. That's how I figured that it was dandling connections to the OptimizationMind.

**Comment by chaen** [comment]
Closing in favor of #5232
