### ISSUE TITLE
Use CVMFS for all dirac-install config files?

### ISSUE THREAD

**Issue by sfayer** [DIRACGrid/DIRAC#4820]
Hi,

I think dirac-install uses CVMFS to get the globalDefaults.cfg if it's available, but this file then refers back to http://diracproject.web.cern.ch/diracproject/dirac.cfg . This means that dirac-install still fails if diracproject.web.cern.ch is down (as it is today). Would it be possible for the core dirac.cfg file to be synced onto CVMFS and the CVMFS version of globalDefaults.cfg be modified to point at this file instead? The goal would be to be able to install a vanilla DIRAC client even if CERN is offline (as long as CVMFS is available on the client node).

Regards,
Simon

Tagging @marianne013 .

**Comment by fstagni** [comment]
This is a task for management: https://github.com/DIRACGrid/management/issues/10 so if you don't mind I close this task. Please comment in management one.
