### ISSUE TITLE
dirac-proxy-init silent fallback to /etc/vomses

### ISSUE THREAD

**Issue by petricm** [DIRACGrid/DIRAC#4846]
When running `dirac-proxy-init` on a very vanilla system, there is no folder `etc/grid-security/vomses` parallel to `bashrc` and no system folder `/etc/vomses` the proxy creation will fail with

```
dirac-proxy-init -o LogLevel=NOTICE --strict --rfc
Generating proxy...
Enter Certificate password:
Could not add VOMS extensions to the proxy
Failed adding VOMS attribute: VOMS Error ( 1121 : Failed to set VOMS attributes. Command: voms-proxy-init2 -cert "/tmp/x509up_u0" -key "/tmp/x509up_u0" -out "/tmp/tmp9Khb9i" -voms "lhcb:/lhcb/Role=user" -valid "23:54" -r -timeout 12; StdOut: Your identity: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=mpetric/CN=668365/CN=Marko Petric/CN=9191511650
; StdErr: Cannot find file or dir: /etc/vomses
VOMS Server for lhcb:/lhcb/Role=user not known!
)
Could not add VOMS extensions to the proxy
Failed adding VOMS attribute: VOMS Error ( 1121 : Failed to set VOMS attributes. Command: voms-proxy-init2 -cert "/tmp/x509up_u0" -key "/tmp/x509up_u0" -out "/tmp/tmp9Khb9i" -voms "lhcb:/lhcb/Role=user" -valid "23:54" -r -timeout 12; StdOut: Your identity: /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=mpetric/CN=668365/CN=Marko Petric/CN=9191511650
; StdErr: Cannot find file or dir: /etc/vomses
VOMS Server for lhcb:/lhcb/Role=user not known!
)
```

The problem is in 

https://github.com/DIRACGrid/DIRAC/blob/ea0facf13c75419772c115338280771b042b401b/Core/Security/VOMS.py#L200-L202

as DIRAC implicitly assumes the location `vomses` to be parallel to the DIRAC root. This can be solved by setting `export DIRAC_VOMSES=__some_location__/etc/grid-security/vomses` which is an optional variable of `bashrc` where it is stated

```sh
# before enabling any of these variables, please see the documentation 
# https://dirac.readthedocs.io/en/latest/AdministratorGuide/ServerInstallations/environment_variable_configuration.html
``` 

I would argue that this implicit search for `vomses` should be disabled and an error should be thrown, as we probably have now a situation where people believed that they have shipped all the `grid-security` stuff in e.g. CVMFS but in reality the local system values are used.

The user should provide all the necessary locations for `certificates`, `vomses`and `vomsdir` if not DIRAC should complain.

**Comment by chaen** [comment]
I would rather argue that there should be sensible defaults.
Also, `DIRAC_VOMSES` should go to favour the standard `X509_VOMSES` (I think `VOMS_USERCONF` is for `MyProxy` only)

**Comment by fstagni** [comment]
I would remove this line

https://github.com/DIRACGrid/DIRAC/blob/ea0facf13c75419772c115338280771b042b401b/Core/Security/VOMS.py#L202

and add one that looks for `X509_VOMSES`. And return an error (with minimal instructions) if the required variables are not set.

**Comment by chaen** [comment]
was this done or not yet ? I lost track of all these changes

**Comment by fstagni** [comment]
@petricm news on this? It's time to close v7r0 developments/patches.

**Comment by fstagni** [comment]
I believe this can be closed now.
