### ISSUE TITLE
Move integration tests under /tests

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#4859]
[from https://github.com/DIRACGrid/DIRAC/pull/4858]

> I have seen you moved tests/Utilities → src/DIRAC/tests/Utilities/
> I thought the tests directory would have not been moved.

Unfortunately it's a bit messy as some bits of test code are being imported as:

```python
from DIRAC.tests.Utilities import something
```

There are other ways of fixing this this and I'm happy to do it differently if you have a strong opinion? I think the correct solution is probably to tidy up the tests a bit but that's a task for another PR.

_Originally posted by @chrisburr in https://github.com/DIRACGrid/DIRAC/issues/4858#issuecomment-740127034_

**Comment by chrisburr** [comment]
This commit should also be reverted as part of this: https://github.com/DIRACGrid/DIRAC/pull/4867/commits/b58ff440f5fb9de2593a22d25434e7b6464dc984

**Comment by chrisburr** [comment]
Closing as agreed during today's BiLD, can be revisited in future if needed.
