### ISSUE TITLE
[v7r0] FTS3Job: multiVO bug in tapeSE check

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRAC#4878]
Inside the FTS3Agent, this function is not working for multiVO instances.

https://github.com/DIRACGrid/DIRAC/blob/6eb7c931625330e4aa4207c25a7c42c03c9c1bc3/DataManagementSystem/Client/FTS3Job.py#L215-L217

As the FTS3Agent is running without a proxy, and the FTS3Job instance is created without an active proxy the StorageElement status function says, 
```
{'Errno': 13, 'Message': 'Permission denied ( 13 : StorageElement.isValid: StorageElement is not allowed for VO)', 'OK': False, 'CallStack': ['  File "checkKekdisk.py", line 11, in <module>\n    print StorageElement(seName, vo=\'foo\').getStatus()\n', '  File "/cvmfs/clicdp.cern.ch/DIRAC/DIRAC/Resources/Storage/StorageElement.py", line 327, in getStatus\n    valid = self.isValid()\n', '  File "/cvmfs/clicdp.cern.ch/DIRAC/DIRAC/Resources/Storage/StorageElement.py", line 550, in isValid\n    return S_ERROR(errno.EACCES, "StorageElement.isValid: StorageElement is not allowed for VO")\n']}
```
and thus all SEs are considered tapeSE == True. 

Probably one can get the VO from the usergroup, if set at the time this is called. 
To be investigated next year.

**Comment by fstagni** [comment]
Released.
