### ISSUE TITLE
Core/scripts/dirac-install.py was removed

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRAC#4880]
Not sure which PR, but please put it back

**Comment by fstagni** [comment]
It was moved to /src/DIRAC/Core/scripts.

Instead of putting it back in that location we should probably find out where to fix the hardcoded location(s). **BUT**, if there's a good reason (urgent one) we can restore it _temporarily_. What's your use case?

**Comment by andresailer** [comment]
I know that is has a different place, and it should go to the DIRAC management, not just moved inside DIRAC.

But:
My CI is failing to install iLCDirac because it picks up that file.
All my docs point to this location for custom installations. 
Dirac-management images are not building.
There wasn't really any further debate following https://github.com/DIRACGrid/DIRAC/pull/4858#issuecomment-741629392 So I assume this wasn't intentional.
It isn't in Dirac Management yet (#4860)

**Comment by andresailer** [comment]
You just need to hit merge on https://github.com/DIRACGrid/DIRAC/pull/4881

**Comment by atsareg** [comment]
The Core/scripts/dirac-install.py is restored
