### ISSUE TITLE
Tests fail with hypothesis 6

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRAC#4892]
From the [release notes](https://hypothesis.readthedocs.io/en/latest/changes.html#v6-0-0):

> Using function-scoped pytest fixtures is now a health-check error, instead of a warning.

this results in the error:

> hypothesis.errors.FailedHealthCheck: src/DIRAC/Core/Security/test/Test_X509Chain.py::test_delegation[M2_X509Request-M2_X509Chain] uses the 'get_X509Request' fixture, which is reset between function calls but not between test cases generated by `@given(...)`.  You can change it to a module- or session-scoped fixture if it is safe to reuse; if not we recommend using a context manager inside your test function.  See https://docs.pytest.org/en/latest/fixture.html#sharing-test-data for details on fixture scope.
>
> See https://hypothesis.readthedocs.io/en/latest/healthchecks.html for more information about this. If you want to disable just this health check, add HealthCheck.function_scoped_fixture to the suppress_health_check settings for this test.

Example log: https://github.com/DIRACGrid/DIRAC/runs/1694028407?check_suite_focus=true

**Comment by fstagni** [comment]
@chaen you wrote these tests, would you mind taking care?

**Comment by chrisburr** [comment]
I can take care of it
