### ISSUE TITLE
Remove IRODS?

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRAC#4895]
I believe the IRODS stuff should go (together with the code). @atsareg  ?

_Originally posted by @chaen in https://github.com/DIRACGrid/DIRAC/pull/4865#discussion_r540962618_

Briefly discussed in the BiLD on 14/01/2021 with the conclusion that @atsareg should check if anyone is using it.

**Comment by atsareg** [comment]
I think iRods can be removed from DIRACOS. When we use it we use it on the server side, so it is not needed in numerous clients. On the server side it can be installed by hand specifically for this (rare) purpose

**Comment by chrisburr** [comment]
If the IRODS code is staying on DIRAC then it should be functional and not rely on hacks unless absolutely necessary. I've added it to DIRACOS2 in https://github.com/DIRACGrid/DIRACOS2/pull/23 so I'll close this.

**Comment by chrisburr** [comment]
Actually I was wrong, it turns out DIRAC is dependent on some Python bindings which are no longer maintained and don't support Python 3: https://github.com/JeromeFuselier/irodspython

At a glance the API in `python-irodsclient` is completely different so I'll open a PR to remove the code. Someone can revive it from the commit history and convert it to use `python-irodsclient` if they want to use it.

**Comment by chaen** [comment]
Yes I think that is the correct approach. It's not the first time we do it this way (e.g. the LFC)
