### ISSUE TITLE
Selectively install console_scripts

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRAC#4915]
Currently when running `pip install DIRAC` all console scripts are being installed. As we already have a `server` "extra" (i.e. `pip install DIRAC[server]`) it makes sense to only install some scripts for the server installation. It's probably better for someone more familiar with the scripts to do, any volunters?

All that needs to be done is to read the list in `setup.cfg` and edit like below app appropriate:

```diff
-    dirac-install-web-portal = DIRAC.Core.scripts.dirac_install_web_portal:main
+    dirac-install-web-portal = DIRAC.Core.scripts.dirac_install_web_portal:main [server]
```

Another thing to consider is adding more "extras" (e.g. `admin` to hide scripts which shouldn't be used by normal users).

This can also be guided by the dependencies which will be missing if the corresponding extra is not installed, i.e.

https://github.com/DIRACGrid/DIRAC/blob/d48c1e16623614d2e766600064091c9c89bc9b9d/setup.cfg#L53-L78

**Comment by chrisburr** [comment]
Any volunteers to take a look at this? I think we should do it before releasing v7r2.

**Comment by chaen** [comment]
I agree that splitting the server scripts is probably worth it, but for the admin commands it's a bit trickier. The scripts are a bit messy to say the least. 
So a `[server]` section is a good idea, I would not go for more splitting at this point in time. Maybe `[testing]`... 
if nobody objects, I will do it

**Comment by fstagni** [comment]
My attempt in https://github.com/chaen/DIRAC/pull/18
