### ISSUE TITLE
Bug in pilot submission efficiency

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#5038]
![image](https://user-images.githubusercontent.com/785576/111184391-37fd8800-85b1-11eb-9a14-8c72bf6e2393.png)

is not reflected when plotting "by Site" nor "by Site Director":

![image](https://user-images.githubusercontent.com/785576/111184521-56638380-85b1-11eb-8786-08a4c93558f6.png)

![image](https://user-images.githubusercontent.com/785576/111184542-59f70a80-85b1-11eb-8d94-ab34d72f2b05.png)

_Originally posted by @fstagni in https://github.com/DIRACGrid/DIRAC/issues/4226#issuecomment-799544362_

**Comment by hmiyake** [comment]
Summoning @yujikato

**Comment by yujikato** [comment]
Sorry for the late reply, and bug.

I could not reproduce the issue. 
In the Belle II productions running with v6r22 and certification with v7r0,
 the efficiency plot grouped by site is properly shown.

Which version did you use?

**Comment by yujikato** [comment]
I could reproduce the issue.
Let me check in detail. Sorry

**Comment by yujikato** [comment]
![image](https://user-images.githubusercontent.com/13082637/118916181-6315a680-b969-11eb-8ebb-29850e6a1b5d.png)
![image](https://user-images.githubusercontent.com/13082637/118916214-7163c280-b969-11eb-98bd-b7cfa5016ebf.png)

Fixed (quite silly bug.. sorry).

I made PR, but it is failing some test not not related with my change..  
Could you please let me know what is wrong? 
https://github.com/DIRACGrid/DIRAC/pull/5151

**Comment by yujikato** [comment]
PR made for v7r1:
https://github.com/DIRACGrid/DIRAC/pull/5152

**Comment by fstagni** [comment]
Closing as PR created.
