### ISSUE TITLE
Command line script changes

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRAC#5059]
During the build we've agreed to split #5035 into two PRs.

1. First the changes which don't change the script's themselves and only change the surrounding infrastructure. Naively I expect this PR to affect:
    * `src/DIRAC/Core/Base/Script.py`
    * `src/DIRAC/Core/Utilities/DIRACScript.py`
    * the documentation
2. After (1) is merged, the files in the `scripts` directories can be updated in a separate PR. Having this separation should also minimise the disruption to extensions as we will have tested that the changes in (1) are mostly backwards compatible.

**Comment by TaykYoku** [comment]
#5060 and #5061  was created as first part of this and ready for review.
The remaining changes will affect all scripts.

**Comment by TaykYoku** [comment]
I think first step is done and since #5060 and #5061 has been merged for a long time, I guess that this changes are mostly tested.
Looks like the #5035 - last step in this issue.
