### ISSUE TITLE
Better checking for bad X509 environment variables

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRAC#5083]
* Check /etc/grid-security/certificates isn't empty, use DIRAC defaults if needed
* Warn if the certificates are out of date

**Comment by petricm** [comment]
> Check /etc/grid-security/certificates isn't empty, use DIRAC defaults if needed

this is in principle done in `getCAsLocation` https://github.com/DIRACGrid/DIRAC/blob/e3aa6a63cafca7a621f45b36e184a63303e6b36c/src/DIRAC/Core/Security/Locations.py#L35-L63

however:
 - `X509_CERT_DIR` is read in many locations in the code from the env, I could add something in `getCAsLocation`, but e.g. dirac-proxy-init reads `X509_CERT_DIR` from the env. 
 - `X509_VOMS_DIR` is read only at one place
 - `X509_VOMSES` is read only at one place

**Comment by chrisburr** [comment]
I think the idea was that the `bashrc` (and `diracosrc` in DIRACOS2) should only accept the externally provided value for `X509_*` if it exists and is not empty.

**Comment by chaen** [comment]
> I think the idea was that the `bashrc` (and `diracosrc` in DIRACOS2) should only accept the externally provided value for `X509_*` if it exists and is not empty.

correct, that was the idea

Now, as @petricm points out, there are some inconsistent behavior in DIRAC as of how these variables are used and they could be factorized, but I propose to do this in a second step
