### ISSUE TITLE
Payload proxy renewal mechanism is screwed when using M2Crypto

### ISSUE THREAD

**Issue by atsareg** [DIRACGrid/DIRAC#5114]
The payload proxy renewal mechanism inside the pilot is screwed when using M2Crypto. The payload proxy is renewed in the thread coded in the [ComputingElement.py ](https://github.com/DIRACGrid/DIRAC/blob/54d89885089ba29205d50bee9c3bff068e1aed2d/src/DIRAC/Resources/Computing/ComputingElement.py#L388). However, the call to the ProxyManager in this case fails with RuntimeError "Proxy string no longer supported." from [here](https://github.com/DIRACGrid/DIRAC/blob/54d89885089ba29205d50bee9c3bff068e1aed2d/src/DIRAC/Core/DISET/private/Transports/SSL/M2Utils.py#L106). I guess that the problem is due to this [piece of code](https://github.com/DIRACGrid/DIRAC/blob/54d89885089ba29205d50bee9c3bff068e1aed2d/src/DIRAC/Core/DISET/private/BaseClient.py#L236). 

  What would be the right way to fix this ?

**Comment by chaen** [comment]
Do you have the stack trace of the `ProxyManager` to pinpoint exactly where the call fails ?

**Comment by chaen** [comment]
I think I found it, but I am not sure of the logic of this whole stuff. The fix can be either to pass that info differently (providing I understand what it actually is trying to do), or to implement the deprecated feature in the M2crypto implementation.

**Comment by atsareg** [comment]
The exception is in the ProxyManager client in the pilot and I have difficulties to get the output right now (the jobs are in the ARC CEs with problems to download the pilot output). When I managed, I have seen the exception reported and the origin. I guess the problem is that the pilot proxy location is passed as a parameter to the service call explicitly, while the M2Crypto is only allowing the proxy discovery in standard locations. So, may be it is enough to just not to pass the pilot proxy location.

**Comment by chaen** [comment]
Well in fact this is what should be done: pass the proxy location rather than passing it as a string. I'll take a quick look, but to validate it I would need you to come with a reproducer once you have the callstack

**Comment by atsareg** [comment]
These are lines that reproduce the problem:

    from DIRAC.Core.Base import Script
    from DIRAC.Core.DISET.RPCClient import RPCClient
    from DIRAC.Core.Security.ProxyInfo import getProxyInfo
    
    Script.parseCommandLine()
    
    result = getProxyInfo()
    if not result['OK']:
      print "failed getProxyInfo()"
    
    proxy = result["Value"]["chain"]
    
    result = RPCClient('Framework/ProxyManager', proxyChain=proxy).ping()

**Comment by atsareg** [comment]
ERROR:
Traceback (most recent call last):
  File "/sps/hep/lhcb/atsareg/test/dirac/DIRAC/Core/DISET/private/BaseClient.py", line 469, in _connect
    transport = gProtocolDict[self.__URLTuple[0]]['transport'](self.__URLTuple[1:3], **self.kwargs)
  File "/sps/hep/lhcb/atsareg/test/dirac/DIRAC/Core/DISET/private/Transports/M2SSLTransport.py", line 94, in __init__
    self.__ctx = getM2SSLContext(**kwargs)
  File "/sps/hep/lhcb/atsareg/test/dirac/DIRAC/Core/DISET/private/Transports/SSL/M2Utils.py", line 106, in getM2SSLContext
    raise RuntimeError("Proxy string no longer supported.")
RuntimeError: Proxy string no longer supported.
