### ISSUE TITLE
[URGENT] HTCondorCE killing machines

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#5118]
The HTCondorCE runs `find` subprocess to remove some files. When you have mutliple HTCondorCE, they all run find processes in the same directory, and everytime `getJobStatus` is called. 
That is totally destroying the machine

The problematic line is https://github.com/DIRACGrid/DIRAC/blob/9a88b022dceb41f60ea07b63505f3ac7b773e51c/src/DIRAC/Resources/Computing/HTCondorCEComputingElement.py#L537

**Comment by aldbr** [comment]
I might need to execute `find` commands this way for something else.
We could probably just make an attribute that iterates every time `getJobStatus` is called until reaching a certain value, and then make a cleanup - as it is done in the `CREAMCE` to renew the proxy.

But if we have similar use case (I don't know if it is the case) what about making a `CleanupAgent` that would clean specific directories every `n` seconds/minutes/days?

In the configuration we could have something like:

```
CleanupAgent
{
  case1
  {
     path = /path/to/htcondor/DIRAC_*
     repeat = 10min
  }
  case2
  ...
}
```

Or maybe something more general, a kind of observer service. Objects could register to it to execute a certain method every `n` seconds/minutes/days. In the case of HTCondor, we would have something like:

``` python
class HTCondorCE():
def __init__(...):
  observerClient.attach(id='htcondor_cleanup', object=self, method= '__cleanup', params=params, time='120s')
  ...
```

And then the service would group objects under their common `id`, and would execute the method once for a group of object every `n` times (btw, I guess `workingDirectory`, `daysToKeepLogs` could be class attributes as well as the `__cleanup` method right?).

**Comment by chaen** [comment]
Factorizing the call to `find` is probably a first step, but why the hell do we need to do something as stupid as that. Don't we keep enough information somewhere to know where and what to delete ? This is alongside the 37b13eb83adce64cea27681dbb9386dc7f4249d2 changes you did

**Comment by andresailer** [comment]
See  #5119 for my solution.

Also this

https://github.com/DIRACGrid/DIRAC/blob/9a88b022dceb41f60ea07b63505f3ac7b773e51c/src/DIRAC/WorkloadManagementSystem/Agent/SiteDirector.py#L834-L839

**Comment by aldbr** [comment]
> Factorizing the call to `find` is probably a first step, but why the hell do we need to do something as stupid as that. Don't we keep enough information somewhere to know where and what to delete ? This is alongside the [37b13eb](https://github.com/DIRACGrid/DIRAC/commit/37b13eb83adce64cea27681dbb9386dc7f4249d2) changes you did

For the pilot outputs: 
From what I understand, other CEs (ARC, CREAM) keep pilot outputs on their side and we can access them for a long time. 
HTCondor directly sends back the pilot outputs to us, and we do not have any other copy.
So we need to make our own cleanup sometimes, as ARC and CREAM do on their side.

For the pilot executable:
In the same way, we send the executable to ARC and CREAM directly and then we can destroy it on our side.
I don't know much about what HTCondor does with the executable, but it apparently takes a few seconds before HTCondor makes a copy of it. I don't think we can wait until it is done every time we want to submit a job, right?

**Comment by chaen** [comment]
> I don't think we can wait until it is done every time we want to submit a job, right?

I don't say we should wait, but aren't we keeping enough information about a pilot job location on disk to know we can remove it, instead of relying on Linux time stamp ?! This is what is beyond me. 

Reading all of this, HTCondor does not really look like an improvement to me... :-D

**Comment by andresailer** [comment]
> why the hell do we need to do something as stupid as that

The same reason for anything else stupid in DIRAC, because so far it worked and all other implementations would require more work than it seemed worth by whomever implemented it and nobody complained during code review?

**Comment by andresailer** [comment]
I mean I was practically begging for someone to contradict me
https://github.com/DIRACGrid/DIRAC/pull/2735#issue-52849332
>Using find to find the files (which is fast enough...)

**Comment by fstagni** [comment]
> Reading all of this, HTCondor does not really look like an improvement to me... :-D

It's a big improvements for sites, that this way they need to maintain a much simpler service. For us it just introduces complications.

As clients, up to now let's not forget that almost all of us are running without a local `schedd`. @andresailer please let me and everyone else know if things would get better for us if we would use it.

In general: the "correct" way of doing things was described in this BiLD meeting: https://indico.cern.ch/event/1001396/. See its minutes, the part on "HTCondorCE submission and usage", but in there I got very little enthusiasm.

**Comment by aldbr** [comment]
> In general: the "correct" way of doing things was described in this BiLD meeting: https://indico.cern.ch/event/1001396/. See its minutes, the part on "HTCondorCE submission and usage", but in there I got very little enthusiasm.

Indeed, this could solve the `find` issue with the HTCondor pilot output files. Each time `getJobOutput` is called, we get the content of the files, we delete the files, we return the content that goes to ElasticSearch.
But what about the pilot executables?

> I don't say we should wait, but aren't we keeping enough information about a pilot job location on disk to know we can remove it, instead of relying on Linux time stamp ?! This is what is beyond me.

Well, actually no from what I understand :sweat_smile: 
We would need to store the name of the executables in the `PilotAgentsDB` and link it to the pilot identifiers (an executable can be used to instantiate multiple pilots).
Then we would need to check that every pilot id linked to a given executable have started/been scheduled before deleting it.

**Comment by chaen** [comment]
> > why the hell do we need to do something as stupid as that
> 
> The same reason for anything else stupid in DIRAC, because so far it worked and all other implementations would require more work than it seemed worth by whomever implemented it and nobody complained during code review?

That is a VERY good reason actually :laughing: 

Anyway, the why and the how are beyond me, this is a part of the code I have absolutely no idea about. But clearly that cannot stay as is now. I can have a look at your new PR of course, but when it comes to HTCondor, I know literally zero.

**Comment by andresailer** [comment]
Yeah, the parallel running `find + delete` is definitely an unintended side effect that happens because of the parallelization of the updateJobStatus.
The running of updateJobStatus for each CE though could be considered intentional.

This doesn't depend on local or remote schedd.

**Comment by andresailer** [comment]
Also people need to clean all the ???/??? folders from the HTCondor SiteDirector working directory after moving to v7r0
