### ISSUE TITLE
Pilot Submission Accounting - Group by Queue: queues are not all displayed 

### ISSUE THREAD

**Issue by aldbr** [DIRACGrid/DIRAC#5120]
On the Accounting page of the webapp, when selecting `Pilot Submission` grouping them by 'Queue', we only get a subset of the queues.
Indeed, contrary to Sites and CEs that have distinct names, multiple queues can share a same identifier (e.g. many queues in different Sites or CEs can be name `lhcb` or `condor`).
From what I observed, the accounting page only displays one of the queues that share the same name.
 
I have not investigated too much, I don't know if this is related to the WebApp or DIRAC itself.
Maybe we should concatenate the name of the CE with the name of the Queue somewhere to have unique queue identifiers.

**Comment by fstagni** [comment]
CC @yujikato

**Comment by yujikato** [comment]
Sorry for very late reply
I'm testing to concatenate CE and Queue in the BelleDIRAC environment
Port to DIRAC after confirming it works.

**Comment by fstagni** [comment]
Hello @yujikato thanks for the fix. Did you already port it to DIRAC?

**Comment by yujikato** [comment]
![image](https://user-images.githubusercontent.com/13082637/119764109-cb293700-beeb-11eb-9d4e-23d3661a970a.png)

Black:  Original 
Orange: After combining CE and queue name

**Comment by yujikato** [comment]
Unfortunately, sometimes too long to be shown in efficiency plot..

![image](https://user-images.githubusercontent.com/13082637/119764197-ef851380-beeb-11eb-97e1-81eb7d693bf5.png)

**Comment by yujikato** [comment]
Anyway, PR made:
https://github.com/DIRACGrid/DIRAC/pull/5161
