### ISSUE TITLE
RegisterFile in dirac-dms-filecatalog-cli have no checksum input

### ISSUE THREAD

**Issue by zhangxiaomei** [DIRACGrid/DIRAC#5203]
The command "register file" in  dirac-dms-filecatalog-cli doesn't require checksum:
register file <lfn> <pfn> <size> <SE> [<guid>]  - register new file record in the catalog
The files registered by this command will cause problems when using transformation or RMS to do the replication although you can't see any problems in DFC:
"ERROR: putRequest: request not valid File in operation #0 is missing Checksum () or ChecksumType (ADLER32)"
Therefore, its implementation is better to use DataManager.registerFile() to have a complete info for the files:
https://github.com/DIRACGrid/DIRAC/blob/integration/src/DIRAC/DataManagementSystem/Client/DataManager.py

**Comment by chaen** [comment]
I never played with these CLI, I think @andresailer si more familiar. Or maybe @marianne013 ?

**Comment by marianne013** [comment]
Noted. Maybe once I get my other pull request through.

**Comment by andresailer** [comment]
Can we drop the PFN parameter for register file while we are at it?

**Comment by marianne013** [comment]
@sfayer Would probably mean we'd have to educate the odd user not to use the PFN from the catalog as a shortcut.
@andresailer Should probably be a separate issue.

**Comment by andresailer** [comment]
I didn't realize people still use the PFN, no then keep it there as a parameter.

**Comment by marianne013** [comment]
It is actually problematic, as sometimes files are written with srm and so srm ends up in the PFN and then sites switch to xrootd and the PFN stops working. So removing it might actually be a good idea in the long term. As far as I know some of our users use the PFN as input to experiment specific data verification/curation tools.
We might have to fix up dirac-dms-pfn-accessURL and related code to reconstruct the PFN from first principles (rather than putting the responsibility on the user).

**Comment by atsareg** [comment]
If we want to registerFile with more parameters (Checksum), then we will have to require all the parameters to be present. But some parameters sometimes are not necessary. I would suggest to have a special value, i.e. None, to instruct the command to ignore this value. Then a default value/action would be taken:

- For PFN - empty string
- For GUID - generated guid
- For Checksum - empty string

For example:
> register file /lz/user/d/daniela/myfile None 1234 SE-disk None <check sum>

**Comment by atsareg** [comment]
See #5211

**Comment by chaen** [comment]
> It is actually problematic, as sometimes files are written with srm and so srm ends up in the PFN and then sites switch to xrootd and the PFN stops working. So removing it might actually be a good idea in the long term. As far as I know some of our users use the PFN as input to experiment specific data verification/curation tools.
> We might have to fix up dirac-dms-pfn-accessURL and related code to reconstruct the PFN from first principles (rather than putting the responsibility on the user).

I think all this mechanics is already in place for many years. But for less confusion, why not just ditching all the `dirac-dms-pfn`, and use the `dirac-dms-lfn` scripts together with the `--SE` options if one REAAAAALY wants to target a specific site ?

**Comment by marianne013** [comment]
I would have to ask what they are doing. I think it's data consistency checks.

**Comment by fstagni** [comment]
There's a utility for data consistency: https://github.com/DIRACGrid/DIRAC/blob/integration/src/DIRAC/DataManagementSystem/Client/ConsistencyInspector.py

**Comment by marianne013** [comment]
I've pointed the people I think might be using this at this issue.

**Comment by marianne013** [comment]
I got this from t2k (it's a bit lengthy, but illustrates what our users do quite nicely).
```
We use the `dirac-dms-add-file` command line utility to upload new
files. (Never got around to switch to the API.)

We use the `Dirac.getReplicas(lurl)` API to get physical paths to the
replicas.

We use the `DataManager.RemoveReplica(se, [lurl]) API to remove replicas.

We use `gfal-copy` to actually copy the closest physical replica to the
local machine.

We use `DataManager.registerFile((lurl, surl, size, se, guid,
checksum))` and `DataManager.registerReplica((lurl, surl, se))` to deal
with "dark replicas", i.e. files on a storage element that are not
registered as replicas in the DFC.

I guess the last one is most likely to be relevant to your question, and
pretty much the only place where we directly talk to the DFC about
physical paths. You can find the relevant code here, if you want to take
a look:

https://github.com/t2k-software/t2kdm/blob/9024365cc1c3633f33c99addff2379d5b5f9e1f0/t2kdm/backends.py#L904-L928

If there is a better way to deal with "dark replicas", let me know. It
is not something we do very often (certainly not something that should
come up in regular operation), and I am open to implement this in a
different way.
```

**Comment by chaen** [comment]
I am a bit confused by all that. OK I understand that they are dealing with dark data, but I guess this dark data still respects the "golden rule" of havign the LFN as the last part of their physical path ? If so, the actual physical path put in the DFC does not matter at all.

**Comment by atsareg** [comment]
Technically speaking, the DFC can still store PFNs even if the LFN-PFN golden convention is not respected. In this case the PFN is taken as it is and is not constructed on the fly. This behavior is controlled by the LFNPFNConvention configuration option which can be None, Weak or Strong. But sticking to the strong convention is certainly a must for the new data, deviations can be only considered for preexisting "dark" data.

**Comment by chaen** [comment]
That is not completely correct.
There are other flags which come into play:
* `Operations/DataManagement/UseCatalogPFN` which should be `False` in normal cases. This is a sort of global ON/OFF flag
* `UseCatalogURL` for each SE.

Note that all these flags only impact the reading operation, meaning that something sensible will anyway always be put in the catalog (which is certainly not very useful, but well...)

**Comment by fstagni** [comment]
As discussed in the BiLD, I close this task. Discussion points here might be useful for a different issue, for this I let @atsareg @chaen and @marianne013 to summarize/open if necessary.
