### ISSUE TITLE
Set XrdSecGSIDELEGPROXY=1 to enable third party copy with xrootd

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#5207]
As noted in the google forum it looks like we need to replicate a hack present in gfal in DIRAC to enable third party copy for sites that use the xroot protocol.
It would probably be easiest to add it to the bashrc, unless there is something I am missing. 

Related: 
https://ggus.eu/index.php?mode=ticket_info&ticket_id=151985
https://groups.google.com/u/1/g/diracgrid-forum/c/n2IugXQPWxQ

**Comment by andresailer** [comment]
Thanks to you and Simon for digging into the TPC with xroot!

I think we could be adding it to the python like we for XrdSecPROTOCOL

https://github.com/DIRACGrid/DIRAC/blob/e0b4c5ef2359c54d9fa7eb0ee81ce609a0f6b515/src/DIRAC/Resources/Storage/GFAL2_XROOTStorage.py#L66

**Comment by marianne013** [comment]
This would probably work. I'll have a go in my local install and see if it breaks anything obvious.

**Comment by chaen** [comment]
Sorry, for some reason I completely lost track of that problem of yours ! 
I agree with @andresailer that we probably should add it alongside `XrdSecProtocol`

**Comment by marianne013** [comment]
I just tested this (set in GFAL2_XROOTStorage.py) on my test server and the UI and it seems to work and I can't see any side effects. Should I have another go at a pull request ?

**Comment by marianne013** [comment]
https://github.com/DIRACGrid/DIRAC/pull/5217
