### ISSUE TITLE
DIRAC_USE_TORNADO_IOLOOP set after Refresher is imported in tornado_start_all

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRAC#5223]
In `tornado_start_all.py` `DIRAC_USE_TORNADO_IOLOOP` is set in the `main` function but the `DIRACScript` import triggers `DIRAC.ConfigurationSystem.private.Refresher` to be imported which reads this variable at import time.

```python
In [1]: import sys
   ...: assert "DIRAC.FrameworkSystem.Client.MonitoringClient" not in sys.modules
   ...: assert "DIRAC.ConfigurationSystem.private.Refresher" not in sys.modules
   ...: from DIRAC.Core.Utilities.DIRACScript import DIRACScript
   ...: assert "DIRAC.FrameworkSystem.Client.MonitoringClient" not in sys.modules
   ...: assert "DIRAC.ConfigurationSystem.private.Refresher" not in sys.modules
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-1-8197cf08d195> in <module>
      4 from DIRAC.Core.Utilities.DIRACScript import DIRACScript
      5 assert "DIRAC.FrameworkSystem.Client.MonitoringClient" not in sys.modules
----> 6 assert "DIRAC.ConfigurationSystem.private.Refresher" not in sys.modules

AssertionError:
```

_Originally posted by @chrisburr in https://github.com/DIRACGrid/DIRAC/pull/5214#discussion_r657168736_

**Comment by chrisburr** [comment]
There are two places where this variable is read, can they be converted to read later than import time?

https://github.com/DIRACGrid/DIRAC/blob/54d89885089ba29205d50bee9c3bff068e1aed2d/src/DIRAC/FrameworkSystem/Client/MonitoringClient.py#L89-L94

This is only used in `MonitoringClient.initialize` so I think the initialisation of the global variable can be moved into there?

https://github.com/DIRACGrid/DIRAC/blob/8269146d64a8c3345e7c5e785fb70f3a89f6d7b4/src/DIRAC/ConfigurationSystem/private/Refresher.py#L110-L115

This one looks a little tricker.

**Comment by chaen** [comment]
I knew this would bite us https://github.com/DIRACGrid/DIRAC/pull/4865/files#r557381856

Again: why not putting the variable definition at the very top of the file and be done with it ?

**Comment by chrisburr** [comment]
As all modules containing a `@DIRACScript` decorated function are imported every time a `dirac-` command is ran in order to figure out which command is currently being ran so it can be replaced with the function from an DIRAC extension instead.

**Comment by chaen** [comment]
> As all modules containing a `@DIRACScript` decorated function are imported every time a `dirac-` command is ran in order to figure out which command is currently being ran so it can be replaced with the function from an DIRAC extension instead.

Ah true... I guess it is due to this check that all the scripts use `DIRACScript` ? 

https://github.com/DIRACGrid/DIRAC/blob/cf55bc473f64012c256fea5e659fa5e0b7eca1ef/src/DIRAC/Core/Utilities/DIRACScript.py#L53-L59

I'd be tempted to remove that check actually, and relying on the name... Importing hundreds of module every time we call a script is an overkill anyway isn't it ? 

Another option would be to have that variable set in the `run` file, but that is really black magic, and means the installation cannot be automated with the current tools, so not so nice. 
Another bad option: dedicated servers for https services, where we set that variable in the `bashrc` 

Or, would by any chance adding the following at the very top of `tornado-start-all` solve our problem ? 

```
if __name__ == "__main__":
  import os
  os.environ['DIRAC_USE_TORNADO_IOLOOP'] = 'Yes'
```

**Comment by chrisburr** [comment]
>  Another bad option: dedicated servers for https services, where we set that variable in the bashrc

It can also be added to the `runit` scripts:

https://github.com/DIRACGrid/DIRAC/blob/9515f7e3af0c1a92f0ad9dff351774846fa63256/src/DIRAC/FrameworkSystem/Client/ComponentInstaller.py#L2357-L2367

(for `tornado-start-all`, I'm not sure where `tornado-start-CS` is used)

**Comment by chaen** [comment]
Yes, that's what I proposed (it's the `run` file), but I had forgotten that it's the ComponentManager writing this file. 

`tornado-start-CS` is used for the master CS.

My choice goes to

```python
if __name__ == "__main__":
  import os
  os.environ['DIRAC_USE_TORNADO_IOLOOP'] = 'Yes'
```

I think it's the best solution

**Comment by chrisburr** [comment]
When using entrypoints that will never trigger as `__main__` is the wrapper script that `pip` generates at install time.

**Comment by chaen** [comment]
argh, yeah.... oh my... 
OK, so `ComponentInstaller` it is, and for the custom scripts like `tornado-start-CS`, it's anyway a manual operation

**Comment by chrisburr** [comment]
Yeah...to stay safe shall we make the script exit with an error if the environment is invalid?

**Comment by chaen** [comment]
that is exactly what I have done. PR coming :)
