### ISSUE TITLE
v7r3: Bdii2CSAgent seems to ignore BannedCEs list

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#5224]
The symptom/logs can be seen on the DIRAC certification server:
ceprod03.grid.hep.ph.ic.ac.uk is in the BannedCEs list, yet the agent keeps overwriting my setting for NumberOfProcessors.
In order to preserve the setting I had to take the parent site (LCG.UKI-LT2-IC-HEP.uk) out of of the SelectedSites list.
@andresailer You seen to be the last person to touch Bdii2CSAgent.

**Comment by andresailer** [comment]
So you want clarification in the docs that BannedCEs only ignores CEs that are not already configured?

**Comment by marianne013** [comment]
I'd like a feature where I can stop the agent from reconfiguring a CE - there doesn't seem to be an option. AFAIK we use bannedCEs for that in GridPP (if CE doesn't exist, don't add, if it does, don't update) Andrei T seemed to suggest that I could use BannedCEs for that, but that seems to have been a misunderstanding. Some CEs are more special than others ;-)

**Comment by fstagni** [comment]
Sorry, is this issue still valid?

**Comment by marianne013** [comment]
Yes. Though it's more of a design choice rather than anything else. I wanted to be able to exclude individual CEs from being auto reconfigured rather than only being able to do this on site level.
