### ISSUE TITLE
Allow for RunningLimit per CE

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#5238]
At the moment we have the possibility to limit the number of running job on a site level. 

https://github.com/DIRACGrid/DIRAC/blob/7ae801953e137dfb95b47f3bcc32b1879b3fba7e/src/DIRAC/WorkloadManagementSystem/Utilities/QueueUtilities.py#L203-L214

For example

```
      RunningLimit
      {
        LCG.CERN.cern
        {
          JobType
          {
            MCSimulation = 10000
          }
        }
    }
```

It would be a very desirable feature to be able to do so at the CE level 

```
      RunningLimit
      {
        LCG.CERN.cern
        {
          JobType
          {
            MCSimulation = 10000
          }
          CEs
          {
            ce1.cern.ch
            {
               MCSimulation = 3
            }
          }
        }
    }
```

**Comment by fstagni** [comment]
A completely untested implementation of this is in https://github.com/DIRACGrid/DIRAC/pull/5242/commits/9e6683b99e9e6590a0dcd30c5b82c6ec533241c1

@atsareg  please have a look.

**Comment by fstagni** [comment]
PR merged, issue closed.
