### ISSUE TITLE
v7r2/r3 multi-core submission does not start multi-core jobs on HTCondorCEs

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#5240]
(moved here from the forum)

For CEs/queues configured with LocalCEType = Pool and NumberOfProcessors = 8 jobs submitted with the requirement
NumberOfProcessors = "8"; (or Tags = {"8Processors"}; ) are matched to these queues, but it seems that only on ARCCEs these jobs are actually assigned 8 cores, while on HTCondorCEs they are matched, but only assigned one core from the batch system.
I *don't* see this happening in v7r, i.e. jobs submitted with an 8 core tag user 8 cores on the batch system. In all cases pilot3 is used.
Can be checked on https://lbcertifdirac70.cern.ch using ceprod03.grid.hep.ph.ic.ac.uk (HTCondorCE) and any ARCCE from UKI-SOUTHGRID-RALPP.
At least until the next reinstall this effect can be seen on the certification server jobs 2983 and 2984: 
In the output for the HTCondorCE iit's: OMP_NUM_THREADS=1 (should be 8)

**Comment by fstagni** [comment]
Check https://github.com/DIRACGrid/DIRAC/pull/5242 (following what I found in https://htcondor.readthedocs.io/en/v8_8/users-manual/parallel-applications.html#requesting-multiple-cores-per-slot)

**Comment by fstagni** [comment]
So, it seems that we would need at least condor 8.8: https://htcondor-wiki.cs.wisc.edu/index.cgi/tktview?tn=6918
as version 8.6, which we have in DIRACOS, is not equipped to understand these Ads : https://github.com/DIRACGrid/DIRACOS/issues/171

DIRACOS2 has, of course, the correct version but that's v7r3 + py3.

**Comment by marianne013** [comment]
I just tested the following sub file using diracos v1r22 (which came packaged by default with my py2 install of my v7r2p10 UI).
This seems to be using condor 8.6.9 and the sub file requested an 2 core job, so I think that works.

```
# Required for local HTCondor-CE submission
universe = vanilla
use_x509userproxy = true
+Owner = undefined
request_cpus = 2
# Files
executable = pilot_test.sh
output = job.log
error = job.err
log = ce_test.log

delegate_job_GSI_credentials_lifetime = 0
# File transfer behavior
ShouldTransferFiles = YES
WhenToTransferOutput = ON_EXIT

# Run job once
queue
```

**Comment by marianne013** [comment]
@chrisburr Can you remind me what the quickest way to get a dirac ui with diracos2 in it is ?

**Comment by marianne013** [comment]
So I managed to get it to work with diracos2 (just testing condor, none of the DIRAC infrastructure). 
I followed the instructions from the trello board and retrieved diracos using curl:
curl -LO https://github.com/DIRACGrid/DIRACOS2/releases/latest/download/DIRACOS-Linux-$(uname -m).sh
I couldn't find its version anywhere (what happened to versions.txt?) 
However looking at the condor version I get:
(base) lx02:dirac_py3 > condor_version 
$CondorVersion: 9.0.1 May 21 2021 $
$CondorPlatform: X86_64-CentOS_7.9 $

So by the looks of it the request_cpus parameter is understood by 8.6.9 and 9.0.1.
@fstagni Is that what you wanted to know ?

**Comment by fstagni** [comment]
> So by the looks of it the request_cpus parameter is understood by 8.6.9 and 9.0.1.
> @fstagni Is that what you wanted to know ?

Yes! Thank you.

So, the PR is ready to be merged IMHO.
