### ISSUE TITLE
[RSS] VOFlag in rss scripts

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#5247]
According to @martynia, since he has done the multi vo implementation of RSS some scripts require a `vo` switch, some don't.

@atsareg proposed that the VO is taken from the proxy:
* it always had to be an admin proxy (using the property checks on the service side)
* if the proxy has a vo assigned in the voms role (e.g. `lhcb_admin`) specify that VO
* otherwise (like `diracAdmin`) consider `vo=all`

As mentioned, this would in principle call for the notion of VO specific properties.
However, given that we aim at transitioning to tokens, where that concept already exists, I would propose not to embark into changing DISET now.

A very easy alternative is to select the VO service side, when reading the proxy.

**Comment by fstagni** [comment]
Of all the multi-VO scripts/services of DIRAC, is this the only one that would call for a `vo` switch and VO specific properties checks?

**Comment by martynia** [comment]
I looked into the code again, the `dirac_rss_set_token` operation seems to be the only one which requires the `VO` switch and `dirac_rss_set_status` does not (a missing switch defaults to 'all'), although their "severity" is pretty the same. when using a super admin account _dirac_admin_ .  We could relax the requirement when setting the token, in that case both operations will only act on all but specifically listed VOs, if it's OK with everyone. I would go a safe route however and require the switch for setting the status as well.

An automatic VO discovery is a good concept, however the RSS contains mostly non VO-aware data, so those would have to be modified with a super admin user account, wouldn't they ?

reminder: _all_ means all but those _VO specific rows_ added by VO aware policies.

**Comment by chaen** [comment]
> reminder: all means all but those VO specific rows added by VO aware policies.

Clearly there should be a mechanism to overwrite everything ! So you would need a concept of `all` and a concept of `others` (which corresponds to what you describe)
