### ISSUE TITLE
Do not use BLOB in JobsDB and PilotAgentsDB tables

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#5253]
@TaykYoku has debugged this further and got to the bottom of it on slack: https://lhcbdirac.slack.com/archives/C3AGWCA8J/p1625147097062700

In summary, the JobParameters table is using `BLOB` for the value when it should be using a text type.

_Originally posted by @chrisburr in https://github.com/DIRACGrid/DIRAC/pull/5246#discussion_r662346125_

**Comment by fstagni** [comment]
Self reminder: there are several BLOB and MEDIUMBLOB (mis)used instead of TEXT or VARCHAR, especially in JobDB and PilotAgentsDB. The change should be tested on a DB clone first.

**Comment by fstagni** [comment]
For reference, changes to be tested:
```
use JobDB;
ALTER TABLE `JobJDLs` MODIFY COLUMN `JDL` MEDIUMTEXT, MODIFY COLUMN `JobRequirements` TEXT, MODIFY COLUMN `OriginalJDL` MEDIUMTEXT;
ALTER TABLE `JobParameters` MODIFY COLUMN `Value` TEXT;
ALTER TABLE `OptimizerParameters` MODIFY COLUMN `Value` MEDIUMTEXT;
ALTER TABLE `AtticJobParameters` MODIFY COLUMN `Value` TEXT;
ALTER TABLE `SiteMask` MODIFY COLUMN `Comment` TEXT;
ALTER TABLE `SiteMaskLogging` MODIFY COLUMN `Comment` TEXT;
ALTER TABLE `HeartBeatLoggingInfo` MODIFY COLUMN `Value` TEXT;
use PilotAgentsDB;
ALTER TABLE `PilotAgents` MODIFY COLUMN `GridRequirements` TEXT;
ALTER TABLE `PilotOutput` MODIFY COLUMN `StdOutput` MEDIUMTEXT, MODIFY COLUMN `StdError` MEDIUMTEXT;
```

**Comment by chrisburr** [comment]
I don't know how MySQL handles this internally but can this be made faster by doing it with a single `ALTER TABLE` command?

**Comment by fstagni** [comment]
IIUC you can alter only one table at a time.
