### ISSUE TITLE
Bug in AccountingDataStore

### ISSUE THREAD

**Issue by arrabito** [DIRACGrid/DIRAC#5261]
Since long time already I get some MySQL errors in AccountingDataStore of this type:

```
`2021-07-09 09:01:40 UTC Accounting/DataStore/Accounting/AccountingDB ERROR: _update (INSERT INTO `ac_bucket_CTA_DataOperation` ( `startTime`, `bucketLength`, `entriesInBucket`, `OperationType`, `User`, `ExecutionSite`, `Source`, `Destination`, `Protocol`, `FinalStatus`, `TransferSize`, `TransferTime`, `RegistrationTime`, `TransferOK`, `TransferTotal`, `RegistrationOK`, `RegistrationTotal` ) VALUES  ON DUPLICATE KEY UPDATE `entriesInBucket`=`entriesInBucket`+VALUES(`entriesInBucket`), `TransferSize`=`TransferSize`+VALUES(`TransferSize`), `TransferTime`=`TransferTime`+VALUES(`TransferTime`), `RegistrationTime`=`RegistrationTime`+VALUES(`RegistrationTime`), `TransferOK`=`TransferOK`+VALUES(`TransferOK`), `TransferTotal`=`TransferTotal`+VALUES(`TransferTotal`), `RegistrationOK`=`RegistrationOK`+VALUES(`RegistrationOK`), `RegistrationTotal`=`RegistrationTotal`+VALUES(`RegistrationTotal`)): Execution failed. 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ON DUPLICATE KEY UPDATE `entriesInBucket`=`entriesInBucket`+VALUES(`entriesIn...' at line 1`
```

All errors concern the bucket ac_bucket_CTA_DataOperation:

`[PENDING] Got 14 pending records for type CTA_DataOperation`

By debugging a little bit I see that the problem with this particular query is that the list of values to be inserted is empty:

VALUES .**...Missing list of values....** ON DUPLICATE KEY UPDATE 

The relative code is here:

https://github.com/DIRACGrid/DIRAC/blob/937634f5a8a4609c28df56d9114aaaabc74225e4/src/DIRAC/AccountingSystem/DB/AccountingDB.py#L911

However for this particular case valuesGroups list is empty and this because also buckets is empty. 
I don't know what did it cause the __writeBuckets function to be called with empty buckets, but it looks like a bug.

**Comment by fstagni** [comment]
Is this supposed to be addressed in https://github.com/DIRACGrid/DIRAC/pull/5257 ?

**Comment by arrabito** [comment]
No. I just reported as an additional bug.

**Comment by fstagni** [comment]
I have never seen this error, not even in the LHCb certification nor in the DIRAC certification. I can't figure out how it might happen, looks somehow related to your setup.
