### ISSUE TITLE
Pilot Status: Difference between `Scheduled` and `Waiting`?

### ISSUE THREAD

**Issue by aldbr** [DIRACGrid/DIRAC#5278]
Is there any difference between the pilot status `Scheduled` and `Waiting`? I do not see any.
- `CREAM` and `ARC` use `Scheduled`
- `HTCondorCE` and batch system interfaces use `Waiting`

If they have the same meaning, which one should be favored?

**Comment by fstagni** [comment]
Translate to "Waiting" everywhere.

**Comment by fstagni** [comment]
I change milestone to v7r3 and close this issue.
