### ISSUE TITLE
"memory leak" from gLogger

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#5280]
The way we are using `logging` is not correct because we are constantly creating child logger which are not garbage collected, which results in sort of a memory leak.

It can be illustrated with this simple script:

```python
#!/usr/bin/env python
import sys
from DIRAC import gLogger

def createSubLogger(nb):
  if nb % 1000 == 0:
    print(nb)
  x = gLogger.getSubLogger('toto_%s'%nb)

if __name__ == '__main__':
  for i in range(int(sys.argv[1])):
    createSubLogger(i)
```

The memory raises quickly. Here are examples with running with 100000

That plot is from running this script on an LHCb server with python 2.7

![memory_python2 7_server](https://user-images.githubusercontent.com/3728211/126489915-60c185cf-1d98-4561-9149-188a5f1aa4b8.png)

And this is the same code running with a python3 installation, but without the LHCb configuration

![memory_python3_client](https://user-images.githubusercontent.com/3728211/126490008-75131676-7afe-444d-88a2-03040f2abd3d.png)

So the difference in memory consumption may come from python3 or from the lack of config. It doesn't matter, there still is an issue. 

In practice, it is a real problem for services, since they are creating a lot of `subLogger`. An example here https://github.com/DIRACGrid/DIRAC/blob/14a63527fed6e8d5baeff1e4f7ac3af9a8ce3cda/src/DIRAC/WorkloadManagementSystem/Service/JobStateUpdateHandler.py#L210  on the `JobStateUpdateHander` that we have seen kneeling down machines in LHCb

The python logging cookbook some advice on how to handle that, so I am going to have a look at it

https://docs.python.org/3/howto/logging-cookbook.html#adding-contextual-information-to-your-logging-output

**Comment by chaen** [comment]
With #5284

![fixedLogger](https://user-images.githubusercontent.com/3728211/126768970-109b2e6e-f376-4bc6-882a-7e3cd2407744.png)

It takes an extra 2 seconds to create 500 000 loggers, but we save 800MB of memory, so I think it is acceptable

**Comment by fstagni** [comment]
We can close this one I guess.
