### ISSUE TITLE
Use Read the Docs Sphinx Theme for documentation

### ISSUE THREAD

**Issue by TaykYoku** [DIRACGrid/DIRAC#5309]
Can we consider using next sphinx extensions?

`sphinx-rtd-theme`
**[RTD Sphinx theme](https://sphinx-rtd-theme.readthedocs.io/en/latest/installing.html#installation)** already contain CSS(Sass) styles and designed for both desktop and mobile devices. IMHO this theme provides a more readable view, especially in Code Documentation.

`sphinx-panels`
**[sphinx-panels](https://sphinx-panels.readthedocs.io/en/latest/#installation)** support [Bootstrap 4](https://getbootstrap.com/docs/4.0/getting-started/introduction/) framework and provide elements like [panels](https://dirac--5313.org.readthedocs.build/en/5313/index.html#documentation-sources), [tabs](https://dirac--5313.org.readthedocs.build/en/5313/AdministratorGuide/ServerInstallations/InstallingDiracServer.html#installing-runit), [dropdown](https://dirac--5313.org.readthedocs.build/en/5313/AdministratorGuide/ServerInstallations/InstallingDiracServer.html#primary-server-installation), etc. 

You can try it using [build](https://dirac--5313.org.readthedocs.build/en/5313/) of #5313.

**Comment by andresailer** [comment]
Maybe you can provide a few more arguments that are more concrete than "better"?

Also a PR with the other theme so we can explore?

**Comment by TaykYoku** [comment]
Issue updated

**Comment by atsareg** [comment]
Am I understanding correctly that with this PR the newly generated RTD docs will have commercial advertisements now ?

**Comment by fstagni** [comment]
The commercial advertisements should have been there already, I don't know why they were not appearing on our hosted one.

**Comment by TaykYoku** [comment]
Here's what I found about it, and it appears to be part of a service agreement:
https://docs.readthedocs.io/en/stable/advertising/ethical-advertising.html#ethical-ads

Here are instructions on how to opt out of some advertising, unfortunately I can't try to do so because I'm not a project owner:
https://docs.readthedocs.io/en/stable/advertising/ethical-advertising.html#opting-out
