### ISSUE TITLE
SkipCAChecks should not remain True on client installation

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#5361]
When doing dirac-configure (py2 or py3), the `SkipCAChecks` flag is set to `True`. This is to allow the initial download of CA/CRL bundle. 
However, this flag then remains in the configuration ad vitam aeternam, which is of course not good.

**Comment by fstagni** [comment]
Please check #5416 for possible simple resolution (I didn't run - yet - any tests with this patch in).
