### ISSUE TITLE
Enabling IPV6 in GFAL2_StorageBase causes a problem

### ISSUE THREAD

**Issue by iueda** [DIRACGrid/DIRAC#5401]
Enabling IPv6 in general causes access problems with a certain combination of IPv6-enabled SEs and IPv4-only UI:

https://github.com/DIRACGrid/DIRAC/blob/integration/src/DIRAC/Resources/Storage/GFAL2_StorageBase.py#L97
```
    # Enable IPV6 for gsiftp
    self.ctx.set_opt_boolean("GRIDFTP PLUGIN", "IPV6", True)
```

Can it be set depending on the UI environment?

**Comment by iueda** [comment]
eg. https://ggus.eu/index.php?mode=ticket_info&ticket_id=153684

**Comment by chaen** [comment]
Hi,

It is a known globus bug, for which CERN once mentioned a patch "coming soon" (aug 2019). I asked for some news about that patch.
In any case, I can introduce a new environment variable yes. I'll do it shortly. v7r2 is ok for you ?

**Comment by iueda** [comment]
thanks. ah, yes that one... yes. v7r2 is ok.

**Comment by chaen** [comment]
According to Oliver Keeble
> The fix is out there (latest gridftp packages from EPEL) but has to be configured (epsv_match 1 in /etc/gridftp.conf) on the DPM. I think this has to be done explicitly by the administrator.

**Comment by iueda** [comment]
Thanks for the work and the information.
I have just made a test and confirmed it works with a patch following #5402.
Details in #5402.
