### ISSUE TITLE
8.x style deployment failing

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRAC#5486]
@atsareg This is failing as the `8.0.0a1` deployment didn't quite go pefectly as it failed to push the release notes back so the `8.0.0a1` tag is a dangling commit. I'll think about how to fix it properly in the morning. 

In the meantime, can you cherry-pick `db09bfed176ab847f8e40f6511ce4155e53df0ff` and push it directly to `integration` on `DIRACGrid`?

_Originally posted by @chrisburr in https://github.com/DIRACGrid/WebAppDIRAC/issues/561#issuecomment-937200256_

@atsareg The cherry pick of db09bfed176ab847f8e40f6511ce4155e53df0ff to integration hasn't been done so the WebAppDIRAC CI is still broken.

For fixing the CI, @DIRACGridBot account needs permission to push to `integration` without the code being approved by @fstagni or @atsareg.

> ```
> Making GitHub release for v8.0.0a1
> remote: error: GH006: Protected branch update failed for refs/heads/integration.        
> remote: error: Waiting on code owner review from atsareg and/or fstagni.        
> To https://github.com/DIRACGrid/DIRAC
>  ! [remote rejected]     integration -> integration (protected branch hook declined)
> error: failed to push some refs to 'https://github.com/DIRACGrid/DIRAC'
> Created draft release at: https://github.com/DIRACGrid/DIRAC/releases/tag/untagged-6917381cac8f16ef5baa
> Published release at: https://github.com/DIRACGrid/DIRAC/releases/tag/v8.0.0a1
> ```

**Comment by fstagni** [comment]
> @fstagni Shall I make `8.0.0a6` to check?

Sorry, I missed this one. Yes, go ahead.

**Comment by fstagni** [comment]
@atsareg just created 8.0.0a7 which has not pushed a corresponding tag.

**Comment by chrisburr** [comment]
Finally, success! https://github.com/DIRACGrid/DIRAC/blob/integration/release.notes
