### ISSUE TITLE
Commands failing but still giving status 0

### ISSUE THREAD

**Issue by acampove** [DIRACGrid/DIRAC#5580]
Hi,

If I run:

```
dirac-dms-replicate-lfn /lhcb/user/a/acampove/GangaFiles_11.12_Wednesday_27_October_2021/2011_skimmed.roos PIC-USER
```
where the `LFN` should end in `root`, I see:

![image](https://user-images.githubusercontent.com/14037062/141231755-e6f43d12-58f8-4231-94a1-27a81107a232.png)

Also, if I do:

```
lb-dirac dirac-dms-replicate-lfn /lhcb/user/a/acampove/GangaFiles_11.12_Wednesday_27_October_2021/2011_skimmed.root PIC-USET
```
mistaking the site, I do get the exit code 0. This means that we cannot automate the checking of the success of the process and we always have to go through the log file to check that everything happened as planned. This is time consumming and therefore should be improved, the status code on exit of failed processes should not be zero.

Cheers.

**Comment by fstagni** [comment]
Thanks for the report. That's actually LHCb-specific error. I notify @phicharp since this is actually his code.

**Comment by phicharp** [comment]
This is because we were not taking into account the presence of files with "Failed" status... Fixed in a coming release

**Comment by phicharp** [comment]
```
[localhost] ~ $ dirac-dms-replicate-lfn /lhcb/user/a/acampove/GangaFiles_11.12_Wednesday_27_October_2021/2011_skimmed.roos PIC-USER
Failed :
    PIC-USER :
        /lhcb/user/a/acampove/GangaFiles_11.12_Wednesday_27_October_2021/2011_skimmed.roos : Completely failed to replicate file. Failed to get replicas for LFN. No such file or directory
[localhost] ~ $ echo $?
1
```

**Comment by fstagni** [comment]
Fixed in https://gitlab.cern.ch/lhcb-dirac/LHCbDIRAC/-/merge_requests/1122
