### ISSUE TITLE
v7r2 (&up): Jobs cannot be submitted to ARC-CEs if DIRAC queue name doesn't match real queue name

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#5582]
In order to get around the "one core job requesting 8 core pilot" 'feature',  GridPP now has two DIRAC queues per CE:
One with NumberOfProcessors =1 and one with NumberOfProcessors =8.
The multi-core queue has the additional parameters of Tag = MultiProcessor and RequiredTag =  MultiProcessor to avoid attracting single core jobs.
These queues have different names. This causes no problems on the HTCondorCEs. 
On the ARC-CE however jobs will only get submitted if the DIRAC queue name matches the 'real' queue name. 
Looking at the code, DIRAC inserts the queue name in the rsl:
https://github.com/DIRACGrid/DIRAC/blob/171184d4afea112ef181ff2e4afe9889015a83a7/src/DIRAC/Resources/Computing/ARCComputingElement.py#L184
As now one or more queues doesn't exists as 'real' queue, the submission fails. 
Having looked at it,  I don't think arcsub actually requires the queue name -- it happily went its merry way and ran the job correctly (i.e. with 8 cores) once I commented out the above line (there might be other instances, I only checked for my multi core jobs). Reading through the code it looks like the original author (sorry Raja) wasn't all that convinced by the need to have the queue name in there in the first place.
I'm rather not break LHCb, so I didn't submit a patch, but I think that queue name needs to go, unless someone can come up with a more elegant solution. The DIRAC certification server is set up to test this, if anyone would like to try.

**Comment by fstagni** [comment]
Thanks for the report. Let's see if Raja has anything against it.

**Comment by andresailer** [comment]
Cross-Posting from the BiLD
All the ArcCE cares about is the bit after the second hyphen https://github.com/DIRACGrid/DIRAC/blob/f0b28398d7d40224fc6fbc7fdf4f821a8bcf0a14/src/DIRAC/Resources/Computing/ARCComputingElement.py#L210

Thus creating queues like foo-bar-theActualQueue (and foo-bar1core-theActualQueue) should work (and seems to work for me) https://gist.github.com/andresailer/4392d65112451a7a4089c8e1f83e8113

**Comment by marianne013** [comment]
Just to say that Andre's suggestion works for us. Not sure where in the documentation this should go ? I guess ARC and if there is one: multi-core ? 
I won't be able to do anything about anything for the next 2 weeks though.
