### ISSUE TITLE
should `getQueuesResolved()` create a directory per queue?

### ISSUE THREAD

**Issue by aldbr** [DIRACGrid/DIRAC#5587]
The `SiteDirector` calls `getQueuesResolved()` to build a dictionary of queue attributes.
The function also generates a directory per queue in `workingDirectory`:
https://github.com/DIRACGrid/DIRAC/blob/integration/src/DIRAC/WorkloadManagementSystem/Utilities/QueueUtilities.py#L62

IIUC, these directories generated are not really used in the process. 
If such is the case, shouldn't we delete this line?

**Comment by fstagni** [comment]
Indeed, I think it can be removed.

**Comment by fstagni** [comment]
In #5330
