### ISSUE TITLE
Jobs with "impossible" logging info

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#5699]
(writing down before it's forgotten)

We have cases of jobs with this logging info:

```
Running     Application                        Executing finalization     2021-12-02 21:17:38
Running     Application                        Job Finished Successfully  2021-12-02 21:18:38
Completing  Application Finished Successfully  Job Finished Successfully  2021-12-02 21:18:52
Completing  Uploading Output Sandbox           Job Finished Successfully  2021-12-02 21:19:04
Completed   Uploading Output Sandbox           Job Finished Successfully  2021-12-02 21:19:04
...
here repeating maaany times (probably trying to update from Completed to Completing/OutputSandboxUploaded?) and failing, because StateMachine forbids to go from "Completed" to "Completing"
....
Completed   Uploading Output Sandbox           Job Finished Successfully  2021-12-02 21:19:04
Completing  Output Sandbox Uploaded            Job Finished Successfully  2021-12-02 21:19:06
Completed   Output Sandbox Uploaded            Job Finished Successfully  2021-12-02 21:19:06
...
<same as above>
...
Completed   Output Sandbox Uploaded            Job Finished Successfully  2021-12-02 21:19:06
Completed   Pending Requests                   Job Finished Successfully  2021-12-02 21:19:32
```

And from here on the RequestExecutingAgent is still trying to update the JobStatus/MinorStatus.

My suspicion is that the `StatusDict` in

https://github.com/DIRACGrid/DIRAC/blob/28e83cdd949d257dd3213f07d8423a0df635e22d/src/DIRAC/WorkloadManagementSystem/Service/JobStateUpdateHandler.py#L149-L154

contains entries with the same timestamp (to the milliseconds). So, the order becomes wrong. nanoseconds precision might be used only from py3.7 and anyway it seems only a brute force idea. A smarter idea should be used (a counter, probably).

A second point is that we maybe should not create forwardDISET requests for this specific case.

**Comment by phicharp** [comment]
The ForwardDiset operation only has two entries:

dirac-bash-4.2$ dirac-rms-request --Job 559598198 --Verbose
Request name='00147855_00005788_job_559598198' ID=36284709 Status='Done' Job=559598198
Created 2021-12-02 21:19:06, Updated 2021-12-04 17:12:44, NotBefore 2021-12-04 17:12:18
Owner: '/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=fstagni/CN=693025/CN=Federico Stagni', Group: lhcb_mcproc
  [0] Operation Type='ForwardDISET' ID=51931580 Order=0 Status='Done'
      Created 2021-12-02 21:19:31, Updated 2021-12-04 17:12:44
      Arguments:
          [
            [
              'WorkloadManagement/JobStateUpdate'
              {
              keepAliveLapse: 150
              skipCACheck: True
              timeout: 600
              }]
            'setJobStatusBulk'
            [
              559598198
              {
              2021-12-02 21:19:03.652431: {
              MinorStatus: 'Uploading Output Sandbox'
              Source: 'JobWrapper'
              Status: 'Completing'
              }
              2021-12-02 21:19:06.358053: {
              MinorStatus: 'Output Sandbox Uploaded'
              Source: 'JobWrapper'
              Status: 'Completing'
              }
              }
              False
            ]
          ]
  [1] Operation Type='RemoveFile' ID=51931581 Order=1 Status='Done'
      Created 2021-12-02 21:18:35, Updated 2021-12-04 17:12:44
    [01] ID=139061794 LFN='/lhcb/MC/2018/SIM/00147854/0005/00147854_00054873_1.sim' Status='Done'
    [02] ID=139061795 LFN='/lhcb/MC/2018/SIM/00147854/0005/00147854_00054476_1.sim' Status='Done'
    [03] ID=139061796 LFN='/lhcb/MC/2018/SIM/00147854/0005/00147854_00054460_1.sim' Status='Done'
    [04] ID=139061797 LFN='/lhcb/MC/2018/SIM/00147854/0005/00147854_00054221_1.sim' Status='Done'
    [05] ID=139061798 LFN='/lhcb/MC/2018/SIM/00147854/0005/00147854_00054211_1.sim' Status='Done'
    [06] ID=139061799 LFN='/lhcb/MC/2018/SIM/00147854/0005/00147854_00053943_1.sim' Status='Done'
    [07] ID=139061800 LFN='/lhcb/MC/2018/SIM/00147854/0005/00147854_00053924_1.sim' Status='Done'
    [08] ID=139061801 LFN='/lhcb/MC/2018/SIM/00147854/0005/00147854_00053332_1.sim' Status='Done'
    [09] ID=139061802 LFN='/lhcb/MC/2018/SIM/00147854/0005/00147854_00053173_1.sim' Status='Done'
    [10] ID=139061803 LFN='/lhcb/MC/2018/SIM/00147854/0005/00147854_00053155_1.sim' Status='Done'

This status (as Completing) is entered in the logging info ahead of all other status changes that have status "Completed"... Not clear really what may have happened in the JobWrapper except if it succeeded to set the status but thought it didn't?

**Comment by phicharp** [comment]
Ah, no! It's just that the request was executed repeatedly :

[lbvobox309] /opt/dirac/runit/RequestManagement/RequestExecutingAgent/log $ grep 559598198 * | grep -c 'DISET forwarding done'
1293
because it is not put back when the status updated is given up.

**Comment by fstagni** [comment]
I am quite convinced that simply the order of state updates got messed up. It should never reach a point when the Status/MinorStatus pair is "Completed/Uploading Output Sandbox", while it should be 

"Completing/Uploading Output Sandbox"
"Completing/Output Sandbox Uploaded"
"Completed/Output Sandbox Uploaded"

Anyway my theory that the order got messed because the `statusDict` contains the same timestamp does not hold. So, right now I don't know anymore how this could have happened.

**Comment by phicharp** [comment]
We have another related issue: when failover requests are uploaded, the job status is set to "Completed/Pending Requests" or "Failed/Pending Requests" depending on the success of the job... If this request cannot be put for any reason (including on RequestProxy services), there is no "recovery"... This is a bit a chicken and egg problem but we had recently the case when IN2P3 had severe connectivity issues. Should there be a "recovery" when completing the request (i.e. accepting that if the minor status is not "Pending Request" we change the major status depending on the application status? Note that it is not always easy to figure out whether the job was successful or not...

**Comment by fstagni** [comment]
Closing this, but might re-open if needed.
