### ISSUE TITLE
Replace RPCClient by CLient everywhere

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#5740]
For HTTPS transition:

 * [x] Add a url parameter to `Client` constructor
 * [x] Replace all `RPCClient` instantiation with `Client` (https://github.com/DIRACGrid/DIRAC/pull/5761)
 * [x] Replace `TransferClient` with ` TransferClientSelector` (https://github.com/DIRACGrid/DIRAC/pull/5741/)

**Comment by fstagni** [comment]
Fixed in v7.3.15.
