### ISSUE TITLE
Rescheduled job is immediately killed when previous pilot stalled

### ISSUE THREAD

**Issue by hmiyake** [DIRACGrid/DIRAC#5849]
We found the case that rescheduled job is immediately killed if previous job failed by stalled pilot (i.e. "Job stalled: pilot not running").

When pilot died and StalledJobAgent marked corresponding job Failed, "Kill" is registered to JobCommand.
If the pilot is not running actually, cannot consume the job command. Finally rescheduled job (pilot) receives the command and then killed...this is my guess.

We observed this issue at DIRAC v7r1 but the workflow above is not changed in 7.3 as far as I checked...am I right?
If so can we remove "Kill" command when the job is rescheduled, or make successor job ignore commands apparently older than the job start time?

**Comment by fstagni** [comment]
JobCommand is actually not really used (the machinery is there "since ever" but the info added are actually not consumed. We have not seen such issues in 7.2 or 7.3 even though it does not mean that they are not there.

**Comment by hmiyake** [comment]
Thank you for clarification, and good to know JobCommand is not direct cause, and the issue does not widely happen.
OK we will revisit this issue after migration to 7.2/7.3 and let you know if it still persists.
