### ISSUE TITLE
Integration with RCAuth

### ISSUE THREAD

**Issue by TaykYoku** [DIRACGrid/DIRAC#5866]
# <a href=https://rcauth.eu/><img src="https://rcauth.eu/images/RCauth-eu-logo.gif" width="100"></a>
**RCAuth** issues certificates to end-entities based on a successful authentication in the appropriate Identity Provider. 

_There are many requests to integrate this tool, so this issue aims to implement it and consider conceptual issues._

## Technical details
- [RCauth.eu and MasterPortal VOPortal integration guide](https://wiki.nikhef.nl/grid/RCauth.eu_and_MasterPortal_VOPortal_integration_guide)
- [RCauth.eu and MasterPortal architecture](https://wiki.nikhef.nl/grid/RCauth.eu_and_MasterPortal_architecture)
<img src="https://wiki.nikhef.nl/grid/images/thumb/6/66/RCAuth_Prototype.svg/2016px-RCAuth_Prototype.svg.png">

Based on the recommendations in the instructions, the **DIRAC server** must be a **MasterPortal client**(OAuth 2.0 OIDC), ie **"Example Portal"**. The client registration procedure is described [here](https://cilogon.github.io/oa4mp/client/manuals/registering-with-an-oauth2-server.html).

### Limitations
- when authenticating, the service generates a very short certificate, from which you can get a maximum of **10-day** proxy certificate
- To update the certificate/proxy, the user must **re-authenticate**
- **Access token** can be used only once to obtain proxy certificate
- Generated proxy can be uploaded from `MasterPortal` through ssh with **rsakey**(`MasterPortal` can remember maximum 5 rsakeys for each user), but with rsakey it is not possible to generate a new certificate, this requires user authentication, but now from any client (not only DIRAC)

This means that in order to ensure the asynchronous operation of the user's tasks from his RCAuth certificate, the user needs to log in to DIRAC at least once a week. This will allow DIRAC to upload new proxy certificates to `ProxyManager`.

**Comment by fstagni** [comment]
...story of the past!
