### ISSUE TITLE
ElasticSearch index duplicate document

### ISSUE THREAD

**Issue by panta-123** [DIRACGrid/DIRAC#5920]
I am using ElasticsearchDB for a extended component in DIRAC.
Elasticsearch version : 6.8.9
DIRAC version: v6r22
When I index document in elasticsearch using:
https://github.com/DIRACGrid/DIRAC/blob/rel-v6r22/Core/Utilities/ElasticSearchDB.py#L266
```
def index(self, indexName, doc_type='_doc', body=None, docID=None):
```
Its calling the API in https://github.com/DIRACGrid/DIRAC/blob/rel-v6r22/Core/Utilities/ElasticSearchDB.py#L281
```
res = self.__client.index(index=indexName,
                                doc_type=doc_type,
                                body=body,
                                id=docID)
```
I am indexing the doc with mapping:
```
"_doc": {
        "properties": {
          "lpn": {
            "type": "keyword"
          },
          "bkgLevel": {
            "type": "keyword"
          },
          "dataLevel": {
            "type": "keyword"
          }
          }
          }
```
and documentID  `docID = str(lpn)`.
If i index the new document with same docID already present, it just update/replace the doc and the operation is sucessful.
What i want to do, the doc indexing must be rejected if the doc with same docID is present.
It can be achived via adding parameters `op_type = 'create'` in https://github.com/DIRACGrid/DIRAC/blob/rel-v6r22/Core/Utilities/ElasticSearchDB.py#L281 as:
```
res = self.__client.index(index=indexName,
                                doc_type=doc_type,
                                body=body,
                                id=docID,
                                op_type = 'create')
```
I will eventually use DIRAC version v7r2 in future with elasticsearch version 6.8.9. 
And i think this issue will still be there?
->  If yes, Could  this option be made available in v7r2 ?

**Comment by fstagni** [comment]
We have not changed this bit in later releases. I see no specific issues in adding the suggested parameter, would you create the Pull Request? Target `rel-v7r2` branch.

Notes:
- you are using a VERY old DIRAC release, completely un-supported. The oldest still supported release (not for long) is v7r2.
- We are dropping ES version 6 support as of DIRAC release 8.0 (which is in development).
- In general, I would suggest you migrating to OpenSearch.
