### ISSUE TITLE
UTF-8 problems with job output (mostly on python2)

### ISSUE THREAD

**Issue by sfayer** [DIRACGrid/DIRAC#5968]
Hi,

We're running v7r2p41 and we have two problems trigged by user jobs that generate UTF-8 characters in their output. We have two communities triggering these issues, so it seems it isn't a very isolated problem.

The first problem is a long log message in the pilot log generated by this line of code:
https://github.com/DIRACGrid/DIRAC/blob/336f5986a0adce9a053085192ad42f053b4555a3/src/DIRAC/Core/Utilities/Subprocess.py#L386

If the user prints a lot of long lines containing UTF-8 character(s), the pilot log can be enormous (we had a single user consume 60GB of space with these log messages in one day). Perhaps we could consider removing that log line entirely?

The bigger problem is that if a site doesn't have the LANG environment set (which isn't that uncommon), the python2 interpreter defaults to ASNI for input/output streams: This causes trouble when that unicode string is also written out.
- If the user is running their script directly as the payload, you get a second similar copy of the error (using yet more pilot log space) and the line doesn't get included in the output file (but other lines are included):
```
Unicode decode error in readFromFile (UnicodeDecodeError('ascii', '\xe2\x98\x86\nTest Done.\n', 0, 1, 'ordinal not in range(128)')): ''
Exception while calling callback function sendOutput
Traceback (most recent call last):
  File "/srv/localstage/condor/dir_21117/DIRAC_XF5BXNpilot/DIRAC/Core/Utilities/Subprocess.py", line 534, in __callLineCallback
    self.bufferList[bufferIndex][1] : self.bufferList[bufferIndex][1] + nextLineIndex
  File "/srv/localstage/condor/dir_21117/DIRAC_XF5BXNpilot/DIRAC/WorkloadManagementSystem/JobWrapper/JobWrapper.py", line 1478, in sendOutput
    print(line, file=outputFile)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2606' in position 0: ordinal not in range(128)
```

- If the user is using the Workflow Script module, it crashes writing at the end while writing the stdout/stderr files and gives a completely blank output file:
```
2022-03-17 17:00:03 UTC dirac_jobexec/Script ERROR: 'ascii' codec can't encode character u'\u2606' in position 497365: ordinal not in range(128)
Traceback (most recent call last):
  File "/srv/localstage/condor/dir_4122/DIRAC_QO0VXZpilot/DIRAC/Workflow/Modules/ModuleBase.py", line 131, in execute
    self._executeCommand()
  File "/srv/localstage/condor/dir_4122/DIRAC_QO0VXZpilot/DIRAC/Workflow/Modules/Script.py", line 116, in _executeCommand
    fopen.write(u"<<<<<<<<<< %s Standard Output >>>>>>>>>>\n\n%s " % (self.executable, stdout))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2606' in position 497365: ordinal not in range(128)
```

My suggested fix for this is that we set LANG to something like en_US.UTF-8 in the diracos1 diracosrc if it isn't already set. That way it only affects python2 versions and can still be set to more exotic things if the site really wants to. Any thoughts on this or suggestions for better ways to fix it?

Regards,
Simon

**Comment by chrisburr** [comment]
> If the user prints a lot of long lines containing UTF-8 character(s), the pilot log can be enormous (we had a single user consume 60GB of space with these log messages in one day). Perhaps we could consider removing that log line entirely?

How about modifying the message to be something like (working in both Python 2 and 3):

```python
In [1]: dataString = "x"*1000 + u"hello \u2606 world" + "x"*1000
   ...: try:
   ...:     dataString.encode("ascii")
   ...: except UnicodeEncodeError as e:
   ...:     print("Unicode decode error in readFromFile", "(%s): %r" % (e, dataString[max(0, e.start-10):e.end+10]))
   ...:
Unicode decode error in readFromFile ('ascii' codec can't encode character '\u2606' in position 1006: ordinal not in range(128)): 'xxxxhello ☆ worldxxxx'
```

> My suggested fix for this is that we set LANG to something like en_US.UTF-8 in the diracos1 diracosrc if it isn't already set.

We can't modify the Python 2 `diracosrc` witout making a new DIRACOS 1 release which very unlikely. It could be added in the default bashrc from DIRAC install else I'm pretty sure the `SiteDirector` has an option to set environment variables.

I guess none of this applies to Python 3 releases? Though if it does we can handle it much better in DIRAC v8.0 using the `errors=` keyword argument to `encode`/`decode`.

**Comment by sfayer** [comment]
> How about modifying the message to be something like (working in both Python 2 and 3):

Yes, that would halve the amount of text in the pilot log, although it's still a lot of entries if the user process is particularly noisy (one of our communities has a progress bar that's printed out every couple of seconds which contains a unicode character). It's the volume of logs generated that is the main issue here.

How about having a boolean so that the log message is only printed once for the first line that contains a unicode character and then suppressed after that?

> We can't modify the Python 2 `diracosrc` witout making a new DIRACOS 1 release which very unlikely. It could be added in the default bashrc from DIRAC install else I'm pretty sure the `SiteDirector` has an option to set environment variables.

Understood... I'm not keen on setting the environment via the SiteDirector: We then also have to tweak the cloud stuff independently, the syntax is quite messy and it doesn't fix it for anyone else. Perhaps we could include it in just the v7r2 bashrc? I imagine most people using v7r3 are also using python3, or am I being too optimistic?

> I guess none of this applies to Python 3 releases? Though if it does we can handle it much better in DIRAC v8.0 using the `errors=` keyword argument to `encode`/`decode`.

Indeed, the bulk of this is all python2 (I suspect you still get the large volume of log messages on python3 although I haven't tested it). The encoding on python3 seems to default to something UTF-8 compatible if LANG isn't set, so the errors shouldn't appear there at all (I mean there is probably still a more obscure case where the user code generates corrupt/invalid unicode characters, but that isn't an issue I've seen or really expect).

Regards,
Simon

**Comment by chrisburr** [comment]
> How about having a boolean so that the log message is only printed once for the first line that contains a unicode character and then suppressed after that?

Ah I hadn't realised the repetitiveness was an issue. Yes that seems reasonable (maybe keep the first N instances rather than a boolean).

> Perhaps we could include it in just the v7r2 bashrc? I imagine most people using v7r3 are also using python3, or am I being too optimistic?

Adding it to the bashrc generated by `dirac-install.py` should cover both v7r2 and v7r3. My bubble is biased to see the usage of Python 3 but I hope so too!

> I mean there is probably still a more obscure case where the user code generates corrupt/invalid unicode characters, but that isn't an issue I've seen or really expect

We see this occasionally in LHCb so it should partially work at the very least. (I suspect it's memory corruption in some legacy software but it's not worth debugging.)

Would you be able to take care of the PRs?

**Comment by fstagni** [comment]
If you are going to modify the (py2) `dirac-install`, remember to do it both in the https://github.com/DIRACGrid/management and https://github.com/DIRACGrid/Pilot repositories.

**Comment by sfayer** [comment]
Thanks, sure, I'll submit the PRs within the next couple of days.

Regards,
Simon
