### ISSUE TITLE
gLogger and external libraries: discrepancies

### ISSUE THREAD

**Issue by aldbr** [DIRACGrid/DIRAC#6042]
Years ago I created two methods to enable/disable logs coming from external libraries (e.g. DB12).
But apparently I forgot to properly define the default case, which can create weird situations.

Here is an example:
- In the external app:
  ```python
  logging.warn("Message coming from an external lib")
  logging.debug("Another message coming from an external lib")
  ```
- In DIRAC:
  ```python
  # self.log is in DEBUG
  self.log.info("Message")
  ```

- Situations:
  - `enableLogsFromExternalLibs` has been set:
  ```md
  2022-04-26 14:43:57 UTC ExternalLibrary/root WARN: Message coming from an external lib
  2022-04-26 14:43:57 UTC ExternalLibrary/root DEBUG: Another message coming from an external lib
  2022-04-26 14:43:57 UTC System/Component INFO: Message
  ```
  - `disableLogsFromExternalLibs` has been set:
  ```md
  2022-04-26 14:43:57 UTC System/Component INFO: Message
  ```  
  - **None of the methods is called (default and most common case):**
  ```md
  WARN:root: Message coming from an external lib
  2022-04-26 14:43:57 UTC System/Component INFO: Message
  ```

When not defined, the root of `logging` uses its default level (`WARN`) and its own format (`level:root: message`).
The question is: what should be the default behavior? `enableLogsFromExternalLibs` or `disableLogsFromExternalLibs`?

**Comment by chaen** [comment]
Naively I would go with disabling the external libs logging by default, and if the DIRAC log level, then we enable it

**Comment by chrisburr** [comment]
> Naively I would go with disabling the external libs logging by default, and if the DIRAC log level, then we enable it

I presume this should be "if the DIRAC log level _is increased_".

If so, I agree for the CLI scripts and servers but when using DIRAC as a library it shouldn't interfere with other logging handlers at all (i.e. `DIRAC.initialize` vs `DIRACScript`).

**Comment by chaen** [comment]
> I presume this should be "if the DIRAC log level _is increased_".

Oops, I meant *if the DIRAC log level is debug*

 
> If so, I agree for the CLI scripts and servers but when using DIRAC as a library it shouldn't interfere with other logging handlers at all (i.e. `DIRAC.initialize` vs `DIRACScript`).

Not sure how you would make the difference. For example:
https://github.com/DIRACGrid/DIRAC/blob/bf72397b576be7a12cbe6b9870f41ef7183668da/src/DIRAC/Resources/Storage/GFAL2_StorageBase.py#L79-L81

**Comment by aldbr** [comment]
Or may be he meant "if the DIRAC log level *is debug*"?

What about disabling the logs coming from external libraries for agents/services/CLI scripts unless the log level is `DEBUG` (or `VERBOSE`? In this case we explicitly enable it) and not configuring `logging` when DIRAC is used as a library as @chrisburr suggested?

**Comment by chaen** [comment]
> What about disabling the logs coming from external libraries for agents/services/CLI scripts unless the log level is `DEBUG` (or `VERBOSE`? In this case we explicitly enable it) and not configuring `logging` when DIRAC is used as a library as @chrisburr suggested?

but how would you manage that realistically ? The `logging` for the external library can only be configured where it is used (for example inside `GFAL2_StorageBase`) and at this stage, you lost the information about whether you are using it as a script or a library (unless we introduce a new global variable, like `DIRAC.RUN_AS_LIBRARY=True/False`, set by `initialize/parseCommandLine`

**Comment by chaen** [comment]
> when using DIRAC as a library it shouldn't interfere with other logging handlers at all

Moreover, I am not even sure I even agree with this statement.
As a user, if I have a script in which I do `import StorageElement; StorageElement('CERN-EOS').getFileSize()`, I do not want to see all the gfal2 mess

**Comment by chrisburr** [comment]
To give the reverse perspective, analysis productions and Ganga shouldn't have their logging high-jacked by DIRAC.

If gfal2 is loud when the default level is left at `WARN` then that's a bug in `gfal2`'s Python bindings.

**Comment by aldbr** [comment]
> The `logging` for the external library can only be configured where it is used (for example inside `GFAL2_StorageBase`)

Why can it be only configured from where it is used?
I might be wrong, but we could set `enable/disableLogsFromExternalLibs()` from `LocalConfiguration` (for Agents and Services) and `Script` (for CLI Script) depending on `gLogger` level for instance (the same way we do with `gLogger.showHeaders()`).
Then, if one wants to use DIRAC as a library, it is not impacted by any modification of the root logger from us.

> Moreover, I am not even sure I even agree with this statement.

Also, a good practice from the documentation that we don't follow (may be there is a good reason but I don't remember):

*It is strongly advised that you do not add any handlers other than [NullHandler](https://docs.python.org/3/library/logging.handlers.html#logging.NullHandler) to your library’s loggers. This is because the configuration of handlers is the prerogative of the application developer who uses your library. The application developer knows their target audience and what handlers are most appropriate for their application: if you add handlers ‘under the hood’, you might well interfere with their ability to carry out unit tests and deliver logs which suit their requirements.*
(https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library)

**Comment by aldbr** [comment]
1. 
I propose the following change:

- developers should stop using `enable/disableLogsFromExternalLibs()` within DIRAC (or only temporarily for debugging purposes - we could add a message in the docstrings of the methods?). As @chrisburr (following the recommended practices from the documentation) said: "DIRAC as a library shouldn't interfere with other logging handlers".
- we use `enable/disableLogsFromExternalLibs()` only from agents, services, executors and scripts. To make sure we are in this case, we could add the following lines in `LocalConfiguration.__initLogger()`:

```python
# If I'm not wrong, this code is only executed by 
# an agent/service/executor/script (when DIRAC is not used as a library)

# Disabled by default
disableLogsFromExternalLibs()

if self.__debugMode == 1:
    gLogger.setLevel("VERBOSE")    
elif self.__debugMode == 2:
    gLogger.setLevel("VERBOSE")
    gLogger.showHeaders(True)
elif self.__debugMode >= 3:
    gLogger.setLevel("DEBUG")
    gLogger.showHeaders(True)
    enableLogsFromExternalLibs()
```

What do you think?

2.

> Also, a good practice from the documentation that we don't follow (may be there is a good reason but I don't remember):

Currently, anyone using DIRAC as a library would get its log in stdout. Here is an example:

- Script using DIRAC as a library:

```python
import logging
from DIRAC import diracMethod

# root logger sends logs to a StdoutStreamHandler
logging.getLogger().addHandler(logging.FileHandler("log.txt"))

logging.info("Executing DIRAC method")
diracMethod() # gLogger.error("Error")
logging.info("Done")
```

- `log.txt`:
```md
Executing DIRAC method
Done
```

- stdout:
```md
Error
```

DIRAC logs produced by the method are not forwarded to the root logger because `LoggingRoot._logger.propagate` is `False`.
Therefore, they do not appear in `log.txt`.
Instead, DIRAC logs are displayed in stdout (default handler defined in `LoggingRoot`), which is not what the user wants.

The documentation recommends us to initialize `LoggingRoot` with a `NullHandler` instead of stopping the propagation of the DIRAC logs to the root logger.
There is actually a "good" reason for not doing that: we would lose some information by initializing the DIRAC logger with a  `NullHandler`.
When starting an agent/service for instance, here are the logs that would be lost (between `LoggingRoot.__init__()` and `LoggingRoot.initialize()`):

```md
2023-03-10 08:54:33 UTC Framework [13998464489712] DEBUG: dirac.cfg should be at ...dirac.cfg
2023-03-10 08:54:33 UTC Framework [13998464489712] DEBUG: CFG merged
2023-03-10 08:54:33 UTC Framework [13998464489712] DEBUG: Updating configuration internals
2023-03-10 08:54:33 UTC Framework [13998464489712] DEBUG: Updating configuration internals
2023-03-10 08:54:33 UTC Framework [13998464489712] DEBUG: Parsing command line
2023-03-10 08:54:33 UTC Framework [13998464489712] DEBUG: Updating configuration internals
2023-03-10 08:54:33 UTC Framework [13998464489712] DEBUG: Refreshing configuration...
2023-03-10 08:54:33 UTC Framework [13998464489712] DEBUG: Refreshing from list ['https://dirac:1234/Configuration/Server']
2023-03-10 08:54:33 UTC Framework [13998464489712] DEBUG: Randomized server list is https://dirac:1234/Configuration/Server
2023-03-10 08:54:33 UTC Framework [13998464489712] DEBUG:  Trying to refresh from https://dirac:1234/Configuration/Server
2023-03-10 08:54:33 UTC Framework/DIRAC.Core.Tornado.Client.ClientSelector [13998464489712] DEBUG: Trying to autodetect client for https://dirac:1234/Configuration/Server
2023-03-10 08:54:33 UTC Framework/DIRAC.Core.Tornado.Client.ClientSelector [13998464489712] DEBUG: Using HTTPS for service https://dirac:1234/Configuration/Server
2023-03-10 08:54:33 UTC Framework [13998464489712] DEBUG: Already given a valid url https://dirac:1234/Configuration/Server
2023-03-10 08:54:33 UTC Framework [13998464489712] DEBUG: Already given a valid url https://dirac:1234/Configuration/Server
2023-03-10 08:54:33 UTC Framework [13998464489712] DEBUG: New version available Updating to version 2023-03-10 08:24:48.501375...
2023-03-10 08:54:33 UTC Framework [13998464489712] DEBUG: Updating configuration internals
2023-03-10 08:54:33 UTC Framework [13998464489712] DEBUG: Updated to version 2023-03-10 08:24:48.501375
2023-03-10 08:54:33 UTC Framework [13998464489712] DEBUG: Updating configuration internals
```

By adding a `StdoutStreamHandler` in ` LocalConfiguration.__initLogger()` (because from here we know that we are not using DIRAC as a library(?)), we would "only" lose this portion of logs (generated by the import of `gConfig` in the main DIRAC `__init__`, here we have no way to know how we are using DIRAC):

```md
2023-03-10 08:54:33 UTC Framework [13998464489712] DEBUG: dirac.cfg should be at ...dirac.cfg
2023-03-10 08:54:33 UTC Framework [13998464489712] DEBUG: CFG merged
2023-03-10 08:54:33 UTC Framework [13998464489712] DEBUG: Updating configuration internals
2023-03-10 08:54:33 UTC Framework [13998464489712] DEBUG: Updating configuration internals
```

From here, I see different solutions:
- we keep the current solution: we don't follow the recommended practice, but so far nobody has complained. In this case, we could add documentation about how to configure DIRAC logs when using it as a library (would be tricky).
- we follow the recommendations of the documentation: we follow the recommended practice, but we lose a few logs from `gConfig` unless we integrate an environment variable (`DIRAC_INIT_LOGS`) to set up an initial handler if defined (this could be a `StdoutStreamHandler` or even something else).

Any opinion? I think I have a preference for the second solution.

**Comment by chaen** [comment]
I agree for 1.

For 2, I would stop any big change in the DIRAC logging. It's a terrible mess, yet much better than it used to be before you fixed it. And any change we do now will for sure have consequences. I think we should just leave things as they are now, and reconsider completely new options once we start discussing a new underlying framework...

**Comment by aldbr** [comment]
I am closing this issue as:
- `1.` was addressed in https://github.com/DIRACGrid/DIRAC/pull/6967
- `2.` will not be included in DIRAC as it is not a big issue.

I will be "monitoring" the use of `logging` in diracx throughout its development, to ensure that we continue to follow the recommended practices.
