### ISSUE TITLE
dirac-wms-cpu-normalization crashes with v7r3p20

### ISSUE THREAD

**Issue by hmiyake** [DIRACGrid/DIRAC#6053]
In our environment, our pilot always crashes with DIRAC v7r3p20 (python2) as follows:
```
/RClNDmfdH40n4J8tmqCBXHLnABFKDmABFKDmtEMKDmABFKDm5WCdon/DIRAC_RY0DvLpilot/DIRAC/WorkloadManagementSystem/Client/DIRACbenchmark.py", line 139, in multipleDiracBenchmark
    "median": raw[(copies - 1) / 2],
TypeError: list indices must be integers, not float
```
With v7r3p19, using singleDiracBenchmark, our pilot successfully works.
I guess // is expected to use...am I correct?

**Comment by aldbr** [comment]
Indeed, `//` was expected.
I just created a PR to fix the issue.
