### ISSUE TITLE
Singularity needs to mount local directory to use File storage plugin

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#6074]
We have the possibility to define a File storage plugin to directly access files using posix file system.
However, when running singularity container, the local folder is not mounted. 

Singularity needs to look at the list of local SEs, check if any has the File protocol enabled, and if so, mount it.
I can provide a utility the necessary directory but I would not know where to call it.

**Comment by chrisburr** [comment]
I presume these are always read-only? If so, on the singularity side it just needs `["--bind", f"{path}:{path}:ro"]` to be added to the new command for each path like this:

https://github.com/DIRACGrid/DIRAC/blob/7ff48a8793617ce3e111edc4e3ee4daa47e01e82/src/DIRAC/Resources/Computing/SingularityComputingElement.py#L400-L401

**Comment by chaen** [comment]
Actually I am just thinking of a use case where this does not work: the case where SRM returns us the `file` protocol. And we unfortunately can't always replace it with the `File` plugin (this is the case at CNAF for the moment).
So two options: 
* We have a list of mountpoint in the CE configuration (not incompatible with discovering them automatically btw)
* We look at the mountpoints on the worker node, and selectively bind them. That may prove tricky though

Any thoughts ?

**Comment by chrisburr** [comment]
> We have a list of mountpoint in the CE configuration (not incompatible with discovering them automatically btw)

The manual case is addressed by having a Site and CE specific `ContainerBind` parameter (https://github.com/DIRACGrid/DIRAC/pull/6252).
