### ISSUE TITLE
PilotLogger - How to identify pilots in an early submission state

### ISSUE THREAD

**Issue by martynia** [DIRACGrid/DIRAC#6077]
### Discussed in https://github.com/DIRACGrid/DIRAC/discussions/6075

<div type='discussions-op-text'>

<sup>Originally posted by **martynia** May 13, 2022</sup>
Hi,

In my work on remote pilot logging I identified the following problem: 
  In the original extended (==remote) logger, which is now being removed, pilots were identified by a UUID. The UUID was created by ExtendedLogger and saved to a file, so it could be accessed easily. I used the UUID to identify pilot files shipped to Tornado. From an old description by the original author this was supposed to be a reliable way to identify pilots. But even then, the UUID generated this way had nothing to do with the pilot reference stored in the PilotDB. In the current setup pilot reference is known only when ConfigureSite command is run, so quite late. This created a problem, when pilot dies early - we have no way to identify it. On the other hand even in an early stage the pilot reference is displayed as a frame title in the WebApp, so there must be a way to get it early. One of the possibility would be moving the code of `__setFlavour` method from ConfigureSite command to SiteDirector and use it, but it looks like a cumbersome solution. Or create a thin command which is run first and just gets required info from the CE ?

Thanks, JM</div>

**Comment by fstagni** [comment]
Should https://github.com/DIRACGrid/DIRAC/pull/6405 solve this issue?

**Comment by martynia** [comment]
Yes.
I tested it for ARC and HTCondor CEs
J.

**Comment by fstagni** [comment]
IIUC (and correct me if I am wrong) with #6405 we created effectively an alternative way to identify the pilots:
- The *PilotReference* (saved as `PIlotJobReference` in PilotAgentsDB) is a CE-specific, unique reference that existing computing element implementations use.
- The _PilotStamp_ (saved as `PilotStamp` in PilotAgentsDB) is a DIRAC-generated stamp, created by simply calling `makeGuid[:8]`. This is saved (and/or supposed to be found) in the pilot environment as `$DIRAC_PILOT_STAMP`. 

SiteDirectors are aware of both identifiers above and register the pilots to the PilotAgentsDB. 

Pilots do not necessarily know about their own *PilotReference*, but as of today "deduct" it through the `__setFlavour` [method](https://github.com/DIRACGrid/Pilot/blob/master/Pilot/pilotCommands.py#L757) mentioned above, which IMO is rather error-prone. This is then used at server side, by the Matcher. This way of doing things is not only error-prone, but also can't work when Pilots are started in the vacuum.

I suggest to remove the `__setFlavour` method from the Pilot code, and always use the  _PilotStamp_ to identify Pilots inside DIRAC. The problem I see is that this would work only when the server is updated to v8.0. @atsareg let me know if you have comments.

PR related to this, on the server side: https://github.com/DIRACGrid/DIRAC/pull/6914

**Comment by fstagni** [comment]
Moving from using, inside DIRAC, from *PilotReference* to *PilotStamp* also means that several updates would need to be done to how `PilotAgentsDB` work (many of its methods assume that a *PilotReference* exists, and it is there to identify uniquely a Pilot.

**Comment by chrisburr** [comment]
> The _PilotStamp_ (saved as `PilotStamp` in PilotAgentsDB) is a DIRAC-generated stamp, created by simply calling `makeGuid[:8]`. This is saved (and/or supposed to be found) in the pilot environment as `$DIRAC_PILOT_STAMP`.

I don't think `makeGuid[:8]` is sufficient for a unique identifier. It has 8 hex digits so 32-bits of entropy. If you have 100,000 pilots you have a ~70% of having a two or more pilots with the same identifier.

**Comment by chaen** [comment]
Absolutely !! Just don't truncate the `makeGuid`

**Comment by fstagni** [comment]
I think fixed by https://github.com/DIRACGrid/DIRAC/pull/6914
