### ISSUE TITLE
MultiVOMetadata - build-in fields are also expanded with a VO specific suffix

### ISSUE THREAD

**Issue by martynia** [DIRACGrid/DIRAC#6092]
Build-in fields (like CreationDate) are also expanded here:

[(https://github.com/DIRACGrid/DIRAC/blob/6764f043334b7d90f28df8fa7b62e41e1cb835c9/src/DIRAC/DataManagementSystem/DB/FileCatalogComponents/DirectoryMetadata/MultiVODirectoryMetadata.py#L25)](https://github.com/DIRACGrid/DIRAC/blob/6764f043334b7d90f28df8fa7b62e41e1cb835c9/src/DIRAC/DataManagementSystem/DB/FileCatalogComponents/DirectoryMetadata/MultiVODirectoryMetadata.py#L25)

As the result of this, a search by date does not work.

cheers, JM

**Comment by marianne013** [comment]
@fstagni et al:
Is there a list of all the built-in fields ?

**Comment by andresailer** [comment]
https://github.com/DIRACGrid/DIRAC/blob/6764f043334b7d90f28df8fa7b62e41e1cb835c9/src/DIRAC/DataManagementSystem/Client/MetaQuery.py#L15-L31

Not sure if this is the same for the directory metadata

**Comment by martynia** [comment]
Let me look into this tonight.
JM

**Comment by fstagni** [comment]
Was this fixed at the end?

**Comment by martynia** [comment]
Yes. In #6180
