### ISSUE TITLE
[integration] Cannot kill or delete jobs from webinterface

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#6097]
I'm trying to delete a job of mine on https://lbcertifdirac70.cern.ch via the web interface, but I get the error:
Error: You are nonauthorized to delete jobs with JobID: [4769]
I checked and I am assigned to the  dirac_admin group in the web browser.

**Comment by TaykYoku** [comment]
It looks like this issue has a common reason with https://github.com/DIRACGrid/WebAppDIRAC/issues/653

**Comment by fstagni** [comment]
> It looks like this issue has a common reason with [DIRACGrid/WebAppDIRAC#653](https://github.com/DIRACGrid/WebAppDIRAC/issues/653)

Then I close this task to avoid duplications (it is linked anyway)
