### ISSUE TITLE
python3 support in cloudBootstrap

### ISSUE THREAD

**Issue by zhangxiaomei** [DIRACGrid/DIRAC#6163]
The current version of CloudBootstrap can't support python3.  If need to support python3,  I found the following to be added in cloudBootstrap:
(1) Cloudinit parameters need to import the parameter pythonVersion
(2) In the file "vm-bootstrap-functions", vm_dirac_install() need to add python3 DIRAC install
(3) In the file "vm-pilot", dirac-pilot need to have an option to provide pythonVersion 
(4) dirac-pilot need to have "pilot.json",  which can use "curl" to get from pilotFileServer in "vm-bootstrap"

**Comment by sfayer** [comment]
Hi,

We're not really supporting the CloudBootstrap scripts any more. If you would like to patch them to work with python3 then I'm sure that would be accepted, otherwise I suggest switching to the cloud-init based contextualisation (`Operations/<setup>/Cloud/BootType = cloudinit`) instead, which does support python3. I'm not sure there is any complete documentation for this, but it's this code path: https://github.com/DIRACGrid/DIRAC/blob/071f15869e1ccd70599026d70446d8cb21bc71f0/src/DIRAC/Resources/Cloud/Endpoint.py#L54
which loads this default template for VM initialisation (although the template location can be changed if you want it to use a different one):
https://github.com/DIRACGrid/DIRAC/blob/integration/src/DIRAC/Resources/Cloud/cloudinit.template

(This also neatly leads on to a migration to CloudCE which only supports a similar cloud-init style contextualisation, so if you can get it working with VMDIRAC/CloudDirector, it should just continue to work if you move to CloudCE in the future).

Regards,
Simon

**Comment by zhangxiaomei** [comment]
Thank you for the suggestion.  In my case, it is working with cloudBootstrap after fixed.  When I  directly changed to the cloudinit mode (Operations/<setup>/Cloud/BootType = cloudinit), it failed and I even failed to login VMs to have a look with previous password. Is there any documents to understand how to write my own cloudinit from cloudinit.template, or need some different configurations to make it working in this mode? Thank you!

**Comment by zhangxiaomei** [comment]
I didn't use SSH key since the cloud we connected is in remote and we can only login in with control console from web page.  From the control console the only way I get in is to use user/passwd.  Any suggestions?

**Comment by sfayer** [comment]
Hi,

Can you please try copying the `Resources/Cloud/cloudinit.template` to a different name and set `CITemplate` in your cloud resource settings to contain the full path to the new file.

You can then edit the template to add a user with a password, something like:
```yaml
users:
- name: debuguser
  sudo: ALL=(ALL) NOPASSWD:ALL
  shell: /bin/bash
  plain_text_passwd: passwordfordebugaccount
```
The full documentation for the user section is here:
https://cloudinit.readthedocs.io/en/latest/topics/modules.html#users-and-groups

I'm a little surprised your cloud doesn't allow you SSH access (I've never seen a cloud set-up like that before), do they not let you add a floating IP to an instance to allow an SSH login for debugging?

Regards,
Simon

**Comment by zhangxiaomei** [comment]
Sorry to reply late!  The clouds we used are two private cloud inside institutes and haven't enabled the floating IP.  
I just have a try today with the new cloudinit.template adding:
users:
4647  - name: dirac
4648    sudo: ALL=(ALL) NOPASSWD:ALL
4649    shell: /bin/bash
4650    plain_text_passwd: xxxxxxxx
But in the log, I found the error of creating vms:
"4654 2022-07-01 06:51:14 UTC WorkloadManagement/CloudDirectorJUNO/CloudEndpoint [140392722462528] VERBOSE: name: DIRAC_A34359B3
4655 2022-07-01 06:51:16 UTC WorkloadManagement/CloudDirectorJUNO/CloudEndpoint [140392722462528] ERROR: Exception in driver.create_node 403 Forbidden Maximum number of ports exceeded
4656 2022-07-01 06:51:16 UTC WorkloadManagement/CloudDirectorJUNO [140392722462528] ERROR: Failed submission to queue cloud-areapd.pd.infn.it_CentOS7-cloudinit-ihep1:
4657  403 Forbidden Maximum number of ports exceeded"

**Comment by sfayer** [comment]
The "Maximum number of ports exceeded" usually means you've reached the neutron port quota limit on the cloud... You can check the current value and maximum on the OpenStack dashboard overview page. (It's not related to the cloud-init stuff, that happens much later in the boot process).

Regards,
Simon

**Comment by zhangxiaomei** [comment]
You are right.  I can't create VMs from the dashboard because of the same problem.  But the overview page said only 1/3 ports was used.  I contacted the cloud admin and retried later.

**Comment by zhangxiaomei** [comment]
VMs are created, but cloudinit has problems. I try to understand the problem. Here is the screenshot from control console.
![image](https://user-images.githubusercontent.com/1860588/177709134-a05cf03c-9e7e-444f-bcc3-5116f88f452f.png)

**Comment by sfayer** [comment]
OK, that's looking a bit promising... It's mainly having trouble with the dirac user permissions: I think what's happening is that your extra user with the password set for debugging is called dirac, but the cloud pilot start-up also tries to create the dirac user, so two things happen:
 * The script expects the home directory to be in /mnt, but as the user already exists this doesn't get created with the correct permissions (which is why you're seeing the permission denied errors).
 * It also locks the dirac user account, so you won't be able to login with the password either.

I suggest that you try changing your test user to "diracdebug" or something else (anything other than just "dirac")... After that you should be able to login with the password on the console and see why the pilot isn't working.

Regards,
Simon

**Comment by zhangxiaomei** [comment]
I add "- [ chown, -R, "dirac:dirac", /mnt/dirac]" and am able to use another user instead of "dirac" to login. I am able to see the pilots start to run, but look like having problems to find dirac.cfg under diracos:
![image](https://user-images.githubusercontent.com/1860588/177733999-d86b2866-3f83-414d-8d80-888517ec730d.png)

**Comment by sfayer** [comment]
OK, that's looking close to working...

Do you have a queue defined in your DIRAC Configuration system for this site? The thing it's looking for is:

`/Resources/Sites/CLOUD/CLOUD.INFN-PADOVANA.it/CEs/cloud-areapd.pd.infn.it/Queues/Cloud`

(If that doesn't exist, it falls through to looking for VMTypes and things, but it's better to do it in the standard non-VMDIRAC way as it's then easier to switch to CloudComputingElement in the future)

This should contain just the minimal settings that all DIRAC sites and queues would normally contain, specifically you need the following settings:

```
/Resources/Sites/CLOUD/CLOUD.INFN-PADOVANA.it/CEs/cloud-areapd.pd.infn.it
 - CEType = VMDIRAC (or anything that doesn't match an existing CEType)
 - Architecture = x86_64
 - OS = <whatever you normally set for OS or Platform on other sites>
 Queue/
    Cloud/
       - maxCPUTime = <maximum job runtime in minutes, we set this to the very large value 24000000>
```

You can test if this is working from any v7r3 client UI (no need to run a full VM until it works), just run the dirac-resource-get-parameters by hand:
`dirac-resource-get-parameters -S CLOUD.INFN-PADOVANA.it -N cloud-areapd.pd.infn.it -Q Cloud -d`

If it's working, it should return a JSON document describing the queue, for example this is what it looks like for one of our clouds:
```
$ dirac-resource-get-parameters -S CLOUD.UKI-LT2-IC-HEP-lz.uk -N iccloud.gridpp.ac.uk -Q CentOS-7-x86_64-GenericCloud-1905 -d
{"CEType": "VMDIRAC", "Architecture": "x86_64", "OS": "EL7", "maxCPUTime": "24000000", "Tag": ["HighMem"], "Queue": "CentOS-7-x86_64-GenericCloud-1905"}
```

Regards,
Simon

**Comment by zhangxiaomei** [comment]
Yes, I have also realized that.  My configuration is really a little bit not mapping with your description:
![image](https://user-images.githubusercontent.com/1860588/177745268-a275e94f-964c-4749-a9c4-7a1b6d52af31.png)

Now I fixed "cloud-areapd.pd.infn.it" to "Cloud", and it is working with the command:
(base) -bash-4.2$ dirac-resource-get-parameters -S CLOUD.INFN-PADOVANA.it -N cloud-areapd.pd.infn.it -Q Cloud -d
{"CEType": "Cloud", "Architecture": "x86_64", "maxCPUTime": "24000000", "Queue": "Cloud"}

I continued to see the progress in VMs.

**Comment by zhangxiaomei** [comment]
With the above configuration,  I can't see the queue for this cloud in RSS and only see the queue "Cloud" for all the cloud.  It must be something wrong with it.

**Comment by zhangxiaomei** [comment]
getVMTypes() looks fine:
'VMTypes': {'WN-CentOS78-NEW2-DIRAC': {'Image': 'WN-CentOS78-NEW2-DIRAC', 'ImageName': 'WN-CentOS78-NEW2-DIRAC', 'FlavorName': '1-4-40', 'VO': 'juno, bes, cepc', 'Platform': 'x86_64_CentOS_Core_7.9'}

**Comment by zhangxiaomei** [comment]
Not quite understand in CloudEndpoint.py the VMType was assigned to CEType:
CloudEndpoint.py:        self.parameters["VMType"] = self.parameters.get("CEType", "OpenStack")

**Comment by zhangxiaomei** [comment]
I modified " -Q "%(vmtype)s" " in cloudinit.template to be  "-Q "%(image-name)s" " (in bootype=pilot, use image-name instead of vmtype for queue name),  VMs now can work with the original queue name.

**Comment by zhangxiaomei** [comment]
The problem with RSS was also found. It is caused by the wrong configuration: the section "CEs" should be in parallel with "Cloud".

**Comment by fstagni** [comment]
Hello, updates on this? Is your setup working now or there's still an issue?

**Comment by zhangxiaomei** [comment]
@sfayer  It is fully working with CloudDirector? Do I need to continue migrating to CloudCE?
Another thing, in my case,  in cloudinit.template,  we work only with -Q "%(image-name)s"  instead of -Q "%(vmtype)s" :
  python dirac-pilot.py \
          --pythonVersion=3 \
          --setup %(setup)s \
          -r %(release-version)s \
          --MaxCycles %(max-cycles)s \
          --configurationServer %(cs-servers)s \
          --Name "%(ce-name)s" \
          --name "%(dirac-site)s" \
          -Q "%(image-name)s" \
           --cert \
           --userEnvVariables DIRACSYSCONFIG:::/mnt/dirac/pilot.cfg \
           -o /LocalSite/VMID=%(vm-uuid)s \
           -o /LocalSite/LocalCE=%(ce-type)s \
           -o /Resources/Computing/CEDefaults/VirtualOrganization=%(vo)s \
           -o /Resources/Computing/CEDefaults/WholeNode=%(whole-node)s \
           -o /Resources/Computing/CEDefaults/ContainerRoot=%(user-root)s
Do I need to create a pull request on that? or GridPP works in other ways?

**Comment by sfayer** [comment]
> @sfayer It is fully working with CloudDirector now. Do I need to continue migrating to CloudCE?

Eventually yes: The CloudDirector will be removed in future versions, being replaced with standard SiteDirector + CloudCE (you can either use the same SiteDirector you do for the grid or have a separate instance just for cloud submission based on the CETypes parameter).

I suggest trying out CloudCE in the near future even if you don't fully migrate immediately just to check that it works for your set-up before CloudDirector is removed entirely (and if it doesn't work, let me know so it can be improved!).

> Another thing, in my case, in cloudinit.template, we work only with -Q "%(image-name)s" instead of -Q "%(vmtype)s": Do I need to create a pull request on that? or GridPP works in other ways?

Perhaps @atsareg can comment on this one? It was originally image-name, but he changed it to vmtype in pull request #5500 ( https://github.com/DIRACGrid/DIRAC/pull/5500/commits/4111faec18f4e0078441b1f489286ab7e9be408e ). In the GridPP case, these seem to be set to the same thing (both work), so I'm not sure what the difference between them elsewhere is.
(CloudCE also doesn't use either of them due to its use of the standard pilot wrapper which has the queue set from the SiteDirector automatically).

Regards,
Simon

**Comment by zhangxiaomei** [comment]
@sfayer  I just saw a new problem:  the VMs can't shutdown itself correctly after jobAgent finished its cycles.
![image](https://user-images.githubusercontent.com/1860588/187810968-3e8f3fcc-0238-4f30-94cf-971441e8e902.png)
Am I missing something?

**Comment by sfayer** [comment]
What should happen is that the VirtualMachineMonitor agent should detect the JobAgent isn't running any more and shutdown the machine... The logs for this should be in `/mnt/monitor/monitor_start.log` and `/mnt/monitor/runit/VirtualMachineMonitorAgent/log/current`: There is probably an error in one of those that will indicate why it didn't work.

A workaround you can do is to simply add `- [ poweroff ]` to the very end of the template (in the runcmd section); this is the default in the CloudCE template but we didn't backport it to VMDIRAC for a couple of reasons (it leaves the database entries for the VMs in the wrong state and makes it harder to debug some kinds of failures).

Regards,
Simon

**Comment by zhangxiaomei** [comment]
I  found the problem: In /root/run_monitor.sh provided in the CloudCE template, it should be:
-pip install "DIRAC==%(release-version)s" 
+pip install "IHEPDIRAC==%(release-version)s"
After fixing that, it works now.

**Comment by zhangxiaomei** [comment]
@sfayer  In the monitoring log, it looks like it is halting the instance:
![image](https://user-images.githubusercontent.com/1860588/188383733-190fb6a9-f908-4639-86f2-3f048b7155d2.png)
 but the VMs didn't get halted, there is an ERROR which I don't know if it is the reason:
![image](https://user-images.githubusercontent.com/1860588/188382662-0c447943-d916-41d7-853a-6c0ba042d19b.png)

**Comment by sfayer** [comment]
Hi,

Hmm, it looks like the halt line was left commented out, I've put in a pull request to re-enable it:
https://github.com/DIRACGrid/DIRAC/pull/6353
(You could potentially patch it from the cloudinit.template, either directly or by installing a pre-patched DIRAC version for the VMM but it's much easier to wait and use an officially released version).

The error you see later is a side-effect rather than the cause: The VMM keeps running (because the machine hasn't halted) and a minute later it tries to send a "still running" heartbeat, but that fails because an instance marked as halted in the database can't then switch back to the running state.

Regards,
Simon

**Comment by zhangxiaomei** [comment]
"simply add - [ poweroff ] to the very end of the template (in the runcmd section)" didn't work completely.  The VMs are closed and still occupied resource, but not are completely deleted as before. Do you know what happened? @sfayer

**Comment by sfayer** [comment]
Hi,

With the poweroff at the end, the instances should go into the OpenStack "SHUTOFF" state; this prevents the VMM agent from sending any further heartbeats. After a set amount of time (default is 40 minutes, although the function is only called every 15 minutes, so maximum wait time is 55 minutes), the database should transition them to stalled:
https://github.com/DIRACGrid/DIRAC/blob/573913cf4268779d85c0bd334c6a47697195aabf/src/DIRAC/WorkloadManagementSystem/DB/VirtualMachineDB.py#L43
https://github.com/DIRACGrid/DIRAC/blob/573913cf4268779d85c0bd334c6a47697195aabf/src/DIRAC/WorkloadManagementSystem/DB/VirtualMachineDB.py#L336

This should then be removed by the VirtualMachineManager service:
https://github.com/DIRACGrid/DIRAC/blob/573913cf4268779d85c0bd334c6a47697195aabf/src/DIRAC/WorkloadManagementSystem/Service/VirtualMachineManagerHandler.py#L105

If it isn't happening within about an hour of the instance shutting down, it's probably worth checking the VirtualMachineManager log files for any errors.

This mechanism has all been redesigned in the CloudCE to make it quicker and more reliable.

Regards,
Simon

**Comment by zhangxiaomei** [comment]
The further halting was not happened.  I don't see any errors in the log of VirtualMachineManager except:
WorkloadManagement_VirtualMachineManager/log/@400000006315667a141c5e6c.s:2022-09-05 03:01:04 UTC WorkloadManagement/VirtualMachineManager NOTICE: Returning response ([::ffff:192.168.90.58]:43682)[hosts:cloudvm] (0.55 secs) ERROR: Transition ( Halted -> Running ) not allowed
@sfayer

**Comment by sfayer** [comment]
The error implies there is an instance still running after it has tried to shutdown, which isn't really a problem (it should still be removed as stalled after about an hour). Are you able to check what state some of the problem VMs are in on both OpenStack and the DIRAC VirtualMachine database?

Regards,
Simon

**Comment by zhangxiaomei** [comment]
These problem VMs is shown "shutdown" in OpenStack and "stalled" in database:
mysql> select * from vm_Instances where Name="679AC199";
+------------+------------+----------+-------------------------------------------------+--------------------------------------+-----------+---------+---------------------+-----------------+-------------+--------------+-----------------+--------+------+------+
| InstanceID | RunningPod | Name     | Endpoint                                        | UniqueID                             | VMImageID | Status  | LastUpdate          | PublicIP        | PrivateIP   | ErrorMessage | MaxAllowedPrice | Uptime | Load | Jobs |
+------------+------------+----------+-------------------------------------------------+--------------------------------------+-----------+---------+---------------------+-----------------+-------------+--------------+-----------------+--------+------+------+
|    1683225 | juno       | 679AC199 | CLOUD.INFN-PADOVANA.it::cloud-areapd.pd.infn.it | 79f14521-9a39-4043-a604-bb410bf72787 |         7 | Stalled | 2022-09-07 14:47:29 | 193.206.210.240 | 10.64.17.12 |              |            NULL |  22868 |    0 |    2 |
+------------+------------+----------+-------------------------------------------------+--------------------------------------+-----------+---------+---------------------+-----------------+-------------+--------------+-----------------+--------+------+------+

**Comment by zhangxiaomei** [comment]
I also set the log to debug mode for the VirtualMachineManager.  I don't see any DELETE or UPDATE operations on these "stalled" VMs, just SELECT.

**Comment by zhangxiaomei** [comment]
@sfayer  It looks like some old problem VMs can't get cleaned and stuck the VirtualMachineManager. I updated some old VMs state from "stalled" to "halted" manually in the database, and I begin to see some VMs get deleted now.
mysql> select * from vm_Instances where Status="Stalled" limit 10;
+------------+------------+----------+--------------------------------------+----------+-----------+---------+---------------------+----------+-----------+--------------+-----------------+--------+------+------+
| InstanceID | RunningPod | Name     | Endpoint                             | UniqueID | VMImageID | Status  | LastUpdate          | PublicIP | PrivateIP | ErrorMessage | MaxAllowedPrice | Uptime | Load | Jobs |
+------------+------------+----------+--------------------------------------+----------+-----------+---------+---------------------+----------+-----------+--------------+-----------------+--------+------+------+
|     882387 | juno       | 36402A3E | CLOUD.JINRONE.ru::jinrone-opennebula | 179510   |         2 | Stalled | 2020-04-20 14:29:05 |          |           |              |            NULL |      0 |    0 |    0 |
|     882390 | juno       | DD5F7BE4 | CLOUD.JINRONE.ru::jinrone-opennebula | 179511   |         2 | Stalled | 2020-04-20 14:29:05 |          |           |              |            NULL |      0 |    0 |    0 |
|     882402 | juno       | 1C278C56 | CLOUD.JINRONE.ru::jinrone-opennebula | 179515   |         2 | Stalled | 2020-04-20 14:29:06 |          |           |              |            NULL |      0 |    0 |    0 |
|     882404 | juno       | B6DAA772 | CLOUD.JINRONE.ru::jinrone-opennebula | 179516   |         2 | Stalled | 2020-04-20 14:29:06 |          |           |              |            NULL |      0 |    0 |    0 |
|     882410 | juno       | B4ACB84A | CLOUD.JINRONE.ru::jinrone-opennebula | 179517   |         2 | Stalled | 2020-04-20 14:29:06 |          |           |              |            NULL |      0 |    0 |    0 |
|     882982 | juno       | 590FE78C | CLOUD.JINRONE.ru::jinrone-opennebula | 179779   |         2 | Stalled | 2020-04-20 21:14:05 |          |           |              |            NULL |      0 |    0 |    0 |
|     882983 | juno       | 4BCA19A2 | CLOUD.JINRONE.ru::jinrone-opennebula | 179780   |         2 | Stalled | 2020-04-20 21:14:05 |          |           |              |            NULL |      0 |    0 |    0 |
|     882984 | juno       | 10CBD7C1 | CLOUD.JINRONE.ru::jinrone-opennebula | 179781   |         2 | Stalled | 2020-04-20 21:14:05 |          |           |              |            NULL |      0 |    0 |    0 |
|     882985 | juno       | 5AB51815 | CLOUD.JINRONE.ru::jinrone-opennebula | 179782   |         2 | Stalled | 2020-04-20 21:14:05 |          |

**Comment by sfayer** [comment]
Hi,

Once a machine is in the stalled state, it should have been removed already: If it's still on openstack and setting it back to halted then causes it to get deleted, that implies the first delete failed for some reason.

Can you please add some print statements around this block and see what happens for future VMs? (I'm not sure deletion error messages are particularly well reported otherwise):
https://github.com/DIRACGrid/DIRAC/blob/9670cea6cf65cdb7efa978ab7113e468df8caa3b/src/DIRAC/WorkloadManagementSystem/Service/VirtualMachineManagerHandler.py#L180-L185

My best guess is that it's trying to delete too many in one go or something like that.

One of the faults in this code is that the delete is a one-time operation: If it fails the VMs get left behind. The new CloudCE implementation doesn't have this problem, it fetches the current state from the cloud every ~20 minutes and will retry deletes if the instances haven't been removed.

Regards,
Simon

**Comment by zhangxiaomei** [comment]
I have added print messages to the VirtualManagerHandler.py and found there are about 470 problem VMs which keep reporting errors and the new VMs have been stopped successfully.   It looks like the only way to get rid of these problem VMs is to delete from database. No idea why these problem VMs were there. @sfayer

**Comment by zhangxiaomei** [comment]
I have just deleted all the problemetic VMs in the database and looks fine.  I closed the issue.
