### ISSUE TITLE
Queue specific XRSLExtraString?

### ISSUE THREAD

**Issue by sfayer** [DIRACGrid/DIRAC#6260]
Hi,

Is is possible to set the XRSLExtraString at the queue level, e.g. for specifying a high memory queue or one that asks for a GPU on a CE that also has a general queue? The documentation seems to imply this isn't possible:

https://github.com/DIRACGrid/DIRAC/blob/ab13ec3615fad7e45e126cb4c8d67aab51927277/src/DIRAC/Resources/Computing/ARCComputingElement.py#L151-L154

This search order also seems to be inconsistent with other options: The natural search order for all other CE parameters is:
`...CE.../<Queue>, ...Site.../<CE>, Computing/<CEType>, Computing/CEDefaults`
Is there a reason why this one option/parameter is different?

Including @marianne013 in the discussion.

Regards,
Simon

**Comment by fstagni** [comment]
I made similar comment in https://github.com/DIRACGrid/DIRAC/pull/5542#discussion_r885573160 but no answer.

**Comment by sfayer** [comment]
Adding @rajanandakumar to this ticket.
I agree that it should be as simple as looking it up in self.ceParameters across all of the ARC CE versions (and updating any associated documentation / release notes for people who already have it set).
Perhaps this could be discussed at the next BiLD meeting?

Regards,
Simon

**Comment by rajanandakumar** [comment]
Hi @sfayer , @fstagni and @marianne013 ,

Apologies - I did not see this before as I was not (yet) working on it, waiting for the DIRAC certification instance to come up. Now, I am getting around to the different points one-by-one.

I am currently working on the AREXComputingElement and assume that this is soon going to replace the ARCComputingElement for most, if not all sites. Given this, how important is it to backport the option to ARCComputingElement?

Cheers,
Raja.

**Comment by fstagni** [comment]
What is wrong with the DIRAC certification setup? It has been used successfully for running DIRAC certifications. Also the LHCbDIRAC one should be OK.

> how important is it to backport the option to ARCComputingElement?

It is not "necessary" as we have of course been living with it for a long while. It is anyway rather easy to do it, I think.

**Comment by rajanandakumar** [comment]
Hi,

Thanks for the pointer about self.ceParameters. What information does it give? I have tried to print it out on the test system and I am basically getting what I am guessing is garbage.

- I have put in a test XRSLExtraString but that does not get printed out
- The dictionary does contain MaxTotalJobs (and other such parameters) which seem to be incorrect, looking at the configuration.

Cheers,
Raja.

**Comment by fstagni** [comment]
> Hi,
> 
> Thanks for the pointer about self.ceParameters. What information does it give? I have tried to print it out on the test system and I am basically getting what I am guessing is garbage.

It should give at runtime all info that are for the CE (and the queue) that are stored in the CS.

> 
> * I have put in a test XRSLExtraString but that does not get printed out
> * The dictionary does contain MaxTotalJobs (and other such parameters) which seem to be incorrect, looking at the configuration.
> 

Can you try to investigate further?

**Comment by rajanandakumar** [comment]
Okay - so, I try to print out the following

```        print(self.ceHost)
        print(self.ceParameters)
        print(self.mandatoryParameters)
```
and I get the following

```
arc-ce-test02.gridpp.rl.ac.uk
{'OutputURL': 'gsiftp://localhost', 'MaxTotalJobs': 100, 'MaxWaitingJobs': 10, 'WaitingToRunnin
gRatio': 0.02, 'FileCatalog': 'FileCatalog', 'Site': 'lhcbvoboxcertif00.cern.ch', 'SharedArea':
 '/cvmfs/lhcb.cern.ch/lib/'}
['Queue']

```

Now, if I look at the CS, the MaxTotalJobs should be either 2500 or 0 (depending on the queue) and the MaxWaitingJobs is 100 or 500 for the above CE.

So, what could be going on here?

Cheers,
Raja.

**Comment by rajanandakumar** [comment]
Okay - it is kind of understood then after I trawled through the whole of the configuration. The numbers printed out are from the CEDefaults. They are not coming from the actual CE information.

So, a bug somewhere preventing the actual CE information coming from the CS and populated only by the CEDefaults? Should I open a bug report?


Cheers,
Raja.

**Comment by fstagni** [comment]
I believe that this issue can now be closed, as solved as explained above.
