### ISSUE TITLE
[v7r3] Rucio integration is broken with Python 2

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRAC#6264]
Since v7r3 the rucio integration uses the `default_extract` keyword argument with `extract_scope` however this was added in `ruico-clients` 1.27. This is fine except DIRACOS contains 1.26 so the option isn't available.

I've added a hack in #6262 (8a5623aa2) to get the CI passing again however this needs to be reverted and the underling issue fixed.

**Comment by cserf** [comment]
Just noticed this ticket. It looks like this `default_extract` was introduced in https://github.com/rucio/rucio/commit/1c2c8e4292ae2a67e9f6d64d56a5657c7813dfbe by @martynia 
Can we update to use `1.27.x` ?

**Comment by chrisburr** [comment]
DIRACOS v1.x (i.e. the only supported way of using DIRAC with Python 2) is now archived and is unlikly to be revived for an update. If anyone wants DIRAC + Python 2 + Rucio to work they'll need to find another solution (or try to revive DIRACOS 1 themselves).

**Comment by chrisburr** [comment]
During the BiLD everyone was happy for this to only work with Python 3 so closing.
