### ISSUE TITLE
python3 version of v7r3p25 not commited properly

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#6273]
I'm trying to install v7.3.25 from git, but it isn't having it. The python2 version looks fine:

https://github.com/DIRACGrid/DIRAC/tree/v7r3p25 -> Commit 68303d3 -> All fine
https://github.com/DIRACGrid/DIRAC/tree/v7.3.25 -> Commit 22a06a2 -> Yellow
warning bar: Commit isn't in repo, it'll work on github but not any client.

@atsareg Could you please have a look ?
@sfayer FYI

**Comment by chrisburr** [comment]
It looks like v7.3.25 is basically the same as v7.3.24 (which also explains why some bugs I expected to be fixed weren't).

I can't see the GitHub security logging for DIRACGrid but from the CI log it looks like `v7r3p25` was originally tagged as 22a06a2 and then deleted. As mentioned on many occasions in the past, we should never retag commits as the CI cannot handle it (and even if it could PyPI refuses to allow versions to be replaced to avoid security issues of known-good versions being replaced with malicious ones).

```
  /usr/bin/git checkout --progress --force refs/tags/v7r3p25
  Note: switching to 'refs/tags/v7r3p25'.
  
  You are in 'detached HEAD' state. You can look around, make experimental
  changes and commit them, and you can discard any commits you make in this
  state without impacting any branches by switching back to a branch.
  
  If you want to create a new branch to retain commits you create, you may
  do so (now or later) by using -c with the switch command. Example:
  
    git switch -c <new-branch-name>
  
  Or undo this operation with:
  
    git switch -
  
  Turn off this advice by setting config variable advice.detachedHead to false
  
  HEAD is now at 22a06a2 docs: DIRAC release v7r3p25 notes and tags
```

@atsareg Can you confirm that you retagged `v7r3p25` and make a new `v7r3p26` that contains the expected changes?

**Comment by chrisburr** [comment]
Actually the code on PyPI is what is expected to be there as the deployment CI for https://github.com/DIRACGrid/DIRAC/commit/22a06a25442014fbd0a7ff759829f88984b00c49 [failed due to a conflict with the tag](https://github.com/DIRACGrid/DIRAC/runs/7387653786?check_suite_focus=true) so it's only the v7.3.25 tag which is in an inconsistent state. Regardless it still shouldn't be changed as it affects anyone who has pulled the repository in the last few days.

**Comment by atsareg** [comment]
I can not think of retagging the v7r3p25, but may be I did something wrong. I have tagged and created a new v7.3.26 release with the latest merges. Sorry for the mess
