### ISSUE TITLE
Avoid logging sensitive information

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRAC#6290]
Currently it's possible for sensitive information to be accidentally logged in various places such SQL queries:

```
DEBUG: _update: REPLACE INTO `ProxyDB_VOMSProxies` ( UserName, UserDN, UserGroup, VOMSAttr, Pem, ExpirationTime ) VALUES (***REDACTED***)
```

This mostly affects debug logging so it's rare to be running, though as we move to more centralised logging it would be good to minimise the risk of leaks.

From searching online it the solution I've found is to use a custom logging formatter which can then remove patterns like `-----BEGIN CERTIFICATE-----.*?-----END CERTIFICATE-----`.

**Comment by aldbr** [comment]
We can have many different formatters and handlers, each of them would have to implement an internal "filter", which does not sound very convenient.
IMHO, a custom filter attached to `gLogger` seems more generic: 
- https://docs.python.org/3/howto/logging-cookbook.html#using-filters-to-impart-contextual-information
- https://docs.python.org/3/howto/logging.html#logging-flow

I am going to make some tests.
