### ISSUE TITLE
Nested PoolCE / SingularityCE Issues (Job 0 has no specified executable)

### ISSUE THREAD

**Issue by sfayer** [DIRACGrid/DIRAC#6308]
Hi,

I'm trying to set-up nested Pool/Singularity pilots on a cloud (CloudCE submission) but the user jobs fail to run: They stick in the "Submitted to CE" state and eventually get rescheduled.

I did some digging through the logs and I found that the Singularity side of things is getting a JobID of 0 and no job details, so it fails with this as the inner-most error:
```
2022-08-11 11:32:55 UTC None/JobWrapper[0] INFO: Starting Job Wrapper Initialization for Job0
2022-08-11 11:32:55 UTC None/JobWrapper[0] INFO: JobID is not defined, running in current directory
2022-08-11 11:32:56 UTC None/JobWrapper[0] INFO: Job Wrapper is starting execution phase for job 0
2022-08-11 11:32:56 UTC None/JobWrapper[0] INFO: Job has no CPU time limit specified,  applying default of 600 to 0
2022-08-11 11:32:56 UTC None/JobWrapper[0] WARN: Job 0 has no specified executable
Failed to execute job Job 0 has no specified executable
```
I spent some time adding some print-outs in the code and found that this bit of the PoolCE is dropping a lot of the job details that are handed to the InnerCE:
https://github.com/DIRACGrid/DIRAC/blob/8c4a5547d115b210a90802d7189b2b8f2914b084/src/DIRAC/Resources/Computing/PoolComputingElement.py#L145-L146

I wrote a naive patch to forward more of the job details through to the inner layer:
```patch
--- a/src/DIRAC/Resources/Computing/PoolComputingElement.py
+++ b/src/DIRAC/Resources/Computing/PoolComputingElement.py
@@ -68,7 +68,7 @@ def executeJob(executableFile, proxy, taskID, inputs, **kwargs):
     else:
         ce = InProcessComputingElement("Task-" + str(taskID))
 
-    return ce.submitJob(executableFile, proxy, inputs=inputs)
+    return ce.submitJob(executableFile, proxy, inputs=inputs, **kwargs)
 
 
 class PoolComputingElement(ComputingElement):
@@ -144,6 +144,7 @@ class PoolComputingElement(ComputingElement):
 
         # Here we define task kwargs: adding complex objects like thread.Lock can trigger errors in the task
         taskKwargs = {"InnerCESubmissionType": self.innerCESubmissionType}
+        taskKwargs["jobDesc"] = kwargs.get("jobDesc", {})
         if self.innerCESubmissionType == "Sudo":
             for nUser in range(MAX_NUMBER_OF_SUDO_UNIX_USERS):
                 if nUser not in self.userNumberPerTask.values():
```

With this patch it all seems to work correctly. My question is really: Have I misunderstood how this works? If not, should I be opening a pull request with that patch?

Regards,
Simon

**Comment by sfayer** [comment]
Ah, I forgot to say, this is on 7.3.26!

**Comment by fstagni** [comment]
I see nothing wrong with your proposed patch. Go ahead!
