### ISSUE TITLE
Cancellation of FTS3 job when request is cancelled?

### ISSUE THREAD

**Issue by sfayer** [DIRACGrid/DIRAC#6360]
Hi,

We have a large number of RMS file transfer requests submitted by an end user (we're running v7r3 with FTS3 agent backend), but due to SE TPC interoperability problems they aren't transferring correctly. The requests were cancelled, but this left the FTS jobs in the queue: These are going to take a long time to complete as they're staging the files from tape at the source.

I had a look and couldn't find any reference in the code to cancelling an FTS job if the RMS operation is cancelled, is this a feature that exists and if not, would it be possible to implement it?

Regards,
Simon

**Comment by chaen** [comment]
@sfayer would you have a chance to try https://github.com/DIRACGrid/DIRAC/pull/6371 ?
I did this a bit quickly but haven't had time to properly test it.

**Comment by sfayer** [comment]
Sure, I've given it a go... It seems to work to me: I submitted a large job (with failing transfers) and cancelled it part way through successfully with it cancelling the FTS jobs as expected.

I wasn't able to do a test of cancelling a successful job part way through to check things ended consistently: Every successful job I ran finished too quickly to get the cancellation through before it finished.

Regards,
Simon

**Comment by sfayer** [comment]
Fixed by #6371.
