### ISSUE TITLE
Creation of real releases "deployment" GitHub Actions

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#6362]
We now have a "rel-v8r0" branch from which we can create production releases, that should be done through the "deployment" actions

2 issues:
- the creation of the v8.0.0 tag worked only if starting from the _integration_ branch (for today it was possible because the content of _integration_ was identical to _rel-v8r0_). It is probably a simple change to be done in this line https://github.com/DIRACGrid/DIRAC/blob/rel-v8r0/.github/workflows/deployment.yml#L67 [@chrisburr ]
- the release notes of the created release on https://github.com/DIRACGrid/DIRAC/releases/tag/v8.0.0 would be fine if we were creating a patch (a "diff" from the previous tag that was v8.0.0a29) but not for a minor/major release where it should be a diff from the last non-pre-release patch. At the same time that has the risk of being "huge" so what to do? We simply edit the release on github? [@andresailer ]

**Comment by andresailer** [comment]
Release Notes: 
* Merging release notes by hand would be most straight forward
* Huge could be an issue, because we would need pagination to go through the PRs and tags, or some other logic change in the script

**Comment by chrisburr** [comment]
I think both points have now been adressed and the 8.0.1 release went through smoothly.
