### ISSUE TITLE
Presumably wrong order of checking VO information

### ISSUE THREAD

**Issue by IgorPelevanyuk** [DIRACGrid/DIRAC#6400]
Hello, 

I have just installed DIRAC 7.3.29. During installation it was necessary to set VirtualOrganization parameter. Since we have multiVO setup I have just put there some general value(name of organization)

But after installation during dirac-dms-add-file that general VO name was used no matter which proxy I used. I found the source of problem: 
https://github.com/DIRACGrid/DIRAC/blob/073655c5ab05ae8d270295b5ca20cc297f5bbbba/src/DIRAC/ConfigurationSystem/Client/Helpers/Registry.py#L423

And getVO from CSGlobal just does that:
https://github.com/DIRACGrid/DIRAC/blob/073655c5ab05ae8d270295b5ca20cc297f5bbbba/src/DIRAC/ConfigurationSystem/Client/Helpers/CSGlobals.py#L22

I have just commented out all occurances of DIRAC/VirtualOrganization parameter. So, VO check works for me now. But, maybe CS.Client.Helpers.Registry should just check VO in different order? First check value from Registry/Groups/{group}/VO and then get data from VirtualOrganization parameter.

**Comment by fstagni** [comment]
Hi,

> I have just commented out all occurances of DIRAC/VirtualOrganization parameter

What do you mean? That you had to remove the config entry `DIRAC/VirtualOrganization` from the CS?

**Comment by fstagni** [comment]
Anyway, from BiLD:

> VirtualOrganization parameter should not be defined for multi-VO installations, then there is no problem with the wrong order of VO evaluation.

**Comment by IgorPelevanyuk** [comment]
Thanks Federico for reply! Ok, I will add this information to documentation.
