### ISSUE TITLE
Remove master branch?

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRAC#6424]
I'm not sure the `master` branch serves any purpose now that DIRAC 8.0 has been released. What do people think about removing it?

**Comment by fstagni** [comment]
It is (only) used by readthedocs as far as I remember.

**Comment by chrisburr** [comment]
Ah yes I'd forgotten about that, I'd suggest changing that to use `integration` by default.

**Comment by chrisburr** [comment]
Alternatively if we want to show something else we should be able to get the desired effect using: https://docs.readthedocs.io/en/stable/automation-rules.html

**Comment by fstagni** [comment]
The idea was to always show with "latest" the most recent production release, so `integration` is not the correct branch. 

Automation rules could be used to hide too old (un-supported) versions @andresailer

**Comment by andresailer** [comment]
* added an automation rule to update the "latest" to the latest release branch.
* There already was a rule to create new active versions when new branches are made
* cannot add a rule to hide unsupported version. Rules only act on new branches or tags, or removal of tags or versions. As we shouldn't delete branches, we cannot unpublished automatically.

**Comment by chrisburr** [comment]
> we cannot unpublished automatically

I think this is desirable and effectively what we already did. While we're looking at it, shall we remove `rel-v7r1`/`rel-v7r0`/`rel-v6r22` from readthedocs?

**Comment by andresailer** [comment]
Fine for me to remove those

**Comment by fstagni** [comment]
Yes, please do remove them.

**Comment by andresailer** [comment]
They are gone now.
