### ISSUE TITLE
diracdoctools Command Reference title 

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#6455]
While trying to fix up the COMDIRAC documentation ready for merging, I noticed that all commands (e.g.
https://dirac.readthedocs.io/en/latest/Commands/index.html#dirac-dms-add-file
) end up with "Accounting" in the title bar.
I think this is set in diracdoctools/cmd/commandReference.py, but all  my creative efforts to get it to display something sensible, i.e.the actual Section it's in (here: "DataManagement") have failed. 
Probably one for @andresailer

**Comment by andresailer** [comment]
All the command details are now on a single page, which probably doesn't have a good parent section and It ends up the accounting for alphabetical reasons.

**Comment by marianne013** [comment]
Yes, I tried to change that so that the overall title would be "Command Reference" (if you scroll all the way up, it's actually there), but I suspect I got confused with the =/-/@ syntax.
