### ISSUE TITLE
v8.1 (and possibly earlier): pilots fail on ARC-CE with proxy not found

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#6467]
Converted from https://github.com/DIRACGrid/DIRAC/discussions/6465

I noticed on the DIRAC certification server that a lot (though not all) pilots on ARC-CEs fail with "proxy not found" in the pilot log.
They start running, but then never pick up a job and eventually reach the Failed state.
I tried to work out what the difference was between jobs that succeeded and those that failed. I had some luck, though some of these might be red herrings.
a) Adding (runTimeEnvironment="ENV/PROXY") as an XRSLExtraString in CEDefaults
This seemed to make jobs at Glasgow work. Though at least one job (but only one) had worked before I made this change.
b) PoolCE: I initially suspected using this as the LocalCEType was necessary, however this does not seem to be the case (i.e. it makes no difference to whether it is working or not)
c) ARC-CEs with more than one queue. RALPP was configured to have a multi-core and a single core each per CE (heplnx07 still is). This mimics the setup with have on the GridPP production server and it works without a problem. However I only managed to get some (but still not all ?) pilot jobs running at RALPP on CEs where I changed the configuration to only have one queue.

Both sites work fine with the GridPP production server (v7r3, without the ExtraString and with multiple queues per CE), so I don't think it's a site issues.

**Comment by fstagni** [comment]
I don't how using PoolCE would make any difference. 
You are mentioning: 
> I tried to work out what the difference was between jobs that succeeded and those that failed. I had some luck, though some of these might be red herrings.

so what are the differences?

And BTW, can you try moving (some) of these CEs to `ARC6` instead of `ARC`?

**Comment by marianne013** [comment]
@fstagni 
I mean the two things I tried: - the ENV/PROXY and the only one queue per CE.
But my point is that I *don't* need to do these things on the production server and those CEs work fine and that even *with* these changes I can't make Janusz' stuff work. Have a look at the certification server to see what I mean. 
I'm going to put RALPP on the production server back to what it was, as we need the multi-queue per CE to work.
If ARC6 is going to work, that's fine, but then we need to disable the other mechanism, plus I don't think we should certify a realease that doesn't work on ARC.

**Comment by rajanandakumar** [comment]
Hi @marianne013 

Just to confirm - is this the EGI DIRAC certification instance?

Cheers,
Raja.

**Comment by fstagni** [comment]
No, the DIRAC certification instance: https://lbcertifdirac70.cern.ch/

**Comment by marianne013** [comment]
I double check my production server and I don't have "ENV/PROXY" set anywhere in the configuration. I still left it in on the certification server. 
I wasn't able to get the SiteDirector to print the rsl it submits to ARC, even when setting the log level to DEBUG, I had to put in a print statement. The output from this print statement seems to suggest that the rsl is fine:
```
&(executable="DIRAC_qyt4u8o6_pilotwrapper.py")
(inputFiles=(DIRAC_qyt4u8o6_pilotwrapper.py "/opt/dirac/work/WorkloadManagement/SiteDirectorGridpp/DIRAC_qyt4u8o6_pilotwrapper.py") )
(stdout="E3839161.out")
(stderr="E3839161.err")
(outputFiles=("E3839161.out" "") ("E3839161.err" ""))
(queue=condor)


(runTimeEnvironment="ENV/PROXY")
```

**Comment by fstagni** [comment]
After the last hackathon, is this behavior still there? 
And BTW @aldbr introduced recently few more fixes in https://github.com/DIRACGrid/DIRAC/pull/6558

**Comment by marianne013** [comment]
@martynia: Can you try and do a merge/rebase on your pilot logging machine and see if the ARC jobs now work ?
On the certification server that was kind of lost in the ARC6/AREX transition.
I can run a test on the certification machine with RALPP (not RAL-LCG2) set to the old ARC (as their AREX setup isn't working) and check if it's resolved in integration.

**Comment by martynia** [comment]
Rebase w.r.t. what ? I would really like a v8 machine, so I could also handle @chaen Tornado log fixes.

**Comment by marianne013** [comment]
I'll happily upgrade diractest to v8.0 for you. You just have to put all your code actually in git, because it will involve wiping the DIRAC directory.

**Comment by martynia** [comment]
I committed one change (Andrei's fix for ARC and pilot ID), anything else may go. I hope I'll be able to submit jobs ...

**Comment by fstagni** [comment]
I believe this is solved...
