### ISSUE TITLE
Bug in ComputingElementFactory?

### ISSUE THREAD

**Issue by rajanandakumar** [DIRACGrid/DIRAC#6471]
https://github.com/DIRACGrid/DIRAC/blob/f0077ecc350e8a4c3f994415efe39a6b344b90c5/src/DIRAC/Resources/Computing/ComputingElementFactory.py#L56

Hi,

In line 55, the "result" does not contain the keyword "OK". As a result, the setting of the ceParameters is failing. And as a further result, the AREX CE is not being instantiated.

Cheers,
Raja.

**Comment by andresailer** [comment]
~~What is the traceback for the exception that should come a few lines later~~
https://github.com/DIRACGrid/DIRAC/blob/f0077ecc350e8a4c3f994415efe39a6b344b90c5/src/DIRAC/Resources/Computing/ComputingElementFactory.py#L61 
Sorry, doesn't make sense. traceback will point to line 55

Which computing element is tried to be instantiated?

**Comment by sfayer** [comment]
Hi Raja,

I suspect the _reset() function of the CE needs to return S_OK() rather than a plain type (which is then eventually returned via the default ComputingElement.setParameters function to this bit of code).

Regards,
Simon

**Comment by rajanandakumar** [comment]
@andresailer It is the AREX computing element that I am testing.

@sfayer Thanks a lot - that was the problem. Guru level debugging - thanks!

Cheers,
Raja.
