### ISSUE TITLE
Issue when using self-signed CA

### ISSUE THREAD

**Issue by IgorPelevanyuk** [DIRACGrid/DIRAC#6474]
Hello, dear colleagues,

In our installation there is a need in using our own CA which is not present in EGI certificate list. In version v7r0p26 the following approach was working: 
1. We generate certificate diracCA_cert.pem
2. We put it in /opt/dirac/etc/grid-security/certificates and also create link to it: 9ccdc0aa.0 -> /etc/grid-security/certificates/diracCA_cert.pem
After restart DIRAC would accept certificates from this CA as correct. 

Now I have tried to make something similar on 7.3.29. And something strange happening.
If I upload certificate to my browser, I can connect to WebApp with no problem:
```
2022-10-31 10:52:39 UTC WebApp/RootHandler INFO: AUTH OK: /Authentication by user101@dirac_user (/C=RU/O=JINR/OU=DIRAC SelfSigned CA/CN=user101/emailAddress=gavelock@gmail.com)
2022-10-31 10:52:39 UTC WebApp/Web NOTICE: 200 GET /DIRAC/s:JINR-Production/g:dirac_user/Authentication/getCurrentAuth?_dc=1667213559973 (159.93.40.159) user101@dirac_user (/C=RU/O=JINR/OU=DIRAC SelfSigned CA/CN=user101/emailAddress=gavelock@gmail.com) 2.85ms
```
But if I try to generate proxy or configure client with this certificate I see the error related to the fact that peer closed connection. Following example from dirac-proxy-init -g dirac_user: 
```
Generating proxy...
Can't contact DIRAC CS: Reason(s):
        Peer closed connection
```

Does anybody faced similar issue? Or may be there is some other, more correct way to work with personal CA?

Kind regards,
Igor Pelevanyuk

**Comment by chaen** [comment]
Hi Igor,

We do that constantly for integration tests, including with latest releases.
Please see https://github.com/DIRACGrid/DIRAC/blob/2df1b85d3d6208378a50cd44b8c5b6be468e5a04/tests/Jenkins/utilities.sh#L347-L519

**Comment by fstagni** [comment]
@IgorPelevanyuk , does this issue still need to be open?

**Comment by IgorPelevanyuk** [comment]
Yes, the issue was fixed. I needed to ensure that diracCA files present both on server and client

**Comment by IgorPelevanyuk** [comment]
@chaen Thank you!

**Comment by maxnoe** [comment]
Hi,

I am running into the same issue in a docker based setup. I have the server certificates on the client, I tried both in

```
/etc/grid-security/certificates
```

and 

```
/home/dirac/diracos/etc/grid-security/certificates
```
where diracos is installed.

Any pointers for debugging this would be appreciated!

**Comment by IgorPelevanyuk** [comment]
@maxnoe 
For me that was enough. Let me ask if you created hash link to the certificate in these directories?

**Comment by maxnoe** [comment]
Hi,

Turns out docker was using old certificates in the build cache. Clearing everything and restarting made it work.
