### ISSUE TITLE
DIRAC logger to use the ISO 8601

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#6493]
In order to use the ISO 8601 format and microseconds. If this is done, then all log messages will have the same format.

**Comment by aldbr** [comment]
Alright, just to make sure I understand correctly, you want this kind of format right?

```bash
<YYYY>-<MM>-<DD>T<hh>:<mm>:<ss>Z (because it is UTC)
2008-03-01T13:00:00Z
```

> all log messages will have the same format

Do we already have some logs following this format?

**Comment by fstagni** [comment]
Logs from the Pilots, introduced by @martynia with https://github.com/DIRACGrid/Pilot/pull/158/files (which was also merged in `master` branch later).

**Comment by martynia** [comment]
In pilot we have timestamps with microseconds:

2023-02-14T10:34:30,470959Z

.. and a continental decimal comma ...
