### ISSUE TITLE
Provide minimal support for non-DIRAC DIRAC client 

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#6496]
Provide minimal support for non-DIRAC DIRAC client (solving [Submitting DIRAC jobs via HTTP](https://github.com/DIRACGrid/DIRAC/discussions/6121) and more). A good starting point would be to provide instructions on how to do it for read-only operations, e.g. for monitoring.

**Comment by fstagni** [comment]
So, jobs submission can't work ATM because in `JobManagerHandler` there is this:

```python
    def initializeRequest(self):
        credDict = self.getRemoteCredentials()
        self.ownerDN = credDict["DN"]
        self.ownerGroup = credDict["group"]
```

But of course the correct `credDict["group"]` would normally be added by DIRAC's own "dirac-login/dirac-proxy-init". Since here we are doing `voms-proxy-init`, the DIRAC group is not added.

We might or we might not fix this specific case -- maybe just wait for tokens.

**Comment by chaen** [comment]
Hum, I manage to submit:

```python
import json
import os
import requests

jdl="""
JobName = "DIRAC_lkreczko_642778";
Executable = "/bin/ls";
Arguments = "-ltrA";
StdOutput = "std.out";
StdError = "std.err";
OutputSandbox = {"std.out","std.err"};
"""

def _query(url, params):
    capath="/etc/grid-security/certificates"
    cert=f"/tmp/x509up_u{os.getuid()}" # TODO: default path should be /tmp/x509up_u<user id>
    with requests.post(url, data=params, cert=cert, verify=capath) as r:
        return r.text


def submit_job(server, jdl):
    url=f"https://{server}:8443/WorkloadManagement/JobManager"
    params = { "method": "submitJob", "args": json.dumps([jdl])}
    return _query(url, params)


if __name__ == "__main__":
    server = "lbcertifdirac70.cern.ch"
    result = submit_job(server, jdl)
    # result = get_jobs(server)
    # result = get_files(server)
    print(result)
```

```bash
[chaen@lxplus7111 ~]$ python /tmp/chaen/test.py                                                                                                                                              
{"OK": true, "Value": 5777, "JobID": 5777, "requireProxyUpload": false}
```

but then the job is failed with `No VirtualOrganization defined in manifest`

**Comment by fstagni** [comment]
There will be no further/planned push for this in DIRAC. DiracX (https://github.com/DIRACGrid/diracx) will provide the above natively.
