### ISSUE TITLE
Docs: No configuration info AREX in AdministrotorGuide/ComputingElements (or anywhere)

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#6497]
Hi,

I wanted to try out the new AREX Computing Element, but there seems to be no information on how to configure ARCs of any kind in
https://dirac.readthedocs.io/en/integration/AdministratorGuide/Resources/computingelements.html
A search over the whole document didn't unearth any configuration documentation for AREX either. 

(I noticed the CloudComputingElement is missing from the AdministratorGuide  as well, even though the documentation exists (https://dirac.readthedocs.io/en/latest/CodeDocumentation/Resources/Computing/CloudComputingElement.html), I will try and submit a fix to include the link in the documentation in the Administrator Guide.)

Probably one for @rajanandakumar

**Comment by rajanandakumar** [comment]
Hi @marianne013 

Apologies for missing this. I will be submitting the update for the documentation shortly. In the meanwhile, I  attach it below and hope that this is enough. Do let me know if you would like anything to be added here.

Edit - apologies for the formatting below. I understand this is the format of the documentation.

Cheers,
Raja.

```rst
AREX Computing Element
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
By default, bulk of the configuration is performed in the CE itself. Most of the generic defaults
apply to this CE too. Things that are specific to this computing element are :
   # Section placed in the */Resources/Sites/<domain>/<site>/CEs* directory
   AREXCE.site.country
   {
     CEType = AREX
    }

This CE is now written to follow the DIRAC guidelines - so, it should pick up the ceParameters
correctly. For specific customisation, the following parameters can be provided

"RESTEndpoint"      - CE is Queried if not available in CS
        - The endpoint we talk to
"Port" - The port that the REST interface of the CE listens to.
        - Defaults to 443 (I think)
"XRSLExtraString" - Default = ""
        - Any CE specific string with additional parameters
"XRSLMPExtraString" - Default = ""
        - Any CE specific string with additional parameters for MP jobs
"ARCRESTTimeout"    - DEfault = 1.0 (seconds)
        - Timeout for the rest query
"proxyTimeLeftBeforeRenewal" - Default = 10800 (seconds)
        - As the name says
````

**Comment by marianne013** [comment]
@rajanandakumar @andresailer is the documentation expert, but it looks fine to me :-)
Would you be able to configure and test a CE on the certification server (https://lbcertifdirac70.cern.ch/DIRAC/) ? Maybe one of the RALPP ones (heplnx208 ?). Chris Brew is usually fairly responsive if there are problems.

**Comment by rajanandakumar** [comment]
Hi @marianne013 ,

Thanks. As I have mentioned in slack, I don't yet have any karma to work on the dteam test server. It works with the RAL tier-1 CEs. I have not yet had the chance to test with the RAL PPD CEs.

Cheers,
Raja

**Comment by marianne013** [comment]
@rajanandakumar Sorry, didn't see the Slack (I only see the DIRAC certification and then I only look at them during the hackathon unless someone tags me). Maybe @fstagni could give you access before tomorrow ? RALPP is also configured for the gridpp VO, so you can use that for testing as well.

**Comment by fstagni** [comment]
@rajanandakumar you are registered in DIRAC test server with DN `/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=nraja/CN=471708/CN=Raja Nandakumar`. Do you mean that you are not in `dteam` VO?

**Comment by rajanandakumar** [comment]
Hi Federico,

I am definitely in the dteam VO. And it works today - something that definitely did not happen a week ago. I will take a look.

Cheers,
Raja.

**Comment by andresailer** [comment]
As I wrote in slack, I added you to some groups.

**Comment by marianne013** [comment]
@rajanandakumar and/or @aldbr I think this fell of the radar, at least I can't see any documentation. Given that AREX more or less works now, could you please submit a pull request for the documentation ?

**Comment by aldbr** [comment]
This PR contains documentation about `ARC6` and `AREX`: https://github.com/DIRACGrid/DIRAC/pull/6646

**Comment by aldbr** [comment]
@marianne013 may I close this issue?
