### ISSUE TITLE
Expand integration tests for IaM

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#6625]
The integration tests (https://github.com/DIRACGrid/DIRAC/actions/workflows/integration.yml) should be expanded with interactions with IAM and CheckIn. 

For IAM, a docker container is provided: https://indigo-iam.github.io/v/v1.8.0/docs/getting-started/docker/
I could not find one for CheckIn yet.

This starts by adding to https://github.com/DIRACGrid/DIRAC/blob/integration/tests/CI/docker-compose.yml

**Comment by aldbr** [comment]
Should we close this issue?
