### ISSUE TITLE
getFile  to have  `diskOnly`  option .

### ISSUE THREAD

**Issue by panta-123** [DIRACGrid/DIRAC#6700]
For the getFile method :
https://github.com/DIRACGrid/DIRAC/blob/1c35b44cd3cf8a2402d5dc477002c8fa1b35a59b/src/DIRAC/DataManagementSystem/Client/DataManager.py#L309 .
We want to have `diskOnly` option so that we can avoid any TAPE Only replica download.
The internal fucntion used in getFile Method like:
https://github.com/DIRACGrid/DIRAC/blob/1c35b44cd3cf8a2402d5dc477002c8fa1b35a59b/src/DIRAC/DataManagementSystem/Client/DataManager.py#L1551 

https://github.com/DIRACGrid/DIRAC/blob/1c35b44cd3cf8a2402d5dc477002c8fa1b35a59b/src/DIRAC/DataManagementSystem/Client/DataManager.py#L1695

Uses the option `diskOnly`.  

Target v7r3 and above

**Comment by chaen** [comment]
Hi @panta-123 , feel free to make a PR, that will surely be accepted :-)
