### ISSUE TITLE
FileHelper.networkToString does not work at DIRAC v7.3

### ISSUE THREAD

**Issue by hmiyake** [DIRACGrid/DIRAC#6724]
In our DIRAC v7.3 environment, FileHelper.networkToString() fails by following error:

```
2023-01-25 04:36:49 UTC ProductionManagement/ProductionManager ERROR: Uncaught exception when serving Transfer fromClient
Traceback (most recent call last):
  File "/opt/dirac/versions/v5.6.0.dev1-1663776348/Linux-x86_64/lib/python3.9/site-packages/DIRAC/Core/DISET/RequestHandler.py", line 198, in __doFileTransfer
    uRetVal = self.transfer_fromClient(fileInfo[0], fileInfo[1], fileInfo[2], fileHelper)
  File "/opt/dirac/versions/v5.6.0.dev1-1663776348/Linux-x86_64/lib/python3.9/site-packages/BelleDIRAC/ProductionManagementSystem/Service/ProductionManagerHandler.py", line 508, in tran
sfer_fromClient
    ret = fileHelper.networkToString(self.__maxUploadBytes)
  File "/opt/dirac/versions/v5.6.0.dev1-1663776348/Linux-x86_64/lib/python3.9/site-packages/DIRAC/Core/DISET/private/FileHelper.py", line 149, in networkToString
    result = self.networkToDataSink(stringIO, maxFileSize=maxFileSize)
  File "/opt/dirac/versions/v5.6.0.dev1-1663776348/Linux-x86_64/lib/python3.9/site-packages/DIRAC/Core/DISET/private/FileHelper.py", line 183, in networkToDataSink
    dataSink.write(strBuffer)
TypeError: string argument expected, got 'bytes'
```
It is called from transfer_fromClient function of our own service:
```
def transfer_fromClient( self, fileId, token, fileSize, fileHelper ):
...
        ret = fileHelper.networkToString(self.__maxUploadBytes)
```

By replacing StringIO with six.BytesIO at DIRAC/Core/DISET/private/FileHelper.py, it worked.
```
def networkToString(self, maxFileSize=0):
        """Receive the input from a DISET client and return it as a string"""

        #stringIO = StringIO()
        stringIO = six.BytesIO()
```
Same error occurred at stringToNetwork, called from our own transfer_toClient
```
    def stringToNetwork(self, stringVal):
        """Send a given string to the DISET client over the network"""

        #stringIO = StringIO(stringVal)
        stringIO = six.BytesIO(stringVal)
```

Although I want to open PR, I wonder if it affects others.
For example the latter is used by DIRAC/DataManagementSystem/Service/FileCatalogHandler.py
Furthermore this change may not match with function name...

Of course for the latter, I can avoid to give bytes but string, but the former is not controllable...

What is better way to resolve the issue?

**Comment by andresailer** [comment]
Can you try with the changes in #6720

**Comment by hmiyake** [comment]
Mmm... I applied same change as #6720, but
```
2023-01-26 16:17:09 UTC ProductionManagement/ProductionManager ERROR: Uncaught exception when serving Transfer fromClient
Traceback (most recent call last):
  File "/opt/dirac/versions/v5.6.0.dev1-1663776348/Linux-x86_64/lib/python3.9/site-packages/DIRAC/Core/DISET/RequestHandler.py", line 198, in __doFileTransfer
    uRetVal = self.transfer_fromClient(fileInfo[0], fileInfo[1], fileInfo[2], fileHelper)
  File "/opt/dirac/versions/v5.6.0.dev1-1663776348/Linux-x86_64/lib/python3.9/site-packages/BelleDIRAC/ProductionManagementSystem/Service/ProductionManagerHandler.py", line 508, in transfer_fromClient
    ret = fileHelper.networkToString(self.__maxUploadBytes)
  File "/opt/dirac/versions/v5.6.0.dev1-1663776348/Linux-x86_64/lib/python3.9/site-packages/DIRAC/Core/DISET/private/FileHelper.py", line 151, in networkToString
    result = self.networkToDataSink(stringIO, maxFileSize=maxFileSize)
  File "/opt/dirac/versions/v5.6.0.dev1-1663776348/Linux-x86_64/lib/python3.9/site-packages/DIRAC/Core/DISET/private/FileHelper.py", line 188, in networkToDataSink
    dataSink.write(strBuffer)
TypeError: string argument expected, got 'bytes'
```
Probably because networkToString still gives six.StringIO (i.e. io.StringIO in py3) to networkToDataSink...

**Comment by hmiyake** [comment]
As for stringToNetwork, I confirmed error is gone if I certainly give string (previously it was bytes in my code...), so no modification would be necessary.

**Comment by andresailer** [comment]
Are things working for you now? Including when #6720 is applied? Or are there still changes needed in DIRAC?

**Comment by hmiyake** [comment]
No, I can avoid trouble of stringToNetwork by choosing adequate type but networkToString does not work even after #6720 applied. So I think similar recipe as #6720 is necessary for the function.

**Comment by andresailer** [comment]
I am writing tests for this FileHelper Module, but I am having a hard time to figure out how to make it call `stringToNetwork` and `networkToString` isn't used anywhere in DIRAC as far as I could see.

**Comment by hmiyake** [comment]
Yes, networkToString is not utilized by vanilla DIRAC while stringToNetwork is used by 
DataManagementSystem/Service/FileCatalogHandler.py, though the usage seems very minor.
In my extension, networkToString is called in transfer_fromClient() of my ServiceHandler.
Similar usage (transfer_fromClient) is found from SandboxStoreClient, ProxyStorage, and DIPStorage but unfortunately I cannot find corresponding tests...I guess it is not easy to run the test of the functionality.

**Comment by andresailer** [comment]
The test for DIPStorage are added in #6745, a bit hard to tell directly but the tests talk to the StorageElement set up in the integration tests, which is a DIPStorage.

@chaen Does the getSEDump function still work for you in LHCbDIRAC? As far as I understand this is only implemented for the LHCb FileCatalog thingies? And that's the only thing that uses `stringToNetwork`...

**Comment by andresailer** [comment]
If I manually trigger the code path for `stringToNetwork` in the FileCatalogHandler transfer_toClient things are working as is (not something I see how to make automatic).

@hmiyake Can you just fix `networkToString` for your use case? If no-one else is using it...

**Comment by chaen** [comment]
Oh yes it works, and being used ! :-) 
And `stringToNetwork` is extensively used in LHCbDIRAC

**Comment by andresailer** [comment]
But what about `networkToString` in LHCbDIRAC?

**Comment by andresailer** [comment]
Looking for networkToString and stringToNetwork in LHCbDIRAC master branch now yields one result for `stringToNetwork` and none for `networkToString`
```
LHCbDIRAC (master)$ git grep -e stringToNetwork -e networkToString 
src/LHCbDIRAC/BookkeepingSystem/Service/BookkeepingManagerHandler.py:        retVal = fileHelper.stringToNetwork(fileString)
LHCbDIRAC (master)$ 
```
Did I miss anything?

So @hmiyake can fix networkToString for BelleDIRAC?

**Comment by hmiyake** [comment]
OK, I'll open PR of networkToString by recipe above.

**Comment by hmiyake** [comment]
Opened #6762

**Comment by fstagni** [comment]
I think this can be closed now (still pending a release, though)
