### ISSUE TITLE
COMDIRAC: improvements wishlist

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#6746]
PR https://github.com/DIRACGrid/DIRAC/pull/6403 merged the COMDIRAC package in DIRAC v8.0 release series. As agreed verbally, the merging could be done without big modifications. Nevertheless, for release v8.1 the following list of tasks will be needed:

- [ ] certification tests (to be run during certification hackathons)
- [ ] possibly remove *dconfig.py* (and `dcommands.conf`)
- [ ] ? possibly remove *DConfigCache.py* and other utilities
- [x] possibly remove *Dinit.py* (see also [comment](https://github.com/DIRACGrid/DIRAC/pull/6403/files#r1049785987)
- [ ] duplicate commands should just be alias one of the other (e.g. isn't *dkillI* the same of *dirac-wms-job-kill*? and similar cases e.g. *dreplicas*, etc.)
- [ ] explicit dependencies to "proxy stuff" should be removed. 
- [ ] address https://github.com/DIRACGrid/DIRAC/pull/6403/files#r1049774115
- [ ] address https://github.com/DIRACGrid/DIRAC/pull/6403/files#r1051974621
- [x] do not use `print` (https://github.com/DIRACGrid/DIRAC/pull/6849)
- [ ] Clean up exception handling
- [ ] Make sure all Wiki content was transferred to readthedocs.

Some of COMDIRAC commands peculiarities (highlighted in several comments - [1](https://github.com/DIRACGrid/DIRAC/pull/6403/files#r1049778911), [2](https://github.com/DIRACGrid/DIRAC/pull/6403/files#r1049776286), [3](https://github.com/DIRACGrid/DIRAC/pull/6403/files#r1051984158) )
might be sorted out in a yet-to-come (bigger, general) plan for how DIRAC commands could or should be -- but this is for later.

**Comment by marianne013** [comment]
@fstagni Quick question about the print: Looking at 8.1 a lot of the dirac-* (as opposed to the d* commands) commands still seem use print. What should I be using instead ? Or is this a question for the python3 specialist @cburr ?

**Comment by fstagni** [comment]
Just use `gLogger`, that would understand the log level.

**Comment by marianne013** [comment]
@fstagni Can you please also assign this to @sfayer ? He's volunteered (I am sure I heard him say this ;-) to do the session inits properly.

**Comment by marianne013** [comment]
We need one more checkbox: "Make sure all Wiki content was transferred to readthedocs."

**Comment by marianne013** [comment]
@fstagni  could you please tick the "removed dinit.py" box  ? This file is now gone.
I would also like to remove the dcommands.conf request, I kind of like that feature and as far as I can tell it's used as it allows you to set some defaults. I'm working on an update to the documentation (the "Make sure all Wiki content was transferred to readthedocs." bit) that should address this.

**Comment by fstagni** [comment]
We're good for now.
