### ISSUE TITLE
Poor error given when configuration completely missing

### ISSUE THREAD

**Issue by Tobychev** [DIRACGrid/DIRAC#6772]
Hello,
I was trying to check if my installation of DIRAC was working properly, and I got the following
```
$ dirac-proxy-info
Missing mandatory local configuration option /DIRAC/Setup
There were errors when loading configuration
```
and it took me some time to establish that the error was actually that _no_ configuration file was found at all. 

It would be helpful if DIRAC could make that distinction, as it more clearly points out that it is the install itself that is unhealthy.

**Comment by fstagni** [comment]
I created a very simple PR for this: https://github.com/DIRACGrid/DIRAC/pull/6945

This is not the most precise solution, but the "problem" is that you *could* run DIRAC without a configuration file (and have the whole configuration on the command line...)...

**Comment by fstagni** [comment]
This was solved by https://github.com/DIRACGrid/DIRAC/pull/6945
