### ISSUE TITLE
Adjust references to old Google Groups forum in documentation

### ISSUE THREAD

**Issue by nifuki** [DIRACGrid/DIRAC#6781]
Readme still lists the old forum in the [Important links](https://github.com/DIRACGrid/DIRAC/tree/integration#important-links) section and it is probably also mentioned in [documentation](https://dirac.readthedocs.io/en/latest/AdministratorGuide/Systems/ResourceStatus/install.html?highlight=forum#installation) (where it doesn't contain the actual link, though).

I think that in the readme file the old forum should be marked as archived and the new discussions place mention should be added, and the mention in documentation should contain the actual link.

**Comment by fstagni** [comment]
Done.
