### ISSUE TITLE
Incorrect behavour of BundleDelivery with HTTPS

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRAC#6821]
When using `https://` with the `BundleDeliveryHandler` the client behaves incorrectly. With `dips://` the proccess for getting the CAs is:

1. Load `.dab.CAs` which should contain a hexidecimal ASCII characters of the MD5 hash of the files in the bundle (`01234567890abcdef01234567890abcd`).
2. Call `receiveFile` method on the `BundleDeliveryClient` with the arguments `["CAs", "01234567890abcdef01234567890abcd"]` 
3. The `BundleDeliveryHandler` then compares `01234567890abcdef01234567890abcd` with the hash of the latest bundle:
  a. If it matches: Transfer nothing and return the hash `01234567890abcdef01234567890abcd`
  b. If doesn't match: Send a tarball and return the new hash `ffffffffffffffffffffffffffffffff`

The key thing here is that the DISET `receiveFile` method has two return products. The file data _**and**_ the `S_OK/S_ERROR` object.

When `https://` is used the `streamToClient` method returns the binary data directly as the `S_OK` `Value` field so there is no way of returning the MD5 hash of the content. Currently, this results in the full tarball being written as the hash which never matches with what the server expects. We can think of workarounds but the `streamToClient` is supposed to be a temporary workaround so we should think about if there is a better way.

### Removing the BundleDeliveryHandler

After chatting with @chaen we think there is a better way of handling this. We currently use the `PilotSyncAgent` to make the pilot files available for a static web host to serve. We could expand this in `v8.0` to also syncronise the tarball of CAs and CRLs. Then in `v8.1` we can make it so that the (renamed?) `BundleDeliveryClient` downloads the tarball using `requests` directly. In `v8.2` we can then remove the `BundleDeliveryHandler` entirely (it'll only be needed for the first few days after updating from v8.0 to v8.1).

That leaves the caching mechanism. For this we can record the [`ETag`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) that is sent with the bundle and then use the [`If-None-Match`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match) to make it so that the server sends a 304 (Not Modified) response if the content is unchanged.

If this seems reasonable to everyone I'll implement it.

**Comment by fstagni** [comment]
Looks very reasonable to me.

**Comment by atsareg** [comment]
I think the easiest is that for the streamToClient call we adopt a convention that the output data is returned as, for example,
result["OutputData"] in addition to the standard "OK" and "Value" fields. Then the semantics will not change.

**Comment by atsareg** [comment]
Yes, this is a reasonable suggestion. Can the another solution be the following ? - streamToClient implementation now is streaming on the client side (without keeping much data in memory) but on the server side the entire file is written from to the request connection from memory IIUC. So, it can deal with relatively small files (small number of files) anyway. In this case a standard method returning S_OK structure can be used to deliver the file contents in yet another field of the structure. 
You keep saying that streamToClient (and what about streamFromClient ?) is a temporary solution. Would be nice to see what do you think is a definite solution.

**Comment by fstagni** [comment]
Maybe a more stable (I would not call it "definite") solution would lie in pure HTTP.

**Comment by fstagni** [comment]
I think that, given the last few months developments, this is not relevant anymore. Feel free to re-open.
