### ISSUE TITLE
[VOMS2CSAgent] strip nickname

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#6824]
There were spaces in VOMS, which resulted in the user being created with spaces..... 

```sql
select * from FC_Users where UserName like '%santov%';
+-------+----------+
| UID   | UserName |
+-------+----------+
| 22839 |       santovet          |
| 19875 | santovet |
+-------+----------+
```

**Comment by fstagni** [comment]
Didn't I just fix this in https://github.com/DIRACGrid/DIRAC/pull/6770?

**Comment by chaen** [comment]
From a quick glance at your PR, you strip the DN, not the nickname, right ?

**Comment by fstagni** [comment]
> From a quick glance at your PR, you strip the DN, not the nickname, right ?

Correct
