### ISSUE TITLE
[v7r3] Something is wrong with the v7.3.35 tag

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#6843]
When I look at the tag on the DIRAC github page it says:
"This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."
which probably explains some other issues I saw with this tag.

**Comment by chrisburr** [comment]
It looks like the commit was made twice and one was used for the tags and the other was pushed to `rel-v7r3`. @atsareg would have to comment if he remembers doing anything unusual.

* https://github.com/DIRACGrid/DIRAC/commit/0c1097ab97d827019bbb763e8c2b4e347b9ae46d
* https://github.com/DIRACGrid/DIRAC/commit/1b77167f806be6167095a9bc7d02289bcdc4203a

I don't think there is anything wrong with the tag other than the cosmetic weirdness.
