### ISSUE TITLE
COMDIRAC drm -F option broken

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#6896]
The -F option to drm complains that it didn't receive any arguments, even if they are provided. We'll fix this for v8r0 (although it'd be a pretty simple backport to the unmerged COMDIRAC for v7r3 if someone wanted to do that).

@IgorPelevanyuk We think this is the issue you mentioned in the BiLD meeting today.

**Comment by marianne013** [comment]
I would assign this to myself, but apparently I  can't.....

**Comment by IgorPelevanyuk** [comment]
Thank you, Daniela! This is exactly the issue.

**Comment by marianne013** [comment]
@IgorPelevanyuk You can have a look at the code, however Simon and me are only looking after the comdirac code after it was merged into DIRAC, i.e. the current v8.0 branch onwards. If you are using stand-alone COMDIRAC, @atsareg might be able to merge it there, or you might be able to just drop the code into your own install.

**Comment by IgorPelevanyuk** [comment]
Thank you @marianne013 and @sfayer I think I will try to put the code directly in my client.
