### ISSUE TITLE
Stalled jobs identified by the `StalledJobAgent` seems to be incorrectly reported within the Accounting plots

### ISSUE THREAD

**Issue by aldbr** [DIRACGrid/DIRAC#6936]
Not entirely sure whether it is an issue.
We can have "many" stalled jobs that are currently not reported by the `Watchdog` but by the `StalledJobAgent`.
They seem to be correctly committed within the `Accounting` system as `STALLED_PILOT_NOT_RUNNING = "Job stalled: pilot not running"`.
For some reason, they correctly appear in `ElasticSearch`, but not in the DIRAC plots.
Is this expected?

Here is an example with `ElasticSearch` and with `DIRAC`.
I know that it is not exactly identical but, do we expect such a difference between these two plots?
`ElasticSearch` seems to report the current status of all the existing jobs while the `DIRAC` plot reports the jobs/hour (`Running jobs` would be probably more adapted but do not report any `STALLED_PILOT_NOT_RUNNING` jobs).

![Screenshot from 2023-03-28 08-55-34](https://user-images.githubusercontent.com/19813740/228154032-4ee47c82-189b-4200-84da-7841439860a6.png)
![ccd93a3504adbc110bd58b99867fad0e](https://user-images.githubusercontent.com/19813740/228154118-f0ac2b09-e9d6-4b4f-a721-d52c5b358f65.png)

These plots come from the `LHCb` production environment.

**Comment by fstagni** [comment]
Can you clarify how you made the 2 plots? 
Was the first created with kibana or grafana? In this case, which indexes were involved?
Was the second created from "Job" accounting type?

**Comment by aldbr** [comment]
Yes sure, sorry.

The 1st one was extracted from the Kibana `WMSDashboard` and the plot is named `Jobs by MinorStatus`. The `WMSHistory` index is involved.
The second one was create from the `Accounting` dashboard:
- category: `Job`
- plot to generate: `Job execution rate`
- grouped by:  `FinalMinorStatus`

**Comment by fstagni** [comment]
These 2 accounting/monitoring types work in completely different way:
- the WMSHistory is a "picture" taken every 15 minutes of the content of JobDB
- Job accounting is filled in by the jobs themselves. In this sense it's only fully valid for terminal job states.

A job normally does not declare itself as "Stalled" (which means "stuck somewhere") so this is mostly done by the StalledJobAgent. And if a job is stalled, it won't report back to the Accounting DB. 

I think that there's no issue here, but other opinions are of course welcome.
