### ISSUE TITLE
Tornado logs

### ISSUE THREAD

**Issue by bertrandrigaud** [DIRACGrid/DIRAC#6939]
Hi,

Looking at fluent-bit and elasticsearch to grab Tornado logs, I'm now able to use this dashboard (https://github.com/DIRACGrid/DIRAC/blob/integration/dashboards/diracLogs/diracLogsDashboard.ndjson) using same field names in kibana. I would like to know if it is possible to get the mapping from the logs stored at cern (index_name/_mapping) to be compliant and to see if I could optimise fields (for instance, "componentname" which is currently like "Tornado/Tornado/ComponentName")?

Thanks,

**Comment by chaen** [comment]
> Looking at fluent-bit and elasticsearch to grab Tornado logs,

Did you write a fluent-bit config to read the json stdout of a Tornado process ? if so, I am interested :-)

> it is possible to get the mapping from the logs stored at cern (index_name/_mapping)

We let ES do it automatically
```json
{
  "lhcb-dirac-logs-tornado-tornado-2023.10" : {
    "mappings" : {
      "properties" : {
        "@timestamp" : {
          "type" : "date"
        },
        "@version" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "asctime" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "color" : {
          "type" : "boolean"
        },
        "componentindex" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "componentname" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "contextIsShown" : {
          "type" : "boolean"
        },
        "customname" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "exc_info" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "headerIsShown" : {
          "type" : "boolean"
        },
        "hostname" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "levelname" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "message" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "sec_log" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "spacer" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "threadIDIsShown" : {
          "type" : "boolean"
        },
        "timeStampIsShown" : {
          "type" : "boolean"
        },
        "tornadoComponent" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "type" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "varmessage" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        }
      }
    }
  }
}
```

> for instance, "componentname" which is currently like "Tornado/Tornado/ComponentName")?

Not sure what you mean here.  What version of DIRAC are you running ? 

This is more or less what a Tornado log looks for us. It has `Tornado/Tornado` as componentname, but as a `TornadoComponent` too.

```json
{
    "sec_log": "true",
    "varmessage": "([2001:1458:d00:b::100:3e9]:43554)[lhcb_prmgr:fstagni] RequestManagement/TornadoReqManager: getRequestFileStatus",
    "customname": "/TornadoReqManagerHandler",
    "type": "stomp",
    "hostname": "lbvobox316.cern.ch",
    "componentname": "Tornado/Tornado",
    "tornadoComponent": "RequestManagement/TornadoReqManager",
    "message": "Incoming request",
    "exc_info": "",
    "@timestamp": "2023-03-29T15:52:43.944Z",
    "levelname": "NOTICE",
    "asctime": "2023-03-29 15:52:43,944132",
    "componentindex": "tornado-tornado"
  }
```

**Comment by bertrandrigaud** [comment]
Thanks for informations!

On our testbed current version is: v8.0.8-1671710496

usual logs look like:

```
2023-03-30 06:54:18 UTC Tornado/Tornado/FrameworkComponentMonitoringHandler [140606266517312] NOTICE: Returning response (127.0.0.1:50026)[hosts:xxx] Framework/ComponentMonitoring (33.69 ms) OK
```
Logs can also be multiline (for debug mainly)

So to me, now componentname is `Tornado/Tornado/FrameworkComponentMonitoringHandler`, and this is the reason of my question, apparently you split this into different attributes (componentname and customname (split), and tornadoComponent (took from message)
So I have to modify my configuration to be compliant.

Here is what my fluent-bit configuration looks like now:

DIRAC.CONF
```
[SERVICE]
    flush        1
    log_level    info
    parsers_file parsers_multiline.conf

[INPUT]
    name              tail
    path              <path to dirac/startup/Tornado_Tornado/log/current>
    read_from_head    true
    Tag tornadolog
    multiline         on
    parser_firstline  multiline
    Mem_Buf_Limit     50MB

[FILTER]
    Name modify
    Match *
    Add hostname ${HOSTNAME}

[OUTPUT]
    name              es
    host                <es host>
    port                <port>
    logstash_format     true
    logstash_prefix     dirac-test-tornado
    logstash_dateFormat %Y.%m
    tls                 on
    tls.verify          off
    tls.ca_file         <path to ca file>
    tls.crt_file         <path to crt file>
    tls.key_file        <path to key file>
    match               tornadolog
    trace_output        on
```
PARSERS_MULTILINE.CONF
```
[PARSER]
    Name multiline
    Format regex
    Regex /^(?<logtime>[^ ]* [^ ]* [^ ]*) (?<componentname>[^ ]*) \[(?<timestamp>\d*)\] (?<levelname>[^:]+): (?<message>[^*]*)/
    Time_Key    logtime
    Time_Format %Y-%m-%d %H:%M:%S %Z
    Time_Keep   On
    Types componentname:string timestamp:integer hostname:string
```

**Comment by chaen** [comment]
Is there any reason not to use the `stdoutJson` backend as I mentioned during the BILD ?

**Comment by bertrandrigaud** [comment]
Are you talking about https://chaen-dirac.readthedocs.io/en/stable/CodeDocumentation/Resources/LogBackends/StdoutJsonBackend.html?
I didn't know about that, can you tell me more on this and tell me how to deploy/start it on our Testbed?

**Comment by chaen** [comment]
I thought I mentioned it during the BILD, nevermind.

This should get you started: https://dirac.readthedocs.io/en/latest/DeveloperGuide/AddingNewComponents/Utilities/gLogger/gLogger/Basics/index.html

you can also look at the full config example (`LogBackends`)
https://dirac.readthedocs.io/en/latest/AdministratorGuide/Configuration/ExampleConfig.html

**Comment by bertrandrigaud** [comment]
Here is what I get from Tornado logs:

```
{"message": "Returning response", "componentname": "Tornado/Tornado", "varmessage": "(127.0.0.1:43780)[hosts:cctbdirac02.in2p3.fr] Framework/ComponentMonitoring (52.01 ms) OK", "spacer": " ", "customname": "/FrameworkComponentMonitoringHandler", "headerIsShown": true, "timeStampIsShown": true, "contextIsShown": true, "threadIDIsShown": true, "color": true, "tornadoComponent": "Framework/ComponentMonitoring"}
```
There is no level, normal?

**Comment by chaen** [comment]
I fixed this in the release v8.0.18

**Comment by bertrandrigaud** [comment]
Alright, so it works well, as component name is declined in `componentname`, `customname` and `tonadocomponent` attributes, it is easier/cleaner to manage in kibana.
Would it be possible to extract host from `varmessage` and to create a `hostname` attribute?

**Comment by bertrandrigaud** [comment]
OK finally, I extracted varmessage values and created keys for `varmessage_ip`, `varmessage_port`, `hostname` and `varmessage_msg`. So now I got:
  
{
  "_index": "dirac-test-tornado-2023.04",
  "_type": "_doc",
  "_id": "HnSneYcB3_JOXyLg5eMJ",
  "_score": 1,
  "_source": {
    "@timestamp": "2023-04-13T08:07:38.119Z",
    "varmessage_ip": "`xxx.xxx.xxx.xxx>`",
    "varmessage_port": "<port>",
    "hostname": "`fqdn`",
    "varmessage_msg": "Framework/ComponentMonitoring (67.77 ms) OK",
    "levelname": "NOTICE",
    "message": "Returning response",
    "asctime": "2023-04-13 08:07:38,117497",
    "componentname": "Tornado/Tornado",
    "customname": "/TornadoComponentMonitoringHandler",
    "tornadoComponent": "Framework/ComponentMonitoring",
    "tornadoHostname": "`tornado hostname`"
  },
  "fields": {
    "@timestamp": [
      "2023-04-13T08:07:38.119Z"
    ]
  }
}

**Comment by bertrandrigaud** [comment]
But problem is that varmessage is not always formatted like (ip:port)[hosts:somehost] msg, for example:
`(127.0.0.1:42654)[dirac_admin:brigaud] Framework/TokenManager (32.53 ms) OK` 
so unfortunately I'm not able to extract hostname for each log.

**Comment by chaen** [comment]
Sorry I was away for a while.
We can't extract it from the the logger directly, but it sounds very doable with logstash, so I am sure fluent-bit should do it to

**Comment by bertrandrigaud** [comment]
I noticed that there are many logs where `customname` is empty, which is not great when filtering logs on it. I wonder if it would be a good idea to add, when it is possible, something like: 
```
# in init functions
 self.__log = gLogger.getSubLogger(self.__class__.__name__)
 # then in methods
 self.__log.debug(....)
 #instead of
 gLogger.debug(...)
```
Thus we could have messages like:
```
[componentname] [customname] ...
[Tornado/Tornado] [/TornadoRefresher] Refreshing configuration... 
[Tornado/Tornado] [/InnerRPCClient] Already given a valid url...
```
What do you think? Is it something relevant? Should it be implemented antother way?

**Comment by marianne013** [comment]
You mean disentangling all these logs so I can read them on disk instead of having to install flavour-of-the-day-search ?
I'm all for it: https://github.com/DIRACGrid/DIRAC/discussions/6994 
#noteveyonehascerntoinstallthemaninfrastructure

**Comment by bertrandrigaud** [comment]
Unfortunately, Tornado logs are stored in a single file. The goal here is to say: "OK you're a Tornado log but from which component". But logs are still in the same file. What I'm trying to do is to grab logs from these "current" files with fluent-bit and throw it to an elastic search instance, then with Kibana and Grafana I'm able to filter it easily. But you're right it supposes to install an entire monitoring infrastructure.

**Comment by chaen** [comment]
> What do you think? Is it something relevant? Should it be implemented antother way?

This is what we tried to do, but we did not make a single PR with alllll these changes, so we do it as we go

> You mean disentangling all these logs so I can read them on disk instead of having to install flavour-of-the-day-search ?

They still go on disk, so I don't really see what ES has to do here

> "OK you're a Tornado log but from which component". 

I don't get it. That's the whole point of the  `tonadocomponent` attribute

Actually, in general I don't get what you are missing. 
That's the typical messages you can get in `json` format from tornado:

```json
{
  "levelname": "NOTICE",
  "message": "Incoming request",
  "asctime": "2023-05-05 08:59:15,468719",
  "componentname": "Tornado/Tornado",
  "varmessage": "([2001:1458:d00:a::100:7]:39558)[hosts:lhcbvoboxcertif00.cern.ch] Transformation/TransformationManager: getTransformation",
  "customname": "/TornadoTransformationManagerHandler",
  "tornadoComponent": "Transformation/TransformationManager",
  "hostname": "lhcbvoboxcertif00.cern.ch"
}

{
  "levelname": "NOTICE",
  "message": "Returning response",
  "asctime": "2023-05-05 08:59:15,471560",
  "componentname": "Tornado/Tornado",
  "varmessage": "([2001:1458:d00:a::100:7]:39558)[hosts:lhcbvoboxcertif00.cern.ch] Transformation/TransformationManager (5.69 ms) OK",
  "customname": "/TornadoTransformationManagerHandler",
  "tornadoComponent": "Transformation/TransformationManager",
  "hostname": "lhcbvoboxcertif00.cern.ch"
}
```

**Comment by bertrandrigaud** [comment]
In fact, for me, `customname`, which is nearly the same as `tornadoComponent` is more interesting as you have it in all logs (not only Tornado logs). This way I can grab all component logs with fluent-bit, sending all to ES and then display it with kibana in the way I want, filtering it by `componentname`, by `customname`, by `levelname`...

**Comment by chaen** [comment]
I don't think it is realistic to treat `tornado` and `dips` logs the same way. They are architecturally different, so I am afraid that there will be different treatments

**Comment by bertrandrigaud** [comment]
> You mean disentangling all these logs so I can read them on disk instead of having to install flavour-of-the-day-search ? I'm all for it: #6994 #noteveyonehascerntoinstallthemaninfrastructure

Using (only) fluent-bit and Dirac StdOutputJson, I'm now able to separate logs in different `log.tornado.<tornadoComponent>` files  on disk and to have it in classic or json way (as you prefer). The only thing is that I can't write files in separate folders as it is now in `.../startup/<component>/`... for several reasons, so all logs can be for instance in `.../startup/log`

on my dirac instance, this is like:
```
$ ll /vo/dirac/startup/log/
log.Configuration_Server
log.tornado
log.tornado.Framework_ComponentMonitoring
log.tornado.Framework_ProxyManager
log.tornado.Framework_UserProfileManager
log.WorkloadManagement_StatesAccountingAgent
```
in log.tornado, I got all Tornado logs that don't have yet a `tornadoComponent` set, and also "print in code" for debugging, so in the end there should be only debug trace in it.

Comparatively to the ES solution, it is lighter, but in counterpart logs are separated, on disk but also on servers while ES offers a centralized way of displaying and filtering logs.
Of course both solutions can live together in a single fluent-bit configuration file.
In both cases, data retention has to be managed externally with help of logrotate for instance for files or API calls for ES.

**Comment by fstagni** [comment]
I am under the impression that this is "solved". Closing, comment if it's not.
