### ISSUE TITLE
mysqlclient 2.1 no longer provides escape_string

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRAC#6978]
https://github.com/PyMySQL/mysqlclient/pull/511

Once dealt with we should revert https://github.com/DIRACGrid/DIRACOS2/commit/4ca5a1b775ef604c9109a9c086cf0bfe4b2b5ec3

**Comment by fstagni** [comment]
This would mean using parametrized queries (I have not found other solutions, at least not after a quick search). 
Unfortunately, this would mean for DIRAC  **a lot** of changes and we are not, I think, willing to embark on that for not obvious gains. Therefore I close this, and we'll "solve" it with sqlalchemy in DiracX. Feel free to disagree.
