### ISSUE TITLE
File with no replicas causes infinite loop in replicate and register process

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#7075]
Taken from the email chain:
As noted in the last BiLD meeting we saw a failure mode where q replicate and register request never finished, instead it was caught in a loop querying the data catalogue over and over again.
 
```
2023-06-21 07:31:25 UTC RequestManagement/RequestExecutingAgent/ReplicateAndRegister DEBUG: TimeOutPerFile = 600
2023-06-21 07:31:25 UTC RequestManagement/RequestExecutingAgent/ReplicateAndRegister DEBUG: UseNewFTS3 = True
ValueError("invalid literal for int() with base 16: ''")
ValueError("invalid literal for int() with base 16: '?'")
ValueError("invalid literal for int() with base 16: '?'")
ValueError("invalid literal for int() with base 16: ''")
ValueError("invalid literal for int() with base 16: ''")
ValueError("invalid literal for int() with base 16: ''")
2023-06-21 07:31:26 UTC RequestManagement/RequestExecutingAgent/pid_30378/prod6A_2_9776 ERROR: hit by exception: sequence item 0: expected str instance, NoneType found
Traceback (most recent call last):
  File "/opt/dirac/DIRAC/src/DIRAC/RequestManagementSystem/private/RequestTask.py", line 361, in __call__
    exe = handler()
  File "/opt/dirac/DIRAC/src/DIRAC/DataManagementSystem/Agent/RequestOperations/ReplicateAndRegister.py", line 225, in __call__
    return self.fts3Transfer()
  File "/opt/dirac/DIRAC/src/DIRAC/DataManagementSystem/Agent/RequestOperations/ReplicateAndRegister.py", line 426, in fts3Transfer
    "File %s doesn't exist at %s" % (opFile.LFN, ",".join(noReplicas)),
TypeError: sequence item 0: expected str instance, NoneType found
...
```
There are quite a few of these too:
```
2023-06-21 07:31:29 UTC RequestManagement/RequestExecutingAgent INFO: callback: 714313 result is S_ERROR(sequence item 0: expected str instance, NoneType found), put S_OK()

```

On closer inspection it turned out that the data set contained a file with zero replicas. Creating such an entry reliably replicates the issue.

@sfayer had a look at the code and noted the following issues: 

If there is one of these files without replicas:

 - In filterReplicas, this line puts a None object into the list that then
   crashes later as it can't do a ",".join(noReplicas) on it:
   result["NoReplicas"].append(None)

 - In that generic exception case, the Attempts counter is never incremented,
   so it goes around forever.

 - The hexAdlerToInt contains a print() in an error case, when it probably
   shouldn't if it's meant as a general utility function.

The Attempts counter not being implemented means the job never finishes.

**Comment by chaen** [comment]
I have started drafting solutions here: https://github.com/DIRACGrid/DIRAC/pull/7077

> In filterReplicas, this line puts a None object into the list that then
crashes later as it can't do a ",".join(noReplicas) on it:
result["NoReplicas"].append(None)

Yep

> In that generic exception case, the Attempts counter is never incremented,
so it goes around forever.

I think that's fine. There should be no unhandled exceptions, so it means that there is a code bug (as opposed to an operational issue). So you sort of want that this is noticed by the installation admins and fixed. 

> The hexAdlerToInt contains a print() in an error case, when it probably
shouldn't if it's meant as a general utility function.

I agree, but given that it just returns `False` in case of issue, the caller never knows what the actual issue is, if it is not printed before. Any idea how we can make that better ?

**Comment by chrisburr** [comment]
@marianne013 Do you have any follow-up or shall we merge https://github.com/DIRACGrid/DIRAC/pull/7077 and close this?

**Comment by fstagni** [comment]
No follow-up, closing for now. @marianne013 re-open if you need to!
