### ISSUE TITLE
WebApp broken with latest v8.0.x release

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRAC#7084]
Apparently the safe tested changes weren't actually.

              This changes are merged to integration and tested in the certification hackathon. Note that the actual change is one line https://github.com/DIRACGrid/DIRAC/blob/2c35698c75d0347ffb00180cf67a1876f13b2b97/src/DIRAC/Core/Tornado/Server/HandlerManager.py#L116. Others are rather cosmetics. Further comments ?

_Originally posted by @atsareg in https://github.com/DIRACGrid/DIRAC/issues/6943#issuecomment-1515886135_

**Comment by fstagni** [comment]
Hopefully fixed by https://github.com/DIRACGrid/WebAppDIRAC/pull/737
