### ISSUE TITLE
v8.0.24 AREX multi-VO issues

### ISSUE THREAD

**Issue by marianne013** [DIRACGrid/DIRAC#7095]
We tried to upgrade our production server to v8.0.24 today and noticed that on AREX computing elements only, user jobs started running in the wrong group, i.e. we had NA62 user jobs running under a snoplus pilot. 
Going down to v8.0.23 'fixed' the issue. 
The main difference between the releases is the AREX proxy renewal/dealing with tokens code, but we have not been able to work out how this code could have caused this problem. 
We didn't see it on our pre-prod server, but we assume that the job pressure never gets high enough to trigger this particular bug.
Any ideas ?
Tagging @aldbr as the author of most of the AREX code.

**Comment by aldbr** [comment]
Indeed, https://github.com/DIRACGrid/DIRAC/pull/7048 might be the source of your issue.

Here is the previous behavior (`v8.0.23`):
- each time you submit a pilot, a new delegation ID is created
- the delegation ID comes with a CSR (certificate signing request) that is signed using the proxy stored in `Locations.getProxyLocations()`

Here is the current behavior (`v8.0.24`):
- at the submission time:
  -  if there is no delegation ID associated to the AREX CE, then one is created and stored in an instance attribute, the CSR is signed using the proxy stored in `Locaions.getProxyLocations()`.
  - else, the existing delegation ID is used.
- there is a single delegation ID for all the pilots submitted by the same AREX CE (DIRAC interface) instance.
- which means that if you want to use a new proxy to submit pilots of another group, it will not be taken into account.

Are you using multiple proxies (belonging to different groups) in a same AREX CE (DIRAC interface) instance?
For instance:

```python
arex_ce = AREXComputingElement("ce-test")
arex_ce.setProxy(proxy_group1)
arex_ce.submitJob(job1)
arex_ce.setProxy(proxy_group2)
arex_ce.submitJob(job2)
```

**Comment by marianne013** [comment]
@aldbr Yes. We have multiple VOs using the same AREX elements. Each VO obviously has their own pilot proxy (though we use the same certificate for all - the pilot certificate is a member of all VOs we support.)  Are you a member of the gridpp VO ? Then I think you could test it on any UK AREX instance. They should all have dteam and gridpp enabled. I usually use RALPP (not RAL_LCG2).

**Comment by aldbr** [comment]
I think I understand the problem and I am coming with a fix.

**Comment by fstagni** [comment]
Should be hopefully fixed.
