### ISSUE TITLE
Revert pydantic workaround

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/DIRAC#7096]
Which was added in https://github.com/DIRACGrid/DIRAC/pull/7094/commits/ce6f06c94d5e4a057f41c13ec0e9e2fbb298bc16

**Comment by chrisburr** [comment]
See also https://github.com/DIRACGrid/DIRACOS2/pull/108 and https://gitlab.cern.ch/lhcb-dirac/LHCbDIRAC/-/merge_requests/1401
