### ISSUE TITLE
dirac-install-tornado-service overwrites Port?

### ISSUE THREAD

**Issue by sfayer** [DIRACGrid/DIRAC#7126]
Hi,

We're trying to use `dirac-install-tornado-service Framework/TokenManager` to install just the new endpoint on a machine that already has the base Tornado service installed and running... We've found that it overwrites the `/Systems/Tornado/<Setup>/Port` setting to 8443 even though we already had it set to 8444 (which then caused a failure as our Webapp is on 8443). Is this possibly a bug?

We also normally do service installs from a UI rather than directly on the server (as we don't have a dirac_admin user proxy readily available on there): We found that while it did install the TokenManager, it put the client hostname in the URLs section (with port 8444, despite overwriting it elsewhere) rather than the DIRAC server hostname.

Regards,
Simon

**Comment by fstagni** [comment]
Is this with v8.0 or v8.1? (there are changes in this area)

**Comment by marianne013** [comment]
v8.0

**Comment by fstagni** [comment]
Prob fixed in https://github.com/DIRACGrid/DIRAC/pull/7130

**Comment by fstagni** [comment]
Should be fixed.
