### ISSUE TITLE
OAuth2 logs client secret in log file

### ISSUE THREAD

**Issue by sfayer** [DIRACGrid/DIRAC#7128]
Hi,

Would it be possible to remove the client secret from this message (or maybe truncate/obscure it so that only a small part is printed)?
https://github.com/DIRACGrid/DIRAC/blob/d24f3aefb1cfac83808fbff6ceb9b71b52fdbe13/src/DIRAC/Resources/IdProvider/OAuth2IdProvider.py#L168

We tend to run our SiteDirectors at DEBUG level, so the client secrets get printed a lot otherwise...

Regards,
Simon

**Comment by fstagni** [comment]
Oh, remove it please!
