### ISSUE TITLE
Getting allocated time left from a SingularityCE does not work

### ISSUE THREAD

**Issue by aldbr** [DIRACGrid/DIRAC#7177]
There is currently no way to get the allocated time left from a SingularityCE because environment variables are not propagated from the host to the container as noted here: 

https://github.com/DIRACGrid/DIRAC/blob/integration/src/DIRAC/Resources/Computing/SingularityComputingElement.py#L325

Elastic jobs might need to get access to the batch system type to compute the time left in order to avoid running out of time.
The batch system type is retrieved from the environment variables present in the host such as:

https://github.com/DIRACGrid/DIRAC/blob/integration/src/DIRAC/Resources/Computing/BatchSystems/TimeLeft/TimeLeft.py#L132-L139

I see different possibilities:
- `SingularityCE` searches for a batch system jobID environment variable and includes it if present (probably the easiest way)
- The pilot adds the batch system type and jobID to the local `cfg` file (might be cleaner)

Any opinion?

**Comment by fstagni** [comment]
I would go for the 2nd option (The pilot adds the batch system type and jobID to the local `cfg` file). This is definitely cleaner.
