### ISSUE TITLE
New permissions in the transformation system

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRAC#7198]
In https://github.com/DIRACGrid/DIRAC/pull/7113/ access to `TransformationClient.getTransformation` was restricted however access to `TransformationClient.getTransformations` was not.

Though in the actual method, it seems at a glance that `getTransformation` is just an wrapper around `getTransformations` so it's not clear to me why they wouldn't be treated the same way:

https://github.com/DIRACGrid/DIRAC/blob/df6a89f02aa6c9f04dc6891cd0a267e6699e3ce9/src/DIRAC/TransformationSystem/DB/TransformationDB.py#L318-L327

It's the same for `getTransformationParameters`. 

The WebApp also now silently fails due to accessing these methods as well as `getTransformationStats`, `getTransformationFilesCount` and potentially more.

I guess more importantly the original PR stated:

> we decided that we'll be fine with people seeing other transformations - just not modifying them.

but in practice the change restricts large parts of the "seeing other transfromations". This is somewhat pressing as LHCbDIRAC extensively relies on users having read access to all transformations.

**Comment by marianne013** [comment]
Tagging @sfayer 
We'll have a look.

**Comment by marianne013** [comment]
@chrisburr What permissions (of any) do these users have ?

**Comment by chaen** [comment]
They have 
```
      Properties = NormalUser
      Properties += PrivateLimitedDelegation
```
