### ISSUE TITLE
Refactor the PilotLoggingAgent loop

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#7249]
My proxy has been downloaded almost 200k times in September, mapped to dteam. The only reason I can think of is the `PilotLoggigAgent`, which downloads my proxy at every loop (https://github.com/DIRACGrid/DIRAC/blob/271a3e110edc925b2c7f0be75b57238c520fdc8d/src/DIRAC/WorkloadManagementSystem/Agent/PilotLoggingAgent.py#L99)
It does not account anywhere near 200k, but I suspect that @martynia worked on it a lot in September and probably triggered heavy activities. 

Could this agent please be refactored as to download the shifter proxies in the initialization, and then reuse the same proxy file in every agent loop ? 
Thanks

**Comment by martynia** [comment]
Fixed in #7257
