### ISSUE TITLE
Faster Dirac.deleteJob Implementation?

### ISSUE THREAD

**Issue by sfayer** [DIRACGrid/DIRAC#7314]
Hi,

When a user deletes a large batch of jobs via the API or command line, it can take a long time. We've tracked it down to this loop making a call to the server for each individual job:
https://github.com/DIRACGrid/DIRAC/blob/64f2d36dbeb62cf800294ea77e9431cc3c1f8bb0/src/DIRAC/Interfaces/API/Dirac.py#L1453-L1457

(We tried it with that loop removed and it was significantly faster).

Would it be possible to replace it with some kind of bulk version? (I was going to suggest removing those lines entirely as I think the same check is done server-side, but it seems like they were added specially here for some reason?)

Regards,
Simon

**Comment by fstagni** [comment]
This check was first introduced by me in https://github.com/DIRACGrid/DIRAC/pull/5752 and then edited by you in https://github.com/DIRACGrid/DIRAC/pull/6665. Unfortunately, my bad, I did not add in the first PR an explanation on why it was necessary but I think I remember that it was done exactly to avoid some issues with the interplay of server side check (like: the user was setting some status that was then "silently" refused server side).

It is I think possible to make it bulk. Would you give it a try, or should I?

**Comment by sfayer** [comment]
Thanks, I'll have a look at sorting it out...
