### ISSUE TITLE
Index of the Transformations table ? 

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRAC#7335]
Hi,

Investigating a bit, I've realized that most of the slow queries concern queries like 

```sql
SELECT TransformationID,TransformationName,Description,LongDescription,CreationDate,LastUpdate,AuthorDN,AuthorGroup,Type,Plugin,AgentType,Status,FileMask,TransformationGroup,GroupSize,InheritedFrom,Body,MaxNumberOfTasks,EventsPerTask,TransformationFamily,Hot FROM Transformations    WHERE `Status` IN ( "Active", "Completing", "Stopped", "Testing" ) AND `Type` IN ( "MCSimulation", "MCFastSimulation" ) LIMIT 100  
```

there are no index on `Status` nor `Type`. I'll probably add it in LHCb DB. Any objectiion in making this the default in the code ?

**Comment by fstagni** [comment]
Seems fine to me, go ahead.

**Comment by chrisburr** [comment]
Definitely :+1:

**Comment by chrisburr** [comment]
Shall we do Type and State for the ProductionRequestDB in LHCb as well as I've noticed that one getting slower as well.

**Comment by chaen** [comment]
Let me have a quick look at the DB, and I can do that at the same time on Monday

**Comment by chrisburr** [comment]
I guess something should be added one of the wikis.

**Comment by chaen** [comment]
:+1:  I'll add it to v9
