### ISSUE TITLE
CentOS 7 EOL

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRAC#7368]
I thought it was worth opening an issue to track what would be needed for CentOS 7's EOL:

- [x] Change default SingularityCE image
- [x] Rebuild the runsv RPMS : [runit-2.1.2-2.el9.x86_64.rpm](https://diracproject.web.cern.ch/diracproject/rpm/runit-2.1.2-2.el9.x86_64.rpm)
- [x] Move the certification instances
- [x] Move the CI container images
- [x] puppet updates?

**Comment by andresailer** [comment]
To state more publicly: I am already running RHEL9 servers in production (for about a year). 

The first runit-el9 RPMs kind-of put my servers offline (runsvctrl was missing, for example). @chaen quickly purged them, and I managed to recover. 

Next step QA repo for runit :)

Puppet-module dirac is also el9 compatible, at least for the parts I am using.
