### ISSUE TITLE
dirac-cert-convert.sh gives crypto error with some certificates

### ISSUE THREAD

**Issue by mdpunch** [DIRACGrid/DIRAC#7381]
In converting `p12` to `pem`, I get the following error:

```
$ dirac-cert-convert MP.p12
No CFG file loaded, was that intentional?
Running without remote configuration
Back up /pbs/home/p/punch/.globus/usercert.pem file to /pbs/home/p/punch/.globus/usercert.pem.2023-12-20T19:40:06.269671.
Back up /pbs/home/p/punch/.globus/userkey.pem file to /pbs/home/p/punch/.globus/userkey.pem.2023-12-20T19:40:06.269671.
Converting p12 key to pem format
Enter Import Password:
Enter PEM pass phrase:
Verifying - Enter PEM pass phrase:
Error outputting keys and certificates
40D79FECF17F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:342:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()

Restore /pbs/home/p/punch/.globus/usercert.pem file from the /pbs/home/p/punch/.globus/usercert.pem.2023-12-20T19:40:06.269671
Restore /pbs/home/p/punch/.globus/userkey.pem file from the /pbs/home/p/punch/.globus/userkey.pem.2023-12-20T19:40:06.269671
```

I fix this by editing `dirac-cert-convert.sh`, to add `-legacy` in the two lines after the `$OPENSSL pkcs12`.

With this fixed version, it works fine:

```
$ dirac-cert-convert.sh MP.p12 
Back up /home/punch/.globus/MP.p12 file
Converting p12 key to pem format
Back up /home/punch/.globus/userkey.pem file
Enter Import Password:
Mac verify error: invalid password?
Enter Import Password:
Enter PEM pass phrase:
Verifying - Enter PEM pass phrase:
Converting p12 certificate to pem format
Back up /home/punch/.globus/usercert.pem file
Enter Import Password:
Information about your certificate: 
subject=O=GRID-FR, C=FR, O=CNRS, OU=APC, CN=Michael Punch
issuer=C=FR, O=MENESR, OU=GRID-FR, CN=AC GRID-FR Personnels
Done
```

Perhaps add a `-legacy` option to `dirac-cert-convert.sh` itself?

**Comment by mdpunch** [comment]
Example `dirac-cert-convert.sh` with `-l` legacy option attached.
[dirac-cert-convert.sh.gz](https://github.com/DIRACGrid/DIRAC/files/13751735/dirac-cert-convert.sh.gz)

**Comment by chrisburr** [comment]
Where did you get this certificate from? In general this is probablly a bad idea to support as, to quote the openssl docs:

> The OpenSSL legacy provider supplies OpenSSL implementations of algorithms that have been deemed legacy. Such algorithms have commonly fallen out of use, have been deemed insecure by the cryptography community, or something similar. 

You might also run into issues using the certificate due to some services rejecting it for being unsupported or insecure.

**Comment by mdpunch** [comment]
> Where did you get this certificate from? In general this is probablly a bad idea to support as, to quote the openssl docs:
> 
> > The OpenSSL legacy provider supplies OpenSSL implementations of algorithms that have been deemed legacy. Such algorithms have commonly fallen out of use, have been deemed insecure by the cryptography community, or something similar.
> 
> You might also run into issues using the certificate due to some services rejecting it for being unsupported or insecure.

Hi,

I agree that it would be best to have "non-legacy" certificates!  But it might take some time to get the behemoth of the French CNRS and/or MENESR (Ministère de l'Éducation nationale, de l'Enseignement supérieur et de la Recherche) to update their systems (which as above is the origin of the certificate).  Already, their instructions say to use outdated browsers to download the certificates, though! (see https://services.renater.fr/ssi/grid-fr/vos_certificats/demande/certificat_personnel if you read French).

So indeed, this is a workaround of French admin... and I can understand if you prefer not to implement this (I can share the workaround with my colleagues in CTA-France, which may be enough).

**Comment by fstagni** [comment]
After some considerations, we decided to NOT accept the PR you kindly proposed, as:
- we think (hope!) yours is an unfortunate and single (?) case
- you already know the solution to it, and this is a script you run once per year!
- we prefer in general to not add legacy support.

Therefore, I am closing the issue and the connected PR.

**Comment by mdpunch** [comment]
This is up to you people; I did this as a service to others.

> After some considerations, we decided to NOT accept the PR you kindly proposed, as:
> 
>     * we think (hope!) yours is an unfortunate and single (?) case

Definitely not, in fact I was encouraged to submit this by my colleague Karl Kosack at the CEA, Saclay (responsible for the CTA work-package Data Storage and Preservation System, DPPS) who also ran into this problem and remembered I had given the solution on a CTA Slack channel.

It will be a problem for all people who have to use certificates from the French Ministry of Education (including all CNRS and CEA), who are working on CTA, experiments at CERN, etc., many of whom you have signed papers with.

> 
>     * you already know the solution to it, and this is a script you run once per year!

Yes, fine for me ... but everyone who runs into this problem will lose some hours of time trying to understand and fix it.  Sure, the French Ministry of Education should get their act together, but it isn't possible for us at the base to get the behemoth to move.

> 
>     * we prefer in general to not add legacy support.

So, if you have the courage of your convictions, then you will close off legacy support.  It would be interesting to watch the fall-out!

Perhaps Luisa @arrabito , DIRAC responsible for CTA-France, could comment?

> 
> 
> Therefore, I am closing the issue and the connected PR.

**Comment by arrabito** [comment]
Honestly I didn't remember that I had this issue with my certificate, but I've just tried again and I confirm that I have the same issue.
Also all French community in principle has the same since we all have certificates issued by the same CA.

Waiting for an action from the French Ministry of Education, I propose that we implement a cta-cert-convert script with the legacy option in CTADIRAC extension.

**Comment by mdpunch** [comment]
As some helpers told us just recently, at least on the CNRS side we can do an end-run around the French Ministry of Education by using our CNRS certificates (which somehow don't have this problem).

So, this might only be needed for CEA (and maybe not even for them, with CEA certificates).
