### ISSUE TITLE
Are Per User Subproxies used?

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRAC#7410]
As part of https://github.com/DIRACGrid/diracx/issues/31 I stumbled upon the concept of Per User Subproxies (PUSP).

The feature was added in https://github.com/DIRACGrid/DIRAC/pull/2648

> The Per User Subproxies ( PUSP ) is the mechanism pushed by the EGI developers to support communities where users do not have personal certificates but use proxies derived from a single community identity ( robot ) with a user identity added as an extension. The support for such proxies in DIRAC should be transparent for those communities that use real user certificates.

@atsareg is this still used or can I ignore this case and remove support for them?

**Comment by fstagni** [comment]
"Story of the past: drop it!"

**Comment by fstagni** [comment]
Done in #7413
