### ISSUE TITLE
README in tests/CI/ outdated

### ISSUE THREAD

**Issue by maxnoe** [DIRACGrid/DIRAC#7423]
The README in https://github.com/DIRACGrid/DIRAC/tree/integration/tests/CI seems to be outdated, it references a `run_docker_setup.sh` multiple times, which doesn't seem to exist in this repository.

**Comment by chrisburr** [comment]
Thanks for opening the issue, I'll clean that up shortly.

This is probably the page you want to start from (it's linked from the main README):

* https://dirac.readthedocs.io/en/integration/DeveloperGuide/DevelopmentEnvironment/DeveloperInstallation/editingCode.html

and for running the full integration tests specifically:

* https://dirac.readthedocs.io/en/integration/DeveloperGuide/DevelopmentEnvironment/DeveloperInstallation/stuffThatRun.html#stuff-that-run
