### ISSUE TITLE
Installation from Scratch -  MySQL problems

### ISSUE THREAD

**Issue by hamar** [DIRACGrid/DIRAC#752]
Hi,

I am installing a machine from scratch, the /etc/hostname was like:

127.0.0.1 localhost.localdomain localhost
X.X.X.X machine_name.domain machine_name

And, I got this error during installation:

Installing MySQL 
MySQL root password: 
Installing MySQL server at XXX
Initializing MySQL... 
Starting MySQL... 
Setting MySQL root password 
Failed to execute mysqladmin
Exit code: 1

mysqladmin: connect to server at 'xxx.in2p3.fr' failed
error: 'Host XXX.in2p3.fr' is not allowed to connect to this MySQL server'

[dirac@cctbdiracli01 DIRAC]$ ps -ef|grep mysql
dirac     1943     1  0 16:02 pts/2    00:00:00 /bin/sh /vo/dirac/versions/v6r4p2_1337090238/Linux_x86_64_glibc-2.5/bin/mysqld_safe --datadir=/vo/dirac/mysql/db --pid-file=/vo/dirac/mysql/db/XXX.pid
dirac     2083  1943  5 16:02 pts/2    00:00:00 /vo/dirac/versions/v6r4p2_1337090238/Linux_x86_64_glibc-2.5/libexec/mysqld --basedir=/vo/dirac/versions/v6r4p2_1337090238/mysql --datadir=/vo/dirac/mysql/db --log-error=/vo/dirac/mysql/db/XXX.err --pid-file=/vo/dirac/mysql/db/XXX.pid --socket=/tmp/mysql.sock --port=3306

After I changed to

127.0.0.1 machine_name.domain machine_name localhost.localdomain localhost

and it works.

Thanks in advance,

Vanessa

**Comment by fstagni** [comment]
Old task. I install in Jenkins all the DBs and services using standard tools, and all works (fixed fully within v6r12)
