### ISSUE TITLE
MultiVOMetadata doubling VO identifier

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRAC#7687]
It happens that the metadata key has twice appended (for example in the Transformation.InputDataAgent)

https://github.com/DIRACGrid/DIRAC/blob/4886513ac7a42f01c06cd5b2339fa666d3a04115/src/DIRAC/DataManagementSystem/DB/FileCatalogComponents/DirectoryMetadata/MultiVODirectoryMetadata.py#L23

Should
1. Prevent the creation of meta data keys with `___` inside
2. Only append `___<vo>` if it hasn't been appended yet

cc. @marianne013 @martynia

**Comment by martynia** [comment]
@andresailer could you post medatadata commands you used with @marianne013  to add to the catalog, so I could reproduce the issue ?

**Comment by andresailer** [comment]
https://dirac.readthedocs.io/en/latest/AdministratorGuide/Tutorials/dmsWithTs.html#using-metadata-queries-to-add-files-to-transformations

**Comment by martynia** [comment]
Fix proposal here: #7708
