### ISSUE TITLE
Typo in checksum field of file registration dict in DataManager

### ISSUE THREAD

**Issue by maxnoe** [DIRACGrid/DIRAC#7704]
It's Adler, not Addler:

https://github.com/DIRACGrid/DIRAC/blob/95bb0b136e5e52b0b64f6ef10ace969fe43aa5c0/src/DIRAC/DataManagementSystem/Client/DataManager.py#L572

This is the only occurrence of `Addler` in the DIRAC code base:

```
❯ rg Addler
src/DIRAC/DataManagementSystem/Client/DataManager.py
572:            "Addler": checksum,
```

**Comment by fstagni** [comment]
Thank you. You can make the PR :)

**Comment by maxnoe** [comment]
I opened the issue because I don't know enough of the code to just make this fix, is this value used downstream anywhere? Or is it just returned / printed?

**Comment by fstagni** [comment]
It's just returned, not used anywhere, so it's the simplest fix.
