### ISSUE TITLE
Installation failure on OSX arm64 system

### ISSUE THREAD

**Issue by amjjbonvin** [DIRACGrid/DIRAC#7747]
I have been following the installation instructions for installing DIRAC on my MacBook M2 (arm64 processor):

```
curl -LO https://github.com/DIRACGrid/DIRACOS2/releases/latest/download/DIRACOS-Darwin-$(uname -m).sh
bash DIRACOS-Darwin-$(uname -m).sh
rm DIRACOS-Darwin-$(uname -m).sh
source diracos/diracosrc```
```

When executing the second command I am getting the following error:

```
bash-3.2$ bash DIRACOS-Darwin-$(uname -m).sh
PREFIX=/Users/abonvin/software/DIRAC/diracos
Unpacking payload ...
DIRACOS-Darwin-arm64.sh: line 273: 62553 Exit 141                extract_range $boundary1 $boundary2
     62554 Killed: 9               | "$CONDA_EXEC" constructor --extract-tarball --prefix "$PREFIX"
DIRACOS-Darwin-arm64.sh: line 276: /Users/abonvin/software/DIRAC/diracos/preconda.tar.bz2: No such file or directory
```

Has the installation been tested on Mac arm processors?

**Comment by fstagni** [comment]
This issue was already reported in https://github.com/DIRACGrid/DIRAC/issues/6977, so I hope you do not mind but I close this as duplicate. I am afraid we still do not have a suggestion for you on solving this issue.

**Comment by amjjbonvin** [comment]
OK - but then at least update the instructions stating that DIRAC is not supposed on OSX arm processors.
