### ISSUE TITLE
Lack of ReplicaManager.removeDirectory()

### ISSUE THREAD

**Issue by phicharp** [DIRACGrid/DIRAC#782]
There is a way to "clean" a directory, i.e. remove all its files and then remove the directory itself (rm -r). However there is no way to delete a directory. This functionality should be exposed (rmdir), and an error returned if not empty.
A complication is that the RM relies on a list of SEs at which it should try and remove the directory (physically), which is far from optimal and now rather limited (MC and FAILOVER). I am afraid however there is no other way than looping on all SEs as one doesn't know where a directory exists... but the important point is to remove it from the LFC.

**Comment by chaen** [comment]
The best is probably that the agent checking the integrity between an SE and the FileCatalog does it. This agent anyway needs a complete rewrite.

**Comment by fstagni** [comment]
@chaen what would we do about this after the late discussions on directory operations on SEs?

**Comment by chaen** [comment]
I think this is the kind of things that will be solved when we get consistent dump across storages. But as said in the first message already, there is no real solution to that
