### ISSUE TITLE
Fixing deployment

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRAC#7890]
Instead of sourcing something

https://github.com/DIRACGrid/DIRAC/blame/7fe654eef5f4b0c23a7047e6e046580b1e354e97/.github/workflows/deployment.yml#L146

that should follow the docs of the action: https://github.com/conda-incubator/setup-miniconda?tab=readme-ov-file#example-1-basic-usage

**Comment by fstagni** [comment]
I think it is done.
