### ISSUE TITLE
SE2CS: something like the CE2CS but for SEs

### ISSUE THREAD

**Issue by sposs** [DIRACGrid/DIRAC#927]
It would be very nice to have an agent that performs the same kind of tasks that the CE2CS agent does: take from the BDII the storage elements that are valid for a given vo, and some basic info: endpoint, path, SRM version, protocol, etc. In fact, if possible it would be nice to have the info that is currently filled in the CS under /Resources/StorageElements/SE/AccessProtocol.1 
The type of storage is also needed (T1D0, T0D1, etc.) if possible as it's used in the InputDataAgent for staging requests.

Maybe with Mario some agreement could be found as he promised to work on an agent that picks the info of the size and availability of an SE using the lcg_utils (the equivalent of the SRMSpaceTokenUsageAgent functionality).

As how the SE should be registered I would suggest to use the same kind of logic as the CE2CS: first a mail is sent to the administrator to register the SE with some name, and the next iteration of the SE2CS agent would then fill the missing bits (just like the CE2CS again). I guess the SEUniqueID should be stored in the CS to allow the lookup in the second iteration. 

What do you think?

Vladimir and Mario are aware of this already.

**Comment by chaen** [comment]
Also done by the new agent, isn't it ?

**Comment by atsareg** [comment]
Bdii2CSAgent does both CE ans SE information synchronization
