### ISSUE TITLE
Accounting info for File Catalog

### ISSUE THREAD

**Issue by sposs** [DIRACGrid/DIRAC#995]
Hi,
It would be very nice to have accounting plots for the file catalog. The kind of plots I'd like to see are:
insertions/unit of time,
cumulative number of files/directories, 
additions / removal per unit of time
Storage usage per time/SE with maybe the possibility to chose the directory, but that is not simple, and possibly extremely heavy on the accounting side.

**Comment by chaen** [comment]
Related to https://github.com/DIRACGrid/DIRAC/issues/2138 
In any case, for these particular requests, I added most of them in the monitoring.

**Comment by chaen** [comment]
Closing that one
